### ISSUE TITLE
python_modular compilation fails on FreeBSD

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#1023]
With the current state of develop branch python_modular interface cannot be compiled on FreeBSD, because of the following reasons:
- in ./configure:
  LINKFLAGS_PYTHON="-ldl -lutil"
  POSTLINKFLAGS_PYTHON="-ldl -lutil
  there's no libdl on FreeBSD, it should be removed and put somewhere with a system switch, i.e. in case one tries to compile it on linux distro it should be added.
- one should be able to pass the swig executable name for the ./configure script, e.g.:
  ./configure --swig=swig2.0
- once the errors above are fixed, we will still get the following error:

```
gmake[1]: Entering directory `/usr/home/wiking/shogun/src/interfaces/python_modular'
clang++ -fPIC -g -O0 -DSWIG_TYPE_TABLE=shogun -DSHOGUN -DFREEBSD -DUSE_BOOL -DUSE_CHAR -DUSE_UINT8 -DUSE_UINT16 -DUSE_INT32 -DUSE_INT64 -DUSE_UINT64 -DUSE_FLOAT32 -DUSE_FLOAT64 -DHAVE_SQRTL -DHAVE_LOG2 -DHAVE_PTHREAD -DHAVE_JSON -DHAVE_XML -DHAVE_ATLAS -DHAVE_LAPACK -DHAVE_CATLAS -DHAVE_EIGEN3 -DUSE_GLPK -DUSE_SNAPPY -DUSE_GZIP -DUSE_BZIP2 -DUSE_LZMA -DHAVE_LARGEFILE -DUSE_SHORTREAL_KERNELCACHE -DUSE_BIGSTATES -DUSE_HMMCACHE -DUSE_REFERENCE_COUNTING -DUSE_SVMLIGHT -DUSE_SPINLOCKS -DHAVE_PYTHON -c -I. -I..  -I/usr/local/include/json   -I/usr/local/include/libxml2 -I/usr/local/include   -isystem /usr/local/include/eigen3   -I../../shogun -I../.. -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include  -o modshogun_wrap.cxx.o modshogun_wrap.cxx
modshogun_wrap.cxx:5476:3: error: "SWIG wrapped code invalid in 32 bit architecture, regenarete code using -DSWIGWORDSIZE32"
# error "SWIG wrapped code invalid in 32 bit architecture, regenarete code using -DSWIGWORDSIZE32"
  ^
modshogun_wrap.cxx:737606:3: warning: expression result unused; should this cast be to 'void'? [-Wunused-value]
  (void *)clientdata;
  ^     ~
1 warning and 1 error generated.
```

**Comment by pamrash** [comment]
My code is like this ...
$(CROSS_COMPILE)$(CC) -I$(RUBY_H) -fPIC $(CFLAGS) $(CFLAGSEXTRA) -c openwrap.c 
$(CROSS_COMPILE)$(CC) -shared openwrap.o -o $@ $(LDFLAGS) $(LFLAGSEXTRA)

Can anyone tell me the format of adding the "DSWIGWORDSIZE32"

**Comment by pamrash** [comment]
I am using SWIG RUBY

**Comment by karlnapf** [comment]
@pamrash what exactly is the problem?
