### ISSUE TITLE
Cross-Product for lists of kernels (MKL, CombinedKernel)

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1042]
People sometimes ask us how to make shogun select the parameter of sub-kernels of a combined kernel.

Imagine you have two two kernels A and B with parameters P and Q. MKL can select kernel weights for A and B for fixed parameters P and Q. However, the choice of the parameters P and Q also influences the result so one would like to select them automatically.

In principal, we can use shogun's modelselection framework to select parameters of single kernels. However, for combined kernels this does currently not apply. We had a discussion about it and agreed that its way to complicated to add direct support for this in the model-selection framework. HOWEVER, since it is possible to select the best single kernel, we can do this another way: We create a bunch of combined kernels from a set of lists of kernels with the parameters to try.

Example:
kernel list A: gaussian(2), gaussian(3)
kernel list B: string(10), string(20)

cross-product:
combined kernel: gaussian(2) string(10)
combined kernel: gaussian(2) string(20)
combined kernel: gaussian(3) string(10)
combined kernel: gaussian(3) string(20)

these kernels can then be used with the shogun model-selection framework to select the best combination. This solves the described problem and is very easy to implement.

This task is to add a method to CCombinedKernel, which takes a list of lists of kernels (each inner list contains kernels of the same type), and computes the cross-product as illustrated above. A list of combined kernels is returned.

**Comment by iarroyof** [comment]
A question related to this issue: for large kernel combinations, It is possible dividing the optimization of kernel coefficients into multiple subproblems? I'd like sending each these sobproblems to different machine cores, but with out modifying Shogun objects. Thank you...

**Comment by karlnapf** [comment]
There are two things here: algorithmic changes/approximations and how they affect the solution you are after (dividing the optimisation, etc). You would have to do the math for that, but I guess something can be done here.

From an implementation side of view, Shogun currently lacks a proper framework for doing organised multicore or multimachine calculations -- we do most of the parallelisation using openmp or even pthreads directly in the algorithm implementation, which mixes up algorithm design and technical multicore details and thus makes it hard to parallelise algorithms systematically in Shogun.

Any input here is highly appreciated

**Comment by iarroyof** [comment]
Thank you for answering Heiko,

At the moment Im tying to work on multicore settings. I gave a look to existent ways for parallelizing the estimation of Fourier coefficients. I hope this can be useful for this case. In fact, some contribution will be added here.

Nacho

**Comment by karlnapf** [comment]
This is great!
Keep us posted. It would be amazing to parallelise some of Shoguns algorithms, or work on a general framework for that. We could give you support with the library internals if you want to work on such things
