### ISSUE TITLE
add factory classes for obtain_from_generic functions

### ISSUE THREAD

**Issue by sonney2k** [shogun-toolbox/shogun#1058]
We have in e.g. CBinaryLables and various other classes functions that do casting with error checking from the more general e.g. CLabels type down to CBinaryLabels. This is needed to support languages interfaces that have no notion of casting (e.g. python_modular).

The task here would be to move such conversion functions into factory classes e.g. CLabelFactory and remove them from the particular specialized class.

**Comment by karlnapf** [comment]
We don't want to do this anymore
