### ISSUE TITLE
remove CFeatures::get_size()

### ISSUE THREAD

**Issue by sonney2k** [shogun-toolbox/shogun#1102]

**Comment by karlnapf** [comment]
any ideas what the motivation for this was?

**Comment by lisitsyn** [comment]
@karlnapf is it needed somewhere?

**Comment by sonney2k** [comment]
I used this like 10 years ago to alloc memory / know the size of the feature matrix etc. I guess we don't need this anymore.

On March 27, 2015 5:24:18 PM EET, Heiko Strathmann <notifications@github.com> wrote:
>any ideas what the motivation for this was?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/shogun-toolbox/shogun/issues/1102#issuecomment-86973603

-- 
Sent from Kaiten Mail. Please excuse my brevity.

**Comment by karlnapf** [comment]
ok thanks
