### ISSUE TITLE
fix regression_gaussian_process_sum.cpp

### ISSUE THREAD

**Issue by sonney2k** [shogun-toolbox/shogun#1106]

**Comment by yorkerlin** [comment]
@karlnapf ?

**Comment by karlnapf** [comment]
It references [this one](https://github.com/shogun-toolbox/shogun/blob/develop/examples/undocumented/libshogun/regression_gaussian_process_sum.cpp) Does the program work for you? It doesnt seem to be blacklisted anymore. I will close for now. If there are problems, feel free to re-open
