### ISSUE TITLE
Gradient Model Selection is buggy and weird

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1231]
@votjakovr This one is for you :)
The gradient descent works in general, though has a lot of stability issues.

See some code here:
https://gist.github.com/karlnapf/5968042

1.) ALL model parameters need to be registered. It is not possible to optimize just a few of them (comment out the kernel part of the tree and you will see). I think this is because the gradient model selection iterates over all model parameters and looks for their values in the tree instead of doing this vice verse.

2.) The above code crashes after the optimization has finished. This is caused my the UNREF of grad_search variable at the end. Removing it solves the crash. So there is something freed within the Model selection that should not be freed.

3.) Some parameters get negative. This should not be possible (at least for some). Maybe move to log domain?

4.) The Gradient model selection starts at a random value, rather than picking an existing one from the model. It would be better if it would take the current ones since then one could set starting parameters for the optimization.

5.) The code is messy and weird at some places. It would need a clean-up or some documentation inside it

We should document and test this a bit since it is crucial for the GP stuff to work. Let me know your thoughts on this :)

**Comment by yorkerlin** [comment]
@karlnapf 
maybe this issue is solved?

**Comment by karlnapf** [comment]
yeah I agree. Thanks!
