### ISSUE TITLE
Nice output for CMake

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#1381]
the current output of cmake is not the nicest, although all the important information is there, but it would be great that on the end of the cmake run, there would be nicely indented message, where it's nicely explained what interfaces are turned on, which libraries has been found (and what compiler flags are used for it) and various other misc. info.

For examples opencv's cmake generates a nice summary on the end of a cmake run.

**Comment by lisitsyn** [comment]
I believe it is solved.
