### ISSUE TITLE
Implement pthread/openMP based backend for computation framework

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1623]
@lambday has written first parts of a framework for parallel computation of independent tasks.

It allows to code against a very general interface, which then executes tasks in a serial/parallel/distributed fashion internally, based on the backend.

It is already used by his log-determinant GSoC 2013 project.

This task is to add a parallel backend to it.

This should create multiple threads to run registered jobs.
It might be an interesting question to decide whether to go for pthreads or OpenMP

No code exists so far, however, this should be developed before the distributed one since it is more useful for users (which usually do not have cluster computers)

**Comment by vigsterkr** [comment]
this is basically being handled by the graph computational fw effort
