### ISSUE TITLE
quicklinks for shogun class documentation

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1671]
It would be good if we had something like
www.shogun-toolbox.org/CStatistics pointing to the latest doxygen documentation.

Then we would not have to re-write the full link
http://www.shogun-toolbox.org/doc/en/latest/classshogun_1_1CStatistics.html

everytime we reference it

**Comment by erip** [comment]
Recommend closing.

**Comment by iglesias** [comment]
Thanks for letting us know, @erip.
