### ISSUE TITLE
'MACHINE' was not declared in this scope

### ISSUE THREAD

**Issue by Krzysiaczek99** [shogun-toolbox/shogun#1767]
Next error during MINGW compilation

C:\shogun-develop\Build>mingw32-make
[  0%] Built target class_list
Scanning dependencies of target version
[  1%] Generating version header
[  1%] Built target version
Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/init.cpp.obj

[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Parallel.cpp
.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Parameter.cp
p.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/ParameterMap
.cpp.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/SGObject.cpp
.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Version.cpp.
obj
In file included from C:/shogun-develop/shogun-develop/src/shogun/../shogun/base
/Version.h:14:0,
                 from C:\shogun-develop\shogun-develop\src\shogun\base\Version.c
pp:11:
C:\shogun-develop\shogun-develop\src\shogun\base\Version.cpp: In static member f
unction 'static void shogun::Version::print_version()':
C:\shogun-develop\shogun-develop\src\shogun\base\Version.cpp:44:39: error: 'MACH
INE' was not declared in this scope
  SG_SPRINT("libshogun (%s/%s%d)\n\n", MACHINE, VERSION_RELEASE, version_revisio
n)
                                       ^
C:/shogun-develop/shogun-develop/src/shogun/../shogun/io/SGIO.h:182:98: note: in
 definition of macro 'SG_SPRINT'
 #define SG_SPRINT(...) { sg_io->message(MSG_MESSAGEONLY,**PRETTY_FUNCTION**, __
FILE__, **LINE**, **VA_ARGS**); }

```
              ^
```

C:\shogun-develop\shogun-develop\src\shogun\base\Version.cpp:54:122: error: 'LIN
KFLAGS' was not declared in this scope
  SG_SPRINT("( configure options: \"%s\" compile flags: \"%s\" link flags: \"%s\
" )\n", CONFIGURE_OPTIONS, COMPFLAGS_CPP, LINKFLAGS)

```
                                      ^
```

C:/shogun-develop/shogun-develop/src/shogun/../shogun/io/SGIO.h:182:98: note: in
 definition of macro 'SG_SPRINT'
 #define SG_SPRINT(...) { sg_io->message(MSG_MESSAGEONLY,**PRETTY_FUNCTION**, __
FILE__, **LINE**, **VA_ARGS**); }

```
              ^
```

src\shogun\CMakeFiles\libshogun.dir\build.make:887: recipe for target 'src/shogu
n/CMakeFiles/libshogun.dir/base/Version.cpp.obj' failed
mingw32-make[2]: **\* [src/shogun/CMakeFiles/libshogun.dir/base/Version.cpp.obj]
Error 1
CMakeFiles\Makefile2:115: recipe for target 'src/shogun/CMakeFiles/libshogun.dir
/all' failed
mingw32-make[1]: **\* [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
mingw32-make: **\* [all] Error 2

C:\shogun-develop\Build>

**Comment by Pepslee** [comment]
help me please with compiling shogun on win32 with MinGW !!!

i see, you have already compiled it.  is it true ?
can you give me some guide, how to do it ?

**Comment by karlnapf** [comment]
Dear @Pepslee 
please file a proper error description, with details on what is the problem for you, this way you will get a proper answer.

**Comment by muhannad35990** [comment]
is there anyone compiled shogun in windows and mingw??
I need it but fail to compile ,any precompiled library for mingw?
