### ISSUE TITLE
error: 'DWORD' was not declared in this scope

### ISSUE THREAD

**Issue by Krzysiaczek99** [shogun-toolbox/shogun#1769]
C:\shogun-develop\Build>mingw32-make
[  1%] Generating version header
[  1%] Built target version
[  1%] Built target class_list
Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/init.cpp.obj

[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Parallel.cpp
.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Parameter.cp
p.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/ParameterMap
.cpp.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/SGObject.cpp
.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Version.cpp.
obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/Averag
edPerceptron.cpp.obj
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/Featur
eBlockLogisticRegression.cpp.obj
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/Gaussi
anProcessBinaryClassification.cpp.obj
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/LDA.cp
p.obj
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/LPBoos
t.cpp.obj
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/LPM.cp
p.obj
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/mkl/MK
L.cpp.obj
In file included from C:/shogun-develop/shogun-develop/src/shogun/../shogun/clas
sifier/mkl/MKL.h:27:0,
                 from C:\shogun-develop\shogun-develop\src\shogun\classifier\mkl
\MKL.cpp:15:
C:/shogun-develop/shogun-develop/src/shogun/../shogun/lib/Time.h: In function 'i
nt gettimeofday(timeval_, void_)':
C:/shogun-develop/shogun-develop/src/shogun/../shogun/lib/Time.h:34:5: error: 'D
WORD' was not declared in this scope
     DWORD t;
     ^
C:/shogun-develop/shogun-develop/src/shogun/../shogun/lib/Time.h:34:11: error: e
xpected ';' before 't'
     DWORD t;
           ^
C:/shogun-develop/shogun-develop/src/shogun/../shogun/lib/Time.h:35:5: error: 't
' was not declared in this scope
     t = timeGetTime();
     ^
C:/shogun-develop/shogun-develop/src/shogun/../shogun/lib/Time.h:35:21: error: '
timeGetTime' was not declared in this scope
     t = timeGetTime();
                     ^
src\shogun\CMakeFiles\libshogun.dir\build.make:1055: recipe for target 'src/shog
un/CMakeFiles/libshogun.dir/classifier/mkl/MKL.cpp.obj' failed
mingw32-make[2]: **\* [src/shogun/CMakeFiles/libshogun.dir/classifier/mkl/MKL.cpp
.obj] Error 1
CMakeFiles\Makefile2:115: recipe for target 'src/shogun/CMakeFiles/libshogun.dir
/all' failed
mingw32-make[1]: **\* [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
mingw32-make: **\* [all] Error 2

C:\shogun-develop\Build>

**Comment by vigsterkr** [comment]
this should be fixed in latest develop after 8fdf278dca78f98d4e06058a5ce3defd560d697d
