### ISSUE TITLE
Shogun3.0 for matlab static didn't creat a sg.mexglx file

### ISSUE THREAD

**Issue by septem8918** [shogun-toolbox/shogun#1777]
$ mkdir build && cd build
  $ cmake -DMatlabStatic=ON ..
  $ make
  $ sudo make install
src/interfaces/matlab_static/ weren't any sg.\* files...
help!

**Comment by luckybuilding** [comment]
Hi, I have found this now and wanted to use it. Is this still available on shogun?! I don't see the link!
