### ISSUE TITLE
Octave 3.8 missing libraries

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#1805]
Hi,

I have tried to compile shogun 3.0 with the octave modular  interface but cmake keeps producing the error
FindPackageHandleStandardArgs.cmake:108 (message):
    Could NOT find Octave (missing: OCTAVE_LIBRARIES) (found suitable version
    "3.8.0", minimum required is "3.6")

I compiled octave 3.8.0 as a shared library with prefix= /usr and the libraries and the headers are all in the usual places (/usr/lib and /usr/include)

OS is Ububtu 13.10 64 bits
Thanks

**Comment by iglesias** [comment]
Shogun 4.0.0 with Octave 3.8.2 works well in Ubuntu 14.04 64 bits. Shall we close this issue?

**Comment by carbonox-infernox** [comment]
@iglesias How do you get those working? I installed those, but octave is not finding shogun's libraries.

**Comment by iglesias** [comment]
@carbonox-infernox did you set up the "search path" in Octave so that it knows where its Shogun target is?
