### ISSUE TITLE
Implement Multiclass GP machine

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1900]
This task is to create a class CGaussianProcessMulticlass, a class similar to CGaussianProcessBinaryClassification that is able to deal with multiclass problems in a similar fashion.
Note: the inference method is another task.

This is a bit more involved, so make sure you understand multiclass GP basics before.
See the multiclass algorithm in Williams and Rassmussens book on GPs, and also the 1999 Williams and Barber paper on Gaussian Processes.

**Comment by yorkerlin** [comment]
done at https://github.com/shogun-toolbox/shogun/pull/2484
