### ISSUE TITLE
All univariate distributions in Shogun should come from boost

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#1912]
(apart from maybe Gaussian, and univariate)

This
- reduces the possibility of bugs as we use mature, well-tested code
- we can get rid of the alglib code that we took under the GPL
- in particular, start in CStatistics, and replace all ALGLIB based methods by boost ones (at least gamma cdf, etc)
- we need a cmake check for boost, and an include guard, and maybe even the option to download and locally compile boost in the same fashion as eigen3

**Comment by iglesias** [comment]
But what should we do about the gpl issue with alglib? We must solve it if we are aiming at being completely bsd.

**Comment by thirdwing** [comment]
Boost is the best choice I know and boost-math is really light-weight.

**Comment by iglesias** [comment]
@thirdwing, it is header-only, right? Does it have any dependencies?

**Comment by thirdwing** [comment]
Yes, it is header-only. On ubuntu, all you need is ``libboost-math-dev``. In https://github.com/shogun-toolbox/shogun/pull/2662 all ALGLIB code has been replaced with boost-math. However, it seems you really don't like boost.

**Comment by iglesias** [comment]
We are not only supporting Ubuntu (not even only just Linux).

Regarding the dependencies, if you try to do apt-get install libboost-math-dev, you will see that the whole libboost package will be installed as well (in case you don't have it already installed). So it seems that boost math depends on the whole boost library.

**Comment by thirdwing** [comment]
I am sorry that my word caused some misunderstanding. ``liboost-math-dev`` is just an example. You can install it easily. You can also checkout any module manually.

https://gist.github.com/thirdwing/4ec69f6a4d938863b37d

**Comment by iglesias** [comment]
That would be having the whole boost as dependency (not only boost math),
which is not so light-weight.
