### ISSUE TITLE
Adding support for `SGVector` to Parameter::add_vector

### ISSUE THREAD

**Issue by tklein23** [shogun-toolbox/shogun#1972]
Entrance task for GSoC project: http://www.shogun-toolbox.org/page/Events/gsoc2014_ideas#multilabel

The parameter framework is used to provide generic functions for cloning, comparing and serializing SGObjects in shogun.  In order to make this possible, we need to add only _basic_ types to the framework.

Currently, `Parameter.h`/`DataType.h` only supports String and `SGSparseVector` for add_vector.  This entrance task is about adding support for `SGVector` to the framework.

This extension is needed to allow classes like this:

```
class CMultilabelLabels : public CSGObject
{
    ...
    private: 
        SGVector<int32_t> * m_data;
}
```

An example can be found in `src/shogun/labels/MulticlassMultipleOutputLabels.h` and may be used for testing.  (@lisitsyn may answer questions on this class.)

This is not a hard task - it's basically looking how it is done for the other types and then adapting it to `SGVector`.  Along the way, you will need to talk to parameter framework guy (@karlnapf) and write basic unit tests.

_UPDATE:_

Other example classes (may or may not be solved in this task) can be found using this shell command:

```
find src/ -name "*.h" -print0 |xargs -r0 grep 'SGVector<.*>[[:space:]]*\*[[:space:]]*[[:alnum:]_]*[[:space:]]*;'
```

Examples for affected classes:
- `src/shogun/evaluation/GradientResult.h`
- `src/shogun/transfer/multitask/MultitaskROCEvaluation.h`

**Comment by karlnapf** [comment]
This is way outdated
