### ISSUE TITLE
Possible CSVFile bug with high number of feature vectors

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#1991]
According to a user when one wants to load a csv file with a size of 17000 feature vectors where each vector's dimension is 66, there's an extra feature in the created DenseFeatures class.

Please investigate this bug, i.e. confirm it and fix it if you can confirm it.

a very easy way to generate such a csv:

```
import numpy as np

x = np.random.rand(20000, 70)
np.savetxt('test_20k.csv', x)
```

after this load in this csv with `CSVFile` to shogun creating a SGMatrix. something like:

```
SGMatrix<float64_t> test_m;
CCSVFile* test_file = new CCSVFile("test_20k.csv");
test_m.load(test_file);
```

and check if `test_m.num_cols == 20000` and `test_m.num_rows == 70`
of course you can do the test as well with any modular interface...

**Comment by tklein23** [comment]
@karlnapf: If you read a file bigger than the ring buffer, then there is an additional feature vector.  The ring buffer defaults to 10MB.

In other words:
* A csv file with 10.000 lines with less than 10MB will produce 10.000 vectors.
* A csv file with 10.000 line with more than 10MB will product 10.001 vectors.

The bug itself seems minor.  But as we're checking dimensions of features and labels everywhere, it will produce "unexpected" errors on bigger files.

**Comment by karlnapf** [comment]
If there are only 10,000 lines, what does this 1 more feature vector contain? junk?

I think its pretty bad to have this, since it means one cannot use Shogun to parse large files (we are calling ourselves large-scale machine learning toolbox)

**Comment by karlnapf** [comment]
Hehe, so this is still around......
@OXPHOS @vigsterkr this is yours I think

**Comment by gsomix** [comment]
.__.

**Comment by OXPHOS** [comment]
Is this supposed to be fixed before 23rd (the release)?

**Comment by karlnapf** [comment]
Yes, @vigsterkr put it on the [milestone](https://github.com/shogun-toolbox/shogun/milestones/Shogun%204.2.0%20-%20Takechi%20Hanpeita)
He can comment on his own fixes there. But if we had this in, it would be great. You should catch him in IRC to push :)

**Comment by OXPHOS** [comment]
Update:
When reading in a 12.3M int16 matrix (2e6 * 1) the line count is correct (returns 2000000).
However, reading in a 12.2M int32 matrix (1.664e6 * 1) the line count returns 1664001.

I suspect it's the issue with class `CCircularBuffer`, because in `if` clause of `CLineReader::has_next()`, `!m_buffer->has_next()` return 0 when line count reaches 1664000. It should return 1 to end the reading. 

I'll stop here for today...

12.3M int16 matrix:
```
	int32_t num_rows = 2000000;
	int32_t num_cols = 1;
	SGMatrix<int16_t> data(num_rows, num_cols);
        int16_t k=0;
	for (int32_t i = 0; i < num_rows; i++)
	{
		for (int32_t j = 0; j < num_cols; j++)
			data(i, j) = k;
                        k += 1;
	}


	CCSVFile* fin;
	CCSVFile* fout;
        
        //std::shared_ptr<CCSVFile> fout(new CCSVFile("CSVFileTest_large_matrix_output.txt",'w', NULL));
        fout = new CCSVFile("CSVFileTest_large_matrix_output.txt",'w', NULL);
	fout->set_delimiter('|');
	fout->set_matrix(data.matrix, num_cols, num_rows);
        SG_UNREF(fout);
	
        SGMatrix<float64_t> data_from_file(true);
        
	//std::shared_ptr<CCSVFile> fin(new CCSVFile("CSVFileTest_large_matrix_output.txt",'r', NULL));
        fin = new CCSVFile("CSVFileTest_large_matrix_output.txt",'r', NULL);
	fin->set_delimiter('|');
	fin->get_matrix(data_from_file.matrix, data_from_file.num_cols, data_from_file.num_rows);
        std::cerr << data_from_file.num_rows << ' ' << data_from_file.num_cols << std::endl;
```

**Comment by vigsterkr** [comment]
@oxphos dont waste your time on this i'll push tonight some major changes in a branch

**Comment by OXPHOS** [comment]
@vigsterkr Got it!

**Comment by karlnapf** [comment]
gogogogo! :)

**Comment by iRmantou** [comment]
Is this issue still open? @vigsterkr  It looks like very old

**Comment by vigsterkr** [comment]
@iRmantou yeah but actually i've picked it up yesterday... so sorry.

**Comment by iRmantou** [comment]
@vigsterkr  It seems that I have to go and find one...       Orz
