### ISSUE TITLE
Using C++11s Distributions in Shogun

### ISSUE THREAD

**Issue by cameo54321** [shogun-toolbox/shogun#1998]
The recent addition in shogun for a probability distribution was:
http://www.shogun-toolbox.org/doc/en/3.0.0/classshogun_1_1CProbabilityDistribution.html
with implementation
http://www.shogun-toolbox.org/doc/en/3.0.0/classshogun_1_1CGaussianDistribution.html

The above implementation uses  SIMD-oriented Fast Mersenne Twister (SFMT) pseudorandom number generator for random number generation and Eigen3 for generating the Gaussian Distribution from these samples.

The [C++11s Pseudo-random number generator](http://en.cppreference.com/w/cpp/numeric/random) (as pointed by @vigsterkr) has many built-in distributions and random number generators which can be used for generating distributions in Shogun. So instead of implementing each distribution by ourselves, can we use C++11s distributions?

What if the classes for the Issue #1929 are written utilizing C++11s distributions in mind instead of (or alongwith) SFMT? What can be a good direction to achieve that? 

@karlnapf @vigsterkr Comments please?

**Comment by vigsterkr** [comment]
feature/refactor-random is on this path :)

**Comment by karlnapf** [comment]
FYI: ALGLIB did already got pushed out a while ago (it was GPL code, replace with cdflib)
