### ISSUE TITLE
Fix NeuralNets notebook

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#2098]
@khalednasr have you used the supplied notebook template for creating the neuralnets notebook?

https://github.com/shogun-toolbox/shogun/blob/develop/doc/ipython-notebooks/template.ipynb

since currently that notebook is kind of broken, i.e. it doesn't have an abstract and breaks the page here:
http://shogun-toolbox.org/page/documentation/notebook

please try to fix it ASAP

**Comment by theaverageguy** [comment]
This is fixed!  :)
