### ISSUE TITLE
CSGObject: all parameters needed in generic base class?

### ISSUE THREAD

**Issue by tklein23** [shogun-toolbox/shogun#2113]
@karlnapf - talking about CSGObject again, I again suggest pulling out some variables from CSGObject class.  Since this state is shared in every object, this seems to be lot more than really needed.

As you worked as well on 
- the parameter framework
- the model selection extension

Do you think (a) they are all necessary and (b) do you have an idea how to pull this out?  Easy ideas first, we can do this step-by-step. :)

**Comment by karlnapf** [comment]
This will all be better with tags, once merged
