### ISSUE TITLE
Problem with cygwin installation for python modular ? 

### ISSUE THREAD

**Issue by aveshd** [shogun-toolbox/shogun#2380]
Hi,

Please accept my apologies if this issue has already been solved. But I need help, I am not a big time user of cygwin, but I try to find my way around. 

Before coming to this forum I have tried various options to the best of my ability. 
I am trying to follow the instructions for installation of shogun for cygwin. 

I am am getting this error and everything stops compiling further. 
# 
# 

[ 27%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/io/File.cpp.o
/home/shogun-develop/src/shogun/io/File.cpp: In constructor ‘shogun::CFile::CFile(int, const char_, const char_)’:
/home/shogun-develop/src/shogun/io/File.cpp:44:22: error: ‘fdopen’ was not declared in this scope
  file=fdopen(fd, mode);
                      ^
/home/shogun-develop/src/shogun/io/File.cpp: In member function ‘void shogun::CFile::set_variable_name(const char_)’:
/home/shogun-develop/src/shogun/io/File.cpp:185:27: error: ‘strdup’ was not declared in this scope
  variable_name=strdup(name);
                           ^
/home/shogun-develop/src/shogun/io/File.cpp: In member function ‘char_ shogun::CFile::get_variable_name()’:
/home/shogun-develop/src/shogun/io/File.cpp:190:29: error: ‘strdup’ was not declared in this scope
  return strdup(variable_name);
                             ^
/home/shogun-develop/src/shogun/io/File.cpp:191:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/shogun/CMakeFiles/libshogun.dir/build.make:5368: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/io/File.cpp.o' failed
make[2]: **\* [src/shogun/CMakeFiles/libshogun.dir/io/File.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: **\* [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
# make: **\* [all] Error 2
# 

it seems the problem is with fdopen function. 

Here is my cmake output. Just in case if you need to look at that as well
# 
# 

cmake -DPythonModular=ON ..
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
CMake Warning at /usr/share/cmake-2.8.9/Modules/Platform/CYGWIN.cmake:15 (message):
  CMake no longer defines WIN32 on Cygwin!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that Cygwin is WIN32.
  In that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

```
set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required
```

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/share/cmake-2.8.9/Modules/CMakeSystemSpecificInformation.cmake:36 (INCLUDE)
  CMakeLists.txt:7 (project)

-- Check for working C compiler: /usr/bin/gcc.exe
-- Check for working C compiler: /usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CCache: /usr/bin/ccache.exe
-- Found SWIG: /usr/bin/swig.exe (found suitable version "2.0.12", required is "2.0.4")
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "**func**": works
-- Checking C++11 support for "atomic"
-- Checking C++11 support for "atomic": works
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": works
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": works
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": works
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": works
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": works
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": works
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": works
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": works
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": works
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": not supported
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": works
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": works
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": works
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": works
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Using system's malloc
-- Looking for isfinite
-- Looking for isfinite - not found.
-- Looking for isinf
-- Looking for isinf - not found.
-- Looking for isnan
-- Looking for isnan - not found.
-- Looking for signgam
-- Looking for signgam - not found.
-- Looking for log2
-- Looking for log2 - found
-- Looking for powl
-- Looking for powl - not found
-- Looking for lgammal
-- Looking for lgammal - not found
-- Looking for sqrtl
-- Looking for sqrtl - not found
-- Looking for finite
-- Looking for finite - found
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Performing Test HAVE_STD_ISINF
-- Performing Test HAVE_STD_ISINF - Success
-- Performing Test HAVE_STD_ISFINITE
-- Performing Test HAVE_STD_ISFINITE - Success
-- Performing Test HAVE_STD_ISNAN
-- Performing Test HAVE_STD_ISNAN - Success
-- Looking for arc4random
-- Looking for arc4random - found
-- Found GDB: /usr/bin/gdb.exe
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY)
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Found PkgConfig: /usr/bin/pkg-config.exe (found version "0.28")
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Looking for clapack_dpotrf in /usr/lib/liblapack.dll.a
-- Looking for clapack_dpotrf in /usr/lib/liblapack.dll.a - not found
-- Could NOT find ATLAS (missing:  ATLAS_LIBRARIES ATLAS_INCLUDES)
-- Found CBLAS: /lib/libgslcblas.dll.a
-- Looking for cblas_dsyrk in /lib/libgslcblas.dll.a
-- Looking for cblas_dsyrk in /lib/libgslcblas.dll.a - found
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND)
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR)
-- Could NOT find Eigen3 (missing:  EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR)
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR)
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR)
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR)
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.7")
-- Found PythonInterp: /usr/bin/python (found version "2.7.3")
-- checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR)
-- Found HDF5: debug;/usr/lib/libhdf5_hl.dll.a;debug;/usr/lib/libhdf5.dll.a;debug;/usr/lib/libz.dll.a;debug;/usr/lib/libdl.a;debug;/usr/lib/libm.a;optimized;/usr/lib/libhdf5_hl.dll.a;optimized;/usr/lib/libhdf5.dll.a;optimized;/usr/lib/libz.dll.a;optimized;/usr/lib/libdl.a;optimized;/usr/lib/libm.a
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Found ZLIB: /usr/lib/libz.dll.a (found version "1.2.8")
-- Found BZip2: /usr/lib/libbz2.dll.a (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.dll.a
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.dll.a - found
-- Looking for lzma_auto_decoder in /usr/lib/liblzma.dll.a
-- Looking for lzma_auto_decoder in /usr/lib/liblzma.dll.a - found
-- Looking for lzma_easy_encoder in /usr/lib/liblzma.dll.a
-- Looking for lzma_easy_encoder in /usr/lib/liblzma.dll.a - found
-- Looking for lzma_lzma_preset in /usr/lib/liblzma.dll.a
-- Looking for lzma_lzma_preset in /usr/lib/liblzma.dll.a - found
-- Found LibLZMA: /usr/include (found version "5.0.5")
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR)
-- Lzo Library /usr/lib/liblzo2.dll.a
-- Lzo Include Found in /usr/include
-- Spinlock support not found
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
-- Found PythonLibs: /usr/lib/libpython2.7.dll.a (found version "2.7.3")
-- Found NumPy: version "1.7.2" /usr/lib/python2.7/site-packages/numpy/core/include
-- ===================================================================================================================
## -- Summary of Configuration Variables

-- The following OPTIONAL packages have been found:
- CCache
- GDB
- OpenMP
- BLAS
- Threads
- LAPACK
- CBLAS
- Doxygen
- HDF5
- ZLIB
- BZip2
- LibLZMA
- LZO

-- The following REQUIRED packages have been found:
- SWIG (required version >= 2.0.4)
- PythonLibs
- PythonInterp
- NumPy

-- The following OPTIONAL packages have not been found:
- Mosek
- Atlas
- GLPK
- CPLEX
- ARPACK
- Eigen3 (required version >= 3.1.2)
- NLopt
- LpSolve
- ColPack
- ARPREC
- LibXml2
- CURL
- SNAPPY
- Spinlock
- Protobuf

-- ===================================================================================================================
-- Enabled Integration
--   OpenCV Integration is OFF   - enable with -DOpenCV=ON
-- ===================================================================================================================
-- Enabled Interfaces
--   libshogun is ON
--   python modular is ON
--   octave modular is OFF       - enable with -DOctaveModular=ON
--   java modular is OFF         - enable with -DJavaModular=ON
--   perl modular is OFF         - enable with -DPerlModular=ON
--   ruby modular is OFF         - enable with -DRubyModular=ON
--   csharp modular is OFF       - enable with -DCSharpModular=ON
--   R modular is OFF            - enable with -DRModular=ON
## --   lua modular is OFF          - enable with -DLuaModular=ON

-- Enabled legacy interfaces
--   cmdline static is OFF       - enable with -DCmdLineStatic=ON
--   python static is OFF        - enable with -DPythonStatic=ON
--   octave static is OFF        - enable with -DOctaveStatic=ON
--   matlab static is OFF        - enable with -DMatlabStatic=ON
--   R static is OFF             - enable with -DRStatic=ON
-- ===================================================================================================================
-- To compile shogun type
## --   make

-- To install shogun to /usr/local type
## --   make install

-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
# -- Build files have been written to: /home/shogun-develop/build
# 

Please help. 

kind regards,
Avi

**Comment by iglesias** [comment]
@jmarrietar, @aveshd, could you try if the commit above by @lisitsyn fixes your problem?

**Comment by aveshd** [comment]
will try and let you know the results

On Sun, Jan 25, 2015 at 6:54 AM, Fernando Iglesias <notifications@github.com
