### ISSUE TITLE
C# modular interface compilation fails with mono 3.x

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#2425]
Currently C# modular interface compilation fails on osx bot, where mono version is 3.x:
```
modshogunPINVOKE.cs(9270,141): error CS0100: The parameter name `rows' is a duplicate
modshogunPINVOKE.cs(9270,151): error CS0100: The parameter name `cols' is a duplicate
modshogunPINVOKE.cs(9273,141): error CS0100: The parameter name `rows' is a duplicate
modshogunPINVOKE.cs(9273,151): error CS0100: The parameter name `cols' is a duplicate
modshogunPINVOKE.cs(9276,141): error CS0100: The parameter name `rows' is a duplicate
modshogunPINVOKE.cs(9276,151): error CS0100: The parameter name `cols' is a duplicate
modshogunPINVOKE.cs(9279,141): error CS0100: The parameter name `rows' is a duplicate
modshogunPINVOKE.cs(9279,151): error CS0100: The parameter name `cols' is a duplicate
...
```

the same code generated by swig compiles fine with mono 2.x, i.e. on deb3 - modular interface bot

**Comment by tpokorra** [comment]
we have a similar problem with Shogun 4.0.0 for Fedora with Mono 4.0.1 (https://bugzilla.redhat.com/show_bug.cgi?id=1223446):

```/usr/bin/mcs /t:library *.cs /out:modshogun.dll
modshogunPINVOKE.cs(7271,137): error CS0100: The parameter name `size' is a duplicate
modshogunPINVOKE.cs(17102,255+): error CS0100: The parameter name `size' is a duplicate
modshogunPINVOKE.cs(17888,190): error CS0100: The parameter name `size' is a duplicate
modshogunPINVOKE.cs(17891,190): error CS0100: The parameter name `size' is a duplicate
modshogunPINVOKE.cs(19190,192): error CS0100: The parameter name `size' is a duplicate
```

Is there an easy fix for this?

**Comment by tpokorra** [comment]
I found http://www.shogun-toolbox.org/page/contact/irclog/2014-07-30/ which describes that ignoring the methods in modshogun_ignores.i should resolve the issue.

Is this still appropriate?

**Comment by tpokorra** [comment]
based on the reply from the swig issue referenced above, it seems that shogun is using the inattributes in a way that cannot work if there are multiple parameters of type array:

    %typemap(ctype, out="CTYPE*") shogun::SGVector<SGTYPE> %{int size_$1, CTYPE*%}
    %typemap(imtype, out="IntPtr", inattributes="int size, [MarshalAs(UnmanagedType.LPArray)]") shogun::SGVector<SGTYPE> %{CSHARPTYPE[]%}

I tried to reproduce a test case with swig, but I have to admit I only got so far to see the existing tests for arrays.

    git clone https://github.com/swig/swig.git
    cd swig
    ./autogen.sh
    ./configure --without-go --without-guile --without-java --without-javascript --without-ocaml --without-octave --without-perl5 --without-python  --without-python3 --without-r --without-ruby --without-tcl
    make
    make check
    cd Examples
    find . -type f -name \* -exec grep 'UnmanagedType.LPArray' {} \; -print
    vi ./csharp/arrays/examplePINVOKE.cs
    vi ./test-suite/csharp/csharp_lib_arrays/csharp_lib_arraysPINVOKE.cs

There you can see how the tests do it. It seems that the original method already has an extra parameter for the array size.

I think I will have to stop this investigation here. Please can someone with more knowledge about shogun pick up from here?

**Comment by vigsterkr** [comment]
@tpokorra thanks a lot for digging into this! i'll try to see what i can do about it and get back to you asap

**Comment by tpokorra** [comment]
any news on this?
I also tried the workaround, to just ignore the methods in `modshogun_ignores.i` 
But it seems I have no idea what the syntax is.

to ignore

```
  [global::System.Runtime.InteropServices.DllImport("modshogun", EntryPoint="CSharp_new_IndexBlockTree__SWIG_3")]
  public static extern global::System.IntPtr new_IndexBlockTree__SWIG_3(int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg1, int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg2);
```

what is the correct line in `modshogun_ignores.i`? I tried these but it did not work:

```
%ignore shogun::IndexBlockTree::IndexBlockTree;
%ignore shogun::IndexBlockTree::new;
```

**Comment by lisitsyn** [comment]
As of 038280845fd7fb886f4459996f1405f8ca8c1612 we require SWIG 3.0.7 which supports a feature that is being used by 7b7e1f3dbfae13877819c00b0f612a9a0af3b464 to overcome this problem in general.

Thanks, @tpokorra!

**Comment by tpokorra** [comment]
Great, Thanks lisitsyn!
