### ISSUE TITLE
why do we need separate job for OpenCV on travis

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#2431]
@pickle27 @kislayabhi

ok so i'm a bit concerned. running a travis job is already very long and now we've introduced a *sperate* job for opencv. here are some of my concerns:
 * why does it have to be a separate job, why can't that be part of either of the existing ones?
 * why does it have to be compiled by `gcc` (as it's proven to be slower than `clang`)
 * why does it have to be in `Debug` mode?

**Comment by erip** [comment]
Recommend closing this issue: OpenCV is no longer in the travis builds.
