### ISSUE TITLE
A general data structure for n-dimensional arrays

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2534]
I think we should re-think the array data structures we have. Most other libraries have a general tensor notation, including views. In particular, we should investigate how we can use external code for this.

Main functions should be
- Easy data structure for I/O over interfaces.
- Support for views and slices so that we for example dont have to copy things around when we do subsets of dimensions, see @lambday in #2530

Or can we solve this otherwise somehow? In any case, we should aim for some major clean ups there. The current SGMatrix structure is polluted with lots of linear algebra operations, and not very flexible.

**Comment by mohit9727** [comment]
@karlnapf I would like to take this issue, how to start working ?

**Comment by karlnapf** [comment]
This is nontrivial, please only attempt if you have an idea what you are doing.
Googling libraries for this is the first step. Note that we want just memory management of such structures, math operations will be done via `linalg`
