### ISSUE TITLE
Remove the Changelog

### ISSUE THREAD

**Issue by jondo** [shogun-toolbox/shogun#2545]
I just cloned shogun and got a 5 MB Changlog file, generated from Git. WTF? Please delete this redundant monster :^) Whoever needs this should just use `git log` or [browse/search GitHub](https://github.com/shogun-toolbox/shogun/commits/).

In earlier times (before commit 931e91 in 2011), this file contained hand-edited "What's new" information. This role is now taken by the NEWS file.

**Comment by jondo** [comment]
Do you need a pull request? :-)

**Comment by iglesias** [comment]
Thanks for the heads-up, @jondo. I have now deleted the file.
