### ISSUE TITLE
Remove easysvm tarballs from Repository?

### ISSUE THREAD

**Issue by jondo** [shogun-toolbox/shogun#2546]
The tarballs in `applications\easysvm\dist` seem to be obsolete,because they became corrupted by commit f9a526 "fix trailing and before tab whitespace" in October 2013, and no one cared since.

**Comment by vipints** [comment]
@karlnapf I have tested easysvm against shogun stable release version 3.2.0. All tests passed without any error messages. https://github.com/vipints/oqtans/tree/master/oqtans_tools/EasySVM/0.3.3/ 

I will be pushing this changes to my shogun-dev  soon., 

happy new year!

**Comment by jondo** [comment]
All EasySVM tarballs are available [here](http://www.easysvm.org/releases). Would you accept a pull request that removes the corrupted ones?

**Comment by iglesias** [comment]
Definitely. Let's get rid of them. Waiting for your pr.

**Comment by jondo** [comment]
The sibling directory `applications/easysvm/dependencies/` contains two tar.gz archives (old versions of [ANTLR](http://www.antlr3.org/) and [arff](https://pypi.python.org/pypi/arff)) that also became corrupted at the same commit. I think I can remove those, too.

**Comment by jondo** [comment]
> Waiting for your pr.

It's #2921.
