### ISSUE TITLE
removing -DHAVE_PTHREAD leads to compile time error

### ISSUE THREAD

**Issue by AlexBinder** [shogun-toolbox/shogun#2549]
solution:

The solution which worked for me, was:

put in InputParser.h and ParseBuffer.h
# ifdef HAVE_PTHREAD

//pthread_code
# else

```
SG_SERROR("CInputParser requires -DHAVE_PTHREAD during compile time.\n")
```
# endif

around the relevant code parts. furthermore ParseBuffer.h required a
# ifdef HAVE_PTHREAD
# endif

around some pointers with naming pthread_\* in the protected: section

This compiles at least, and whoever would use Vowpal wabbit, would get an error message.

Alex

**Comment by vigsterkr** [comment]
done
