### ISSUE TITLE
Check for includes in header files

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2557]
What about adding a simple check to cmake that scans all Shogun header files for includes that are not coming from Shogun? This way, we could for example avoid to have Eigen3 includes in headers -- Shogun just wont compile in that case. Would maybe save us some trouble

In fact, this is also an entrace task: remove all non-shogun includes from header files and move to implementation .cpp files

**Comment by spandan1234** [comment]
i tried to compile the shogun file after building it using cmake. But I am encountering error. The details of compilation is as follows:
[ 79%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/libncbm.cpp.obj
[ 79%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/libp3bm.cpp.obj
[ 79%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/libppbm.cpp.obj
[ 79%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MAPInference.cpp.obj
[ 79%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MulticlassModel.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MulticlassSOLabels.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MultilabelCLRModel.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MultilabelModel.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/MultilabelSOLabels.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/Plif.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/PlifArray.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/PlifMatrix.cpp.obj
[ 80%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/PrimalMosekSOSVM.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/SegmentLoss.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/SequenceLabels.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/SOSVMHelper.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/StateModel.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/StochasticSOSVM.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/StructuredModel.cpp.obj
[ 81%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/structure/TwoStateModel.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/domain_adaptation/DomainAdaptationMulticlassLibLinear.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/domain_adaptation/DomainAdaptationSVM.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/domain_adaptation/DomainAdaptationSVMLinear.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/LibLinearMTL.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskClusteredLogisticRegression.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskLeastSquaresRegression.cpp.obj
[ 82%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskLinearMachine.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskLogisticRegression.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskROCEvaluation.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskTraceLogisticRegression.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/Task.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/TaskGroup.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/TaskTree.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIClassifier.cpp.obj
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIConverter.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIDistance.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIFeatures.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIHMM.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIKernel.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUILabels.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIMath.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIPluginEstimate.cpp.obj
[ 84%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIPreprocessor.cpp.obj
[ 85%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUIStructure.cpp.obj
[ 85%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/GUITime.cpp.obj
[ 85%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/ui/SGInterface.cpp.obj
[ 85%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/dSFMT/dSFMT.c.obj
[ 85%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/PMurHash.c.obj
[ 85%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/SFMT/SFMT.c.obj
[ 85%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.obj
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:15:1: error: ‘REPLACE’ does not name a type
 REPLACE includes THIS
 ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:19:1: error: ‘REPLACE’ does not name a type
 REPLACE definitions THIS
 ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:30:2: error: ‘new_sgserializable_t’ does not name a type
  new_sgserializable_t m_new_sgserializable;
  ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:35:1: error: ‘REPLACE’ was not declared in this scope
 REPLACE struct THIS
 ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:35:9: error: expected ‘}’ before ‘struct’
 REPLACE struct THIS
         ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:35:9: error: expected ‘,’ or ‘;’ before ‘struct’
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:37:1: error: expected declaration before ‘}’ token
 };
 ^
F:/Users/SPANDAN/Compressed/shogun/New folder/shogun-4.0.0/src/shogun/base/class_list.cpp:34:27: warning: ‘class_list’ defined but not used [-Wunused-variable]
 static class_list_entry_t class_list[] = {
                           ^
src/shogun/CMakeFiles/libshogun.dir/build.make:16403: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.obj' failed
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.obj] Error 1
CMakeFiles/Makefile2:116: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2


after 85% the compilation stops with this error. I can't understand if I have to change anything in the class_list.cpp file or what?
