### ISSUE TITLE
Reduce complexity of headers with d-pointers and "only declaration" rule

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#2564]
I propose to change:

``` cpp

class CClass
{
public:
  void method();
  int get_field() const
  {
    return field;
  }
private:
  int m_field;
};

// .cpp

void CClass::method()
{
   .. m_field ..
}
```

to a better looking (and faster compiling) variant:

``` cpp

class CClass 
{
public:
    void method();
    int get_field() const;
private:
    class Self;
    Unique<Self> self;
};

// .cpp

class CClass::Self
{
  int m_field;
};

CClass::get_field()
{
  return self->m_field;
}

CClass::method()
{
   .. get_field(); ..
}

```

It would involve massive refactoring so should be done once and fast. One thing that comes for free - in our code we will not use member variables w/o getters anymore (which is considered good). ~~Another advantage is that very likely SWIG will compile much faster.~~

I think possible approach involves writing some script instead of doing it manually.

**Comment by iglesias** [comment]
@lisitsyn, why is it good not to use member variables w/o getters (and setters too, I guess) within the class where they are members?

**Comment by lisitsyn** [comment]
@iglesias I'd say it is more flexible

**Comment by iglesias** [comment]
I am not sure what flexible is here. Can you put an example, @lisitsyn? :-)

**Comment by karlnapf** [comment]
why does this compile faster?

**Comment by lisitsyn** [comment]
Okay guys a few cases that come into my mind:

1. If we go with generic get/set without specific getters for field adding a new field is free - you just recompile the .cpp file (@iglesias).
2. In the same scenario headers are binary compatible with various versions of shogun (@iglesias).
3. We can remove *all* mentions of std vector/list/.. from headers because they are only in .cpp files so it will be faster (@karlnapf).
4. We can probably use simpler saving/loading that just works with that subobject (declared in .cpp) but not the object (declared in .h) - that's a thing I am thinking about yet.

**Comment by karlnapf** [comment]
+1 from my side to all this

**Comment by iglesias** [comment]
It sounds pretty awesome!

**Comment by iglesias** [comment]
Thanks a lot for the nice description, @lisitsyn :-)

**Comment by vigsterkr** [comment]
obsolete
