### ISSUE TITLE
Clean up doxygen documentation

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2599]
Shogun uses doxygen for documentation purposes, the results are at
http://www.shogun-toolbox.org/doc/en/latest/index.html

The way this documentation is generated is via automatic doxygen, and a number of python scripts (that for example insert examples into the doxygen pages)

There are number of issues here:
 * Most things are horribly outdated (authors, implemented methods, install, etc)
 * The way code is put into documentation (for say the examples) is hacky: A python script just dumps all code into the doxygen page
 * This is really hard to maintain due to its complexity

Since this page is the portal for most people to start using Shogun, we should really do something about this.

High level suggestions:
 * Somehow merge all the Readmes, github wiki, and this documentation, to only have *one* ressource to maintain (which then can be displayed at multiple places). Preferable the README.md files which are already linked to the github wiki.
 * Handle example documentation and code in doxygen properly, see #2600

Action items:
 * Find a way to generate a MD (or doxygen) page from a source file - converting all comments to MD style content in the page. DONE ins #2600 2600
 * Make the doxygen pages include text from README's aka the github wiki, so that changes in the wiki directly are merged in our documentation page

**Comment by Eejya** [comment]
Hi, is this still open ?

**Comment by karlnapf** [comment]
This has changed a lot due to the new cookbook. 
Eventually we will remove the documentation part of doxygen (apart from maybe class docs), and move to something else. The current version is broken as well
Closing for now...
