### ISSUE TITLE
Compile problem building 3.2.0 

### ISSUE THREAD

**Issue by hippozhu** [shogun-toolbox/shogun#2624]
Hi all,

I ran 
"ccmake .. -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DPythonModular=ON"

and changed the system's default compiler to newer versions (gcc, g++ 4.9.0) in my home directory.

I got the following error:

In file included from /home/yzhu7/.local/include/c++/4.9.0/complex.h:36:0,
                 from /home/yzhu7/.local/include/openblas_config.h:93,
                 from /home/yzhu7/.local/include/cblas.h:5,
                 from /home/yzhu7/Downloads/shogun-3.2.0/src/shogun/mathematics/lapack.h:37,
                 from /home/yzhu7/Downloads/shogun-3.2.0/src/shogun/distributions/Gaussian.h:21,
                 from /home/yzhu7/Downloads/shogun-3.2.0/src/shogun/clustering/GMM.h:18,
                 from /home/yzhu7/Downloads/shogun-3.2.0/src/shogun/base/class_list.cpp:105:
/home/yzhu7/Downloads/shogun-3.2.0/src/shogun/lib/external/libqp.h:61:29: error: expected ‘,’ or ‘...’ before ‘(’ token
                   uint32_t *I,
                             ^
src/shogun/CMakeFiles/libshogun.dir/build.make:2336: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o' failed
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
CMakeFiles/Makefile2:229: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

I am even not able to find out where this libqp.h is included.
Is it about the c++ compiler's flags setting?
Any idea would help.

Thanks!

**Comment by nachitoys** [comment]
I have the same problem!!!

**Comment by karlnapf** [comment]
Also with the latest version?

**Comment by nachitoys** [comment]
Yes, however, I have been running Lubuntu. When I installed Ubuntu the problem disappeared. I is really weird..

**Comment by karlnapf** [comment]
ok, well then we can close this.
