### ISSUE TITLE
Shogun Matlab Interface Error

### ISSUE THREAD

**Issue by yalcinm** [shogun-toolbox/shogun#2634]
![shogun-1](https://cloud.githubusercontent.com/assets/8990567/5422672/e246b1fa-8244-11e4-9b3f-4d80d058cf5b.png)
![shogun-2](https://cloud.githubusercontent.com/assets/8990567/5422673/e53c2db8-8244-11e4-8dca-616f959798ed.png)
![shogun-3](https://cloud.githubusercontent.com/assets/8990567/5422674/e69f3ac4-8244-11e4-8481-82dbaf48c6bc.png)
![shogun-4](https://cloud.githubusercontent.com/assets/8990567/5422675/e84eeab8-8244-11e4-9c3c-9a57c130448c.png)
![shogun-5](https://cloud.githubusercontent.com/assets/8990567/5422676/e9a882ac-8244-11e4-9b4a-8ac24be7031a.png)

I'm trying to install **Matlab Static Interface** on **Ubuntu** and I've **Matlab R2014b**. I followed the installation instructions on https://github.com/shogun-toolbox/shogun/wiki/INSTALL

`$ mkdir build && cd build`
`$ cmake -DMatlabStatic=ON ..`
`$ make`
`$ sudo make install`

First, I got the following error after "`make`" command;
**`Unknown MEX argument '-o'.`**

I searched for it and found out that R2014b requires "`-output`" instead of "`-o`", so I went to build.make file and changed "`-o`" to "`-output`".

Then I tried make again, and I got the following error;
**`Unknown file extension '.16'.`**

What should I do?

**Comment by beew** [comment]
Any news here? I have encountered the same situation.  First I got
```
Unknown MEX argument '-o'.
```
Then after changing '-o' to '-output' in shogun/src/interfaces/matlab_static and rebuild got
```
Unknown file extension '.1'.
```

**Comment by BrendenWashington** [comment]
Any news here? I have encountered the same problem. First I got

Unknown MEX argument '-o'.

Then after changing '-o' to '-output' in shogun/src/interfaces/matlab_static and rebuild got

Unknown file extension '.1'.

I encount the same problem while I compile shogun---a machine learning framework

does any body know how to fix it ?

**Comment by amroamroamro** [comment]
I'm not a CMake expert, but the `$<TARGET_SONAME_FILE:shogun>` [part][1] is not right. This needs to be something that returns the flag `-lshogun`.

Also `mex -o sg ..` needs to be changed as `mex -output sg ..` for MATLAB. Octave seems to use the `-o` option instead.

[1]: https://github.com/shogun-toolbox/shogun/blob/develop/src/interfaces/matlab_static/CMakeLists.txt

**Comment by karlnapf** [comment]
This is only the static interfaces and is deprecated .... only half of shogun is exposed through this.

**Comment by karlnapf** [comment]
Ah man what are all these screenshots up there?
