### ISSUE TITLE
Unable to build R-modular interface

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#2654]
Hi,

I tried to build the R-modular interface but make failed 

> [100%] [100%] Building CXX object src/interfaces/r_modular/CMakeFiles/r_modular.dir/sg_print_functions.cpp.o
Building CXX object src/interfaces/r_modular/CMakeFiles/r_modular.dir/modshogunR_wrap.cxx.o
In file included from /home/bee/opt/hdf5/include/hdf5.h:24:0,
                 from /home/bee/Downloads/shogun-develop/src/shogun/io/HDF5File.h:19,
                 from /home/bee/Downloads/shogun-develop/build/src/interfaces/r_modular/modshogunR_wrap.cxx:3085:
/home/bee/opt/hdf5/include/H5public.h:198:33: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
 #   define H5_PRINTF_HADDR_FMT  "%"H5_PRINTF_LL_WIDTH"u"
                                 ^
Linking CXX shared module modshogun.so
Generating modshogun.RData
 f="modshogun.R"; fdata="modshogun.RData"; source ( f ) ; save ( list=ls ( all=TRUE ) ,file=fdata, compress=TRUE ) ; q ( save="no" ) 
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'modshogun.R': No such file or directory
Execution halted
make[2]: *** [src/interfaces/r_modular/modshogun.so] Error 1
make[1]: *** [src/interfaces/r_modular/CMakeFiles/r_modular.dir/all] Error 2
make: *** [all] Error 2

Tried both shogun 3.2.0 and developement version. R-static interface built fine though. 

R version 3.1.2, OS is Ubuntu 14.04 64 bit.

Thanks for help in advance.

**Comment by beew** [comment]
> Maybe we could add this to one of the Readmes. Feel free to send a little patch.
Let us know how things go from now!

Getting back a little late since I have not been using shogun's R interface 

I don't know how to fix the codes or make a patch but the problem I think is in

shogun/src/interfaces/r_modular/CMakeLists  

More  precisely these lines

```
ADD_CUSTOM_COMMAND(TARGET r_modular
	POST_BUILD
	COMMAND echo 'f="modshogun.R" \; fdata="modshogun.RData" \; source( f ) \; save( list=ls( all=TRUE ) , file=fdata , compress=TRUE ) \; q( save="no" ) \;' | ${R_EXECUTABLE} --silent --no-save
	WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
	COMMENT "Generating modshogun.RData"
)
```
What follow COMMAND echo are basically commands to be executed in R. When R  runs its work directory is given by the function getwd(), in my case this will return the value in ~/.RProfile, which is not my $HOME but a subdirectory of it. I can imagine others may want to set their default R work directory like this too instead of dumping R outputs all over their $HOME

The CMAKE option WORKING_DIRECTORY apparently cannot override the value in ~/.RProfie, so when the shogun build process executes R, it is looking for modshogun.R in WORK_DIRECTORY, which is it's default work directory (defined by .RProfie)  rather than ${CMAKE_CURRENT_BINARY_DIR}

Here is my take on it, maybe someone who knows his C++ can just edit these lines so that people don't get tripped over on this little thing in the future (I tried but didn't work)

**Comment by besser82** [comment]
@beew: Can you confirm the referenced patch works?

**Comment by beew** [comment]
I am happy to test it but I don't know where the source code is, the development branch has not been updated.

**Comment by beew** [comment]
Just saw the link to your change so I manually edited the file. It works.

**Comment by besser82** [comment]
Issue resolved.
