### ISSUE TITLE
octave interfaces and openmpi

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#2666]
Hi, 

This is probably related to https://github.com/shogun-toolbox/shogun/issues/1856, which has been closed. 

When octave is compiled with libhdf5-openmpi Shogun's octave interfaces (static and modular) don't build even if hdf5 is disabled in shogun (thanks to karlnapf's patch). OS is Ubuntu 14.04. 64 bit. Octave 3.8.2

Here are the errors

>In file included from /home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:154:0:
/usr/local/include/octave-3.8.2/octave/oct.h:31:20: fatal error: config.h: No such file or directory
#include config.h
^
compilation terminated.
In file included from /usr/include/hdf5.h:24:0,
from /usr/local/include/octave-3.8.2/octave/oct-hdf5.h:27,
from /usr/local/include/octave-3.8.2/octave/ov.h:42,
from /home/bee/Downloads/shogun/src/interfaces/octave_modular/sg_print_functions.cpp:3:
/usr/include/H5public.h:63:20: fatal error: mpi.h: No such file or directory
#include mpi.h
compilation terminated.
make[2]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/sg_print_functions.cpp.o] Error 1
make[1]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all] Error 2
make: *** [all] Error 2

**Comment by iglesias** [comment]
This comment does not help to solve your problem; I am going to have a closer look right away and let you know if I can add something which may be helpful. Anyway, why do you want to have both Octave modular **and** static interfaces enabled? If you can afford modular (i.e. having Swig) just use it and ignore static.

**Comment by beew** [comment]
Hi,

Thanks for taking a look. No, I am not trying to have both enabled. I have tried one after another, just saying that neither can be enabled.

Cheers.

**Comment by AlexLuya** [comment]
some problem here,any progress?

**Comment by AlexLuya** [comment]
(Caution:my octave version is 3.8.1)
I think it may be an octave issue,after modifying two files:
/usr/include/octave-3.8.1/octave/oct.h     line 31:#include <config.h>       ----->   #include "config.h"
/usr/include/octave-3.8.1/octave/oct.h     line 28:#include <base-list.h>   ----->   #include "base-list.h"
compilation passed without error.

**Comment by iglesias** [comment]
In my case (Octave 3.8.2), the second change is in the file comment-list.h, not in oct.h.

**Comment by iglesias** [comment]
After making the changes suggested above, you may still run into the trouble

```
$octave_root_dir/include/octave-3.8.2/octave/oct-hdf5.h:27:18: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
```

because it seems that octave sets `HAVE_HDF5` if it finds hdf5 in your system, no matter the dev package is installed or not. Of course, you can solve this by installing the dev hdf5 package.

In any case, this is an Octave issue rather than a Shogun issue.
