### ISSUE TITLE
bug in SGVector 

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2687]
```
SGVector<float64_t> catchbug()
{
	SGMatrix<float64_t> a(2,2);
	a.set_const(-0.05);
	SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols, false);
	return tmp;
}
int main(int argc, char** argv)
{
	init_shogun_with_defaults();
	SGVector<float64_t> ok=catchbug();
	Map<VectorXd> out(ok.vector, ok.vlen);
	std::cout<<out<<std::endl;
	exit_shogun();
	return 0;
}
```
Result in my laptop is
```
4.94066e-324
4.94066e-324
-0.05
-0.05
```

**Comment by yorkerlin** [comment]
I guess this bug is related to `SGVector<float64_t> ok=catchbug();`

**Comment by yorkerlin** [comment]
@karlnapf 
@lisitsyn 
take a look at this bug.

**Comment by yorkerlin** [comment]
@karlnapf 
I spend an hour to find this bug when I refactored the FITC kernels

**Comment by iglesias** [comment]
I am not sure I'd say this is a bug. It might be bad usage of SGVector; you are returning a reference to some memory with local scope only in the function `catchbug`.

**Comment by iglesias** [comment]
@yorkerlin, can you try with this version?

```
SGVector<float64_t> catchbug()
{
	SGMatrix<float64_t> a(2,2,false);
	a.set_const(-0.05);
	SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols);
	return tmp;
}
```

**Comment by yorkerlin** [comment]
It works! Thanks!
I think the auto ref technique in shogun is class-sensitive.

On Friday, January 30, 2015, Fernando Iglesias <notifications@github.com>
wrote:

> @yorkerlin <https://github.com/yorkerlin>, can you try with this version?
>
> SGVector<float64_t> catchbug()
> {
>     SGMatrix<float64_t> a(2,2,false);
>     a.set_const(-0.05);
>     SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols);
>     return tmp;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2687#issuecomment-72163932>
> .
>


-- 
best,

wu lin

**Comment by iglesias** [comment]
What do you mean with class-sensitive? :-)

**Comment by yorkerlin** [comment]
auto ref counts the reference in a class (eg, SGVector)

**Comment by yorkerlin** [comment]
btw @iglesias 
In fact, my question is 
```
SGMatrix<float64_t> fun()
{
	SGMatrix<float64_t> ok(2,2);
	return ok;
}
SGVector<float64_t> catchbug(){
	SGMatrix<float64_t> a=fun();
	a.set_const(-0.05);
	SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols);
	return tmp;
}
int main(int argc, char** argv)
{
	init_shogun_with_defaults();
	//demo7();
	SGVector<float64_t> ok=catchbug();
	Map<VectorXd> out(ok.vector, ok.vlen);
	std::cout<<out<<std::endl;
	exit_shogun();
	return 0;
}
```
If I am not allowed to change the content of `fun()`, can I still this `SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols);` trick? If not, I have to copy the `a` matrix.

**Comment by iglesias** [comment]
It doesn't count the reference in a class (that is, m_refcount is not a static member) but above when you are creating the first SGVector it has no way of getting to know the refcount object of SGMatrix.

**Comment by iglesias** [comment]
So, in the case you cannot change the content of `fun`, I think the issue is that we would like to share the same RefCount object between a SGMatrix and a SGVector. I don't see how we can do this with the current API. We could introduce a new constructor in SGVector that takes an SGMatrix to do this but I am not sure this might bite us somewhere else.

@lisitsyn, @lambday, what do you guys think? Maybe I am missing something, have a look at this issue please.

**Comment by lambday** [comment]
@yorkerlin the trick is, when an SGReferencedData is assigned/copied, it increases the refcount and just copies the pointer, therefore uses the same memory. When it gets destroyed, refcount is reduced, if it reaches 0, then it destroys the memory pointed by it. So, the problem arises because
```c++
// I can't run this example right now, but I'm guessing if we gdb it, this is what we should get
SGMatrix<float64_t> fun()
{
    SGMatrix<float64_t> ok(2,2); // ok.ref_count = 0
    ok.set_const(-0.05);
    return ok;
}
SGVector<float64_t> catchbug(){
    SGMatrix<float64_t> a=fun(); // a.ref_count = 1, points to the same memory as ok
    SGVector<float64_t> tmp(a.matrix, a.num_rows*a.num_cols); // tmp.ref_count = 0
    return tmp; // destroying a, a.ref_count = 0, destroying the memory pointed by the a
}
int main(int argc, char** argv)
{
    init_shogun_with_defaults();
    //demo7();
    SGVector<float64_t> ok=catchbug(); // ok.ref_count = 1 but dangling pointer
    Map<VectorXd> out(ok.vector, ok.vlen);
    std::cout<<out<<std::endl;
    exit_shogun();
    return 0; // destroying tmp, tmp.ref_count = 0, invalid free error
}
```

I think you can just use vector map with matrix memory because using SGVector you're trying to achieve just that. IMO you can try with this
```c++
SGMatrix<float64_t> fun()
{
    SGMatrix<float64_t> ok(2,2);
    ok.set_const(-0.05);
    return ok;
}
SGVector<float64_t> catchbug(){
    SGMatrix<float64_t> a=fun();
    // do stuffs
    return a;
}
int main(int argc, char** argv)
{
    init_shogun_with_defaults();
    //demo7();
    SGMatrix<float64_t> ok=catchbug();
    Map<VectorXd> out(ok.matrix, ok.num_rows * okl.num_cols);
    std::cout<<out<<std::endl;
    exit_shogun();
    return 0;
}
```
Shogun matrices are col-major so I think this should work!

**Comment by yorkerlin** [comment]
@lambday 
If we do not change the return types of  `fun()` (SGMatrix) and `catchbug()` (SGVector),  it is not easy to deal with this issue. .

I try to run your solution, the compiler issues the following error.
`error: conversion from ‘shogun::SGVector<double>’ to non-scalar type ‘shogun::SGMatrix<double>’ requested`

**Comment by lambday** [comment]
Ah that would totally be SGMatrix. My bad! Also, I edited my answer regarding under the hood refcount. Please check  that also.

**Comment by yorkerlin** [comment]
@lambday 
Yes, if we can modify the signature of `catchbug()` (that is the return type), the issue is solved.
If we can not modify the signature, for now I have to copy SGMatrix to SGVector. 
```
SGMatrix<float64_t> fun()
{
    SGMatrix<float64_t> ok(2,2);
    ok.set_const(-0.05);
    return ok;
}
SGVector<float64_t> catchbug(){ // EDIT, the return type would be SGMatrix, sorry for typo
    SGMatrix<float64_t> a=fun();
    SGVector<float64_t> res = copy_from(a);
    return res;
}
int main(int argc, char** argv)
{
    init_shogun_with_defaults();
    SGMatrix<float64_t> ok=catchbug();
    Map<VectorXd> out(ok.vector, ok.num_rows * ok.num_cols);
    std::cout<<out<<std::endl;
    exit_shogun();
    return 0;
}
```

**Comment by lambday** [comment]
@yorkerlin if serves your purposes, you can disable refcounting in the original matrix and just have refcount from the vector.
```c++
SGMatrix<float64_t> fun()
{
    SGMatrix<float64_t> ok(2,2, false);
    ok.set_const(-0.05);
    return ok; 
}
SGVector<float64_t> catchbug(){
    SGMatrix<float64_t> a=fun();
    SGVector<float64_t> tmp = SGVector<float64_t>(a.matrix, a.num_rows*a.num_cols);
    return tmp;
}
int main(int argc, char** argv)
{
    init_shogun_with_defaults();
    SGVector<float64_t> ok=catchbug();
    Map<VectorXd> out(ok.vector, ok.vlen);
    std::cout<<out<<std::endl;
    exit_shogun();
    return 0;
}
```

**Comment by lambday** [comment]
@iglesias I think having a SGMatrix constructor in SGVector that shares same refcount object won't cost much. It might also be useful to represent just one column of SGMatrix as some SGVector, sharing the same memory.

**Comment by yorkerlin** [comment]
@lambday 
Your idea is fine if `fun()` is a private method. In my case, `fun()` is a public method in a class and is used in a standard way.

If we disable refcounting,  does it mean that users who use this method have to take good care of it? 
eg,in the following example, I do not want to change the exiting code in `fun2()`

```
SGMatrix<float64_t> fun()
{
    SGMatrix<float64_t> ok(2,2);
    ok.set_const(-0.05);
    return ok; 
}

SGMatrix<float64_t> fun2() 
//fun() is used in many existing classes (eg, fun2()).  If I use SGMatrix<float64_t> ok(2,2,false) in fun(), do you think whether fun2() should take care of this modification?
{
    SGMatrix<float64_t> a=fun();
   //do stuff
    return a; 
}

SGVector<float64_t> catchbug(){
    SGMatrix<float64_t> a=fun();
    SGVector<float64_t> tmp = SGVector<float64_t>(a.matrix, a.num_rows*a.num_cols);
    return tmp;
}
int main(int argc, char** argv)
{
    init_shogun_with_defaults();
    SGVector<float64_t> ok=catchbug();
    Map<VectorXd> out(ok.vector, ok.vlen);
    std::cout<<out<<std::endl;
    exit_shogun();
    return 0;
}
```

**Comment by lambday** [comment]
Actually, yes - depending on what you do inside fun2. You also need to take care of freeing the memory manually, if that memory is not mapped by some already SGReferencedData instance with refcounting turned on (since SGVector shared same memory here with its own refcounting enabled, it took care of freeing that part). If you don't want to do that, I guess that it is safest that you copy.

**Comment by yorkerlin** [comment]
@lambday 
Thanks, I use `copy` for now until the API supports the following features.
* from SGVector to SGMatrix with auto refcounting
* from SGMatrix to SGVector with auto refcounting

**Comment by lambday** [comment]
@yorkerlin yeah these might be useful. Let's see what @sonney2k @karlnapf @lisitsyn @iglesias say regarding this. Even for copying, `std::copy` is pretty fast :)

**Comment by iglesias** [comment]
I don't have anything against introducing these convenience methods; but still we should keep it simple and do not add lot of clutter (many methods). Maybe one constructor for SGVector from SGMatrix and vice versa and that's all.

But also, I would like to knowthe use case, @yorkerlin. Why do you need to transform the SGMatrix to SGVector in your algorithm? Is it a nonsense to just keep the data in matrix form?

**Comment by yorkerlin** [comment]
@iglesias 
in `./src/shogun/machine/gp/InferenceMethod.cpp`
```	
virtual SGVector<float64_t> get_derivative_wrt_inference_method(
			const TParameter* param)=0;
```
SGVector is fine if non-FITC inference. 
However, for FITC inference indeed the derivative is a matrix.

**Comment by yorkerlin** [comment]
@iglesias 
All GP inference methods and unit tests are based on this API.
I cannot change API. Otherwise, I have to modify all GP source codes.

**Comment by lambday** [comment]
@iglesias I agree. BTW we already have a `T* get_column(index_t)` method in SGMatrix. Would it be fine to make it return a SGVector instead? Its safer actually I think.

**Comment by iglesias** [comment]
Definitely. That method should return a SGVector instead.

**Comment by lambday** [comment]
@iglesias alright. Maybe I'll add the things @yorkerlin needed (one constructor in SGVector and SGMatrix each, sharing the refcount) which will spare him the copying - as well as modification to get_column_vector method. the SGVector it would return will also share the refcount with the original matrix.

**Comment by karlnapf** [comment]
Please support @yorkerlin   with his operations, he writes the most amazing variational GP codes with them :) But of course, too much cluttering is not good either.
