### ISSUE TITLE
Make GPUMatrix compatible with new ViennaCL (1.6.x) matrix_base

### ISSUE THREAD

**Issue by lambday** [shogun-toolbox/shogun#2690]
In the new ViennaCL (1.6.x), [matrix_base](http://viennacl.sourceforge.net/doc/classviennacl_1_1matrix__base.html) takes 3 template parameters instead of 4, which makes compilation fail due to its usage [here](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/GPUMatrix.h#L81).

**Comment by vigsterkr** [comment]
fixed
