### ISSUE TITLE
Make C++11 support mandatory for Shogun 4.x.x

### ISSUE THREAD

**Issue by lambday** [shogun-toolbox/shogun#2719]
Let's vote here. Immediate benefits -
- We can use all the cool stuffs in `linalg` without having to worry about `HAVE_CXX11` guards
- @lisitsyn can use `std::shared_ptr` for `Some`
- GSoC students can use cool C++11 things this year only - for_each, lambdas, type traits.

@iglesias and @karlnapf are already on board. @vigsterkr @sonney2k @lisitsyn @besser82 what do you think? We just say that in order to build Shogun v4.x.x, you **got** to have a C++11 supported compiler - I don't see any harm in that.

**Comment by iglesias** [comment]
+1. See also #2711.

**Comment by sonney2k** [comment]
We can do that. I am sure that it will make shogun not compile on some cc's and archs. But we have to name the release that requires it 5.0!

So Ok from my side.

**Comment by karlnapf** [comment]
+1 And also on the renaming, which is true.

**Comment by iglesias** [comment]
Shall we do a 5.0 release soon then so from pre-gsoc time people can start
using c++11 with no problem?

What does Viktor think?

**Comment by lambday** [comment]
@vigsterkr @lisitsyn @besser82 ?? 
I'll vote for pre-gsoc. Its redundant to write *useful things* from scratch when we *have it there already* in c++11. Of course we can write those on our own but 
(1) they need to be properly tested for bugs which is tricky sometimes.
(2) students will feel more comfy with existing c++ stuffs.

**Comment by karlnapf** [comment]
Lets move soon. But not sure whether we should do another release before GSoC.
5.0 after GSoC is fine.

If you want to release before this switch, also good! But we did not fix too many things since then right?
Releasing as often as possible is a good practice though

**Comment by lambday** [comment]
5.0 is a bit too much for just this change I think! :D 
major version change should include some *major* modification I think! how about we do it in our next cleaned up version within 4.x.x.?

**Comment by iglesias** [comment]
In 4.x.x. sounds good to me. Soeren, any reason why it should be 5.0?

**Comment by karlnapf** [comment]
Requiring a new standard is a major change in my eyes too. But well, it is a matter of taste, just change it in the Dev branch and we can discuss numbers later

**Comment by sonney2k** [comment]
@lambday Well just require C++11 from now on but don't do a release until it's ready. So no need to do things twice/cumbersome.

If we have bugfixes - lets make a 4.0.X release.

**Comment by lambday** [comment]
Already resolved. Closing.
