### ISSUE TITLE
Human readable output of models

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#2728]
We can support human readable output of models so user can evaluate what features are important or not. With #2727 it could be quite useful: one would be able to port the trained model to some simple thing (say put learnt linear SVM to your excel spreadsheet).

Suggested by kingsley_ in irc.

@karlnapf @lambday @sonney2k @vigsterkr @kevinhughes27 tell me what you think

**Comment by iglesias** [comment]
It sounds quite nice. I see it very useful to use for the output of feature selection algorithms (like LMNN).

**Comment by kevinhughes27** [comment]
could be cool!

**Comment by karlnapf** [comment]
Like it, but this is not easily interpreted for example for SVMs.
Good for feature selectors as @iglesias said.

But, this is again something that is super easily done in a target language and increases complexity of our codes. So not sure whether its worth it.

We should rather use some data-storing backend to do such things. Like reading features of a HDF5 frame aka python-pandas. That would be a more sophisticated solution which also has the advantage that its done properly. To me, such ideas often seam to be a quick temporary hack that are not used later on but make maintaining harder. But also not against it

**Comment by lisitsyn** [comment]
@karlnapf I don't see that much complexity in this - all we need is to make features aware of what they store which sounds like a good design anyway
