### ISSUE TITLE
Update list of methods

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2730]
http://shogun-toolbox.org/doc/en/current/methods.html

We have *tons* of stuff in Shogun that is not listed here. This (easy) task is to populate the methods list.
Just go through examples and check whether the method is listed, if not, add.

The page is generated from:
https://github.com/shogun-toolbox/shogun/blob/develop/doc/pages/Methods.mainpage

This will be later used for our user-guide.

H

**Comment by karlnapf** [comment]
Super high priority and easy - so go for it!

**Comment by jimsotelo** [comment]
Has this been taken? I'm trying to get familiar with the shogun toolbox and this looks like a good place to start.

**Comment by iglesias** [comment]
Yes. See #2738.

**Comment by karlnapf** [comment]
Great!

But there are way more classes, so I re-open

**Comment by adit-39** [comment]
Will fix that in a couple of hours by taking every file in the src folder
and its subfolders and only after that generate the list with classes
missing unit tests and examples! :)
Every *.h (except for template classes) in src is eligible to make this
list?

**Comment by karlnapf** [comment]
Thats a good way to start, but keep in mind the list of methods should not contain every class we have, but every algorithm we implement, with a reference to the class(es) it is implemented in.

You don't need to look for missing unit tests, we have a test coverage script that does this, see buildbot

**Comment by rohit12** [comment]
Is this closed? I would like to work on this.

**Comment by iglesias** [comment]
@karlnapf can probably elaborate what else needs to be done here. Anyway, what I understand from his comment is that this list should not only be a list of class names but rather of ML methods/algorithms that are implemented by the classes.

**Comment by karlnapf** [comment]
I think we can leave this for now as the last update was nice and we soon will switch to the new manual.
If you are keen, you can polish this a bit, many things are unresolved, general feedback is appreciated:

https://github.com/karlnapf/shogun_manual

**Comment by karlnapf** [comment]
Closing for now
