### ISSUE TITLE
investigate the use of google benchmark for Shogun

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2749]
https://github.com/google/benchmark

we do have a benchmark folder, but this could maybe be done more systematically?

**Comment by sanuj** [comment]
I wrote `hayai benchmarks` to compare `native` and `eigen3` dots. Sharing it if it is helpful for someone :)
https://gist.github.com/sanuj/1099abec85e90b11eb0d

**Comment by karlnapf** [comment]
I like that framework. Is it well maintained? Thats a big plus for the google one ..... in addition to the readme being shorter ;)

**Comment by lisitsyn** [comment]
@karlnapf hayai is header only which is an advantage - we could just take the code once. As it is dead simple we can maintain that by ourselves

**Comment by karlnapf** [comment]
I would like to avoid any overhead and stick to standard things to do that. But if it is that easy, why not

**Comment by karlnapf** [comment]
We now have benchmarks going.
