### ISSUE TITLE
ideas / work towards a new shogun user guide

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2751]
See https://github.com/karlnapf/shogun_manual

Any contributions welcome

**Comment by souravsingh** [comment]
I would like to work on this.How do I start?

**Comment by iglesias** [comment]
@souravsingh, I'd say get the system running locally as described in the readme in the link in the first comment. Have a look at how the examples already there work and then start creating new ones showcasing Shogun features. For the new ones, draw inspiration from the already existing Shogun examples.

**Comment by karlnapf** [comment]
@souravsingh hi thanks for being interested in this.

In fact, @lisitsyn and me just got a prototype working that is ready to be filled with examples. We will push this to the development branch within the next week. You can then have a look and help us populating and documenting it. There is a lot of very easy tasks that have to be done. You will see.

Ping me next week if the thing is not there by then.

**Comment by souravsingh** [comment]
@karlnapf Is the prototype manual ready?

**Comment by souravsingh** [comment]
Ping @karlnapf

**Comment by karlnapf** [comment]
Sorry for the delay, I was away.

I just deleted my demo repo mentioned above.

We have a growing manual (aka cookbook) in develop now, [here](http://shogun.ml/cookbook/latest) is the latest version:
Note this is *all* executable code which is part of our test build, it is pretty easy to contribute new entries to this. We also want to pimp the visuals -- any help welcome. I close the issue for now
