### ISSUE TITLE
Ruby - error creating Labels object

### ISSUE THREAD

**Issue by neutralino** [shogun-toolbox/shogun#2753]
Hello,

I have Shogun 4.0.0 installed and I'm using ruby 2.1.5p273.  When testing out a basic Shogun example in ruby, I get an error trying to create a Labels object:
```
$ irb
irb(main):001:0> require 'narray'
=> true
irb(main):002:0> require 'modshogun'
=> true
irb(main):003:0>  features = Modshogun::RealFeatures.new
=> #<Modshogun::RealFeatures:0x000000019f5ca8 @__swigtype__="_p_shogun__CDenseFeaturesT_double_t">
irb(main):004:0> labels = Modshogun::Labels.new
TypeError: allocator undefined for Modshogun::Labels
	from (irb):4:in `new'
	from (irb):4
	from /usr/bin/irb:11:in `<main>'
irb(main):005:0>
```

Thanks for any help.

**Comment by lisitsyn** [comment]
Hey @neutralino 

I am surprised by this kind of error you get but the reason for this error is simple. Labels itself is an abstract class and you'd have to instantiate something more concrete like BinaryLabels

**Comment by neutralino** [comment]
Thanks @lisitsyn!  That works, turns out I was also following a really old version of the tutorial.

**Comment by iglesias** [comment]
Where did you find that tutorial, @neutralino?

**Comment by neutralino** [comment]
Just on someone's old [blog post](http://neovintage.org/2011/12/19/start-using-shogun-toolbox-in-ruby),  who I suppose at that time was using the [1.1.0](http://shogun-toolbox.org/doc/en/1.1.0/ruby_modular_examples.html) version of the shogun examples.

**Comment by lisitsyn** [comment]
I am closing now as it seems to be resolved
