### ISSUE TITLE
GaussianARD compilation failure without Eigen3

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#2757]
@yorkerlin

When compiling without eigen3 I get:

```
../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/balanced_conditional_probability_tree] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/base_load_file_parameters] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_load_file_parameters.dir/all] Error 2
../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/base_load_all_file_parameters] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_load_all_file_parameters.dir/all] Error 2
../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/base_map_parameters] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_map_parameters.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by yorkerlin** [comment]
I will add a guard so that it should the compilation should work.

On Tuesday, March 3, 2015, Sergey Lisitsyn <notifications@github.com> wrote:

> @yorkerlin <https://github.com/yorkerlin>
>
> When compiling without eigen3 I get:
>
> ../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/undocumented/libshogun/balanced_conditional_probability_tree] Error 1
> make[1]: *** [examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/undocumented/libshogun/base_load_file_parameters] Error 1
> make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_load_file_parameters.dir/all] Error 2
> ../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/undocumented/libshogun/base_load_all_file_parameters] Error 1
> make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_load_all_file_parameters.dir/all] Error 2
> ../../../src/shogun/libshogun.so.17.0: undefined reference to `shogun::CGaussianARDFITCKernel::get_parameter_gradient(shogun::TParameter const*, int)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/undocumented/libshogun/base_map_parameters] Error 1
> make[1]: *** [examples/undocumented/libshogun/CMakeFiles/base_map_parameters.dir/all] Error 2
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2757>.
>


-- 
best,

wu lin

**Comment by yorkerlin** [comment]
@lisitsyn 
the bug should be fixed at
https://github.com/shogun-toolbox/shogun/pull/2756/files

**Comment by lisitsyn** [comment]
Cool, thanks!
