### ISSUE TITLE
octave modular compile and install succeed but still got:"error: 'init_shogun' undefined.." 

### ISSUE THREAD

**Issue by AlexLuya** [shogun-toolbox/shogun#2762]
I have tried to install shogun 4.0 with octave 3.8.1 from source in my ubuntu 14.04 64bit like this
(By default,compilation will fail,so I modified two header files of octave,please check this:https://github.com/shogun-toolbox/shogun/issues/2666)

    cd shogun-4.0.0
    mkdir build
    cd build
    cmake  -DOctaveModular=ON ..
    make
    sudo make install

I found  a file called:modshogun.oct has been installed at

    /usr/lib/x86_64-linux-gnu/octave/site/oct/api-v49+/x86_64-pc-linux-gnu/shogun/modshogun.oct, 

and I have added this to .bashrc

     export LD_LIBRARY_PATH=/usr/local/lib

then start octave,execute:
  
     init_shogun

got this error:

     error: 'init_shogun' undefined near line 1 column 1

Did I missing something?

**Comment by karlnapf** [comment]
@vigsterkr ?

**Comment by iglesias** [comment]
You should be using `modshogun` rather than `init_shogun` (see octave modular examples).

**Comment by AlexLuya** [comment]
thanks
