### ISSUE TITLE
Ruby - overloaded initialize error when instantiating NeuralNetwork, RBM

### ISSUE THREAD

**Issue by neutralino** [shogun-toolbox/shogun#2765]
Hi all,

I'm hitting an error when trying to instantiate an RBM or NeuralNetwork in Ruby.  Ex:

``` ruby
$ irb
irb(main):001:0> require 'narray'
=> true
irb(main):002:0> require 'modshogun'
=> true
irb(main):003:0> test = Modshogun::RBM.new
ArgumentError: Wrong arguments for overloaded method 'RBM.initialize'.
Possible C/C++ prototypes are:
    void RBM.initialize(float64_t sigma)
    void RBM.initialize()

    from (irb):3:in `initialize'
    from (irb):3:in `new'
    from (irb):3
    from /usr/bin/irb:11:in `<main>'
irb(main):004:0> 
```

I believe the issue is that Ruby uses `initialize` as the name of its constructors (which SWIG automatically creates), but there is another initialize() function already defined in these classes.

**Comment by lisitsyn** [comment]
Hey @neutralino,

good catch, thanks for pointing this out. Although I have no solution but rename all the 'initialize' member functions.

**Comment by karlnapf** [comment]
Oh wow. Why did we never spot this yet?
I will open an issue for this

**Comment by karlnapf** [comment]
Very interested here in other experiences with using Shogun from ruby
