### ISSUE TITLE
make sparse matrix and dense matrix have the same interface

### ISSUE THREAD

**Issue by yingryic** [shogun-toolbox/shogun#2769]
the current constructors for sparse and dense matrix are matrix(int num_feat, int num_vec), but () operator are implemented differently, denseMatrix(feat_index, vec_index) and sparseMatrix(vec_index, featIndex). Thus we need to change the interface of SGSparseMatrix to make it consistent, and test other related member functions. @karlnapf

**Comment by iglesias** [comment]
I even think we should remove the notion of features and vectors from these matrix classes. They should be treated as math objects and use more abstract terms (row and column) than feature and vector. The latter appear when we use matrices to represent feature matrices.

**Comment by iglesias** [comment]
And the same for `SGSparseVector`. From my point view, there should be no feature mention there.

**Comment by yingryic** [comment]
the variables "num_features" and "num_vectors" are defined as public in the sparsematrix class, as well as "num_feat_entries" and "*features" in the sparsevector class. Every file using those sparse structures are taking advantage of it, i.e, the statement "numFeatures=sparseMatrix.num_features" are everywhere, changing the convention would be problematic.
Just check all the files including the SGSparseMatrix.h file, seems all of them are taking advantage of of the sparse matrix data structure rather than calling the (,) operator. All the test using the (,) are just initialize a square matrix and set the diagonal entries. That's why nothing is broken.
Tell me if I need any change on the pull request. @iglesias

**Comment by iglesias** [comment]
Oh, I see. It is understood now. Thanks a lot for the explanation. This makes me wonder whether we should provide after the operator() :D

**Comment by yingryic** [comment]
yes, but some of the unit test are still using () operator, getting rid of it would also pose problems.

**Comment by karlnapf** [comment]
I agree with @iglesias 
No features and vectors in a matrix.

As for semantics. Sparse matrices should really only be treated as linear operators that can be applied to vectors or chained. As a data structure, its more a dictionary of (i,j) pairs to a real number.

The () operator is useful for debuggin/construction, but it should never be used in practice. Imagine you iterate over num_rows, num_columns! Harmful!

It probably makes sense to mimic other libraries implenentation: Maybe check eigen3, scipy, and matlab?

**Comment by iglesias** [comment]
They do provide that operator in other implementations (at least, I am somewhat confident Matlab does).
