### ISSUE TITLE
shogun-4.0.0 compilation error(s). Ubuntu 12.04

### ISSUE THREAD

**Issue by vishalbelsare** [shogun-toolbox/shogun#2772]
I am compiling from the source tarball (SHOGUN Release version 4.0.0 (libshogun 17.0, data 0.9, parameter 1) ) taken from Shogun's website. I am compiling on Ubuntu 12.04. Things seem to go well, until the following shows up :

[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/io/protobuf/Chunks.pb.cc.o
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::BoolChunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:392:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::Int32Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:614:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::UInt32Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:839:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::Int64Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:1064:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::UInt64Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:1289:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::Float32Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:1514:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc: In member function ‘virtual int shogun::Float64Chunk::ByteSize() const’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/io/protobuf/Chunks.pb.cc:1736:9: warning: declaration of ‘data_size’ shadows a member of 'this' [-Wshadow]
[ 83%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
In file included from /home/vishal/Desktop/shogun-4.0.0/src/shogun/kernel/normalizer/KernelNormalizer.h:16:0,
                 from /home/vishal/Desktop/shogun-4.0.0/src/shogun/transfer/multitask/MultitaskKernelMaskNormalizer.h:16,
                 from /home/vishal/Desktop/shogun-4.0.0/src/shogun/base/class_list.cpp:15:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/kernel/Kernel.h: In member function ‘float64_t shogun::CKernel::kernel(int32_t, int32_t)’:
/home/vishal/Desktop/shogun-4.0.0/src/shogun/kernel/Kernel.h:210:21: error: invalid use of incomplete type ‘struct shogun::CKernelNormalizer’
/home/vishal/Desktop/shogun-4.0.0/src/shogun/kernel/Kernel.h:35:8: error: forward declaration of ‘struct shogun::CKernelNormalizer’
/home/vishal/Desktop/shogun-4.0.0/src/shogun/kernel/Kernel.h:211:3: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: **\* [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
make[1]: **\* [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: **\* [all] Error 2
vishal@goedel:~/Desktop/shogun-4.0.0/Build$

**Comment by iglesias** [comment]
What compiler and version are you using?

**Comment by iglesias** [comment]
Could you also check if there is #include
<shogun/kernel/normalizer/KernelNormalizer.h> in your
shogun/kernel/Kernel.h? If so, I think it should be possible to remove
safely the forward declaration your compiler is complaining about.

**Comment by vishalbelsare** [comment]
Compiler version quite dated at:

vishal@goedel:~/Desktop/shogun-4.0.0/Build$ g++ --version
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

Yes, /shogun/kernel/Kernel.h has a include directive for <shogun/kernel/normalizer/KernelNormalizer.h>

Would upgrading the compiler help with this?

**Comment by iglesias** [comment]
I know that it works with the gcc version that comes in Ubuntu 14.04.

Have you tried removing the forward declaration I mentioned in the previous
message?
