### ISSUE TITLE
 No rule to make target `all'

### ISSUE THREAD

**Issue by tengshaofeng** [shogun-toolbox/shogun#2783]
hello ,
     When i run "make -j5 all",it appears " No rule to make target `all'"
what is the problem?

thanks in advance.

**Comment by karlnapf** [comment]
Could you provide some more information of what you are doing?
Make sure check the readme files, they explain how to use cmake and subsequent make

**Comment by karlnapf** [comment]
I close this for now

**Comment by iglesias** [comment]
Just make -j5 should be fine.

**Comment by tengshaofeng** [comment]
when i make -j5, it still have error like "/tmp/ccfDSvzN.s:899: Error: no such instruction: `vfmadd312sd 232(%rsp),%xmm4,%xmm14'
/tmp/ccfDSvzN.s:1158: Error: no such instruction: `vfmadd312sd 232(%rsp),%xmm2,%xmm12'
/tmp/ccfDSvzN.s:1182: Error: no such instruction: `vfmadd312sd 240(%rsp),%xmm0,%xmm13'
/tmp/ccfDSvzN.s:1263: Error: no such instruction: `vfmadd312sd 232(%rsp),%xmm2,%xmm1'
/tmp/ccfDSvzN.s:1779: Error: no such instruction: `vfmadd312sd 232(%rsp),%xmm10,%xmm8'
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/preprocessor/HomogeneousKernelMap.cpp.o] Error 1
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2
"

**Comment by iglesias** [comment]
I must admit that looks very weird and unknown to tme :-) @lisitsyn, any idea?

If you can, @tengshaofeng, copy in pastebin, gist, or somewhere else the list of instructions you are doing to download Shogun, configure the build with cmake and trying to build it.

**Comment by karlnapf** [comment]
This comes from a recent cpu (i7) used with an outdated compiler (such as the one in Ubuntu 12.04)
Could you share your system specs?
