### ISSUE TITLE
Use common naming in target languages 

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#2789]
I suggest to adjust naming of methods in target languages so that 'get_num_features' in Python would be 'getNumFeatures()' in Java. I consider this quite important as it looks pretty ugly in Java now.

@karlnapf @vigsterkr @lambday

**Comment by sonney2k** [comment]
That is a swig name mangling option. 

It will make examples more difficult to maintain though...

On March 28, 2015 11:19:14 PM EET, Sergey Lisitsyn <notifications@github.com> wrote:
>I suggest to adjust naming of methods in target languages so that
>'get_num_features' in Python would be 'getNumFeatures()' in Java. I
>consider this quite important as it would look very ugly in, say, Java.
>
>@karlnapf @vigsterkr @lambday 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/shogun-toolbox/shogun/issues/2789

-- 
Sent from Kaiten Mail. Please excuse my brevity.

**Comment by lisitsyn** [comment]
@sonney2k with @karlnapf initiative to generate examples from some proto language it shouldn't be a problem

**Comment by karlnapf** [comment]
Yep, with the automagically generated ones, we can do this quite easily. I dont know about swig though.

To be honest, I dont think this is too important .... we rather should have example documentation as the manual project @lisitsyn and me have been working on

**Comment by karlnapf** [comment]
We can always change this, once examples are generated automatically, all easy

**Comment by vigsterkr** [comment]
obsolete...
