### ISSUE TITLE
Shogun python interface raises unimplemented error for any function?

### ISSUE THREAD

**Issue by erogol** [shogun-toolbox/shogun#2798]
I installed Shogun by following second answer of this question (http://stackoverflow.com/questions/21680741/shogun-on-ubuntu-12-04 ). However for any function call it raises following error;

NotImplementedError: Wrong number or type of arguments for overloaded function 'new_RealFeatures'.
  Possible C/C++ prototypes are:
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(int32_t)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures()
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::CDenseFeatures< float64_t > const &)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::SGMatrix< double >)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::CFile *)

Do you have any suggestion to diagnose the problem ?

**Comment by karlnapf** [comment]
How do you call the function? This seems like a type error to me

**Comment by erogol** [comment]
It seems like I give the numpy arrays as float32 to RealFeatures function. This is dummy user fault :)

**Comment by karlnapf** [comment]
Yeah I guess the error message could be more clear, stating the given type as well.
Ill open an issue on this.

**Comment by erogol** [comment]
that would be great
