### ISSUE TITLE
remove configure script

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2803]
People do get confused since they run ```./configure && make && sudo make install```

I think our take on cmake is mature enough these days

Thoughts? If no-one complains, I will go ahead...

Should be done before next major release

**Comment by iglesias** [comment]
Where is the script actually? In current develop:

```
find . -name configure
./build/GoogleMock/src/GoogleMock/configure
./build/GoogleMock/src/GoogleMock/gtest/configure
```

It seems it has been gone for some time now 5e2939b0a1dd7651ab18d7991c7ac58710594cac.
