### ISSUE TITLE
cmake for matlab static interface error

### ISSUE THREAD

**Issue by tengshaofeng** [shogun-toolbox/shogun#2805]
hello:
when i cmake ,facing the following problem,too much error ,i don not know which matters.

tbq@tbq-System-Product-Name:~/shogun-4.0.0/build$ cmake -DMatlabStatic=ON ..
-- Could NOT find CCache (missing:  CCACHE) 
-- Using system's malloc
CMake Warning (dev) at CMakeLists.txt:289 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

```
'@CMAKE_SOURCE_DIR@/NEWS'
```

  the old evaluation rules produce:

```
'/home/tbq/shogun-4.0.0/NEWS'
```

  but the new evaluation rules produce:

```
'@CMAKE_SOURCE_DIR@/NEWS'
```

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find Eigen3 (missing:  EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Spinlock support found
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Linear algebra uses c++11 features. Please use a supported compiler
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPythonLibs.cmake:190 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:1006 (FIND_PACKAGE)

thanks

**Comment by karlnapf** [comment]
Matlab is know to have issues currently. We are working on a modular version, but that will take some time. Maybe its easiest for now to either use an older version of Shogun or change to a modular language binding?

@vigsterkr ?

**Comment by iglesias** [comment]
Actually, in the CMake trace I don't see any error that should be related to using Matlab. Your compiler does not seem to support C++11 (which is a requirement for the latest Shogun, this changed quite recently) and Python -- or some required parts of it -- are not found.
