### ISSUE TITLE
can't build on OS X Yosemite with Ruby binding

### ISSUE THREAD

**Issue by mepatterson** [shogun-toolbox/shogun#2808]
I've tried several times to get Shogun built on OS X Yosemite. Trying to use the Ruby bindings. I've got the narray gem installed for ruby. I have installed all the pre-reqs as far as I can tell. But I'm still getting a bunch of errors on version 4.0 (specifically 16 errors, here are some of them)...

```
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6167:23: error: use of undeclared identifier '_seq'
      return iterator(_seq, 0);
                      ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6172:29: error: use of undeclared identifier '_seq'
      return const_iterator(_seq, 0);
                            ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6177:23: error: use of undeclared identifier '_seq'
      return iterator(_seq, size());
                      ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6182:29: error: use of undeclared identifier '_seq'
      return const_iterator(_seq, size());
                            ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6187:24: error: use of undeclared identifier '_seq'
      return reference(_seq, n);
                       ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6192:30: error: use of undeclared identifier '_seq'
      return const_reference(_seq, n);
                             ^
/Users/me/shogun-4.0.0/src/interfaces/ruby_modular/modshogunRUBY_wrap.cxx:6246:29: error: expected unqualified-id
            return rubyseq.check() ? SWIG_OK : SWIG_ERROR;
```

What am I missing?

**Comment by lisitsyn** [comment]
Hey @mepatterson 

This is kind of incompatibility of swig and yosemite (in default settings) we didn't know about at the moment of release. I suggest to either build latest shogun or apply this patch: https://github.com/shogun-toolbox/shogun/pull/2694

**Comment by mepatterson** [comment]
Okay, so using the latest from develop branch compiled and installed properly to my "shogun-install" directory (created 'include', 'lib', and 'share' directories). I cmake'd it with the ruby modular interface ON. But I'm having a disconnect on how to get the 'modshogun' file available? All of the tutorials and example docs suggest that in ruby I can just do `require 'modshogun'` but that is throwing a `LoadError: cannot load such file -- modshogun` ... where is this file created? How do I get access to it now that I've compiled the toolbox to my "shogun-install" directory.

**Comment by lisitsyn** [comment]
@mepatterson as you're using non-standard directories you're probably missing something like `LD_LIBRARY_PATH` which should be set to the directory with compiled `.so`

**Comment by lisitsyn** [comment]
@mepatterson did that help in the end?

**Comment by mepatterson** [comment]
Hi lisitsyn... I haven't had a chance to go back and try it yet. I'll let you know once I do.

**Comment by erip** [comment]
@mepatterson Any update on this?

**Comment by vigsterkr** [comment]
tbis is definitely fixed
