### ISSUE TITLE
Quickstart is for 3.1, not 4.0

### ISSUE THREAD

**Issue by rdaniel** [shogun-toolbox/shogun#2810]
Tried to install on Mac using quickstart instructions at https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART  but then noticed that it's wget was for 3.1, not the new 4.0 release.

**Comment by karlnapf** [comment]
Thanks for reporting. We are currently updating the mac build instructions, and this could be part of it

**Comment by aagarwal-gtr** [comment]
Hello I have modified the QUICKSTART page in the wiki. The modified page can be found in my forked wiki repo https://github.com/aagarwal-gtr/shogun-wiki.git
Please merge.

**Comment by lisitsyn** [comment]
@aagarwal-gtr it's quite inconvenient to take your changes from the repo and your name would be missed in the contribution. Could you please follow the usual github workflow of pull request?

**Comment by aagarwal-gtr** [comment]
Hello I am quite inexperienced at this. I was of the understanding that wiki repos dont accept pull requests so I followed these instructions http://stackoverflow.com/a/11481887
Would you mind explaining or pointing me towards a link that explains the expected workflow?

**Comment by youssef-emad** [comment]
@lisitsyn I made the simple changes needed for shogun 4.1.0, here's a gist 
https://gist.github.com/youssef-emad/0789b4f5cd3ed0227704

**Comment by karlnapf** [comment]
Thanks @youssef-emad 

Is it possible to send a pull request with this?.

Thanks!

**Comment by youssef-emad** [comment]
@karlnapf I am not sure I can make a pull request with a wiki , I depended on this past closed [issue](https://github.com/shogun-toolbox/shogun/issues/2960).

**Comment by lgoetz** [comment]
@youssef-emad is right, github doesn't support pull requests for the wiki, so I've manually updated the wiki for you - for now. 
@karlnapf @lisitsyn we could think of recommending people to do [something like this?](http://fusiongrokker.com/post/how-you-can-contribute-to-taffy-documentation)

**Comment by karlnapf** [comment]
Ah this is annoying.
I don't like the solution of manually merging and the one proposed in your link at all....
We have to find something cleaner.
