### ISSUE TITLE
CParameterCombination prints SGVectors incorrectly

### ISSUE THREAD

**Issue by sorig** [shogun-toolbox/shogun#2819]
When training the hyperparameters of the spectral mixture kernel (see #2818) I noticed that SGVectors didn't print correctly when using the `print_tree` method on the `CParameterCombination` class. The SGVector parameter on the kernel object has a container datatype on the `TSGDataType` object set to `CT_VECTOR` instead of `CT_SGVECTOR`. Consequently the SGVector parameter is not being printed correctly.

I have created a fix, but I don't know if the fact that the container type is wrong constitutes and underlying issue.

**Comment by sorig** [comment]
Can anyone tell me if there is an underlying problem with the container datatype or if my fix is adequate?

**Comment by karlnapf** [comment]
As we discussed, this is a bug related to legacy code.
The method itself should probably be removed as the terminal might not be available in modular interfaces.
We should rather return an adequate data structure with the resulting parameters. But well

**Comment by karlnapf** [comment]
Fixed in #2820
