### ISSUE TITLE
hash in SGObject

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2838]
@vigsterkr , @lisitsyn , @karlnapf 
there may be a bug.
If CSGObject::update_parameter_hash() is called more than once, CSGObject::parameter_hash_changed() always returns true even when variables remain the same.

for example
```
void CExactInferenceMethod::update()
{
	
	CInferenceMethod::update();
	update_chol();
	update_alpha();
	update_deriv();
	update_mean();
	update_cov();

	update_parameter_hash();
	SG_SPRINT("hash value1 %d \n", m_hash);  
	update_parameter_hash();
	SG_SPRINT("hash value2 %d \n", m_hash);  

}
```
`hash value1` and `hash value2` are different since
```
void CSGObject::update_parameter_hash()
{
	uint32_t carry=0;
	uint32_t length=0;

	get_parameter_incremental_hash(m_hash, carry, length); 
	m_hash=CHash::FinalizeIncrementalMurmurHash3(m_hash, carry, length);
}
```
where `m_hash` becomes `non-zero` after `update_parameter_hash()` is called

what is worse,
```
bool CSGObject::parameter_hash_changed()
{
	uint32_t hash=0;
	uint32_t carry=0;
	uint32_t length=0;

	get_parameter_incremental_hash(hash, carry, length); 
	hash=CHash::FinalizeIncrementalMurmurHash3(hash, carry, length);

	return (m_hash!=hash);
}
```
Note that `hash` is `zero`, which means if `update_parameter_hash()` is called more than once, `CSGObject::parameter_hash_changed()` always returns `true` even when variables remain the same.

**Comment by yorkerlin** [comment]
I am not sure whether the hash value should be changed if `parameter_hash_changed()` is called even when `values` of variables in the object remain the same

**Comment by yorkerlin** [comment]
if you think this is a bug, the fix is quite simple.

```
void CSGObject::update_parameter_hash()
{
    uint32_t carry=0;
    uint32_t length=0;

    //CHANGE m_hash to 0
    get_parameter_incremental_hash(0, carry, length);  
    m_hash=CHash::FinalizeIncrementalMurmurHash3(m_hash, carry, length);
}
```

**Comment by karlnapf** [comment]
I think this is a bug! This should not be. Do unit tests break if you fix it?
Make sure to add unit tests for the hashing if you do fix it
Thanks!

**Comment by yorkerlin** [comment]
this issue is solved.
I close this
