### ISSUE TITLE
Make: *** [all] Error 2

### ISSUE THREAD

**Issue by iarroyof** [shogun-toolbox/shogun#2841]
Hi, I currently trying to install Shogun in Lubuntu. I followed this:

$ git clone git://github.com/shogun-toolbox/shogun.git
:~/shogun$ cd shogun
:~/shogun$ mkdir build
:~/shogun/build$ cmake -DPythonModular=ON -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ..

However, when making I have an Error:

:~/shogun/build$ make -j2
[  1%] Generating version header
[  1%] Generating /home/iarroyof/shogun/src/shogun/base/class_list.cpp
[  1%] Built target version
[  1%] Built target class_list
Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
In file included from /home/iarroyof/shogun/src/shogun/kernel/normalizer/KernelNormalizer.h:16:0,
                 from /home/iarroyof/shogun/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:16,
                 from /home/iarroyof/shogun/src/shogun/base/class_list.cpp:44:
/home/iarroyof/shogun/src/shogun/kernel/Kernel.h: In member function ‘float64_t shogun::CKernel::kernel(int32_t, int32_t)’:
/home/iarroyof/shogun/src/shogun/kernel/Kernel.h:212:21: error: invalid use of incomplete type ‘class shogun::CKernelNormalizer’
    return normalizer->normalize(compute(idx_a, idx_b), idx_a, idx_b);
                     ^
In file included from /home/iarroyof/shogun/src/shogun/kernel/normalizer/KernelNormalizer.h:16:0,
                 from /home/iarroyof/shogun/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:16,
                 from /home/iarroyof/shogun/src/shogun/base/class_list.cpp:44:
/home/iarroyof/shogun/src/shogun/kernel/Kernel.h:35:8: error: forward declaration of ‘class shogun::CKernelNormalizer’
  class CKernelNormalizer;
        ^
src/shogun/CMakeFiles/libshogun.dir/build.make:2525: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o' failed
make[2]: **\* [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
CMakeFiles/Makefile2:196: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: **\* [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2

Could someone help me please?

**Comment by karlnapf** [comment]
No idea.
@lisitsyn @besser82 ?

**Comment by besser82** [comment]
@nachitoys Did you try recompiling after `rm -f src/shogun/base/class_list.cpp`?  That should fix the issue in 98% of the cases…  Which compiler, CMake-version and OS you are using?

**Comment by nachitoys** [comment]
Hi. I just tryed what @besser82 said. It didn't help unfortunately:
`<~/shogun/build$ cmake -DPythonModular=ON -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ..>`
`<~/shogun/build$ make>`
`<<same output>>`

`<~/shogun/build$ gcc --version && cmake -version>`
`<gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2>`
`<Copyright (C) 2014 Free Software Foundation, Inc.>`
`<This is free software; see the source for copying conditions.  There is NO>`
`<warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.>`

`<cmake version 3.0.2>`

`<CMake suite maintained and supported by Kitware (kitware.com/cmake).>`

All running in Ubuntu 15.04

**Comment by karlnapf** [comment]
Any updates here?

**Comment by karlnapf** [comment]
This is likely to be caused by conflicting installations of shogun and a different checked out git version.
Make sure your include paths are set up correctly.
