### ISSUE TITLE
general minimizers used in gp (API design)

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2853]
some code skeleton

**Comment by yorkerlin** [comment]
```
class CFirstOrderCostFunction
{
public:
	virtual float64_t get_function_value()=0;
	virtual SGVector<float64_t> get_variable_value()=0;
	virtual SGVector<float64_t> get_variable_gradient()=0;
};
```
```
class CFirstOrderMinimizer
{
public: 
	CFirstOrderMinimizer(CFirstOrderCostFunction *fun)
	{
		m_fun=fun;
	}
	~GradientBasedMinimizer()
	{
		delete m_fun;
	}
	virtual void minimization()=0;
protected:
	CFirstOrderCostFunction *m_fun;
};
```

**Comment by yorkerlin** [comment]
strategy pattern
```
class CMyClass
{
public:
	CMyClass(){}
	~CMyClass()
	{
		delete m_opt;
	}
	virtual void print()=0;
protected:
	virtual void register_minimizer(CFirstOrderMinimizer* opt)
	{
		delete m_opt;
		m_opt=opt;
	}
	CFirstOrderMinimizer* m_opt;
};
```

**Comment by yorkerlin** [comment]
```
class CMyClassInstanceFirstOrderCostFunction;
class CMyClassInstance(): public CMyClass
{
friend class CMyClassInstanceFirstOrderCostFunction;
public:
	CMyClassInstance();
	virtual void set_minimizer(MinimizerFlag flag)
	{
		switch (flag)
		{
		case GradientDescent:
			CFirstOrderCostFunction *cost=new CMyClassInstanceFirstOrderCostFunction(this);
			//CFirstOrderMinimizer will delete cost
			CFirstOrderMinimizer* opt=new GradientDescent(cost);
			//CMyClass will delete opt
			register_minimizer(opt);
			break;
		//case Newton:
			//break;
		}
	}
private:
	float64_t get_cost();
	SGVector<float64_t> get_variable();
	SGVector<float64_t> get_gradient();
};

class CMyClassInstanceFirstOrderCostFunction: public CFirstOrderCostFunction
{
public:
	CMyClassInstanceFirstOrderCostFunction(CMyClassInstance *obj)
	{
		m_obj=obj;
		ASSERT(m_obj);
	}
	virtual float64_t get_function_value()
	{
		return m_obj->get_cost();
	}
	virtual SGVector<float64_t> get_variable_value()
	{

		return m_obj->get_variable();
	}
	virtual SGVector<float64_t> get_variable_gradient()
	{
		return m_obj->get_gradient();
	}

private:
	//do not delete the pointer
	CMyClassInstance* m_obj;
}
```

**Comment by yorkerlin** [comment]
@karlnapf 
any comment about this.
if you agree such design, they will be used  in GP.

**Comment by yorkerlin** [comment]
which classes should use `CSGObject` as the base class?

**Comment by yorkerlin** [comment]
@karlnapf 
some useful minimizer (unconstrained cases)
see the section `Optimizer overview` in http://climin.readthedocs.org/en/latest/

**Comment by karlnapf** [comment]
Hi

so see what you are after here is to have a way to exchange optimization methods in Shogun classes.
Looks cool and elegant. So +1 in general. My questions are about necessarity

 * What does this gain us in general?
 * Most models in Shogun are fixed, and so are many inference algorithms. Is there really the option to change optimisers under the hood? Is that something the user should decide?
 * In GPs, we use all sorts of opt. methods, I guess you want to put the optimiser in the base class?
 * Then the question is: what is the gain as compared to doing this in the subclasses directly
 * Can you maybe come up with an example where this is used?

**Comment by yorkerlin** [comment]
Such design (the cost function part) is to keep the base
Usage:
1. Laplace method using newton method or lbfgs (refactor)
2. Stochastic gradient update schemes (gradient descend, gradient
descend with nesterov momentum, gradient update with annealing
techniques, gradient update with variance reduction techniques)


On Friday, June 12, 2015, Heiko Strathmann <notifications@github.com> wrote:

> Hi
>
> so see what you are after here is to have a way to exchange optimization
> methods in Shogun classes.
> Looks cool and elegant. So +1 in general. My questions are about
> necessarity
>
>    - What does this gain us in general?
>    - Most models in Shogun are fixed, and so are many inference
>    algorithms. Is there really the option to change optimisers under the hood?
>    Is that something the user should decide?
>    - In GPs, we use all sorts of opt. methods, I guess you want to put
>    the optimiser in the base class?
>    - Then the question is: what is the gain as compared to doing this in
>    the subclasses directly
>    - Can you maybe come up with an example where this is used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2853#issuecomment-111411985>
> .
>


-- 
best,

wu lin

**Comment by yorkerlin** [comment]
Any feedback on the class design?
If you think so, the streaming/online GP will use the design.

For stochastic gradients, the key components are
1. subset selection to create a mini batch  (scheduler)
2. Gradient update schemes (minimizer)

My idea is to use the design so that users or developers only need
to change schedulers and minimizers to implement new inference methods
based on stochastic gradients in the future.

On Friday, June 12, 2015, yorker lin <yorkerjaster@gmail.com> wrote:

> Such design (the cost function part) is to keep the base
> Usage:
> 1. Laplace method using newton method or lbfgs (refactor)
> 2. Stochastic gradient update schemes (gradient descend, gradient
> descend with nesterov momentum, gradient update with annealing
> techniques, gradient update with variance reduction techniques)
>
>
> On Friday, June 12, 2015, Heiko Strathmann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hi
>>
>> so see what you are after here is to have a way to exchange optimization
>> methods in Shogun classes.
>> Looks cool and elegant. So +1 in general. My questions are about
>> necessarity
>>
>>    - What does this gain us in general?
>>    - Most models in Shogun are fixed, and so are many inference
>>    algorithms. Is there really the option to change optimisers under the hood?
>>    Is that something the user should decide?
>>    - In GPs, we use all sorts of opt. methods, I guess you want to put
>>    the optimiser in the base class?
>>    - Then the question is: what is the gain as compared to doing this in
>>    the subclasses directly
>>    - Can you maybe come up with an example where this is used?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/shogun-toolbox/shogun/issues/2853#issuecomment-111411985>
>> .
>>
>
>
> --
> best,
>
> wu lin
>
>

-- 
best,

wu lin

**Comment by karlnapf** [comment]
Yeah, I think the design is good. Keeps things clean internally and hides details from our users.
It in particular allows to play around with combinations, so we might even at some point have a framework that allows scientists to compare things systematically.

We should write a JMLR MLOSS paper about your framework at some point, its really getting there

**Comment by yorkerlin** [comment]
@karlnapf 
one application:
On optimization methods for deep learning ICML 2011

**Comment by karlnapf** [comment]
Cool!

**Comment by yorkerlin** [comment]
Done
