### ISSUE TITLE
add a new features for subsamples

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2857]
@karlnapf 
Shogun has a implementation of `CDenseSubsetFeatures`, which uses a subset of `features`.

I need another `features` class, which uses a subset of `samples`. The `features` class is used to create a mini batch, which is a subset of samples.
Please let me know if there exist such features class for subset of samples. If not, I will add my implementation.

**Comment by yorkerlin** [comment]
`CDenseFeatures` has a `copy_subset(SGVector<index_t> indices)` method. However, I do not want to copy the subset.

**Comment by yorkerlin** [comment]
BTW,  in `features` classes,
the following methods 
* get_num_vectors()
* get_num_features()
* get_dim_feature_space()
are confusing.

For `denseFeatures`  
* get_num_vectors() is samples size
* get_num_features() == get_dim_feature_space() is feature size

Maybe it may be good to document the difference between `get_num_features()` and `get_dim_feature_space()`.

**Comment by yorkerlin** [comment]
@karlnapf 
the  `CDenseSubSamplesFeatures` class is implemented.
I will send a PR soon.

**Comment by karlnapf** [comment]
I dont understand why we need such subsample features?
We can just set the subset manually?

Is there anything that is not good about this? Convenience?

**Comment by karlnapf** [comment]
PS I agree with you that the num_features and num_vectors notation is confusing.....

**Comment by yorkerlin** [comment]
this issue is solved.
I closed this.
