### ISSUE TITLE
bug in CDenseSubsetFeatures

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2859]
Please note that
in `CDenseSubsetFeatures` class

`template<class ST> class CDenseSubsetFeatures: public CDotFeatures`

```
    virtual EFeatureClass get_feature_class() const
    {
        return m_fea->get_feature_class(); // BUG!!!
    }
    CDenseFeatures<ST> *m_fea;
```

The bug comes from the get_feature_class()  method. 
The class is indeed `not` `CDenseFeatures` class. (eg, it does not have `get_feature_vector` method)
However, it claims that it is like `CDenseFeatures` class since the `get_feature_class()` method.

If we mix `CDenseFeatures` and  `CDenseSubsetFeatures`, there is a bug. 
the bug can be reproduced by

```
aa->dot(0,bb,0);
```

where aa is CDenseFeatures\*  and bb is CDenseSubsetFeatures \*  

Reason:
the `CDenseSubsetFeatures` does not the `get_feature_vector` method from `CDenseFeatures`.

See

```
template<class ST> float64_t CDenseFeatures<ST>::dot(int32_t vec_idx1, CDotFeatures* df,
        int32_t vec_idx2)
{
    ASSERT(df)
    ASSERT(df->get_feature_type() == get_feature_type())
    ASSERT(df->get_feature_class() == get_feature_class()) //BUG!!! CDenseSubsetFeatures passed the assert
    CDenseFeatures<ST>* sf = (CDenseFeatures<ST>*) df; //we cast CDenseSubsetFeatures  to CDenseFeatures 

    int32_t len1, len2;
    bool free1, free2;

    ST* vec1 = get_feature_vector(vec_idx1, len1, free1);
    ST* vec2 = sf->get_feature_vector(vec_idx2, len2, free2);

    float64_t result = CMath::dot(vec1, vec2, len1);

    free_feature_vector(vec1, vec_idx1, free1);
    sf->free_feature_vector(vec2, vec_idx2, free2);

    return result;
}
```

**Comment by yorkerlin** [comment]
@karlnapf 
@lisitsyn 
please take a look

**Comment by karlnapf** [comment]
Yes, bug.

Why do we even have this class? See my other comment?

**Comment by karlnapf** [comment]
I think it should be removed

We should rather define masks for CFeatures in general, just like numpy does it
