### ISSUE TITLE
a bug in log_sum_exp(SGVector<T> values) in CMath

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2889]
```
        template <class T>
        static T log_sum_exp(SGVector<T> values)
        {
            REQUIRE(values.vector, "Values are empty");
            REQUIRE(values.vlen>0,"number of values supplied is 0\n");

            /* find minimum element index */
            index_t min_index=0;
            T X0=values[0];
            if (values.vlen>1)
            {
                for (index_t i=1; i<values.vlen; ++i)
                {
                    if (values[i]<X0)
                    {
                        X0=values[i];
                        min_index=i;
                    }
                }
            }

            /* remove element from vector copy and compute log sum exp */
            SGVector<T> values_without_X0(values.vlen-1);
            index_t from_idx=0;
            index_t to_idx=0;
            for (from_idx=0; from_idx<values.vlen; ++from_idx)
            {
                if (from_idx!=min_index)
                {
                    values_without_X0[to_idx]=exp(values[from_idx]-X0);
                    to_idx++;
                }
            }

            return X0+log1p(SGVector<T>::sum(values_without_X0));
        }
```

Usually we should find the `maximum element index` instead of the `minimum element index`.
`exp(values[from_idx]-X0)` will overflow and we get `inf`  if we use the `minimum element index`.

If we use the `maximum element index`, `exp(values[from_idx]-X0)`  will underflow but we can still get the result.

For example 
SGVector<T> values=[450, -450], // the function is to compute `log( exp(450)+exp(-450) )`
The function will return `inf`, if we use the `minimum element index`
The function will return `450`, if we use the `maximum element index`

**Comment by yorkerlin** [comment]
@karlnapf 
@lisitsyn 
@iglesias 
you may take a look

**Comment by iglesias** [comment]
You are right, @yorkerlin. Very well spotted :-)

The function could also benefit from some face-lifting (the first if is not necessary, I think we should optimise memory and not create the second vector `values_without_X0`, and perhaps even use std::max_element to find the largest element, if possible).
