### ISSUE TITLE
width value consistence of gaussian kernel in Shogun

### ISSUE THREAD

**Issue by nachitoys** [shogun-toolbox/shogun#2893]
Hi all..

I hope someone can help me. Im really confused. Im trying to use MKL for image classification with the `multiclass_digits` dataset included in Shogun. I was looking for a reliable set of kernel parameters and I found this paper: Wang & Ma, (2008), "An Estimation of the Optimal Gaussian Kernel Parameter for Support Vector Classification". In this paper experiments with widely different values of the svm_C parameter were performed and the range of widths they found is relatively stable (from 0.66² to 4.13²). They used different image datasets, so the ranges of widths are said to be suitable for image classification. In this sense, by using MKL I'd expect the similar ranges of widths, however it is not so. In Shogun I trained a ```CombinedKernel``` whose componets are Gaussian subkernels with quite different values than those found by Wang & Ma, (2008) and Im not sure why. Up to three subkernels with widths valued between 75 and 180 get the best results (about 94% of accuracy), while the range of widths found by Wang & Ma, (2008) get quite poor results (about 70%). 

Said the above I would like to know whether, there is a special consideration in the Shogun implementation of the Gaussian kernel? Wang & Ma's (2008) results are not necessarily reliable for any kind of images because of the bandwidth of task-driven relevant features? given that Eq. 4.10 in Bhamers' thesis is the Shogun Gaussian kernel implementation, the hinge-shaped scaling factor makes the difference? There is another more possible explanation for these results?

Thank you in advance.

**Comment by yorkerlin** [comment]
@nachitoys 
Which version of shogun for your experiments? (release version or developer version)
We moved the internal representation of `width` in log domain in developer version 4.1. I am not sure whether the change affect MKL.
If you use a developer version earlier than May 5, 2015, you may consider the following reason:
* The width used in Shogun may be different from the standard width.

reference
http://www.shogun-toolbox.org/doc/en/latest/classshogun_1_1CGaussianKernel.html
https://en.wikipedia.org/wiki/Radial_basis_function_kernel

**Comment by nachitoys** [comment]
Thank you very much for your very fast answer @yorkerlin . Im using the release version from 4 months ago. I will review things you are suggesting and I will write you if any doubt emerges.

Thank you very much again

**Comment by nachitoys** [comment]
That was indeed the solution to this issue... `2\sigma^2`. There is total
consistence with the results mentioned both in the publication I mentioned
above and the Sonnenburg's Large Scale MKL (2006).

Thank you very much.

2015-08-21 10:49 GMT-05:00 Wu Lin <notifications@github.com>:

> @nachitoys <https://github.com/nachitoys>
> Which version of shogun for your experiments? (release version or
> developer version)
> We moved the internal representation of width in log domain in developer
> version 4.1. I am not sure whether the change affect MKL.
> If you use a developer version earlier than May 5, 2015, you may consider
> the following reason:
>
>    - The width used in Shogun may be different from the standard width.
>
> reference
>
> http://www.shogun-toolbox.org/doc/en/latest/classshogun_1_1CGaussianKernel.html
> https://en.wikipedia.org/wiki/Radial_basis_function_kernel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2893#issuecomment-133469247>
> .
>



-- 
Ignacio Arroyo Fernández

**Comment by lisitsyn** [comment]
@nachitoys that's really good results are still reproducible and no bug here involved :)

@yorkerlin thanks for resolving this issue.
