### ISSUE TITLE
Cannot link to libshogun.dylib

### ISSUE THREAD

**Issue by wcalhoun516** [shogun-toolbox/shogun#2894]
I am trying to link my xcode project to libshogun.dylib and another library called libxxx.dylib

I can link correctly to libxx.dylib however I get a runtime error linking to libshogun.dylib with the error:dyld: Library not loaded: libshogun.17.dylib
Reason: Image not found

After installing shogun I have a build/install/lib with 3 .dylib files. libshogun.17.0.dylib  libshogun.17.dylib and libshogun.dylib. I have tried including flags -l for all three and still the same error.

Please any help will be appreciated.

**Comment by lisitsyn** [comment]
It should be `libshogun.dylib` (as a link referring concrete version of dylib) either in linker's path or in the directory specified by `-L/path/do/that/dir` and the `-lshogun` flag should be used.

Let me know if that helps

**Comment by wcalhoun516** [comment]
I tried:  "-L/path/do/that/dir and the -lshogun flag should be used" and it successfully compiles but still get a runtime error of "Library not loaded: libshogun.17.dylib"

**Comment by sonney2k** [comment]
DYLD_LIBRARY_PATH is your friend

**Comment by wcalhoun516** [comment]
On xcode I've set in my scheme that the environmental variable DYDL_LIBRARY_PATH is equal to my   -L/path/to/lbraries  (obviously without the -L). Still no luck.

**Comment by lisitsyn** [comment]
Its DYLD not DYDL, could be the reason if it is like that in you env

**Comment by wcalhoun516** [comment]
Don't you just love how you can spend hours banging your head against a wall because you didn't recognize a two letter switch? That fixed it. I owe you a debt of gratitude.

**Comment by lisitsyn** [comment]
@wcalhoun516 I am glad it is resolved!
