### ISSUE TITLE
Update travis.yml to allow for container-based builds

### ISSUE THREAD

**Issue by erip** [shogun-toolbox/shogun#2900]
I've been trying to submit a pull request, but travis keeps dying (seemingly) because it runs out of resources mid-build.

Travis now has a [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/), which allows for faster start times, faster builds, more resources, and caching of dependencies for open source projects.

It seems natural to want to take advantage of these resources for shogun, not to mention I'd like to successfully submit this pull request. 😉

erip

**Comment by lisitsyn** [comment]
@erlp thanks! I believe @vigsterkr is the man to handle this ;)

**Comment by iglesias** [comment]
I had a look at this last week and it definitely looks like something we could benefit from. However, iirc, we cannot use sudo when following this approach. We are currently relying on it in our jobs to, at least, install packages. There is documentation in Travis about how to install packages when there is no sudo.

**Comment by vigsterkr** [comment]
yeah no... ;) the problem is that we need a lot of extra packages that we cannot install w/o `sudo`....
and travis does not support custom docker image... so till either of them is fixed we cannot switch to that...

**Comment by iglesias** [comment]
@vigsterkr, can we use the `addons.apt.*` alternatives to install packages without sudo?

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-do-I-install-APT-sources-and-packages%3F

**Comment by iglesias** [comment]
Reopening until we are sure if we can make use of this solution.

**Comment by vigsterkr** [comment]
lalala :) i haven't seen that thingy before... i'll push a pr to see how that works out.

**Comment by iglesias** [comment]
It sounds great :-)

**Comment by besser82** [comment]
Maybe [this doc](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) may come in handy…  =)

**Comment by erip** [comment]
Yes, there's plenty of documentation. The only thing I couldn't seem to find a mention of was how to do something like `sudo pip install ...`. I'm sure it's somewhere, but I couldn't find it. I'm no `travis` expert, though, so it might be easy. Definitely "normal" custom linux packages are easy to take care of, however.

**Comment by erip** [comment]
I spoke with someone at TravisCI and this is what they told me in response to the `sudo pip install foo` question:

> switch to `pip install foo --user` and it'll install and be available in the travis user's import path

**Comment by vigsterkr** [comment]
@erip that's already solved in the feature branch... the problem currently is that there are some outdated packages in that container based lala and i would need to add other ppa-s that are not in the whitelist.... i requested for adding them to the whitelist but it'll take a while till it gets in ... until then this endeavor of ours is on hold...

**Comment by vigsterkr** [comment]
@erip as u can see in that build, the coveralls build just runs fine... pip installed and all....

**Comment by erip** [comment]
@vigsterkr has the requested package been added to the whitelist?

**Comment by vigsterkr** [comment]
@erip noup, these are still missing:
https://github.com/travis-ci/apt-source-whitelist/issues/53
https://github.com/travis-ci/apt-source-whitelist/issues/121
