### ISSUE TITLE
about the MinimizerContext (CMap/CStringMap serialization)

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2903]
@lisitsyn 
Because most of classes in the minimizer framework are not subclasses of `SGObject` for now, we use MinimizerContext to store the mutable variables.

There will be many mutable variables when Adam, RmsProp and other updaters are added.
For example
```
SGVector<float64_t> mut_var1_for_adam
SGVector<float64_t> mut_var1_for_rmsprop
```

Option 1
Should I add these two vectors in data members of `MinimizerContext`?

Or

Option 2
We use a `chain` to manage these variables.

For example
* MinimizerContext is a head node
* Each component (eg,  Adam, RmsProp and other updaters ) creates a node and create an implicit  `SGObject` link list.

Or

Option 3
* create a `CMap<String, SGVector<float64_t> >` to store `SGVector<float64_t>` mutable variables. 
* create a `CMap<String, float64_t >` to store `float64_t` mutable variables. 
* Key (string) = ClassName::DataMemberName

**Comment by yorkerlin** [comment]
I vote for the CMap option.
@lisitsyn 
Any suggestion or anther option ?

**Comment by lisitsyn** [comment]
@yorkerlin yeah I like map as well

**Comment by yorkerlin** [comment]
@lisitsyn 
CMap (including CStringMap) does not support serialization.

**Comment by yorkerlin** [comment]
done
