### ISSUE TITLE
issue in CMap and CHash

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2904]
CMap use thes `CHash::MurmurHash3` algorithm
```
	int32_t CMap::hash(const K& key)
	{
		return CHash::MurmurHash3((uint8_t*)(&key), sizeof(key), 0xDEADBEEF) % hash_size;
	}
```

```
	const char* cc="may";
	std::cout<<CHash::MurmurHash3((uint8_t *)&cc, sizeof("may"), 1)<<std::endl;

	char *c1=SG_MALLOC(char, strlen("may")+1);
	strcpy(c1, "may");
	std::cout<<CHash::MurmurHash3((uint8_t *)&c1, sizeof(c1), 1)<<std::endl;
	
	char *c2=SG_MALLOC(char, strlen("may")+1);
	strcpy(c2, "may");
	std::cout<<CHash::MurmurHash3((uint8_t *)&c2, sizeof(c2), 1)<<std::endl;
```
I guess the function uses the memory address to generate a hash value.
The three outputs are different.
What is worse, the outputs are different every time I run the program.

This is not good for  `serialization` and `deserialization`. 
For example, `CMap<String, SGVector<float64_t> >` 
Any idea to use the `content` not the `memory address` to generate a hash value.

**Comment by yorkerlin** [comment]
@lisitsyn 
@iglesias

**Comment by yorkerlin** [comment]
However, the MD5 algorithm works fine
```
	unsigned char buff[17];
	const char* cc="may";
 
	CHash::MD5((unsigned char *)cc, strlen(cc), buff);
	buff[16]='\0';
	std::cout<<"["<<buff<<"]"<<std::endl;

	char *c1=SG_MALLOC(char, strlen("may")+1);
	strcpy(c1, "may");
	
	CHash::MD5((unsigned char *)c1, strlen("may"), buff);
	buff[16]='\0';
	std::cout<<"["<<buff<<"]"<<std::endl;

	char *c2=SG_MALLOC(char, strlen("may")+1);
	strcpy(c2, "may");
	 
	CHash::MD5((unsigned char *)c2, strlen("may"), buff);
	buff[16]='\0';
	std::cout<<"["<<buff<<"]"<<std::endl;
```
The outputs are the same.

**Comment by yorkerlin** [comment]
A bug is CHash
```
	int32_t index_of(const K& key)
	{
		int32_t index=hash(key);
		CMapNode<K ,T>* result=chain_search(index, key);

		if (result!=NULL)
			return result->index;

		return -1;
	}
```
```
    int32_t hash(const K& key)
    {
        return CHash::MurmurHash3((uint8_t*)(&key), sizeof(key), 0xDEADBEEF) % hash_size;
    }
```
The bug is CHash::MurmurHash3((uint8_t*)(&key), sizeof(key), 0xDEADBEEF) can return `negative` value

**Comment by vigsterkr** [comment]
why is it a bug that the hash can return a negative value? i mean the function defintion is `int32_t hash(const K& key)` which means that the return value is signed, i.e. half of the time it should actually return negative values...

**Comment by vigsterkr** [comment]
on the other hand using that as an index is a pure choice... since the definition of murmurhash3 is `static uint32_t MurmurHash3(uint8_t* data, int32_t len, uint32_t seed)` you can simply change the definition in `CMap::hash` to return `uint32_t`, this way the there will be no problems with negative values

**Comment by yorkerlin** [comment]
@vigsterkr 
Author of Map uses int32_t everywhere.

**Comment by yorkerlin** [comment]
@vigsterkr 
I write an unit test and it give a `segment fault` due to the conversion between `unit32_t` to `int32_t`.
For example, the positive range represent by `int32_t` is  `less than` the positive range represent by `unit32_t`

**Comment by yorkerlin** [comment]
@vigsterkr 
We need to change the index from `int32_t` to `unit32_t`.

**Comment by vigsterkr** [comment]
@yorkerlin no you don't need to: `sizeof(int32_t) = sizeof(unit32_t)` except that the MSB is in one case part of the number while the other case it's the sign value...

**Comment by vigsterkr** [comment]
and please note the modulo hash_size... i  mean by default the hash is a bucket of 41 different values...

**Comment by yorkerlin** [comment]
I think the main issue is
```
return CHash::MurmurHash3((uint8_t*)(&key), sizeof(key), 0xDEADBEEF) % hash_size;
```

(uint32_t) % (int32_t), it seems compiler will autocratically convert unit32_t to int32_t.

If so, the fix is 
```
return CHash::MurmurHash3((uint8_t*)(&key), sizeof(key), 0xDEADBEEF) % (unit32_t) hash_size;
```

**Comment by yorkerlin** [comment]
@vigsterkr 
The fix works!

**Comment by yorkerlin** [comment]
@vigsterkr 
My bad. 
The conversion from `unit32_t` to `int32_t` is due to a method used by me.

**Comment by yorkerlin** [comment]
The issue is solved.
I close this
