### ISSUE TITLE
ImportError: When I try to import modshogun

### ISSUE THREAD

**Issue by srsandeep** [shogun-toolbox/shogun#2907]
Hi,

I am new to shogun-toolkit. I want to use this module from python on my windows system.
Since I had to use cygwin to build it, I installed cygwiung on my window 7 system (64bit).
I thn did the following steps:
1. I downloaded the shogun-4.0.0.tar.bz2 and shogun-data-0.9.tar.bz2.
2. Extracted it as per the instruction on https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART
3. my cmake instruction was: 
cmake -DCMAKE_MAKE_PROGRAM="/usr/bin/make" -DCMAKE_C_COMPILER="/usr/bin/gcc" -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DPythonModular=ON -DENABLE_TESTING=ON -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ../
1. I then did a make and make install.
2. Added the path of shogun-install.
3. Opened Pyton IDLE (Python GUI) and executed the following command:
   from modshogun import *
   I was greeted with an error message:
   ImportError: No module named modshogun
4. So, I thought copied the modshogun.py and _modshogun.dll from shogun-install2\lib\python2.7\site-packages to my C:\Python27\Lib\site-packages directory
5. I now see the following error:
   ImportError: No module named _modshogun

Can you please help me to use this toolkit as a python module?

Sandeep

**Comment by iglesias** [comment]
Unfortunately, we do not have much experience using Shogun in Windows. Perhaps someone who has tried it in the past might be able to help you. @vigsterkr, @lisitsyn ?

**Comment by iglesias** [comment]
Any updates here @srsandeep?

**Comment by vigsterkr** [comment]
use conda-forge package for windows:
```
conda config --add channels conda-forge
conda install shogun
```

**Comment by ARAVINDSEGAR** [comment]
i have installed shogun in windows  using conda. so i have anaconda with python 3.6, i can import shogun, but i can not import modshogun, if i try this command *import modshogun* it shows *no module named modshogun*. could anyone help please ???

**Comment by karlnapf** [comment]
modshogun was renamed to just shogun
