### ISSUE TITLE
Ipython notebook - error calling modshogun module

### ISSUE THREAD

**Issue by jaelim** [shogun-toolbox/shogun#2914]
Shogun (latest git version) installed with Python module on. I'm testing one of your example Ipython notebook example of random forest. I have a problem of importing the modshogun module. 

This is output error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2a5ef96f7e1b> in <module>()
----> 1 from modshogun import CSVFile,RealFeatures,MulticlassLabels
      2 
      3 def load_file(feat_file,label_file):
      4     feats=RealFeatures(CSVFile(feat_file))
      5     labels=MulticlassLabels(CSVFile(label_file))

ImportError: No module named modshogun

As a first try to remedy this problem, I added this to .bashrc:
export PYTHONPATH="${PYTHONPATH}:$HOME/shogun-install/lib/python2.7/dist-packages/shogun/"

No improvement. Any idea?

**Comment by lisitsyn** [comment]
@jaelim this is definitely a problem with your `PYTHONPATH` environment. Be sure it points to correct directory. Please try `echo $PYTHONPATH` and check whether `modshogun.so` is available under one of printed directories.

**Comment by jaelim** [comment]
So, it's in my Python path:
$HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/shogun/

But, why is there an underscore line at the front of modshogun, like this?
~/shogun-install/lib/python2.7/dist-packages/_modshogun.so

**Comment by yorkerlin** [comment]
I think
The following Python path  should work
$HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/
, if _modshogun.so at  ~/shogun-install/lib/python2.7/dist-packages/

On Thursday, September 3, 2015, Jae Lim <notifications@github.com> wrote:

> So, it's in my Python path:
>
> $HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/shogun/
>
> But, why is there an underscore line at the front of modshogun, like this?
> ~/shogun-install/lib/python2.7/dist-packages/_modshogun.so
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2914#issuecomment-137522222>
> .
>


-- 
best,

wu lin

**Comment by jaelim** [comment]
@yorkerlin Sorry I even tried it already (meaning $HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/), but it's not working. Again, I found this _modshogun.so with an underscore line instead. I made a change in TreeEnsemble.ipynb with this line:

from _modshogun import CSVFile,RealFeatures,MulticlassLabels

No luck.

**Comment by yorkerlin** [comment]
Try this:

* $HOME/shogun-install/lib/python2.7/dist-packages/ in your python path
* _modshogun.so at  ~/shogun-install/lib/python2.7/dist-packages/
* modshogun.py at  ~/shogun-install/lib/python2.7/dist-packages/

BTW, modshogun.py will call _modshogun.so and you should import modshogun

On Thursday, September 3, 2015, Jae Lim <notifications@github.com> wrote:

> @yorkerlin <https://github.com/yorkerlin> Sorry I even tried it already
> (meaning
> $HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/),
> but it's not working. Again, I found this _modshogun.so with an underscore
> line instead. I made a change in TreeEnsemble.ipynb with this line:
>
> from _modshogun import CSVFile,RealFeatures,MulticlassLabels
>
> No luck.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/issues/2914#issuecomment-137526489>
> .
>


-- 
best,

wu lin

**Comment by yorkerlin** [comment]
BTW, modshogun.py will call _modshogun.so and you should do

from modshogun import CSVFile,RealFeatures,MulticlassLabels


On Thursday, September 3, 2015, yorker lin <yorkerjaster@gmail.com> wrote:

> Try this:
>
> * $HOME/shogun-install/lib/python2.7/dist-packages/ in your python path
> * _modshogun.so at  ~/shogun-install/lib/python2.7/dist-packages/
> * modshogun.py at  ~/shogun-install/lib/python2.7/dist-packages/
>
> BTW, modshogun.py will call _modshogun.so and you should import modshogun
>
> On Thursday, September 3, 2015, Jae Lim <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @yorkerlin <https://github.com/yorkerlin> Sorry I even tried it already
>> (meaning
>> $HOME/python-codec/src:$HOME/shogun-install/lib/python2.7/dist-packages/),
>> but it's not working. Again, I found this _modshogun.so with an underscore
>> line instead. I made a change in TreeEnsemble.ipynb with this line:
>>
>> from _modshogun import CSVFile,RealFeatures,MulticlassLabels
>>
>> No luck.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/shogun-toolbox/shogun/issues/2914#issuecomment-137526489>
>> .
>>
>
>
> --
> best,
>
> wu lin
>
>

-- 
best,

wu lin

**Comment by jaelim** [comment]
@yorkerlin It's strange. Like you said, I had my Python path with this: 
export PYTHONPATH="${PYTHONPATH}:~/shogun-install/lib/python2.7/dist-packages/"

It even shows by echo $PYTHONPATH. And I see both modshogun.py and _modshogun.so.
Is there other way you can set your Python path? Because, I have it in my ~/.bashrc

**Comment by jaelim** [comment]
@yorkerlin Interesting result. I tried to import methods from modshogun in python command prompt mode:

>>> from modshogun import CSVFile,RealFeatures,MulticlassLabels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "modshogun.py", line 32, in <module>
    _modshogun = swig_import_helper()
  File "modshogun.py", line 28, in swig_import_helper
    _mod = imp.load_module('_modshogun', fp, pathname, description)
ImportError: ./_modshogun.so: undefined symbol: _ZNK6shogun9CFeatures31get_feature_class_compatibilityENS_13EFeatureClassE

**Comment by yorkerlin** [comment]
@jaelim 
Try this,
* make sure  `_modshogun.so`  and `modshogun.py` at `~/shogun-install/lib/python2.7/dist-packages/`
* go to `~/shogun-install/lib/python2.7/dist-packages/`, which means your working direction (`pwd`) is `~/shogun-install/lib/python2.7/dist-packages/`
* run `python` (meaning the interactive mode, not run as script)
* try `from modshogun import CSVFile,RealFeatures,MulticlassLabels` in the Python Interpreter

If this works, you may consider the issue is related to ` LD_LIBRARY_PATH`

**Comment by lisitsyn** [comment]
Just yesterday, we had some user that used $HOME in .bashrc and in the end full path (w/o $HOME) worked. Be sure $HOME is replaced - it won't work otherwise

**Comment by jaelim** [comment]
@yorkerlin Reported in my last message. In the python mode in the folder location as mentioned, and this is following output:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "modshogun.py", line 32, in <module>
    _modshogun = swig_import_helper()
  File "modshogun.py", line 28, in swig_import_helper
    _mod = imp.load_module('_modshogun', fp, pathname, description)
ImportError: ./_modshogun.so: undefined symbol: _ZNK6shogun9CFeatures31get_feature_class_compatibilityENS_13EFeatureClassE

**Comment by lisitsyn** [comment]
@jaelim good. Now set the `LD_LIBRARY_PATH` to the directory that has `_modshogun.so` inside

**Comment by jaelim** [comment]
@lisitsyn I replaced it with $HOME before pasting here to hide my user name identity.

**Comment by lisitsyn** [comment]
@jaelim ok, just be sure it is set properly. If it works in the directory with module then the `PYTHONPATH` is wrong

**Comment by jaelim** [comment]
@yorkerlin @lisitsyn No luck. I did exactly.

**Comment by jaelim** [comment]
@yorkerlin @lisitsyn 

which python: /usr/bin/python
python --version: Python 2.7.6

**Comment by yorkerlin** [comment]
```git clone https://github.com/shogun-toolbox/shogun
cd shogun && mkdir build
cd build
cmake   -DPythonModular=ON ../
make && cd src/interfaces/python_modular/
python```

type `import modshogun` in the Python Interpreter

If this does not work, you please report to us (your OS, compiler, and SWIG including their release version)

**Comment by yorkerlin** [comment]
@jaelim 
do you solve this issue?

**Comment by jaelim** [comment]
@yorkerlin no unfortunately I had a serious computer breakdown while rebuilding shogun. While rebuilding shogun to include the test-examples, it caused a wide computer slowdown. So, I manually had to shut each program I was using, then still the computer ran very slow. I turned off the computer by using physical power button. When I tried to restart the Ubuntu, I was not able to start the graphic desktop. I think shogun corrupted the linux system files.

I had an earlier warning before this computer breakdown. It caused programs to run very slow and I shut down the computer. But this time shogun really killed my machine.

**Comment by lisitsyn** [comment]
@jaelim no, its your power button.

**Comment by jaelim** [comment]
@lisitsyn believe it or not, yes it is related to shogun. the problem happened while building the package. it happened once without killing the machine as a warning, and the second time when it happened during a package rebuilding process, it killed ubuntu. poorly supported.

**Comment by yorkerlin** [comment]
@lisitsyn 
I think we should recommend users to use official binary packages via apt-get or yum.
For shogun developers, compilation for shogun is not so easy. 
In fact, compiling a package written in C/C++  is not trivial since it requires developers have background knowledge in OS.

@jaelim 
You can google your issue related to ubuntu. I think improperly shutting down linux may corrupt your file system.  Compilation will not corrupt your file system unless a process related compilation is writing something into your hard drive and you interrupt the writing process via the power button. Anyway, Thank for your feedback. 

Lesson: 
Easy installation for users (may be for developers too) is essential.

**Comment by lisitsyn** [comment]
@yorkerlin yes, that's pretty clear we should use proper ways of distrubution.

Although the claim of breaking hardware by compilation is absolutely ridiculous.

**Comment by besser82** [comment]
@jaelim When I build complete Shogun from sources, my machine get's slow as hell too…  All eight CPU-cores are running @100%…  How many RAM do you have installed inside your machine?  Terrible slow operation often is related to swapping mempages to HDD.  Building modular-interfaces (e.g. Python) takes serious amounts (~ 8 GByte) of RAM.

@yorkerlin Currently we have two distros shipping Shogun in their native repos:  Fedora (v4.0.0 on <= 22, and git-snapshot in F23-beta / F-rawhide) and Debian (v3.20 in Debian Sid)…

**Comment by yorkerlin** [comment]
@lisitsyn @besser82 maybe, we warn users who want to build shogun from source code, the minimum requirement  (free disk space, RAM, and CPU) to build shogun.

@besser82 In my laptop(i7 8 cores, 16GBtye RAM, SSD), Compilation takes  at least half of hour, more than 6GByte of RAM, and more than 1GBtye of free space to build shogun.

**Comment by yorkerlin** [comment]
Maybe include some minimum hardware requirement  at https://github.com/shogun-toolbox/shogun/wiki/INSTALL

**Comment by besser82** [comment]
@yorkerlin Same specs for my laptop…  Full build (all modular-interfaces and unit-test) takes ~45+ Mins.  RAM usage is avg. ~6 Gigs, too;  peak is 12 GBytes (during octave_modular).

**Comment by jaelim** [comment]
If a package build process freezes your system without giving you an option to get out of it, then what other choice do you have left with other than shutting the system manually?

In this case, the first time while building shogun froze my system completely (mouse pointer completely unresponsive) giving me no choice but to shut it down using the power button, and luckily that did not destroy my OS.

But, when it happened for the second where it caused a system wide slow down, and even after closing all application programs including shogun build process, it still left the system run extremely slow with repetition of freezes (including even mouse pointer froze randomly). Then I had no other means but to rely on shutting down the system manually.

This is the problem of shogun. If you think it's not then that's your choice to leave it as it is without investigating. Because down the road, someone's going to have a similar problem even for developers.

**Comment by yorkerlin** [comment]
@jaelim 
Thanks for your feedback and sorry for inconvenience due to the compilation.

@lisitsyn @besser82 
From the fact mentioned by @jaelim, we can tell that the compiler eats a lot of RAM during the compilation. The swap from memory to hard drive freezes the user's system and the user has to shut down the system using the `power button`, which in turn corrupts the file system. 
We should recommend users (not for developers) `not` to build shogun from source codes if their hardware does `not meet` the `minimum requirement` (free disk space, RAM, CPU and GPU if we enable GPU computing).

Lesson:
* Add some the `minimum requirement` (RAM) to build shogun from source codes
* Building shogun from source  codes in a system which has 4GByte RAM or less may cause unpleasant experience

**Comment by yorkerlin** [comment]
@lisitsyn @besser82 
Some idea about building shogun:
* Offering an option to build needed shogun modules may reduce the memory requirement. 

For me, I only need Gaussian process module, model selection module and optimizer module.
Changing codes in `Kernel` or `CMath` cause the compiler to rebuild MKL, SVM and other unwanted models :(

**Comment by lisitsyn** [comment]
I'd like to note that there is no such thing as 'building shogun package', it's rather standard CMake + Make + GCC + Swig toolchain. We can't and shouldn't control behaviour of tools. Indeed, it takes a lot of memory and we should clarify the design with some techniques to reduce that, but no need to care about every little detail of OS.
