### ISSUE TITLE
Unit test files

### ISSUE THREAD

**Issue by jaelim** [shogun-toolbox/shogun#2915]
I want to test all your unit test files found under ~/shogun/test/unit.

I have no clue how to make executable binaries. I try to make by 'make -j shogun-unit-test', but does not seem to work because there's no Makefile.

How do you make unit test files and run them?

**Comment by lisitsyn** [comment]
1. Create some directory to store build (mkdir build)
2. Go to that directory and run CMake (cd build; cmake -DENABLE_TESTING=ON ..)
3. Build with regular `make` and use `make test`

**Comment by erip** [comment]
Recommend closing. Information on building/testing can be found [here](https://github.com/shogun-toolbox/shogun/wiki/README_cmake).

**Comment by lisitsyn** [comment]
Yeah, true
