### ISSUE TITLE
Python3 - Set paths to what?

### ISSUE THREAD

**Issue by Arnei** [shogun-toolbox/shogun#2918]
Hello,
I've been trying to install this wonderful toolbox for Python3 under Ubuntu 14. Do this is used this cmake command:

cmake -DPYTHON_INCLUDE_DIR=/usr/include/python3.4 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.4/dist-packages -DPythonModular=ON -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ..

It seems this was not the best idea, as I now have some files in the "/home/shogun-install" folder, as well as files in "user/local/lib". So I've been trying to set PYTHONPATH and LD_LIBRARY_PATH in the bashrc file to the right locations, but without much luck. It seems pycharm can already detect modshogun, but none of its modules (like RealFeatures, C45ClassifierTree etc.). The paths I currently have set are:

export PYTHONPATH=/usr/local/lib/python3.4/dist-packages:/home/arwilken/shogun/examples/undocumented/python_modular:$PYTHONPATH 
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

Could anyone give me a hint to which files I have to make these paths point?

**Comment by lisitsyn** [comment]
Ok what files fo you have in /usr/local/lib and what files do you have in that shogun-install directory?

PYTHONPATH should point to the directory that has modshogun.py
LD_LIBRARY_PATH should point to the directory that has modshogun.so

**Comment by besser82** [comment]
LD_LIBRARY_PATH should point to the directory that has modshogun.so
I think you're mistaken here…  LD_LIBRARY_PATH should point to the dir `libshogun.so` is located in…

**Comment by lisitsyn** [comment]
Yeah sorry, libshogun.so

**Comment by Arnei** [comment]
/usr/local/lib contains folders for python2.7 and python3.4, as well as libshogun.so, libshogun.so.15 and libshogun.so.15.1
shogun-install contains the folders include, lib and share. The lib folder has the files libshogun.so, libshogun.so.17 and libshogun.so.17.1. Neither of the two paths seem to work though.

**Comment by lisitsyn** [comment]
Actually, from your description of the problem it should be a PYTHONPATH issue. Wrong LD_LIBRARY_PATH would lead to undefined reference errors; in your case its modshogun.py that is missed by python.

I'd suggest you with running 
```PYTHONPATH=... LD_LIBRARY_PATH=... python -c 'import modshogun'```
until it finally works. This would be the correct configuration.

**Comment by Arnei** [comment]
No combination of paths worked, instead I got this nice little message for each combination:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/modshogun.py", line 32, in <module>
    _modshogun = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/modshogun.py", line 28, in swig_import_helper
    _mod = imp.load_module('_modshogun', fp, pathname, description)
ImportError: dynamic module does not define init function (init_modshogun)

Am I right to assume that something went wrong during the building process?

**Comment by lisitsyn** [comment]
@Arnei yeah that's sort of strange. It detects modshogun.py but fails to load libshogun.so. Could it be that libshogun.so for python2.7 is used?

@besser82 do you have any idea?

**Comment by Arnei** [comment]
Hmm, I previously had modshogun installed for python2.7 and the "libshogun.so.15" files seem to be leftovers from that installation. However, the new libshogun.so files produce the same error. I tried to build everything for python3, but maybe I have overlooked something in my cmake command?

**Comment by besser82** [comment]
@Arnei I'd suggest to remove all leftovers and rebuilding everything from scratch a second time…

**Comment by Arnei** [comment]
Okay, I removed everything shogun related and rebuild it. The same error persists.

**Comment by lisitsyn** [comment]
@Arnei does it work with other python version?

**Comment by Arnei** [comment]
I think I found my mistake. As usual, it was a typo. Instead of using "python -c 'import modshogun'" I of course have to use "python3 -c 'import modshogun'" to test if it works with python3 >.<. Now everything seems to work fine (except for pycharm giving me wrong error messages, but that doesn't belong here).
Thanks a lot for your help. I definitely learned a thing or two from this.

**Comment by lisitsyn** [comment]
@Arnei oh, good it is resolved. Thanks for letting us know
