### ISSUE TITLE
fully support C++11 ?

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2919]
For now, the buildbot does not support some useful features introduced in C++11.
For example, the buildbot complains about the `auto` keyword.
Do we pay more attention on compatibility?
If we can distribute shogun via binary package for users, we may pay more attention on `new technique` for developers.

**Comment by yorkerlin** [comment]
@vigsterkr 
@lambday 
@lisitsyn 
@karlnapf 
@iglesias 
any ideas?

**Comment by lisitsyn** [comment]
I don't think buildbot doesn't support that, it has GCC 4.9.2.

It's a matter of configuration and we should use C++11.

**Comment by iglesias** [comment]
I definitely agree with @lisitsyn. I haven't checked the version of the compiler myself, but it *must* support C++11. If it is not enabled by default, then we have to set the appropriate compiler flag.

**Comment by lambday** [comment]
@yorkerlin check issue #271.

**Comment by yorkerlin** [comment]
please keep this open until the buildbot is fixed

**Comment by erip** [comment]
I don't mean to sound glib, but does the buildbot compile with `-std=c++11`?

**Comment by lisitsyn** [comment]
@erip our machine running buildbot has modern GCC to support that

**Comment by erip** [comment]
@lisitsyn Sure, but you still need to compile with the `-std=c++11` flag. A newer version doesn't allow for omission of some "non-standard" flags.

**Comment by besser82** [comment]
'-std=c++11' gets injected to build-flags automagically by an external CMake-script, if the compiler supports && needs that…  Dunno why build go pop anyways…  :(

**Comment by lambday** [comment]
Done. Closing.
