### ISSUE TITLE
error with from modshogun import LMNN

### ISSUE THREAD

**Issue by danieljf24** [shogun-toolbox/shogun#2925]
I installed shogun3.1.1 on ubuntu14.04 with python interface.
I can import modshogun successfully, while it hint “ImportError: cannot import name LMNN” when enter "from modshogun import LMNN". 
what happened? I just do following this instruction: http://nbviewer.ipython.org/gist/iglesias/6576096
Thanks in advance.

**Comment by iglesias** [comment]
Hey Daniel! Thank you for your interest in Shogun and the LMNN implementation. Note that the LMNN implementation in Shogun depends on Eigen3. Did you compile Shogun with Eigen3 support enabled?

**Comment by danieljf24** [comment]
Hi, iglesias. I didn't comile Shogun with Eigen3, only with command 'cmake -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" -DPythonModular=ON ..'. Could you tell the exact command to compile Shogun? Thanks very much!

**Comment by iglesias** [comment]
`
cmake -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" -DPythonModular=ON -DENABLE_EIGEN=ON ..
`
should make it (providing you have an active internet connection, the option above will download Eigen 3 and bundle it into your Shogun installation.

When dealing with cmake in general, not restricted to Shogun, I suggest you to use ccmake when in doubt of the available cmake options or their exact name.

**Comment by danieljf24** [comment]
I cmake with Eigen on, but it hint "Manually-specified variables were not used by the project: ENABLE_EIGEN". I sure my computer have an active internet connection.

**Comment by iglesias** [comment]
Oh, sorry about that. My mistake.

**Comment by iglesias** [comment]
Solving issue.
