### ISSUE TITLE
How can i develope using c++???

### ISSUE THREAD

**Issue by shin2jhoon** [shogun-toolbox/shogun#2926]
I want to make some program using "GaussianNaiveBayes.h" with c++ language.
I find it how to implementation like this,
"
../examples/documented/libshogun/classifier_gaussiannaivebayes.cpp #include <shogun/labels/MulticlassLabels.h>
#include <shogun/features/DenseFeatures.h>
#include <shogun/multiclass/GaussianNaiveBayes.h>
#include <shogun/base/init.h>
#include <shogun/lib/common.h>
#include <shogun/io/SGIO.h>
using namespace shogun;
int main(int argc, char** argv)
{
	init_shogun_with_defaults();
...
"

But when I compile this, "'shogun/lib/config.h': No such file or directory" error message is come out.
I think i didn't import shogun library well, and have no idea about the others.

Can you help me~~~~~~~~~~?
I want to start~~~!!

**Comment by lambday** [comment]
Hi @shin2jhoon. Thanks for your interest in Shogun. You can get some basic help regarding some beginners' issues at our [wiki](https://github.com/shogun-toolbox/shogun/wiki) pages. Make sure you read the [quickstart guide](https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART) and [getting started](https://github.com/shogun-toolbox/shogun/wiki/README_developer) developer readme. If you follow the guidelines, I am pretty sure you'll get around this issue.

**Comment by lisitsyn** [comment]
I am closing this issue as invalid.
