### ISSUE TITLE
Make travis use new container based infrastructure

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2936]
Travis recently moved to a new docker based container infrastructure, which runs faster.

We can adjust our travis build to run in the new environment. We need a few tweaks to the .travis.yml as no more "sudo" is allowed.

Some cool new features are in there too, for example "caching" (I use that in my python repositories to not compile scipy within travis, but just use a chached version, see [here](https://github.com/karlnapf/kernel_hmc/blob/master/.travis.yml))

See:
https://docs.travis-ci.com/user/workers/container-based-infrastructure/
https://github.com/shogun-toolbox/shogun/blob/develop/.travis.yml
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by vigsterkr** [comment]
dude, this is duplication of #2900 and currently the ball is at the travis people, i.e. this effort is being blocked by them...

**Comment by karlnapf** [comment]
Ah cool, I did not see that back then as I was in holiday.
Is there any way we can push them so that this does not die ?

**Comment by vigsterkr** [comment]
dont care about your excuses! :P :dancer: (joking)
mmmm not really, i've pushed all the requirements to their repos, but the PRs still just hanging there..

**Comment by karlnapf** [comment]
ha! next time I take my computer when cycling through Europe ;)

Dont know how to get people merge things, a ping is always good I guess

**Comment by erip** [comment]
@karlnapf FWIW I've tried to push as well. No luck so far - time will tell.

**Comment by karlnapf** [comment]
Lets just stay on this, ask periodically....sometimes helps ;) But it's a thin line to annoyance ;)

**Comment by erip** [comment]
We should just develop a quick script that checks the status of the issues. If they haven't been merged, just submit a hard-coded comment. [inspiration](https://github.com/NARKOZ/hacker-scripts)
