### ISSUE TITLE
Using precomputed distance kernels and sparse features gives this error: NotImplementedError: Wrong number or type of arguments

### ISSUE THREAD

**Issue by iarroyof** [shogun-toolbox/shogun#2945]
I had time for analyzing a bit more the issue, which persists. The problem takes place when I try to use any kernel which uses a precomputed distance object ('dst' in the attached code snippet). I tested both, the sparse and the dense versions of the 'EulideanDistance' object. The program crashes after calling the `mkl.train()` method. For the Gaussian, Linear and Polynomial kernels (uniquely for these kernels) it is not needed a precomputed distance matrix, so all works fine with them. See the following code example which gives an error for the `CauchyKernel`, which expects a precomputed distance matrix object:
```
from modshogun import *
from numpy import random, array
from scipy.sparse import csr_matrix

# Create the input sparse matrix
r=array([0,2,0,2,1,2,1,2])
c=array([0,0,1,1,2,2,3,3])
data=array([0.950836978354, 2.40814562724, 0.441304200555, 3.7801571175, 0.4498, 3.5287, 1.4163, 0.2434]) 
train_data = csr_matrix((data, (r, c)), shape=(3, 4)).astype('float32').T
# Convert data to Shogun sparse features
feats_train = SparseShortRealFeatures(train_data)
labels_train = RegressionLabels(random.rand(4,))
k0 = PolyKernel(10,3)
dist = EuclideanDistance(feats_train,feats_train)
k1 = CauchyKernel(0, 10, dist)
k0.init(feats_train,feats_train)
k1.init(feats_train,feats_train)
k = CombinedKernel()
k.append_kernel(k0)
k.append_kernel(k1)
k.init(feats_train,feats_train)
mkl = MKLRegression()
mkl.set_C(1,1)
mkl.set_mkl_norm(2)
mkl.set_kernel(k)
mkl.set_labels(labels_tr)
mkl.train()
print mkl.get_subkernel_weights()
```
The following error is given:
```
iarroyof@computer:~$ python mkl22.py
Traceback (most recent call last):
  File "mkl22.py", line 14, in <module>
    dist = EuclideanDistance(feats_train,feats_train)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_EuclideanDistance'.
  Possible C/C++ prototypes are:
    shogun::CEuclideanDistance::CEuclideanDistance()
    shogun::CEuclideanDistance::CEuclideanDistance(shogun::CDenseFeatures< float64_t > *,shogun::CDenseFeatures< float64_t > *)
```
Thank you very much for helping.

**Comment by karlnapf** [comment]
Thanks for putting this up.

I am confused.  Looking at the error message, this is ```CEuclideanDistance``` complaining that it needs dense features as input, but you are giving it sparse ones. Is that your problem?

**Comment by iarroyof** [comment]
Hi... Thank you for reply. I also used CSparseEuclideanDistance and it can
be seen the error is the same.

**Comment by iarroyof** [comment]
The problem is these distance objects give type errors for sparse feature
objects.

**Comment by iarroyof** [comment]
I have edited the posted code for properly running the script.

**Comment by karlnapf** [comment]
Hi.
There were a number of API usage errors in there. You have to use ```SparseEuclideanDistance``` if you are passing sparse features. The error message tells you exactly that you can only pass ```CDenseFeatures``` but you passed ```SparseShortRealFeatures```

See [this snippet](https://gist.github.com/karlnapf/645e1c2744fd9e8f1936), which works on my machine. 

I close the issue, let me know if something else does not work

**Comment by sonney2k** [comment]
and you should normally use ```CombinedFeatures``` and initialize the combined kernel just once with it.

**Comment by iarroyof** [comment]
Thank you guys for your support. I tested with all other kernels I'm using and the gist code revision works. @sonney2k I will change the procedure by using combined features.

It probably remains open the question of what to do for using SparseShortRealFeatures. It could be useful.

**Comment by karlnapf** [comment]
Very welcome!

@iarroyof The idea of the combined features is that different kernels in the combined kernel can use different features. 

I do not understand your last question.

**Comment by iarroyof** [comment]
My last question is regarding to what to do if we need using `SparseShortRealFeatures` with some precomputed distance kernel, e.g., `CTStudentKernel` or `CCauchyKernel`. Would be there some advantage by using `SparseShortRealFeatures` instead of `SparseRealFeatures`? e.g. memory consuming. In the case this particular advantage were provided by Short features, I think it would be useful enabling some distance function (if it does not exist) for using Short features (`shogun::CSparseFeatures< float32_t > *`).

**Comment by karlnapf** [comment]
You are right that the ```SparseDistance``` subclasses are all based on ```float64_t```

See [here](http://www.shogun-toolbox.org/doc/en/latest/classshogun_1_1CEuclideanDistance.html)

This is coming from implementation details. It is possible to add a shorter version, but that is some work. So if you have memory issues (do you?) then we could add a 32bit distance.

**Comment by iarroyof** [comment]
Thank you very much cor your time Heiko. I think there is not problem for
now, however, some tests are pending in my project for realworld data.

I will keep you informed.

**Comment by karlnapf** [comment]
Cool. Let us know how it goes and where we can improve things.

**Comment by iarroyof** [comment]
Hi all, I just tested the corrections in this issue for real-world data. This data must be loaded from a file. It seems this fact changes the matrix object in deep. 

I replaced the line  9 of this file https://gist.github.com/karlnapf/645e1c2744fd9e8f1936 by: 

`train_data =csr_matrix(mmread('sparse_train.mtx')).astype('float64')`

where `sparse_train.mtx` contains:

```
%%MatrixMarket matrix coordinate integer general
%
9 9 5
3 1 40
4 5 16
4 6 20
8 7 24
9 2 4
```

The given error is:

```
Traceback (most recent call last):
  File "gistfile1.py", line 28, in <module>
    mkl.train()
SystemError: [ERROR] In file /home/iarroyof/shogun/src/shogun/features/SparseFeatures.cpp line 407: assertion avec.features failed in float64_t shogun::CSparseFeatures<ST>::compute_squared_norm(shogun::CSparseFeatures<double>*, float64_t*, int32_t, shogun::CSparseFeatures<double>*, float64_t*, int32_t) [with ST = double; float64_t = double; int32_t = int] file /home/iarroyof/shogun/src/shogun/features/SparseFeatures.cpp line 407
```
Which is confusing because I specified 'float64' as data type. It is possible `mmread` is working in an undesirable way?

**Comment by karlnapf** [comment]
Seems weird indeed. What is the output of mmread itself then?

**Comment by iarroyof** [comment]
Thank you for reply @karlnaf.

Given the input is in sparse format mmread returns a coo_matrix (a scipy sparse matrix):

http://docs.scipy.org/doc/scipy/reference/generated/scipy.io.mmread.html#scipy.io.mmread

At the moment it is impossible loading a file in sparse format and then getting SparseFeatures

**Comment by karlnapf** [comment]
The error you have actually comes from the fact that there is no feature data set internally. This can have multiple reasons. Let's try to isolate the problem a bit....

What happens if you ask the feature object for its number of vectors and features? Or for the full matrix?
```
feats_train = SparseRealFeatures(train_data)
print feats_train.get_num_features()
print  feats_train.get_num_vectors()
print feats_train.get_sparse_feature_matrix()
```

**Comment by iarroyof** [comment]
This is the output:

```
>>> print feats_train.get_num_features()
9
>>> print  feats_train.get_num_vectors()
9
>>> print feats_train.get_sparse_feature_matrix()
(array([ 40.,  16.,  20.,  24.,   4.]), array([0, 4, 5, 6, 1], dtype=int32), array([0, 0, 0, 1, 3, 3, 3, 3, 4, 5], dtype=int32))
```
