### ISSUE TITLE
some confusion about the Lloyd kmeans algorithm

### ISSUE THREAD

**Issue by HaiQW** [shogun-toolbox/shogun#2951]
It is obviously that the Lloyed kmeans algorithm implementation only considers one case, the fixed cluster centers,  while ignores the other.

**Comment by iglesias** [comment]
I am not entirely sure I understand you correctly. To me fixed cluster centers would mean that the cluster centers are not moved, fixed from the beginning and not iteratively updated as it should happen as per the method description. In fact, that would not really be a clustering method in my view.

Can you elaborate?

**Comment by HaiQW** [comment]
I agree with you opinion that fixed centers cluster clustering is the really clustering algorithm. But, why the Lloyed Kmeans algorithm implementation updates all cluster centers at the very beginning of the while cycle, like this if (!fixed_centers). I think that the following code does not consider the case of changed cluster centers.

But I am not sure of my viewpoint.

**Comment by iglesias** [comment]
Hello again.

`fixed_centers` is just an option we provide in the algorithm. You can use the algorithm with either the option set to true or false.

Why do you use that it obviously considers one case and ignores the other?

**Comment by HaiQW** [comment]
Hi. 
I am so sorry  that I used the wrong sentence, 'it obviously considers one case and ignores the other'.  I just confused with  the 'fixed_centers' option.

**Comment by iglesias** [comment]
No problem at all :-)
