### ISSUE TITLE
Make NeuralConvLayer use linalg convolution

### ISSUE THREAD

**Issue by sanuj** [shogun-toolbox/shogun#2957]
- Implement convolution in linalg with `NATIVE` backend.
- Change `CConvolutionalFeatureMap::convolve` in `ConvolutionalFeatureMap.cpp` to use `linalg::convolve`

@karlnapf I'll send a PR soon. Tell me if I'm missing something.

**Comment by karlnapf** [comment]
There is already something in place I saw. Better check that before you start....

**Comment by karlnapf** [comment]
[here](http://www.shogun-)toolbox.org/doc/en/latest/structshogun_1_1linalg_1_1implementation_1_1convolve_3_01Backend_1_1EIGEN3_00_01Matrix_01_4.html

**Comment by karlnapf** [comment]
Making the native backend use openmp would be an improvement

**Comment by sanuj** [comment]
@karlnapf I had seen the `linalg/implementations/convolve.h` file and was talking about adding `NATIVE` backend to this.

`HAVE_LINALG_LIB` variable is not always set by cmake as you can see [here](https://github.com/shogun-toolbox/shogun/blob/develop/CMakeLists.txt#L752). Should I also take care of this by using `#ifdef HAVE_LINALG_LIB` and keeping the existing convolution code if `HAVE_LINALG_LIB` is not set?

**Comment by sanuj** [comment]
`CConvolutionalFeatureMap.cpp` would look something like:
```
#ifdef HAVE_LINALG_LIB
#include <shogun/mathematics/linalg/linalg.h>

using namespace linalg;
#endif // HAVE_LINALG_LIB
...
...
...
#if defined HAVE_LINALG_LIB
    // use linalg::convolve
#else
    // The existing convolution code goes here
#endif // HAVE_LINALG_LIB
```

**Comment by sanuj** [comment]
Why is [this code](https://github.com/shogun-toolbox/shogun/blob/d8eb73dd89f47e0da28f07163c4f635b96d0ec00/src/shogun/mathematics/linalg/internal/implementation/Convolve.h#L115) encapsulated in `#ifdef HAVE_EIGEN3 .... #endif`? It can also work without Eigen3.

**Comment by karlnapf** [comment]
@lambday should answer here

**Comment by karlnapf** [comment]
Any code from linalg should only be available if the linalg lib is enabled.

The code that you referenced indeed does not depend on eigen, but @lambday should get back to you about this...
