### ISSUE TITLE
BSD license 

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2958]
As we have now enough "critical mass" to do the license change, here is the list of steps TODO
- create a blacklist of files that cannot be changed to BSD (integrated libs as SVMLight, alglib code in `CStatistics`, ...)
- Add a new LICENSE file with the BSD we use
- Remove GPL license header from all files
- Replace with a reference to LICENSE file and put all authors from git history in
- Discuss blacklist with team
- Once everyone is happy, change the main license and announce

@lisitsyn I'll assign you as discussed

**Comment by vigsterkr** [comment]
Sooooo

merry xmas (both roman catholic and orthodox) and new year!

can i help with this in any ways?

viktor

**Comment by karlnapf** [comment]
Merry :)

Yes, let's do the change.
There are only few files which cannot be updated. We need a cake switch for
them I guess....

Sergey thought it was a good idea to put a small header referencing the
main license file and then put names of authors in order of got log
frequency

Thoughts?

**Comment by lisitsyn** [comment]
hey guys,

I'll start a branch.

**Comment by karlnapf** [comment]
Great, thanks @lisitsyn

**Comment by lisitsyn** [comment]
Ok here is how we could do that:
```bash
git log --format='%aN <%aE>' src/shogun/features/DenseFeatures.h | sort | uniq -c | sort -nr | cut -d' ' -f5-
                                                 
Soeren Sonnenburg <sonne@debian.org>
Heiko Strathmann <heiko.strathmann@gmail.com>
vladislav.horbatiuk@gmail.com <vladislav.horbatiuk@gmail.com>
lambday <heavensdevil6909@gmail.com>
Yuyu Zhang <zhangyuyu2008@gmail.com>
Thoralf Klein <thoralf@fischlustig.de>
Sergey Lisitsyn <blackburn91@gmail.com>
Kevin <kevinhughes27@gmail.com>
Fernando Iglesias <fernando.iglesiasg@gmail.com>
Evgeniy Andreev <gsomix@gmail.com>
Björn Esser <bjoern.esser@gmail.com>
```

**Comment by karlnapf** [comment]
Good. Want to start a PR?

**Comment by skn123** [comment]
Has this change been effected ?

**Comment by karlnapf** [comment]
We are more than 50%
If it is if interest for you we can push this pretty sokn

**Comment by skn123** [comment]
absolutely. If there is anything I can do to help please let me know.

**Comment by karlnapf** [comment]
You can see some of the code is guarded via `USE_GPL_SHOGUN`.
All guarded files will eventually be moved to a separate repository (see `feature/gpl` branch).

The rule is:
 * We got all Shogun devs accepted to move their code to BSD.
 * There is some external code that is GPL and so do the Shogun classes that depend on it
 * If you find any GPL code file in Shogun that is not guarded, sending a PR with the guard (that doesnt break the build when the cmake flag is turned on/off), helps big time.

**Comment by skn123** [comment]
I will do that immediately.
