### ISSUE TITLE
Guide to make unit-tests

### ISSUE THREAD

**Issue by sanuj** [shogun-toolbox/shogun#2960]
Someone needs to correct the [README_developer](https://github.com/shogun-toolbox/shogun/wiki/README_developer) on the wiki (I would have done it but I can't).
- In the unit testing part it says that it is necessary to install Google Mock and Google Test on your machine which is not true. Google Mock files are supposed to be placed in the `build` directory from where unit-tests will be made.
- In order to download the Google Mock source and place it in the `build` directory, one needs to do `make -j GoogleMock` which is only specified in [README_cmake](https://github.com/shogun-toolbox/shogun/wiki/README_cmake). It would be helpful if this step is also specified in README_developer. This step is supposed to be done after `cmake -DENABLE_TESTING=ON ..` and before `make unit-tests`.
- If `make -j GoogleMock` does not work due to hash mismatch error (it always happens in my case) then download the Google Mock zip from [this](http://googlemock.googlecode.com/files/gmock-1.7.0.zip) link manually and place it in `shogun/third_party/GoogleMock`. Then call `make -j GoogleMock` again to extract the zip and place the appropriate Google Mock files in `build`.

**Comment by karlnapf** [comment]
Before I put that stuff in, can't you edit the wiki on your machine and then send a PR with that?

**Comment by karlnapf** [comment]
Argh, apparently not.

if you can copy the file locally, edit, and then send me an email with it, I can review and merge your changes

**Comment by yorkerlin** [comment]
Gist?

**Comment by karlnapf** [comment]
Gist is also fine

**Comment by sanuj** [comment]
[Here](https://gist.github.com/sanuj/e41d074cee97cb87e23e) is the gist.
@karlnapf You can clone it via the following link on your machine.
https://gist.github.com/e41d074cee97cb87e23e.git

**Comment by karlnapf** [comment]
Great, thanks a lot @sanuj 

One request. Could you respect the 80 character margin? As was done in the file before? This makes reading in text editors easier.....

**Comment by sanuj** [comment]
@karlnapf I have updated the gist as you suggested.

**Comment by karlnapf** [comment]
Thanks @sanuj I merged it. See [here](https://github.com/shogun-toolbox/shogun/wiki/README_developer)
