### ISSUE TITLE
Issue audit

### ISSUE THREAD

**Issue by erip** [shogun-toolbox/shogun#2965]
Many issues I see that have been raised seem to have no tags or no recent updates. Asking for an update or recommending closure when searching for work is cumbersome.

I think issues should be audited and tagged so contributors can jump into a specific tag instead of weeding through all of the issues. This has the advantage of closing many out-of-date issues and making shogun contributors look really efficient, vigilant, and hard-working. :smile:

**Comment by karlnapf** [comment]
Haha....yes definitely.
We all do this every now and then. It is hard to keep such things up over a long time.
Generally, I am all up for closing issues that are "old".
What do you suggest to make us look really efficient?

**Comment by erip** [comment]
@karlnapf It's unclear at the moment. I can brainstorm and give some ideas later. Once issues start closing (I imagine there are many), it'll probably become a more maintainable goal. Seeing 300+ open issues at a given time is overwhelming to everyone: owners and contributors alike.

**Comment by karlnapf** [comment]
I think it is better to document all thoughts, problems, bugs etc than to ignore them.
At least new people can choose from a large set.
The art is to group the issues we want to solve for a next release. In fact, we did this in the past. Feel free to suggest things here....

**Comment by erip** [comment]
Right. The goals is to only close issues *that aren't issues anymore*. [This](https://github.com/shogun-toolbox/shogun/issues/2431#event-505466368) is an example of such an issue. If tags were added and issues were tracked regularly (monthly? quarterly?), only **relevant** issues would still be open.
