### ISSUE TITLE
How to build octave modular examples

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#2975]
I am building shogun octave modular on Ubuntu with the option 

  -DGENERATE_EXAMPLES=ON

The first time CMake produced these errors
```
/home/bee/shogun/examples/example-generation/types/get_type_list.sh: 1: /home/bee/shogun/examples/example-generation/types/get_type_list.sh: Bad substitution
grep: /home/bee/shogun/build/../../../src/interfaces/modular/: No such file or directory
```
So I edited get_type_listl.sh to change
```
MODULAR_DIR=$PATH_TO_SELF/../../../src/interfaces/modular/
```
to
```
MODULAR_DIR=$PATH_TO_SELF/../src/interfaces/modular/
```
This time there is no "No such file or directory" error but still the "Bad substitution" persisted, but it did produce a list of examples from typelist. 

Build went through successfully and these examples werr installed in /usr/local/share/shogun/examples But I am missing those .m files in shogun/examples/undocumented/octave_modular
In Fedora's octave-shogun package these are included in their standard install. I am wondering why mine doesn't have them. Not sure if "Bad substitution" has anything to with that.

How do I include these examples in the build process, or do I just symlink them to /usr/local/share/shogun?

Thanks.

**Comment by besser82** [comment]
Hey!

In Fedora's rpm-build, I simply `cp -pr` them into their destination directory after `make install` and pick them up into the package in `%files`.  That's all; no special magic.  This possibly might be an issue with CMake, too;  I'll dig into the build-scripts and try to figure that out…

Cheers

**Comment by karlnapf** [comment]
This script is deleted now, so closing
