### ISSUE TITLE
Proper way to build octave modular interface

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#2976]
Hi,

I  am able to build the octave modular interface for octave 4.0 successfully but only after rebuilding octave with this patch (comment 12 in http://savannah.gnu.org/bugs/?41027)  Same issue since octave 3.8 , see https://github.com/shogun-toolbox/shogun/issues/1995

If just build octave normally or install from distro's repo (Ubuntu 15.10) then shogun doesn't build. What should be the proper way, or is there any fix besides using the patch?  I assume most users would not know about the patch (Fedora 23 packages octave-shogun, I am not sure how they build it if not patching octave)

Thanks.

**Comment by besser82** [comment]
Hello @beew!
We have a patched octave in the Fedora repos…  The bugreport is from the maintainer of Fedora's ocatave-package…

**Comment by beew** [comment]
Hi,

Thanks for the reply. Maybe someone should update the Wiki with a link to the patch so that users will not waste their time unnecessarily?
