### ISSUE TITLE
Adding RNNs, HFO and LSTMs to neural nets

### ISSUE THREAD

**Issue by arasuarun** [shogun-toolbox/shogun#2977]
*Recurrent Neural Networks* and *Long Short Term Memory* would be great additions to the neural nets package. 
They are usually used with the *Hessian Free Optimisation* training algorithm. HFO can also be used with CNNs, I believe. 

I'd like to start building those if I get the green signal. Thanks.

**Comment by lisitsyn** [comment]
@arasuarun this is indeed good. Although lets get really careful with design, RNNs are a bit more tricky. We could need some real redesign to support that, I don't know yet

**Comment by arasuarun** [comment]
@lisitsyn How about we start with HFO? It involves mostly linear algebra: conjugate gradient, R-operator. **hfo** could probably be a separate module in /optimization like **lbfgs**. A corresponding train_hfo method could be added to NeuralNetwork as well. 

I'll start a separate issue for this if you want. Else, we can just continue on this one. Thanks.

**Comment by arasuarun** [comment]
@lisitsyn?

**Comment by lisitsyn** [comment]
@arasuarun yes sure. Sorry for late answer

**Comment by arasuarun** [comment]
@lisitsyn Really sorry for the super late response. I had mid semester exams and submissions for like, 2 weeks.

1. Where directory should the R Operator (used in computing H*v http://www.bcl.hamilton.ie/~barak/papers/nc-hessian.pdf) be put? 

2. This entire HFO business is huge: should we start with a generic class for 2nd order minimizers first? A Conjugate Gradient minimizer method, maybe?
