### ISSUE TITLE
Fix KNN doxygen documentation

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2996]
The Latex contains bugs and looks ugly.

http://www.shogun-toolbox.org/doc/en/latest/classshogun_1_1CKNN.html

**Comment by bollu** [comment]
I'd like to pick this issue up. Tagging on this so I can find it later :)

**Comment by theaverageguy** [comment]
This can be closed @karlnapf ! :)

**Comment by karlnapf** [comment]
Thanks! :)
