### ISSUE TITLE
shogun project with CLion

### ISSUE THREAD

**Issue by ghost** [shogun-toolbox/shogun#2998]
Hi everyone

I'm having troubles compiling shogun project from CLion 1.2.1 on Linux Mint 17.1 x86_64. 
Despite the following line in top CMakeLists.txt the include of `'${CMAKE_SOURCE_DIR}/src` directory isn't working:
`INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/src`
`${CMAKE_SOURCE_DIR}/src/shogun`
`${CMAKE_BINARY_DIR}/src`
`${CMAKE_BINARY_DIR}/src/shogun)` <br>

Which results in all `<shogun/...>` includes being invisible to CLion and build failing with multiple errors like: 
`path_to_project/shogun_fork/src/shogun/base/Version.cpp:22:43: error: unable to find numeric literal operator ‘operator"" x’
 const int32_t Version::version_revision = VERSION_REVISION;`<br>
The same project builds ok if I just do `cmake ${PATH_TO_CMAKELISTS.TXT} && make` from the console in any directory.
In both cases I use cmake 3.2.2. <br>

Does anyone know how to fix this?

**Comment by karlnapf** [comment]
Can you build Shogun on your system without CLion?

**Comment by nginn** [comment]
@karlnapf yes, I can using the same cmake 3.2.2
