### ISSUE TITLE
Importing some models fails if Eigen3 is not present

### ISSUE THREAD

**Issue by youssef-emad** [shogun-toolbox/shogun#3013]
I get name `'LDA' is not defined` when I installed Shogun without Eigen3 and the same for QDA and MCLDA.
So I think it should be made clear at Wiki that Eigen3 is required to use these models or may be Eigen3 can be a required library if there is many models depending on it.

**Comment by youssef-emad** [comment]
@karlnapf should I update the Wiki or should I change the build to make Eigen3 a required library ?

**Comment by karlnapf** [comment]
I think we can make eigen3 a requirement. If not present, we can bundle it easily. We had many discussions about this before and converged onto this without ever doing it.

A patch would remove all of the ```#ifdef HAVE_EIGEN3``` statements (and more, grep for eigen3) , and modify the cmake build to use eigen3 by default. If not available, it should either give an error message asking to bundle it, or turn bundling on straight away.

If you send a pr to start this, we can discuss in there. This would be a great contribution!

@lisitsyn @vigsterkr @besser82 will have comments.

**Comment by karlnapf** [comment]
Done in https://github.com/shogun-toolbox/shogun/tree/feature/eigen3_bundling which will be merged soon
