### ISSUE TITLE
Compare outputs of meta-examples to assure cross-language results identity

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#3015]
From the discussion with @karlnapf:

We could have a mode for meta-examples generation that collects all the outputs across different languages and then checks whether they are identical.

**Comment by karlnapf** [comment]
Purpose: Ensure that numerical results do not change if not covered by unit tests

Improvement over old integration tests:
 * Less false positives as we only test numerical values, and not the full serialized instances
 * We do integration testing across *all* target languages


Note: Meta example listings ```.sg``` files do not have to be touched for this. So this feature does not block starting us to use the new system

How it works  (```generator.py``` is the Python script that generates the target language listings from meta examples)
1.  ```generator.py``` gets an additional option to enable such testing
2.  ```generator.py``` simply collects all created vector and matrix variables
3.  In the translated examples, at the end of script, each variable is passed to a Shogun class
4. The Shogun class stores all variables into a file
5. We collect a collection of "reference results" in our data repository (just like the old integration test results)
6. In our test build, we compare the results in a Python script

**Comment by karlnapf** [comment]
This is now in develop branch
