### ISSUE TITLE
Separate CGaussianKernel from its compact version

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3020]
Separation of concerns: [CGaussianKernel](http://shogun.ml/CGaussianKernel) offers a compact option which slightly changes kernel computations. This should go to its own (sub) class.

This entrance task is to perform this simple re-factoring exercise (and change all places where the compact kernel is used in Shogun accordingly)

**Comment by tonmoy-saikia** [comment]
@karlnapf I am applying for gsoc this year and I found shogun really interesting! Couldn't wait to get my hands dirty. I would be interested in contributing more. Specifically, I am interested in contributing to deep neural network modules. It would be great, if you could throw some pointers!

**Comment by karlnapf** [comment]
Thats the spirit :) Great way to introduce yourself with a patch! Thanks -- lets get it merged!
