### ISSUE TITLE
Installation problem: R with OSX El Capitan

### ISSUE THREAD

**Issue by ellesec** [shogun-toolbox/shogun#3022]
Hi,

I am new to the Shogun toolbox and  have been having problems trying to install the toolbox with the R interface. The installation fails using both macports (Error: Processing of port shogun failed), and also when installing from source. I'm running OSX El Capitan 10.11.3. The new restriction in El Capitan that means that only Apple can install software under /usr has moved the location of R and caused issues with other applications that I use with R. Has the Shogun toolbox been updated to account for these changes?

Ellese

**Comment by vigsterkr** [comment]
@ellesec can you tell us more about which version from the source, and which version of R and where is it located on your system?

**Comment by ellesec** [comment]
I'm trying to install shogun 4.1.0, and using R version 3.2.3 located at /opt/local/bin/R

**Comment by besser82** [comment]
@ellesec:  Can you please try to add `-DR_EXECUTABLE=/opt/local/bin/R` to the CMake-command and see, if it works?

**Comment by ellesec** [comment]
If I run the cmake command with -DRModular=ON and -DR_EXECUTABLE=/opt/local/bin/R, I get the following error during make.

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vDSP.h:9871:41: error: 
      redefinition of 'COMPLEX' as different kind of symbol
typedef DSPComplex      COMPLEX;
                                        ^
/opt/local/Library/Frameworks/R.framework/Resources/include/Rinternals.h:551:12: note: 
      previous definition is here
Rcomplex *(COMPLEX)(SEXP x);
                    ^
1 error generated.
make[2]: *** [src/interfaces/r_modular/CMakeFiles/r_modular.dir/modshogunR_wrap.cxx.o] Error 1
make[1]: *** [src/interfaces/r_modular/CMakeFiles/r_modular.dir/all] Error 2
make: *** [all] Error 2
