### ISSUE TITLE
OSX Segmentation fault: 11

### ISSUE THREAD

**Issue by Vikisix** [shogun-toolbox/shogun#3029]
Hi all!

I have just lost one day trying to solve this problem but I really do not know how to solve it. I want to run shogun on my laptop (OSX 10.11.3). I have installed shogun with macports and I have updated all the libraries with brew (as example I hade libcurl 7.0 so I have updated to 9.0 as requested with brew).

After this odissea , I try to run "import modshogun" in my python console, but I got:

Segmentation fault: 11

Any idea on how to solve this problem?

Any help is really appreciated! 

Thank you for your time :)

**Comment by vigsterkr** [comment]
macports based shogun is pretty outdated :(
try to use either brew or from src

**Comment by Vikisix** [comment]
I have cleaned the previous installation of macports and I tried to install shogun with brew.
The installation went all (apparently), however when I tried to import modshogun in python console It said:
 _modshogun.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
So I have updated it using the suggestions in the following thread:
https://github.com/Homebrew/homebrew-php/issues/2446
Then I tried it again and I have received Segmentation fault: 11
Do you suggest to try to install from src? Or do you think the problem is something else?

**Comment by abhinavmoudgil95** [comment]
Any updates on this? I am also facing the same issue. Following are my environment variables: 

```
Abhinavs-MBP:shogun abhinavmoudgil95$ echo $PYTHONPATH
/usr/local/lib/python2.7/site-packages/
Abhinavs-MBP:shogun abhinavmoudgil95$ echo $DYLD_LIBRARY_PATH

Abhinavs-MBP:shogun abhinavmoudgil95$ 
```
If I change my `DYLD_LIBRARY_PATH` to `/usr/local/lib` as suggested on [INSTALL ](https://github.com/shogun-toolbox/shogun/wiki/INSTALL)wiki page, I get the following error: 

```
Abhinavs-MBP:shogun abhinavmoudgil95$ export DYLD_LIBRARY_PATH=/usr/local/lib
Abhinavs-MBP:shogun abhinavmoudgil95$ python
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import modshogun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/modshogun.py", line 30, in <module>
    _modshogun = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/modshogun.py", line 26, in swig_import_helper
    _mod = imp.load_module('_modshogun', fp, pathname, description)
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_modshogun.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
>>> 
```

**Comment by karlnapf** [comment]
This is why we need [this GSoC project](https://github.com/shogun-toolbox/shogun/wiki/GSoC_2015_project_installation)!
Sorry I am of no help here, but maybe @lisitsyn has an idea?

**Comment by abhinavmoudgil95** [comment]
Yes! This is the major issue I face in Open Source orgs. Most of them are updated for Linux but not for OS X.

**Comment by vigsterkr** [comment]
@abhinavmoudgil95 i'm not so sure how you've managed to get this error, as i really dont get how you've managed to get modshogun depend on libJPEG. could you share your cmake command?

FYI i'm using shogun on OSX without any problems.

**Comment by abhinavmoudgil95** [comment]
Oh! Thanks for informing. I wasn't aware that modshogun doesn't depend on libJPEG. I guess there must be some wrong symlink created between libraries. I'll see and get back. 

Following is the cmake command I used: 
`cmake -DPythonModular=ON ..`

**Comment by vigsterkr** [comment]
symlink between libraries? what exactly do you mean by that?

**Comment by abhinavmoudgil95** [comment]
Symbolic links between files. See [here](https://en.wikipedia.org/wiki/Symbolic_link) for more details.

**Comment by vigsterkr** [comment]
symbolic links between files? a symbolic link to a file, maybe...
but i have a hard time to understand how that would that be the root cause of getting linking errors for your library

**Comment by abhinavmoudgil95** [comment]
Symlinks may not be created while building modshogun. 

In my case, there may be symbolic links to files present in `/usr/local/lib` from linkpath `path/to/anaconda/pkgs/jpeg-8d-1/lib/` (where libJPEG is present). Can this be a cause?

**Comment by vigsterkr** [comment]
still dont understand how did modshogun got the linking dependency for libJPEG.

**Comment by abhinavmoudgil95** [comment]
shogun libraries are present in `/usr/local/lib/ `as `libshogun.17.2.dylib` etc. and all files present in `/usr/local/lib/ ` may be linking from linkpath `path/to/anaconda/pkgs/jpeg-8d-1/lib/`

**Comment by vigsterkr** [comment]
but man do you understand what does it mean to have a linking dependency to libJPEG? and how did you manage to do that?

**Comment by abhinavmoudgil95** [comment]
Doing something like this `ln -s /usr/local/lib/* path/to/anaconda/pkgs/jpeg-8d-1/lib/somelink/ ` can cause such error? Yes, agreed that it makes no sense for modshogun to link to libJPEG. It may be created by mistake while building some other tool. Sorry I don't remember exactly.

**Comment by vigsterkr** [comment]
no it has nothing do with that. i suggest you to read more about shared libraries and linking libraries because the things you've mentioned here makes no sense at al.

**Comment by abhinavmoudgil95** [comment]
I'll take your word.

**Comment by Vikisix** [comment]
After some other working.. I remove all the previous installation and I followed the following instructions https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART.

However when I run the examples... I still get Segmentation fault: 11... do you have any idea of what is the problem?
