### ISSUE TITLE
Installation problem : Arch 4.4.3-1

### ISSUE THREAD

**Issue by aelnouby** [shogun-toolbox/shogun#3036]
I have 

> Linux kernel: 4.4.3-1-ARCH
SWIG Version 3.0.8
python 3.5
gcc 5.3.0-5

I used ccmake with pythonModular=ON

After running make i get this 

>   1%] Built target class_list
[  1%] Built target ShogunVersionProtobuf
[  1%] Generating version header
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[  1%] Built target version
[  1%] Built target HeadersProtobuf
[  1%] Built target ChunksProtobuf
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o
src/shogun/CMakeFiles/libshogun.dir/build.make:965: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o' failed
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o] Error 1
CMakeFiles/Makefile2:315: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aelnouby** [comment]
@besser82 May you help me with this please ?

**Comment by besser82** [comment]
Sure ^^

Smells like a br0k3n git clone…  Please try to do a clean checkout and build inside it…

**Comment by aelnouby** [comment]
I cloned a new fresh version and tried the process again i got this 

> Scanning dependencies of target version
[  1%] Generating version header
[  1%] Built target version
Scanning dependencies of target HeadersProtobuf
[  1%] Running C++ protocol buffer compiler on Headers.proto
[  1%] Built target HeadersProtobuf
Scanning dependencies of target ChunksProtobuf
[  1%] Running C++ protocol buffer compiler on Chunks.proto
[  1%] Built target ChunksProtobuf
Scanning dependencies of target class_list
[  1%] Running C++ protocol buffer compiler on ShogunVersion.proto
[  1%] Generating /home/alaaelnouby/Desktop/shogun/src/shogun/base/class_list.cpp
[  1%] Built target class_list
Scanning dependencies of target ShogunVersionProtobuf
[  1%] Built target ShogunVersionProtobuf
Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o
src/shogun/CMakeFiles/libshogun.dir/build.make:965: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o' failed
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/transfer/multitask/MultitaskL12LogisticRegression.cpp.o] Error 1
CMakeFiles/Makefile2:315: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I created the build directory inside the source `shogun/build`

**Comment by karlnapf** [comment]
Can you please not paste logs directly in the chat? Nobody will look at this if you do. Post a gist.
Also, check your filesystem

**Comment by aelnouby** [comment]
This might sound silly, but by chance i used a different console than the one i have been using and surprisingly the installation was completed successfully, i am not sure what was wrong.

Thanks for you help.
