### ISSUE TITLE
eigen3/linalg for LinearRidgeRegression

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3060]
Get rid of the lapack calls in the above class

**Comment by youssef-emad** [comment]
I checked [LinearRidgeRegression.cpp](http://shogun-toolbox.org/doc/en/latest/LinearRidgeRegression_8cpp_source.html) but I can't see any lapack calls.
I also removed the `#ifdef HAVE_LAPACK` and `#include <shogun/mathematics/lapack.h>` lines from [LinearRidgeRegression.cpp](http://shogun-toolbox.org/doc/en/latest/LinearRidgeRegression_8cpp_source.html) and [LinearRidgeRegression.h](http://shogun-toolbox.org/doc/en/latest/LinearRidgeRegression_8h_source.html) and no compilation errors occured.

**Comment by karlnapf** [comment]
you are right, that got changed when we made it use eigen3

**Comment by karlnapf** [comment]
If you are keen, you could try to add the LLT (cholesky factorization based linear solves) to linalg, and then make the ridge regression use that

**Comment by karlnapf** [comment]
or just remove the lapack guard

**Comment by youssef-emad** [comment]
yeah sure , I'll try linalg

**Comment by karlnapf** [comment]
this is a non-trivial task though, requires some understanding of linalg. Only do if you are interested. But this is also useful for most GSOC projects .)

**Comment by youssef-emad** [comment]
mmmm :smiley: 
I'll try to understand linalg and write what I think should be done and you can correct me if I am wrong.
