### ISSUE TITLE
Improve Ridge Regression

### ISSUE THREAD

**Issue by ali-mohamed** [shogun-toolbox/shogun#3106]
I have made a ([PR](https://github.com/zoq/benchmarks/pull/8)) for benchmark shogun Linear Ridge Regression vs scikit Ridge Regression. The accuracy of shogun is very impressive. Compared to scikit they are almost same. Though, the timing has an issue with bigger datasets.
```
                            scikit       |    shogun 
isolet           |     0.254335   |  0.269475 
webpage     |     0.317556   |        -
```

1. I have run the webpage dataset for shogun and it takes > 20 minutes and still not finished. Thisdataset is > 23000 examples with more than 300 features. Note: I tried the closed form solution for Ridge in scikit and it still can output results in the same time.

2. I can't see any documentation for this, but I think labels for applying binary solver in Linear Ridge should be noted somewhere that it must  be either -1 (negative class) or 1 (positive class). Also, I think it will be good if we can get any binary classes (e.g. (0,1)) and change it in the underlying method.

**Comment by karlnapf** [comment]
As said, binary labels do not make any sense here.

Ridge regression should be lightning fast on these examples, unless you do something wrong. Note that Shogun takes features in column format, which is transposed compared to what sklearn takes as input

**Comment by ali-mohamed** [comment]
Fixed the binary labels.

It is doing great on most datasets. It does great in high dimensional dataset (> 600 features). But this webpage dataset not. I don't have a reason yet but may be it is a benchmark concern as you said. I will investigate this further more and tell you.

For the transpose, I am pretty sure that I do that. Can be viewed here  https://github.com/zoq/benchmarks/pull/8/commits/ff002b18edc6e3d4a6ff8a9447eec603e1e198d4?diff=unified#diff-059ca9cadf3c9954d5962615542a0a3bR77

**Comment by ali-mohamed** [comment]
I have run each measurement (`timing`, `metrics`)separately and get every thing smooth. So it has something to be done with the benchmark itself.

Here are the results:
timing:

              scikit    shogun 
abalone7    0.002160  0.000874 
abalone19   0.001967  0.000847 
isolet      0.255482  0.221381 
webpage     0.292860  0.248900 

metrics:
Metric Measurement: 'Simple MSE'
                  scikit                    shogun
abalone7    1.2830459770114941         0.92446047621362648
abalone19   1.0172413793103448         0.98387491908768498
isolet      0.97999230473258947        0.93389952952779398
webpage     0.012766324506167515       0.011316018126342186

**Comment by karlnapf** [comment]
These results seem very nice, dont they?

**Comment by karlnapf** [comment]
Make sure to include a link to this in your proposal

**Comment by karlnapf** [comment]
Can we improve this

**Comment by ali-mohamed** [comment]
I think so. I can add more datasets in the benchmark to make sure.

So what is the next step here? I see we still don't have gradient decent for large scale datasets.

**Comment by karlnapf** [comment]
Next step is to merge the benchmark into the benchmark repo, and yes, a larger dataset would be a good idea. See [this paper](http://arxiv.org/pdf/1507.04717v6.pdf) for some ideas
