### ISSUE TITLE
Fix broken LDA unit test

### ISSUE THREAD

**Issue by OXPHOS** [shogun-toolbox/shogun#3107]
LDAtest will be enabled once HAVE_EIGEN3 flag is removed from LDA_unittest.cc
And running LDAtest will lead to the failure of the test. 

> 260/379 Test #256: unit-LDATest .......................................................***Failed    0.04 sec
> Note: Google Test filter = LDATest.*
> [==========] Running 4 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 4 tests from LDATest
> [ RUN      ] LDATest.CheckEigenvectors_FLD
> [       OK ] LDATest.CheckEigenvectors_FLD (1 ms)
> [ RUN      ] LDATest.CheckProjection_FLD
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:141: Failure
> The difference between -304.80621346 and projection_FLD[0] is 6.4366247722805383, which exceeds epsilon, where
> -304.80621346 evaluates to -304.80621345999998,
> projection_FLD[0] evaluates to -311.24283823228052, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:142: Failure
> The difference between -281.12285949 and projection_FLD[1] is 6.4366247711261053, which exceeds epsilon, where
> -281.12285949 evaluates to -281.12285949,
> projection_FLD[1] evaluates to -287.5594842611261, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:143: Failure
> The difference between -228.60266985 and projection_FLD[2] is 6.4366247721223147, which exceeds epsilon, where
> -228.60266985 evaluates to -228.60266985000001,
> projection_FLD[2] evaluates to -235.03929462212233, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:144: Failure
> The difference between -300.38571766 and projection_FLD[3] is 6.4366247723569927, which exceeds epsilon, where
> -300.38571766 evaluates to -300.38571766000001,
> projection_FLD[3] evaluates to -306.822342432357, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:145: Failure
> The difference between -258.89964153 and projection_FLD[4] is 6.4366247778518186, which exceeds epsilon, where
> -258.89964153 evaluates to -258.89964153,
> projection_FLD[4] evaluates to -265.33626630785182, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:146: Failure
> The difference between +285.84589701 and projection_FLD[5] is 6.4366247662237015, which exceeds epsilon, where
> +285.84589701 evaluates to 285.84589700999999,
> projection_FLD[5] evaluates to 279.40927224377629, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:147: Failure
> The difference between +274.45608852 and projection_FLD[6] is 6.4366247679361095, which exceeds epsilon, where
> +274.45608852 evaluates to 274.45608851999998,
> projection_FLD[6] evaluates to 268.01946375206387, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:148: Failure
> The difference between +251.15879527 and projection_FLD[7] is 6.4366247659850444, which exceeds epsilon, where
> +251.15879527 evaluates to 251.15879527000001,
> projection_FLD[7] evaluates to 244.72217050401497, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:149: Failure
> The difference between +271.14418463 and projection_FLD[8] is 6.4366247619759065, which exceeds epsilon, where
> +271.14418463 evaluates to 271.14418462999998,
> projection_FLD[8] evaluates to 264.70755986802408, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:150: Failure
> The difference between +291.21213655 and projection_FLD[9] is 6.4366247655551092, which exceeds epsilon, where
> +291.21213655 evaluates to 291.21213655000003,
> projection_FLD[9] evaluates to 284.77551178444492, and
> epsilon evaluates to 1e-08.
> [  FAILED  ] LDATest.CheckProjection_FLD (1 ms)
> [ RUN      ] LDATest.CheckEigenvectors_SVD
> [       OK ] LDATest.CheckEigenvectors_SVD (0 ms)
> [ RUN      ] LDATest.CheckProjection_SVD
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:168: Failure
> The difference between -8.09643097 and projection_SVD[0] is 1.2916039009313591, which exceeds epsilon, where
> -8.09643097 evaluates to -8.0964309700000001,
> projection_SVD[0] evaluates to -6.804827069068641, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:169: Failure
> The difference between -6.95885362 and projection_SVD[1] is 1.2916039093440412, which exceeds epsilon, where
> -6.95885362 evaluates to -6.9588536200000002,
> projection_SVD[1] evaluates to -5.6672497106559589, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:170: Failure
> The difference between -5.76169114 and projection_SVD[2] is 1.2916039021433363, which exceeds epsilon, where
> -5.76169114 evaluates to -5.7616911399999999,
> projection_SVD[2] evaluates to -4.4700872378566636, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:171: Failure
> The difference between -7.45158326 and projection_SVD[3] is 1.2916039068824361, which exceeds epsilon, where
> -7.45158326 evaluates to -7.4515832599999996,
> projection_SVD[3] evaluates to -6.1599793531175635, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:172: Failure
> The difference between -6.67021673 and projection_SVD[4] is 1.2916039048190635, which exceeds epsilon, where
> -6.67021673 evaluates to -6.6702167299999999,
> projection_SVD[4] evaluates to -5.3786128251809364, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:173: Failure
> The difference between +6.85547411 and projection_SVD[5] is 1.291603916450458, which exceeds epsilon, where
> +6.85547411 evaluates to 6.8554741100000003,
> projection_SVD[5] evaluates to 8.1470780264504583, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:174: Failure
> The difference between +6.40276367 and projection_SVD[6] is 1.2916039170611544, which exceeds epsilon, where
> +6.40276367 evaluates to 6.4027636699999997,
> projection_SVD[6] evaluates to 7.6943675870611541, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:175: Failure
> The difference between +6.81301359 and projection_SVD[7] is 1.291603914531712, which exceeds epsilon, where
> +6.81301359 evaluates to 6.8130135899999997,
> projection_SVD[7] evaluates to 8.1046175045317117, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:176: Failure
> The difference between +6.90668279 and projection_SVD[8] is 1.2916039162422273, which exceeds epsilon, where
> +6.90668279 evaluates to 6.9066827899999996,
> projection_SVD[8] evaluates to 8.1982867062422269, and
> epsilon evaluates to 1e-08.
> /opt/shogun/tests/unit/classifier/LDA_unittest.cc:177: Failure
> The difference between +7.96084156 and projection_SVD[9] is 1.2916039137944484, which exceeds epsilon, where
> +7.96084156 evaluates to 7.9608415600000004,
> projection_SVD[9] evaluates to 9.2524454737944488, and
> epsilon evaluates to 1e-08.
> [  FAILED  ] LDATest.CheckProjection_SVD (1 ms)

**Comment by karlnapf** [comment]
In that case, send a patch to [disable](https://github.com/google/googletest/blob/master/googletest/docs/V1_7_AdvancedGuide.md#temporarily-disabling-tests) the test. You can do that via prefixing `DISABLED_LDATest`

This is now an entrance task to fix the disabled LDA unit test
