### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by BrendenWashington** [shogun-toolbox/shogun#3110]
hi,

I am new to shogun

I try to install the shogun into my computer with ubuntu 14.04

but after I compiling the shogun as instructed on: like this:

mkdir build & cd build
cmake -DPythonStatic=ON
make
make install

after I doing this , why is  the folder /shogun_root/build/examples only have the undocumented folder?

it is not like what the wiki said?

and where can I get those examples to learn how to use shogun?

thank you!

**Comment by karlnapf** [comment]
The `examples/undocumented/python_modular` folder has the most complete set of examples. `examples/undocumented/libshogun` also has a few from c++.

What does the wiki say where?

**Comment by BrendenWashington** [comment]
thank you for quick respond

but I get nothing at the folder   shogun-root/build/examples/undocumented/python_modular

and yes, I do have some excutable file under  libshogun folder ,  but how can I call these func in python?

**Comment by karlnapf** [comment]
the python examples are not in the build folder, but in shogun's root itself
