### ISSUE TITLE
help on install shogun

### ISSUE THREAD

**Issue by BrendenWashington** [shogun-toolbox/shogun#3111]
hi 

can anybody help to install shogun into ubuntu 14.04?

there is no configure file, and cmake seem to work

but I still couldn't find the python interface after the compilation, 

so can anybody give me some clear instruction?

**Comment by youssef-emad** [comment]
If `make` and `sudo make install` completed successfully , maybe it's the environmental variables.
Have you tried this ?
```
export LD_LIBRARY_PATH=SHOGUN_INSTALL_DIR/lib
export PYTHONPATH=SHOGUN_INSTALL_DIR/lib/pythonX.Y/dist-packages/
```

**Comment by yorkerlin** [comment]
@BrendenWashington 
Did you try `cmake -DCMAKE_BUILD_TYPE=release -DPythonModular=ON`?

**Comment by karlnapf** [comment]
See the QUICKSTART readme. And please read [how to submit gihub issues](https://github.com/btford/participating-in-open-source)

**Comment by BrendenWashington** [comment]
@yorkerlin 

thank u, I'll have a try
