### ISSUE TITLE
Problem in Shogun-4.1.0's "GETTED STARTTED" page

### ISSUE THREAD

**Issue by zpcxh95** [shogun-toolbox/shogun#3116]
Has anyone run this example from http://www.shogun-toolbox.org/doc/en/current/developer.html ?
The whole code as following:
```
#include <shogun/labels/Labels.h>
#include <shogun/features/DenseFeatures.h>
#include <shogun/kernel/GaussianKernel.h>
#include <shogun/classifier/svm/LibSVM.h>
#include <shogun/base/init.h>
#include <shogun/lib/common.h>
#include <shogun/io/SGIO.h>
using namespace shogun;
void print_message(FILE* target, const char* str)
{
    fprintf(target, "%s", str);
}

void print_warning(FILE* target, const char* str)
{
    fprintf(target, "%s", str);
}

void print_error(FILE* target, const char* str)
{
    fprintf(target, "%s", str);
}

int main(int argc, char** argv)
{
  init_shogun(&print_message, &print_warning,
                    &print_error);
    // create some data
    SGMatrix<float64_t> matrix(2,3);
    for (int32_t i=0; i<6; i++)
        matrix.matrix[i]=i;
    // create three 2-dimensional vectors
    // shogun will now own the matrix created
    CDenseFeatures<float64_t>* features= new CDenseFeatures<float64_t>();
    features->set_feature_matrix(matrix);

    // create three labels
    CBinaryLabels* labels=new CBinaryLabels(3);
    labels->set_label(0, -1);
    labels->set_label(1, +1);
    labels->set_label(2, -1);

    // create gaussian kernel with cache 10MB, width 0.5
    CGaussianKernel* kernel = new CGaussianKernel(10, 0.5);
    kernel->init(features, features);

    // create libsvm with C=10 and train
    CLibSVM* svm = new CLibSVM(10, kernel, labels);
    svm->train();


    // classify on training examples
    for (int32_t i=0; i<3; i++)
        SG_SPRINT("output[%d]=%f\n", i, svm->apply_one(i));
    // free up memory
    SG_UNREF(svm);

    exit_shogun();
    return 0;

}
```
I run this file but return error: 

> [ERROR] In file /build/buildd/shogun-3.1.1/src/shogun/shogun/machine/KernelMachine.cpp line 483 : CKernelMachine::train_locked() call data_lock() before!
> terminate called after throwing an instance of 'shogun:: ShogunException'
> Aborted (core dumped)

I am just start to learn Shogun, I don't understand every line of code, but I confirm that I do every step as the "INSTALL" page and "GETTED STARTTED" page do and it return error..

**Comment by Saurabh7** [comment]
The code snippet you provided does not compile.
`![Uploading Screenshot .png…]()`
After removing that and an import it works fine for with `g++ -g -O3 -std=c++11 test.cpp -lshogun`.

Can you provide exact code you use and compiler flags ?

**Comment by zpcxh95** [comment]
@Saurabh7  you are right, I add some extra symbol when edit my code with Markdown, now I clear it.
but It still return error even if I compile it as what you tell me, this is build log in code::blocks:
```
-------------- Build: Debug in another (compiler: GNU GCC Compiler)---------------

g++ -O3 -std=c++11 -Wall -g  -c /home/burningbear/CodePlace/another/main.cpp -o obj/Debug/main.o
g++  -o bin/Debug/another obj/Debug/main.o  -lshogun  ../../Downloads/shogun-4.1.0/build/src/shogun/libshogun.so
Output file is bin/Debug/another with size 59.43 KB
Process terminated with status 0 (0 minute(s), 1 second(s))
0 error(s), 0 warning(s) (0 minute(s), 1 second(s))
 

-------------- Run: Debug in another (compiler: GNU GCC Compiler)---------------

Checking for existence: /home/burningbear/CodePlace/another/bin/Debug/another
Executing: xterm -T another -e /usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/burningbear/CodePlace/another/bin/Debug/another  (in /home/burningbear/CodePlace/another/.)
Process terminated with status 0 (0 minute(s), 11 second(s))

```
the file can be compiled normally, but XTerm still tell me ERROR

**Comment by Saurabh7** [comment]
Have you tried something simple like this ?
```
#include <shogun/base/init.h>

using namespace shogun;

int main(int argc, char** argv)
{
    init_shogun();
    exit_shogun();
    return 0;
}
```

**Comment by zpcxh95** [comment]
yes, XTerm dialog run and return nothing except "press any key to continue". it means the example run correctly, right?

**Comment by karlnapf** [comment]
@zpcxh95 Might I suggest you read up (Google is your friend) on how to communicate on github?

**Comment by zpcxh95** [comment]
@karlnapf Thanks for your advice, I am newcomer in Github, I have read some suggestions from Google. but my problem has not been solved yet, I will ask it in other place!

**Comment by zpcxh95** [comment]
I delete all of files related to "shogun" in my Ubuntu and install Shogun again, the problem solved. Thanks for your help!
