### ISSUE TITLE
Compilation error using newer Eigen library

### ISSUE THREAD

**Issue by arianepaola** [shogun-toolbox/shogun#3140]
The current shogun develop branch and also earlier versions (e.g. shogun_4.1.0) do not compile with newer Eigen library versions.

Below is the output of Ubuntu 16.04 LTS using libeigen3-dev (3.3~beta1-2)

<div>
<pre>
ubuntu@1604:~/shogun/build$ cmake -GNinja .. && ninja
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CCache: /usr/bin/ccache  
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": works
-- Checking C++11 support for "atomic"
-- Checking C++11 support for "atomic": works
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": works
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": works
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": works
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": works
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": works
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": works
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": works
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": works
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": works
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": works
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": works
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": works
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": works
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": works
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Using system's malloc
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for isinf
-- Looking for isinf - not found
-- Looking for isnan
-- Looking for isnan - not found
-- Looking for signgam
-- Looking for signgam - found
-- Looking for fdopen
-- Looking for fdopen - found
-- Looking for log2
-- Looking for log2 - found
-- Looking for powl
-- Looking for powl - found
-- Looking for lgammal
-- Looking for lgammal - found
-- Looking for sqrtl
-- Looking for sqrtl - found
-- Looking for finite
-- Looking for finite - found
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Performing Test HAVE_STD_ISINF
-- Performing Test HAVE_STD_ISINF - Success
-- Performing Test HAVE_STD_ISFINITE
-- Performing Test HAVE_STD_ISFINITE - Success
-- Performing Test HAVE_STD_ISNAN
-- Performing Test HAVE_STD_ISNAN - Success
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Found GDB: /usr/bin/gdb  
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Looking for clapack_dpotrf in /usr/lib/atlas-base/liblapack_atlas.so.3
-- Looking for clapack_dpotrf in /usr/lib/atlas-base/liblapack_atlas.so.3 - found
-- Found ATLAS: /usr/lib/atlas-base/liblapack_atlas.so.3;/usr/lib/atlas-base/libcblas.so.3;/usr/lib/atlas-base/libf77blas.so.3;/usr/lib/atlas-base/libatlas.so.3;/usr/lib/liblapack.so.3  
-- Found GLPK: /usr/lib/x86_64-linux-gnu/libglpk.so  
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Found Eigen3: /usr/include/eigen3 (found suitable version "3.2.92", minimum required is "3.1.2") 
-- Found OPENCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so  
-- Looking for viennacl::ocl::type_to_string<char>::apply
-- Looking for viennacl::ocl::type_to_string<char>::apply - found
-- Found ViennaCL: /usr/include (found suitable version "1.7.0", minimum required is "1.5.0") 
-- Checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Found NLOPT: /usr/lib/x86_64-linux-gnu/libnlopt.so  
-- Found LPSOLVE: /usr/lib/liblpsolve55.a  
-- Found ColPack: /usr/lib/x86_64-linux-gnu/libColPack.so  
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Found Doxygen: /usr/bin/doxygen (found suitable version "1.8.11", minimum required is "1.8.6") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Ctags flavour: Exuberant
-- Found Ctags: /usr/bin/ctags (found version "exuberant ctags 5.9~svn20110310") 
-- Failed to locate sphinx-build executable (missing:  SPHINX_EXECUTABLE) 
-- Checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3") 
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16") 
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.1.0") 
-- Found SNAPPY: /usr/lib/x86_64-linux-gnu/libsnappy.so  
-- Lzo Library /usr/lib/x86_64-linux-gnu/liblzo2.so
-- Lzo Include Found in /usr/include
-- Spinlock support found
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- ===================================================================================================================
-- Summary of Configuration Variables
-- 
-- The following OPTIONAL packages have been found:

 * CCache
 * GDB
 * OpenMP
 * BLAS
 * LAPACK
 * Atlas
 * GLPK
 * Eigen3 (required version >= 3.1.2)
 * ViennaCL (required version >= 1.5.0)
 * NLopt
 * LpSolve
 * ColPack
 * Doxygen (required version >= 1.8.6)
 * Ctags
 * LibXml2
 * HDF5
 * CURL
 * ZLIB
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * Spinlock
 * Threads

-- The following REQUIRED packages have been found:

 * OpenCL
 * PythonInterp
 * PLY

-- The following OPTIONAL packages have not been found:

 * Mosek
 * CPLEX
 * ARPACK
 * ARPREC
 * Sphinx
 * Protobuf

-- ===================================================================================================================
-- Enabled Integration
--   OpenCV Integration is OFF 	 - enable with -DOpenCV=ON
-- ===================================================================================================================
-- Enabled Interfaces
--   libshogun is ON
--   python modular is OFF 	 - enable with -DPythonModular=ON
--   octave modular is OFF 	 - enable with -DOctaveModular=ON
--   java modular is OFF 	 - enable with -DJavaModular=ON
--   perl modular is OFF 	 - enable with -DPerlModular=ON
--   ruby modular is OFF 	 - enable with -DRubyModular=ON
--   csharp modular is OFF 	 - enable with -DCSharpModular=ON
--   R modular is OFF 		 - enable with -DRModular=ON
--   lua modular is OFF 	 - enable with -DLuaModular=ON
-- 
-- Enabled legacy interfaces
--   cmdline static is OFF 	 - enable with -DCmdLineStatic=ON
--   python static is OFF 	 - enable with -DPythonStatic=ON
--   octave static is OFF 	 - enable with -DOctaveStatic=ON
--   matlab static is OFF 	 - enable with -DMatlabStatic=ON
--   R static is OFF 		 - enable with -DRStatic=ON
-- ===================================================================================================================
-- To compile shogun type
--   make
-- 
-- To install shogun to /usr/local type
--   make install
-- 
-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/shogun/build
[27/893] Building CXX object src/shogun/CMakeF...approx/logdet/opfunc/DenseMatrixExactLog.cpp.o
FAILED: /usr/bin/ccache /usr/bin/c++   -I../src -I../src/shogun -Isrc -Isrc/shogun -isystem /usr/include/eigen3 -I/usr/include/atlas -I/usr/include/libxml2 -I/usr/include/hdf5/serial -std=c++11 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated   -fopenmp   -O3 -fexpensive-optimizations -frerun-cse-after-loop -fcse-follow-jumps -finline-functions -fschedule-insns2 -fthread-jumps -fforce-addr -fstrength-reduce -funroll-loops -mfpmath=sse -fPIC -MMD -MT src/shogun/CMakeFiles/libshogun.dir/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp.o -MF src/shogun/CMakeFiles/libshogun.dir/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp.o.d -o src/shogun/CMakeFiles/libshogun.dir/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp.o -c ../src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp
In file included from /usr/include/eigen3/unsupported/Eigen/MatrixFunctions:59:0,
                 from ../src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp:15:
/usr/include/eigen3/unsupported/Eigen/src/MatrixFunctions/MatrixLogarithm.h: In instantiation of ‘void Eigen::MatrixLogarithmReturnValue<Derived>::evalTo(ResultType&) const [with ResultType = Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >; Derived = Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >]’:
/usr/include/eigen3/Eigen/src/Core/ReturnByValue.h:63:7:   required from ‘void Eigen::ReturnByValue<Derived>::evalTo(Dest&) const [with Dest = Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >; Derived = Eigen::MatrixLogarithmReturnValue<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> > >]’
/usr/include/eigen3/Eigen/src/Core/Assign.h:84:3:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::ReturnByValue<OtherDerived>&) [with OtherDerived = Eigen::MatrixLogarithmReturnValue<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> > >; Derived = Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >]’
../src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp:65:9:   required from here
/usr/include/eigen3/unsupported/Eigen/src/MatrixFunctions/MatrixLogarithm.h:340:54: error: ‘Options’ is not a member of ‘DerivedEvalTypeClean {aka Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >}’
     static const int Options = DerivedEvalTypeClean::Options;
                                                      ^
[27/893] Building CXX object src/shogun/CMakeF...n/job/RationalApproximationIndividualJob.cpp.o
ninja: build stopped: subcommand failed.
ubuntu@1604:~/shogun/build$
</pre>
</div>

**Comment by arianepaola** [comment]
This is also referenced in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809290
Debian Bug report logs - #809290
shogun: FTBFS: /MatrixLogarithm.h:340:54: error: 'Options' is not a member of 'DerivedEvalTypeClean'

**Comment by karlnapf** [comment]
Thanks for the report. BTW whenever you post error messages, please paste them in a gist and post the link to keep the thread short

**Comment by karlnapf** [comment]
@arianepaola same here, want to go and fix this for the release

**Comment by arianepaola** [comment]
@karlnapf yes

**Comment by vigsterkr** [comment]
this is actually a regression in Eigen 3.3+: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1229
