### ISSUE TITLE
Compilation error (static assertion failed) using Eigen 3.3 library

### ISSUE THREAD

**Issue by arianepaola** [shogun-toolbox/shogun#3141]
The current shogun develop branch does not compile due to a static assertion error, when using Eigen 3.3

Below is the output of Ubuntu 16.04 LTS using libeigen3-dev (3.3~beta1-2)

<pre>
ubuntu@1604:~/shogun/build$ cmake -GNinja .. && ninja
-- Using system's malloc
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Ctags flavour: Exuberant
-- Failed to locate sphinx-build executable (missing:  SPHINX_EXECUTABLE) 
-- Checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Lzo Library /usr/lib/x86_64-linux-gnu/liblzo2.so
-- Lzo Include Found in /usr/include
-- Spinlock support found
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- ===================================================================================================================
-- Summary of Configuration Variables
-- 
-- The following OPTIONAL packages have been found:

 * CCache
 * GDB
 * OpenMP
 * BLAS
 * LAPACK
 * Atlas
 * GLPK
 * Eigen3 (required version >= 3.1.2)
 * ViennaCL (required version >= 1.5.0)
 * NLopt
 * LpSolve
 * ColPack
 * Doxygen (required version >= 1.8.6)
 * Ctags
 * LibXml2
 * HDF5
 * CURL
 * ZLIB
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * Spinlock
 * Threads

-- The following REQUIRED packages have been found:

 * OpenCL
 * PythonInterp
 * PLY

-- The following OPTIONAL packages have not been found:

 * Mosek
 * CPLEX
 * ARPACK
 * ARPREC
 * Sphinx
 * Protobuf

-- ===================================================================================================================
-- Enabled Integration
--   OpenCV Integration is OFF 	 - enable with -DOpenCV=ON
-- ===================================================================================================================
-- Enabled Interfaces
--   libshogun is ON
--   python modular is OFF 	 - enable with -DPythonModular=ON
--   octave modular is OFF 	 - enable with -DOctaveModular=ON
--   java modular is OFF 	 - enable with -DJavaModular=ON
--   perl modular is OFF 	 - enable with -DPerlModular=ON
--   ruby modular is OFF 	 - enable with -DRubyModular=ON
--   csharp modular is OFF 	 - enable with -DCSharpModular=ON
--   R modular is OFF 		 - enable with -DRModular=ON
--   lua modular is OFF 	 - enable with -DLuaModular=ON
-- 
-- Enabled legacy interfaces
--   cmdline static is OFF 	 - enable with -DCmdLineStatic=ON
--   python static is OFF 	 - enable with -DPythonStatic=ON
--   octave static is OFF 	 - enable with -DOctaveStatic=ON
--   matlab static is OFF 	 - enable with -DMatlabStatic=ON
--   R static is OFF 		 - enable with -DRStatic=ON
-- ===================================================================================================================
-- To compile shogun type
--   make
-- 
-- To install shogun to /usr/local type
--   make install
-- 
-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/shogun/build
[515/868] Building CXX object src/shog...gun.dir/lib/tapkee/tapkee_shogun.cpp.o
FAILED: /usr/bin/ccache /usr/bin/c++   -I../src -I../src/shogun -Isrc -Isrc/shogun -isystem /usr/include/eigen3 -I/usr/include/atlas -I/usr/include/libxml2 -I/usr/include/hdf5/serial -std=c++11 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated   -fopenmp   -O3 -fexpensive-optimizations -frerun-cse-after-loop -fcse-follow-jumps -finline-functions -fschedule-insns2 -fthread-jumps -fforce-addr -fstrength-reduce -funroll-loops -mfpmath=sse -fPIC -MMD -MT src/shogun/CMakeFiles/libshogun.dir/lib/tapkee/tapkee_shogun.cpp.o -MF src/shogun/CMakeFiles/libshogun.dir/lib/tapkee/tapkee_shogun.cpp.o.d -o src/shogun/CMakeFiles/libshogun.dir/lib/tapkee/tapkee_shogun.cpp.o -c ../src/shogun/lib/tapkee/tapkee_shogun.cpp
In file included from /usr/include/eigen3/Eigen/Core:344:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /usr/include/eigen3/Eigen/Eigen:1,
                 from ../src/shogun/mathematics/eigen3.h:16,
                 from ../src/shogun/lib/tapkee/defines/eigen3.hpp:6,
                 from ../src/shogun/lib/tapkee/defines.hpp:23,
                 from ../src/shogun/lib/tapkee/embed.hpp:10,
                 from ../src/shogun/lib/tapkee/tapkee.hpp:10,
                 from ../src/shogun/lib/tapkee/tapkee_shogun.cpp:22:
/usr/include/eigen3/Eigen/src/Core/DenseBase.h: In instantiation of ‘void Eigen::DenseBase<Derived>::swap(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, -1, 0, -1, -1>; Derived = Eigen::Matrix<double, -1, -1, 0, -1, -1>]’:
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:857:17:   required from ‘void Eigen::PlainObjectBase<Derived>::swap(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, -1, 0, -1, -1>; Derived = Eigen::Matrix<double, -1, -1, 0, -1, -1>]’
../src/shogun/lib/tapkee/defines.hpp:52:20:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseBase.h:420:7: error: static assertion failed: THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY
       EIGEN_STATIC_ASSERT(!OtherDerived::IsPlainObjectBase,THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
       ^
[515/868] Building CXX object src/shog...ogun.dir/structure/TwoStateModel.cpp.o
ninja: build stopped: subcommand failed.
ubuntu@1604:~/shogun/build$
</pre>

**Comment by karlnapf** [comment]
The question is whether we can fix this without having to do a cast distinction for different eigen versions in the source code. I find these very unpleasant.

@vigsterkr I think we can fix this for new eigen version and then bundle the new one?

**Comment by vigsterkr** [comment]
@karlnapf 3.3+ is dev branch, i.e. not yet stable. 3.2.x (which works and is bundled now) is the stable branch. i would bundle stable version and not development version.

we'll have to do similar hacks that i did with viennacl version 1.6 and older vs earlier version. MACRO hacks to the rescue *caramba*! :dancers:

**Comment by karlnapf** [comment]
I see. Agreed then. But in that light, I am actually against the MACRO hacks, but rather just not using the dev version. Cleaner in my eyes

**Comment by vigsterkr** [comment]
@karlnapf yes but one day the dev will become stable and there's gonna be a longer period where both 3.2 and 3.3 will be around... so we'll need to have the macro hack...will look into it asap.

**Comment by karlnapf** [comment]
@arianepaola are you interested in fixing this for the release?

**Comment by arianepaola** [comment]
@karlnapf yes
