### ISSUE TITLE
CMake Error at cmake/FindPLY.cmake:24 (message):   ply import failure:

### ISSUE THREAD

**Issue by AlexLuya** [shogun-toolbox/shogun#3149]
Hello,
    Under a ubuntu 14.04 64bit,I tried to compile shogun from source,but got error:
````bash
...
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
.....
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
.....
CMake Error at cmake/FindPLY.cmake:24 (message):
  ply import failure:

Call Stack (most recent call first):
  CMakeLists.txt:682 (FIND_PACKAGE)
````

Questions are:
   Do these two "Could NOT find"s cause this error?
       if there are,how to install them?(as you may knew,by default,much more "Could Not find"s will occur,and I have installed these missings by googling,but can't find a way to install these two)

  Is  "ply import failure:" the only reason that caused this failure?If it is,how to fix it?It seems that no solution can be found by googling?

  If "ply import failure:" do cause the problem,after fixed it,can I ignore the two "Could not find"s to install?any consequence?

**Comment by besser82** [comment]
Hey!

You just need to install python-ply, using `sudo apt-get install 
python-ply`.  The other two (MOSEK, CPLEX) can be safely ignored.

Cheers
   Björn


Am 08.04.2016 um 16:35 schrieb Alex Luya:

**Comment by karlnapf** [comment]
I improved the situation in https://github.com/shogun-toolbox/shogun/commit/d2e1beacd9a156be2fb50c6c5f12269508224cab
It now tells the user to de-activate meta examples or install ply

**Comment by hao555sky** [comment]
Sorry for interrupting, I met the issue "Python module ply required for meta examples.  Disable meta examples or install python-ply" even if I installed the python-ply. What does the "meta example" mean?

**Comment by karlnapf** [comment]
It is these guys: shogun.ml/examples

If you want to generate the code for those locally, you need ply. If you have it installed and it is not detected, please send a report with details of your setup in a new issue.
