### ISSUE TITLE
refactor  SingleLaplacianInferenceMethodWithLBFGS and SingleLaplacianInferenceMethod

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#3154]
@karlnapf 
https://github.com/shogun-toolbox/shogun/wiki/GSoC_2016_project_large_gps

**Comment by karlnapf** [comment]
Can you give some more specifiy instructions here, so that somebody else would be able to do this? Not clear what this issue is about with this description

**Comment by yorkerlin** [comment]
`SingleLaplacianInferenceMethod` uses Newton method.
` SingleLaplacianInferenceMethodWithLBFGS` uses LBFGS method.
The issue is about refactoring these two methods using `strategy pattern`.

Hint:
Newton optimizer and LBFGS optimizer

**Comment by yorkerlin** [comment]
@karlnapf 
done!
I will send PRs to address this issue.

**Comment by yorkerlin** [comment]
https://github.com/shogun-toolbox/shogun/pull/3168
