### ISSUE TITLE
refactor  SingleFITCLaplacianInferenceMethod  and SingleFITCLaplacianInferenceMethodWithLBFGS

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#3155]
@karlnapf 

https://github.com/shogun-toolbox/shogun/wiki/GSoC_2016_project_large_gps

**Comment by karlnapf** [comment]
Details please! And a label would be good as well

**Comment by yorkerlin** [comment]
SingleFITCLaplacianInferenceMethod uses Newton method.
SingleFITCLaplacianInferenceMethodWithLBFGS uses LBFGS method.
The issue is about refactoring these two methods using `strategy pattern`.

Hint:
Newton optimizer and LBFGS optimizer

**Comment by yorkerlin** [comment]
@karlnapf 
done!
I will send PRs to address this issue.

**Comment by yorkerlin** [comment]
https://github.com/shogun-toolbox/shogun/pull/3169/files
