### ISSUE TITLE
compilation error in methods with no viennacl implementation

### ISSUE THREAD

**Issue by curiousguy13** [shogun-toolbox/shogun#3156]
linalg currently contains methods like range_fill, mean, cholesky etc. which only have their eigen3 implementation and when viennacl is given as backend , it gives a compilation error.

the following is an example of such an error in cholesky.h when viennacl is given as backend in cholesky_unittest.cc.
http://buildbot.shogun-toolbox.org/builders/trusty%20-%20libshogun%20-%20viennacl/builds/616/steps/compile/logs/stdio

In my opinion there should be a way to deal with such situation without producing error.

**Comment by karlnapf** [comment]
I absolutely agree, this is far from optimal. In particular the HAVE_VIENNACL guard to resolve this  doesnt make any sense.
We had some discussions about a re-factored linalg. We will put that to life soon
