### ISSUE TITLE
EigenMatrixXtMap is a private type

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3192]
`SGMatrix.EigenMatrixXtMap()` (see https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/SGMatrix.h#L99) is public but the `typedef` of `EigenMatrixXtMap` is private... this way the operator will not work...

@lambday should we make the typedef public (i second this one) or the operator private?

**Comment by lambday** [comment]
@vigsterkr yeah totally that makes much more sense! I guess at present this operator is not being used anywhere, that's why we haven't caught this yet!

BTW could you please have a look at the gist discussion that Pan started?(https://gist.github.com/OXPHOS/a9b79a995b75a0972811f634e80ff632)

**Comment by vigsterkr** [comment]
@lambday i did comment in the beginning :)

**Comment by lambday** [comment]
@vigsterkr yeah maybe share some thoughts about the latest discussion there?
