### ISSUE TITLE
Support for conditional meta example generation

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3193]
`linear_ridge_regression` meta example depends on `CLinearRidgeRegression` which requires `HAVE_LAPACK`. We need a way to not to generate the `cpp` example if a given library (that is required for the meta example) is not available.

@karlnapf

**Comment by karlnapf** [comment]
This mechanic is already in place, though hacky.
See https://github.com/shogun-toolbox/shogun/blob/develop/cmake/FindMetaExamples.cmake

**Comment by karlnapf** [comment]
I can send a fix later ...

**Comment by karlnapf** [comment]
Should be fixed in de9735a662eba90388f052ddf34c5d6ca6867a8d
