### ISSUE TITLE
FLDATest.CLASSIC_FLDA_Unit_test fails with eigen 3.3

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3194]
see: http://buildbot.shogun-toolbox.org/builders/xenial%20-%20libshogun/builds/4/steps/test/logs/stdio

the value is the opposite i.e. `-1.0*expected_output` of the expected output

**Comment by karlnapf** [comment]
There is a partial fix, and doing this properly is now in #3486
