### ISSUE TITLE
Lapack linking error

### ISSUE THREAD

**Issue by arianepaola** [shogun-toolbox/shogun#3213]
Linking error (git develop) using:
cmake -GNinja -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="./install" ..

ninja GoogleMock && ninja all && ninja install && ninja test

[688/1170] Linking CXX executable tests/meta/meta_example_integration_tester
FAILED: : && /usr/bin/ccache /usr/bin/c++  -std=c++11 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated   -fopenmp   -O3 -fexpensive-optimizations -frerun-cse-after-loop -fcse-follow-jumps -finline-functions -fschedule-insns2 -fthread-jumps -fforce-addr -fstrength-reduce -funroll-loops -mfpmath=sse   tests/meta/CMakeFiles/meta_example_integration_tester.dir/tester.cpp.o  -o tests/meta/meta_example_integration_tester  -rdynamic src/shogun/libshogun.so.17.2 -lpthread -llapack_atlas -lcblas -latlas -lglpk -lOpenCL -lnlopt -Wl,-Bstatic -llpsolve55 -Wl,-Bdynamic -lColPack -lxml2 /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so -lpthread -lsz -lz -ldl -lm -lcurl -lz -ldl -lm -lcurl -lbz2 -llzma -lsnappy -llzo2 -Wl,-rpath,/home/ubuntu/shogun/build/src/shogun:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib && :
src/shogun/libshogun.so.17.2: undefined reference to `dsyev_'
src/shogun/libshogun.so.17.2: undefined reference to`dorgqr_'
src/shogun/libshogun.so.17.2: undefined reference to `dsyevr_'
src/shogun/libshogun.so.17.2: undefined reference to`dsygvx_'
src/shogun/libshogun.so.17.2: undefined reference to `dstemr_'
src/shogun/libshogun.so.17.2: undefined reference to`dgesvd_'
collect2: error: ld returned 1 exit status
[688/1170] Linking CXX executable examples/undocumented/libshogun/converter_jade_bss
FAILED: : && /usr/bin/ccache /usr/bin/c++  -std=c++11 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated   -fopenmp   -O3 -fexpensive-optimizations -frerun-cse-after-loop -fcse-follow-jumps -finline-functions -fschedule-insns2 -fthread-jumps -fforce-addr -fstrength-reduce -funroll-loops -mfpmath=sse   examples/undocumented/libshogun/CMakeFiles/converter_jade_bss.dir/converter_jade_bss.cpp.o  -o examples/undocumented/libshogun/converter_jade_bss  -rdynamic src/shogun/libshogun.so.17.2 -lpthread -llapack_atlas -lcblas -latlas -lglpk -lOpenCL -lnlopt -Wl,-Bstatic -llpsolve55 -Wl,-Bdynamic -lColPack -lxml2 /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so -lpthread -lsz -lz -ldl -lm -lcurl -lz -ldl -lm -lcurl -lbz2 -llzma -lsnappy -llzo2 -Wl,-rpath,/home/ubuntu/shogun/build/src/shogun:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib && :
src/shogun/libshogun.so.17.2: undefined reference to `dsyev_'
src/shogun/libshogun.so.17.2: undefined reference to`dorgqr_'
src/shogun/libshogun.so.17.2: undefined reference to `dsyevr_'
src/shogun/libshogun.so.17.2: undefined reference to`dsygvx_'
src/shogun/libshogun.so.17.2: undefined reference to `dstemr_'
src/shogun/libshogun.so.17.2: undefined reference to`dgesvd_'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by vigsterkr** [comment]
this is waaaay tooo weird :) lemme reproduce this in a docker with ninja :)

**Comment by arianepaola** [comment]
I have also tried to use -DUSE_ORIGINAL_LAPACK=ON
This gives an error that -llapack_atlas is required.

Adding manually -llapack as work around seemed to work.

The installed libraries and tools on Ubuntu 16.04 are:
sudo apt-get install git gcc g++ cmake ccache ninja-build doxygen swig python-dev python-numpy python-jinja2 libblas-dev libatlas-base-dev libglpk-dev libeigen3-dev libcolpack-dev libviennacl-dev libnlopt-dev liblpsolve55-dev exuberant-ctags python-ply libxml2-dev libhdf5-dev libcurl4-openssl-dev libbz2-dev liblzma-dev libsnappy-dev liblzo2-dev libprotobuf9v5 libprotobuf-lite9v5 protobuf-compiler

**Comment by arianepaola** [comment]
@vigsterkr @karlnapf @lgoetz 

Any update on this? I have tried a few workarounds, but the error still occurs.

**Comment by ljw3351639** [comment]
@arianepaola  hello, i also got the problem, ../../../src/shogun/libshogun.so.17.2：对‘dsyev_’未定义的引用
../../../src/shogun/libshogun.so.17.2：对‘dorgqr_’未定义的引用
../../../src/shogun/libshogun.so.17.2：对‘dstemr_’未定义的引用
../../../src/shogun/libshogun.so.17.2：对‘dsyevr_’未定义的引用
../../../src/shogun/libshogun.so.17.2：对‘dsygvx_’未定义的引用
../../../src/shogun/libshogun.so.17.2：对‘dgesvd_’未定义的引用
and what did "Adding manually -llapack as work around seemed to work" mean?  Have you solved it?

**Comment by vigsterkr** [comment]
@ljw3351639 could you tell me the specs of your OS?

**Comment by ljw3351639** [comment]
@vigsterkr ，I just delet the part about FIND_PACKAGE(Atlas) in the markelist.txt,  and  only used FIND_PACKAGE(CBLAS), it will fine. So maybe the problem is about the Atlas libs

**Comment by vigsterkr** [comment]
@ljw3351639 i see... still would be good to know what is your setup so i could reproduce and possibly fix this error :) thnx
