### ISSUE TITLE
cmake not turning off USE_HDF5

### ISSUE THREAD

**Issue by deepakkandasamy** [shogun-toolbox/shogun#3238]
When I did't have HDF5 installed, in ccmake, the HDF5_DIR was set to NOTFOUND but the USE_HDF5 was set to ON. Once I install HDF5, the HDF5_DIR was still NOTFOUND. I used the code from Git.
My system info:
Ubuntu 15.04
memory 5.7 GiB
Processor Intel® Core™ i5-4200U CPU @ 1.60GHz × 4

**Comment by karlnapf** [comment]
Can you provide explicit cmake command and post gists of the the output?

**Comment by deepakkandasamy** [comment]
[https://gist.github.com/deepakkandasamy/54c2b00148c6115a652855ffffdfaec8](url)
Here is the output of the cmake I ran

**Comment by karlnapf** [comment]
The link is 404
