### ISSUE TITLE
Python interface works only partly

### ISSUE THREAD

**Issue by AngryMouser** [shogun-toolbox/shogun#3245]
Hi, I have a problem while trying to use your toolbox:
I call from modshogun import * in python 2.7 and its OK.
However, things like PCA, Isomap, LMNN are not recognized ("cannot import name ...")
How to call cmake properly in such case?

**Comment by karlnapf** [comment]
This is most likely due to a missing eigen3.
The latest development version includes it by default, you could try that.
or run cmake with `-DBUNDLE_EIGEN` (or similar).

Always, when reporting errors, messages and your configuration are helpful to solve them

**Comment by AngryMouser** [comment]
I have tried `-DBUNDLE_EIGEN` with no effect.

**Comment by AngryMouser** [comment]
I have tried` -DBULNDE_EIGEN` with no effect.
I have downloaded the development version and tried to run `cmake -DPythonModular=ON ..` and got errors (attached in file "out"). I also attach 2 other files that were mentioned.

[files.zip](https://github.com/shogun-toolbox/shogun/files/300731/files.zip)

**Comment by karlnapf** [comment]
Can you please put these on github gist rather than attached a zipfile?
Also, what *exact* command did you use to build shogun, and what is your system spec.
Thanks!
