### ISSUE TITLE
Meta example integration for all targets

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3323]
This task is to enable the integration testing of meta examples for all target languages. Currently it only is enabled for cpp. That is, only the cpp meta examples contain will contain code that serialises results and compares them to a reference file. This involves
- enabling the `storeVars` flag in the `generator.py` file other more languages, one by one
- This enables the generated listing to contain serialization code
- This code needs to work, there might be issues such as missing typemaps (java), templating problems, etc
- once this works, we have integration testing across all target languages

**Comment by souravsingh** [comment]
@karlnapf I would like to work on the issue. How do I start?

**Comment by karlnapf** [comment]
This one is tricky, I recomend you start understanding our meta example system first, for example via adding a new example (picky any python modular one and translate it to meta example, check [this](https://github.com/shogun-toolbox/shogun/tree/develop/doc/cookbook) Readme

**Comment by karlnapf** [comment]
I solved this at the GSoC 2016 mentor summit
