### ISSUE TITLE
Tests / illustration for meta language

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3328]
This task to to add a few meta language examples that serve the purpose of
 * testing the possible language constructs (like the ones I put for vectors)
 * illustrating what the meta language can do

In that sense it is both test and language illustration.

 * rename `tests` folder to `example` or `syntax_examples`
 * put in files with tests for everything we do in the meta langauge
  * enums
  * literals
  * Instantiating objects via constructors
  * assignment
  * ...

Think of some clever structure

Note to GSoC students. You can send such an example test patch instead a normal coobook if you wish. 
@sanuj @OXPHOS @Saurabh7

**Comment by sanuj** [comment]
@karlnapf Can you please link to your vectors test, I can't seem to find it.  Which `tests` folder has to be renamed to `example` or `syntax_examples`? Were you talking about `shogun/examples/meta/generator/tests`?

**Comment by karlnapf** [comment]
It is here. I put some tests already but need to make things work with travis before merging them.
You can also send PRs here to increase passing tests

https://travis-ci.org/shogun-toolbox/shogun/builds/145334402
https://github.com/shogun-toolbox/shogun/compare/develop...738612febb82

**Comment by karlnapf** [comment]
@sorig do we have all meta language constructs covered, or do we need more?
