### ISSUE TITLE
smart pointers in shogun

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#3371]
@karlnapf  @vigsterkr  @lisitsyn  @lambday 
Hi all,
Do we plan to use  smart pointers in c++11?
Do you know how to deal with circular reference using shogun's smart pointers?
How to deal with circular reference when it comes to serialization?

**Comment by karlnapf** [comment]
Yes we do plan to use them eventually. We in fact aim for a pointer free interface ....
Internally, we can do whatever we like.

Serialisation is currently being worked on, come to irc to discuss. 
I will close this issue for now, let's do sch discussions somewhere else, issues should be kept for more concrete stuff.
