### ISSUE TITLE
StringFileFeatures.cpp:  unreachable code

### ISSUE THREAD

**Issue by shogun-tester-AT** [shogun-toolbox/shogun#3430]
When compiling shogun-4.1.0  (and earlier version(s)) using the usual `cmake` and `make` commands,
the following warning occurs:

_shogun-4.1.0/src/shogun/features/StringFileFeatures.cpp: In instantiation of_ 
`ST* shogun::CStringFileFeatures<ST>::get_line(uint64_t&, uint64_t&, int32_t&, uint64_t) [with ST = bool; uint64_t = long unsigned int; int32_t = int]:`
_shogun-4.1.0/src/shogun/features/StringFileFeatures.cpp:125:16:   required from here_
_shogun-4.1.0/src/shogun/features/StringFileFeatures.cpp:30:9: warning: comparison of constant ‘'\012'’ with boolean expression is always false [-Wbool-compare]_
`if (c == '\n')`

The compiler warning might be eliminated by  replacing the if-clause by:
`if ((char)c == '\n')` ,

but I doubt whether this is the real solution.

OS: Ubuntu 16.04 LTS

**Comment by vigsterkr** [comment]
@shogun-tester-AT any chance you've tested whether this bug occurs in `develop` branch of the git repo?

**Comment by shogun-tester-AT** [comment]
No, I just downloaded the latest release 4.1.0 (and previous) and compiled it on my computer.
