### ISSUE TITLE
make with DJavaModular=ON fails

### ISSUE THREAD

**Issue by entalent** [shogun-toolbox/shogun#3432]
when 'Generating preprocessor_kernelpca_modular.class' there is an error:
shogun-develop/examples/undocumented/java_modular/preprocessor_kernelpca_modular.java:19: error: cannot find symbol
		KernelPCA preprocessor = new KernelPCA(kernel);
		^
  symbol:   class KernelPCA
  location: class preprocessor_kernelpca_modular
/home/entalent/shogun-develop/examples/undocumented/java_modular/preprocessor_kernelpca_modular.java:19: error: cannot find symbol
		KernelPCA preprocessor = new KernelPCA(kernel);
		                             ^
  symbol:   class KernelPCA
  location: class preprocessor_kernelpca_modular
2 errors
make[2]: *** [examples/undocumented/java_modular/preprocessor_kernelpca_modular.class] Error 1
make[1]: *** [examples/undocumented/java_modular/CMakeFiles/build_java_examples.dir/all] Error 2
make: *** [all] Error 2

**Comment by vigsterkr** [comment]
@entalent could you share the following details:
 * which version of shogun you are using
 * which version is the JDK you are having on your system

**Comment by entalent** [comment]
- The version info printed by Version::print_version function is v4.2.0_2016-8-15_21:39262656
- I'm using Oracle JDK 8u101 on Ubuntu 14.04, the output of "java -version" is
    ```
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by vigsterkr** [comment]
mmm based on the version you are using the git repo...? is it the develop branch?
it's just weird because with the very same properties (jdk, ubuntu etc.) the java modular interface builds and tests successfully, see:
https://travis-ci.org/shogun-toolbox/shogun/jobs/152507031

**Comment by vigsterkr** [comment]
@entalent could you maybe provide the full cmake output please?

**Comment by karlnapf** [comment]
This is likely to be an eigen3 caused problem (i.e. KernelPCA is guarded)
Can we have some more output?
