### ISSUE TITLE
Failed to install DPythonModular on Ubuntu 14.04 with shogun-4.1.0

### ISSUE THREAD

**Issue by Corllll** [shogun-toolbox/shogun#3437]
i have Ubuntu 14.04
swig 2.0.11
python 2.7.6
numpy 1:1.8.1
gcc 4.8.2

i ran cmake .. -DPythonModular=On -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so

then i ran make 

[  0%] Generating /root/shogun-4.1.0/src/shogun/base/class_list.cpp
[  0%] Built target class_list
[  1%] Generating version header
[  1%] Built target version
Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
[ 86%] Built target libshogun
Linking CXX shared library libshogun.so
[ 86%] Built target shogun
[ 86%] copying SWIG files
[ 86%] Built target python_modular_src
[ 86%] Building CXX object src/interfaces/python_modular/CMakeFiles/_python_modular.dir/modshogunPYTHON_wrap.cxx.o
/root/shogun-4.1.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:155:21: fatal error: Python.h: No such file or directory
 # include <Python.h>
                     ^
compilation terminated.
make[2]: *** [src/interfaces/python_modular/CMakeFiles/_python_modular.dir/modshogunPYTHON_wrap.cxx.o] Error 1
make[1]: *** [src/interfaces/python_modular/CMakeFiles/_python_modular.dir/all] Error 2
make: *** [all] Error 2

**Comment by vigsterkr** [comment]
oh this is rather interesting! could you please provide the full cmake output as well (when you ran it the first time). thnks

**Comment by Corllll** [comment]
i follow this https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART
$ cd "$HOME/shogun-4.1.0"

$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ..

$ make -j5 all
$ make install

**Comment by vigsterkr** [comment]
wait i thought you ran:
```cmake .. -DPythonModular=On -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so``` (see your first message).

but anyhow i would need the full output of what you get on your screen after running `cmake`.

**Comment by Corllll** [comment]
oh i see like this？


root@cory-virtual-machine:~/shogun-4.1.0/build# cmake .. -DPythonModular=On -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so
-- Using system's malloc
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find Eigen3 (missing:  EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
-- checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Spinlock support found
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Supported backend(s) for linear algebra NOT FOUND/NOT ENABLED
-- ===================================================================================================================
-- Summary of Configuration Variables
-- 
-- The following OPTIONAL packages have been found:

 * CCache
 * GDB
 * OpenMP
 * BLAS
 * LAPACK
 * Atlas
 * LibXml2
 * ZLIB
 * Spinlock
 * Threads

-- The following REQUIRED packages have been found:

 * SWIG (required version >= 2.0.4)
 * PythonLibs
 * PythonInterp
 * NumPy

-- The following OPTIONAL packages have not been found:

 * Mosek
 * GLPK
 * CPLEX
 * ARPACK
 * Eigen3 (required version >= 3.1.2)
 * ViennaCL (required version >= 1.5.0)
 * NLopt
 * LpSolve
 * ColPack
 * ARPREC
 * Doxygen (required version >= 1.8.6)
 * HDF5
 * CURL
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * Protobuf

-- The following REQUIRED packages have not been found:

 * OpenCL

-- ===================================================================================================================
-- Enabled Integration
--   OpenCV Integration is OFF 	 - enable with -DOpenCV=ON
-- ===================================================================================================================
-- Enabled Interfaces
--   libshogun is ON
--   python modular is ON
--   octave modular is OFF 	 - enable with -DOctaveModular=ON
--   java modular is OFF 	 - enable with -DJavaModular=ON
--   perl modular is OFF 	 - enable with -DPerlModular=ON
--   ruby modular is OFF 	 - enable with -DRubyModular=ON
--   csharp modular is OFF 	 - enable with -DCSharpModular=ON
--   R modular is OFF 		 - enable with -DRModular=ON
--   lua modular is OFF 	 - enable with -DLuaModular=ON
-- 
-- Enabled legacy interfaces
--   cmdline static is OFF 	 - enable with -DCmdLineStatic=ON
--   python static is OFF 	 - enable with -DPythonStatic=ON
--   octave static is OFF 	 - enable with -DOctaveStatic=ON
--   matlab static is OFF 	 - enable with -DMatlabStatic=ON
--   R static is OFF 		 - enable with -DRStatic=ON
-- ===================================================================================================================
-- To compile shogun type
--   make
-- 
-- To install shogun to /root/shogun-install type
--   make install
-- 
-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /root/shogun-4.1.0/build

**Comment by vigsterkr** [comment]
yep this is the one!
i suppose you are using all the default packages of ubuntu. in that case could you please just do the following:
```
rm -rf build
mkdir build
cmake -DPythonModular=ON ..
```

**Comment by Corllll** [comment]
ok i did,but i have error:

> 

root@cory-virtual-machine:~/shogun-4.1.0# cmake -DPythonModular=ON ..
CMake Error: The source directory "/root" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
root@cory-virtual-machine:~/shogun-4.1.0# cd build
root@cory-virtual-machine:~/shogun-4.1.0/build# cmake -DPythonModular=ON ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CCache: /usr/bin/ccache  
-- Found SWIG: /usr/bin/swig2.0 (found suitable version "2.0.11", minimum required is "2.0.4") 
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": works
-- Checking C++11 support for "atomic"
-- Checking C++11 support for "atomic": works
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": works
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": works
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": works
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": works
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": works
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": works
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": works
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": works
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": works
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": not supported
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": works
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": works
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": works
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": works
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Using system's malloc
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for signgam
-- Looking for signgam - found
-- Looking for fdopen
-- Looking for fdopen - found
-- Looking for log2
-- Looking for log2 - found
-- Looking for powl
-- Looking for powl - found
-- Looking for lgammal
-- Looking for lgammal - found
-- Looking for sqrtl
-- Looking for sqrtl - found
-- Looking for finite
-- Looking for finite - found
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Performing Test HAVE_STD_ISINF
-- Performing Test HAVE_STD_ISINF - Success
-- Performing Test HAVE_STD_ISFINITE
-- Performing Test HAVE_STD_ISFINITE - Success
-- Performing Test HAVE_STD_ISNAN
-- Performing Test HAVE_STD_ISNAN - Success
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Found GDB: /usr/bin/gdb  
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Looking for clapack_dpotrf in /usr/lib/atlas-base/liblapack_atlas.so.3
-- Looking for clapack_dpotrf in /usr/lib/atlas-base/liblapack_atlas.so.3 - found
-- Found ATLAS: /usr/lib/atlas-base/liblapack_atlas.so.3;/usr/lib/atlas-base/libcblas.so.3;/usr/lib/atlas-base/libf77blas.so.3;/usr/lib/atlas-base/libatlas.so.3;/usr/lib/liblapack.so.3  
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find Eigen3 (missing:  EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.1") 
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Spinlock support found
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Supported backend(s) for linear algebra NOT FOUND/NOT ENABLED
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPythonLibs.cmake:190 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:904 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/root/shogun-4.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/root/shogun-4.1.0/build/CMakeFiles/CMakeError.log".

**Comment by vigsterkr** [comment]
@Corllll oh ok great! lemme look into it and get back to...

**Comment by Corllll** [comment]
＠vigsterkr thanks to your help,and answer quickly.

**Comment by karlnapf** [comment]
Check your python setup

**Comment by Corllll** [comment]
@karlnapf  what's your mean?

**Comment by Corllll** [comment]
@vigsterkr @karlnapf ok i got that thanks.

**Comment by karlnapf** [comment]
Ill close this for now. If any problems, let us know!
