### ISSUE TITLE
Octave interface doesn't function properly

### ISSUE THREAD

**Issue by elmasee** [shogun-toolbox/shogun#3438]
I compiled the Shogun for static Octave interface without any error, but the interface file "sg.oct" is never generated, and I cannot locate any shogun packages to call in octave.

How can I make sure the interface is properly setup?

**Comment by vigsterkr** [comment]
mmmm @elmasee i would really suggest to use the octave_modular interface instead of the static one.

**Comment by karlnapf** [comment]
static interfaces are deprecated and will probably be removed very soon

**Comment by elmasee** [comment]
used the octave_modular interface, works fine, thanks.
