### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by elmasee** [shogun-toolbox/shogun#3439]
I am using standalone Shogun with some toy data:
    
   shogun classifier_gmnpsvm.sg

I am receiving this error regardless of the input data I use: 

   "Floating point exception (core dumped)"

Any ideas?

**Comment by vigsterkr** [comment]
@elmasee any particular reason you wanna use the old static command line interface?

**Comment by karlnapf** [comment]
We don't support the old command line interface anymore (even though the test-suite passed largely)
