### ISSUE TITLE
Additional Links to Documentation do not work

### ISSUE THREAD

**Issue by souravsingh** [shogun-toolbox/shogun#3445]
After accessing the link here-http://www.shogun-toolbox.org/page/documentation/information
I try to access the links in the English and Chinese sections.Sadly, none of the links work.

**Comment by yorkerlin** [comment]
@vigsterkr 
this should be fixed.

@souravsingh 
All links which begin with `http://www.shogun-toolbox.org/doc/en/current/` are broken.
If you should to read the doc, please use links which begin with `http://www.shogun-toolbox.org/doc/en/latest/`

**Comment by karlnapf** [comment]
This is part of #3446 so closing.
Thanks for the reporting
