### ISSUE TITLE
test script for octave/swig interface missing?

### ISSUE THREAD

**Issue by amwink** [shogun-toolbox/shogun#3449]
After compiling Shogun using the instructions in [INSTALL] (https://github.com/shogun-toolbox/shogun/wiki/INSTALL), and completing the section for octave/swig and using `-DPythonModular=ON -DRModular=ON -DOpenCV=ON -DOctaveModular=ON -DJavaModular=ON` I tried to test it with the suggested command
 
    octave examples/documented/octave_modular/libsvm.m
but that file does not exist any more. Does that mean there is a problem with Octave support?

I used one of the undocumented tests

    octave examples/undocumented/matlab_and_octave/tests/test_sparse.m
but that produced this error:

    error: 'sg' undefined near line 6 column 1
    error: called from:
    error:   /usr/local/shogun/examples/undocumented/matlab_and_octave/tests/test_sparse.m at line 6, column 1

**Comment by karlnapf** [comment]
try the examples in `octave_modular` --- the ones you are running are outdated. Ill close this for now, let me know if you still have problems
