### ISSUE TITLE
"pip install shogun-ml" does not work.

### ISSUE THREAD

**Issue by souravsingh** [shogun-toolbox/shogun#3457]
On Running the command `pip install shogun-ml`, this is the error report which is shown-

`$ pip install shogun-ml`
`Collecting shogun-ml`
`Could not find a version that satisfies the requirement shogun-ml (from versions: )`
`No matching distribution found for shogun-ml`

**Comment by vigsterkr** [comment]
@souravsingh until we dont release a new version you'll have to check out the src from github and then run within the directory the `setup.py`

**Comment by frawha** [comment]
I tried downloading from src from github and running setup.py, got the following error report:

`$ sudo python setup.py install
Conversion of long_description from markdown to reStructuredText failed, skipping...
Retrieving Shogun version
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [False] -  make: [False] - make install: [False]
Bootstrapping Shogun
Running CMake
CMake arguments: -DPythonModular=ON -DENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX=install 
Creating build directory: /home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build
-- Using system's malloc
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Could NOT find Atlas (missing:  Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY) 
-- Could NOT find CBLAS (missing:  CBLAS_LIBRARY) 
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- Checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
-- Could NOT find Ctags (missing:  CTAGS_EXECUTABLE) 
CMake Error at CMakeLists.txt:739 (message):
  Ctags required for meta examples.


-- Configuring incomplete, errors occurred!
See also "/home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build/CMakeFiles/CMakeOutput.log".
See also "/home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build/CMakeFiles/CMakeError.log".
CMake error.
Error running CMake
Running make
make arguments: all 
make: *** No rule to make target 'all'.  Stop.
make error.
Error running make
Running make
make arguments: install 
make: *** No rule to make target 'install'.  Stop.
make error.
Error running make install
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [False] -  make: [False] - make install: [False]
Shogun bootstrapping failed!
Please make sure that you have cmake and make installed.
`

**Comment by zhenyisong** [comment]
I used the same protocol:  src/setup.py
and these were complains:
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [True] -  make: [True] - make install: [True]
Setting Shogun Python packages location
Traceback (most recent call last):
  File "setup.py", line 299, in <module>
    version = get_shogun_version(),
  File "setup.py", line 205, in get_shogun_version
    if shogun_preconditions():
  File "setup.py", line 114, in shogun_preconditions
    shogun_bootstrap()
  File "setup.py", line 91, in shogun_bootstrap
    shogun_python_packages_location = glob.glob(os.path.join(shogun_generated_install, 'lib/*/dist-packages'))[0]
IndexError: list index out of range

**Comment by karlnapf** [comment]
The error message tells you what is going on
```
CMake Error at CMakeLists.txt:739 (message):
Ctags required for meta examples.
```
Either install ctags or disable meta examples
