### ISSUE TITLE
add scala interface to docs and tests

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3485]
# Which is easy, since it uses the java jar. No swig additions needed, just the build and the docs
- meta examples
- integration testing in the above
- cookbook
- installation page
- INTERFACES.MD how to run

**Comment by souravsingh** [comment]
@karlnapf I would like to know about how it needs to be done.

**Comment by souravsingh** [comment]
@karlnapf I would like to know about how it needs to be done.

**Comment by souravsingh** [comment]
@karlnapf I would like to know About how it needs to be done. I am quite beginner to Shogun contribution but am enthusiastic about contributing to it.

**Comment by karlnapf** [comment]
Here is some start:
 * run cmake with enabling the meta examples being built
 * run `make meta_examples` and figure out what it does (you need to follow the cmake configuration files for that, best to google for a tutorial
 * run `make test` (need cmake switch for that) and figure out how the meta examples are executed

Once you have understood all that, you can check the `examples/meta` folder and the python scripts you need to modify to add scala. Then add a json for scala, then .... Then you need to figure out how to compile the generated listings with scala (rather than java)
The final result: making the meta examples generates a number of scala examples.
All this requires quite a bit of back-engineering how the whole process works.
Let me know if you have *concrete* questions

**Comment by abhinavrai44** [comment]
Hi @karlnapf ,
I would like to solve this issue

**Comment by karlnapf** [comment]
Its a not too hard (also not too easy) cmake / build issue. Only attempt if you know what you are doing, requires backwards-engineering of the existing build

**Comment by abhinavrai44** [comment]
I have been looking into the issue. I am able to generate scala meta examples if you pass -DScalaModular=ON. This is what that need to be done, right ?

**Comment by karlnapf** [comment]
That is step 1. Step2 would be to make them part of the build (i.e. they are executed when running `make test`)
Can you send a pull request so we can discuss there? This will take a few iterations
