### ISSUE TITLE
eigen3 operator bug workaround fix

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3486]
See file https://github.com/shogun-toolbox/shogun/blob/769a56112ad34738c7fd0e949124cfaef96de6ff/src/shogun/classifier/LDA.cpp#L176

Replace the line 

```
cen_pos=cen_pos*cen_pos.transpose()/(float64_t(num_pos-1));
```

with

```
cen_pos=cen_pos*cen_pos.transpose()
cen_pos/=(float64_t(num_pos-1));
```

fixes the eigen3 operator bug (TODO needs to be reported) that is currently fixed in via bundling eigen3 in the main `CMakeLists.txt`.
The issue is caused by eigen3 putting zeros only in the left hand side if the statement is done in one line

We want to fix all failing unit tests in xenial (eigen3.3+) in this way using the guard `EIGEN_WITH_OPERATOR_BUG`

To reproduce, disable bundling eigen3 with ubuntu xenial, run unit tests, modify code in the above way to fix, use guards to only apply the fix for the "bad" eigen3 versions

**Comment by karlnapf** [comment]
See #3487 for an example of one fix. There are a few more

**Comment by vigsterkr** [comment]
done
