### ISSUE TITLE
integrate linalg gsoc2016 work

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3500]
Feature branch:
https://github.com/shogun-toolbox/shogun/tree/feature/linalg_refactor

This requires:
- removing all old linalg code
- using the new parts, all tests need to pass
- big cmake cleanup as linalg is not compile time anymore

@OXPHOS you could have a go at this to wrap up the project. No? :)

**Comment by OXPHOS** [comment]
Sure np!

**Comment by OXPHOS** [comment]
Needs to migrate:
- `Apply`
- `Convolve`
- `ElementSqaure` (Not sure about this one as it's just a specialization of `ElementProduct`)
- `ElementUnary`
- `MatrixProduct`
- `SpecialPurpose` (elementwise logistic function)
Can add:
- `Transpose` (Currently in `SGMatrix`)
Optimization
- `ASSERT` in unit-tests
- Integrate `in-place` methods and the not in-place methods

**Comment by karlnapf** [comment]
What is the minimal set of things that we need in order to merge the feature branch?
Is that feasible before say april?

**Comment by vigsterkr** [comment]
rebase :D

**Comment by karlnapf** [comment]
That will take some time. Let me know @OXPHOS if you need help with that. Otherwise I might just do it

**Comment by OXPHOS** [comment]
@karlnapf @vigsterkr Sorry I missed this thread.
The things can be done pretty soon:
- `Cholesky`
- `Sum`
- Clean up interfaces (in-place and non in-place methods)
- Thread-safe GPU transfer methods
Can we aim for Mar 1st for the rebasing?

Most of the `linalg` methods are transfered except `ElementUnary` and `SpecialPurpose`.

**Comment by OXPHOS** [comment]
I wanna keep some notes here and maybe we could discuss further on irc.

- `linalg::special_purpose()`: 
    - Needs to be refactored to get rid of `CGPU*` classes.
    - Defined 7 methods, **none** of which is currently used in develop branch. 
    - (So this should be a good entrance task if we still want to keep the methods)

- `linalg::ElementUnaryOperation()`:
    - Needs to be refactored to get rid of `CGPU*` classes.
    - I cannot integrate it with current `linalg` framework because it allows user-defined operators, which cannot fit the macros we're currently using in `LinalgBackend*`.
    - Not sure what to do with it.

**Comment by karlnapf** [comment]
This is merged so I am closing this one.
@OXPHOS can you update the project for the stuff you think that should be done and potentially open additional issues if there are things that other people also could do?
