### ISSUE TITLE
Make use of CSignal

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3508]
All major outer loops in Shogun should implement CSignal. In particular those ones that implement solver calls that converge at some point.

There needs to be some thought on openmp loops as these cannot be cancelled easily ... maybe c++11 threads can be? pthreads can definitely.
However, for non-parallel loops, this is an easy task. See e.g. KNN

**Comment by vigsterkr** [comment]
a graceful way to break out from openmp loop
http://www.thinkingparallel.com/2007/06/29/breaking-out-of-loops-in-openmp/

**Comment by yorkerlin** [comment]
@karlnapf 
could we use tag `performance improvement` instead of `numerical optimization` ?

**Comment by yorkerlin** [comment]
I will change the tag now. Please let me know if you think tag `numerical optimization` is better.

**Comment by karlnapf** [comment]
This is not about improving performance. This is about outputting the state of optimization algorithms.
