### ISSUE TITLE
Investigate MKL usage

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3514]
Shogun once was able to take advantage of the (super fast) Intel MKL math library.
This task is to integrate this into the build (if present), and particular tell eigen3 about it.
Also, Shoguns number of threads should be forwarded to MKL.

Then, so dome some benchmarks. MKL has parallelised Eigensolvers etc, so many algorithms should be *much* faster when enabled.

Note MKL is proprietory software so you somehow need to get a copy. Check the MKL website for details

**Comment by souravsingh** [comment]
MKL is also available for community [here](https://registrationcenter.intel.com/en/forms/?productid=2558&licensetype=2). We can perhaps make use of it.

**Comment by vigsterkr** [comment]
just need to test it.

current cmake should be able to detect/use it :)

**Comment by sudk1896** [comment]
@karlnapf @vigsterkr : I have downloaded and installed the MKL library. Could you suggest some entrance tasks that I could do ? Thanks.

**Comment by karlnapf** [comment]
Make Shogun's eigen3 use it. If that doesnt make it clear (nontrivial task, will require solving lots of subproblems using the Google-it approach), better pick another entrance task

**Comment by vigsterkr** [comment]
this is definitely done :)
