### ISSUE TITLE
`make cookbook` fails when certain cookbooks are guarded

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3520]
See http://pastebin.com/sDjUi3bb

**Comment by karlnapf** [comment]
This comes since `FindMetaExamples.cmake` sometimes removes certain meta examples.
The cookbook should still build fine, just ignoring that particular page....

**Comment by IOcodegeass** [comment]
I faced this problem. And installing **nlopt** solved it.
Thanks :)

**Comment by karlnapf** [comment]
Yeah, it is not really a solve but rather a workaround :) We should deal with this properly....

**Comment by karlnapf** [comment]
Fixed in #3665
Thanks!
