### ISSUE TITLE
BigInput branch testing and integration 

### ISSUE THREAD

**Issue by ceerobins** [shogun-toolbox/shogun#3531]
We have found amazing benefit/robustness to scaling 'hyper plane cutting algorithms" over wide sparse noisy data, demonstrated this over scale up in sample and dimensionality (we are now at a solution space around 2.037... x10^90 and want to keep pushing).  We followed this from the human genome side of things and initially using the COFFIN framework outside of shogun. 

Vicktor, being the rad dude he is began helping with this noble cause to expand the index int to 128 etc, allowing for VERY LARGE training samples.... kicked this initiative in gear (thank you).

https://github.com/shogun-toolbox/shogun/tree/feature/BigInput

Thanks brilliant shogun dev team for your focus on what actually moves data/research forward.

**Comment by karlnapf** [comment]
Thanks for the feedback :)
So what is this issue about, getting things merged?
@vigsterkr seems like there is only one commit in there?
