### ISSUE TITLE
Propper error message when meta-testsuite doesnt exist

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3535]
See
http://pastebin.com/yQXbN8N2

It should tell to update the git submodule, so people don't need to ask what this error is about.

This is an extremely minimal cmake related entrance task, one line

**Comment by sudk1896** [comment]
@karlnapf: I obviously know how to solve this :)
Which file should I be editing here ?

**Comment by karlnapf** [comment]
Grep is your friend here

**Comment by karlnapf** [comment]
It should be in install already

**Comment by sudk1896** [comment]
@karlnapf: The instruction for git init submodule is already given  [here](https://github.com/shogun-toolbox/docs/blob/master/INSTALL.md#basics-). It says whenever yo've trouble to do `git submodule update --init`. Should I still add something to the `INSTALL` Readme.

**Comment by karlnapf** [comment]
This is not about changing readmes, but the cmake error message that you get when the data module is not present.

**Comment by karlnapf** [comment]
Fixed by #3551
