### ISSUE TITLE
Can't install using setup.py

### ISSUE THREAD

**Issue by frawha** [shogun-toolbox/shogun#3539]
I tried downloading src from github and running setup.py, got the following error report:

`$ sudo python setup.py install
Conversion of long_description from markdown to reStructuredText failed, skipping...
Retrieving Shogun version
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [False] - make: [False] - make install: [False]
Bootstrapping Shogun
Running CMake
CMake arguments: -DPythonModular=ON -DENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX=install 
Creating build directory: /home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build
-- Using system's malloc
-- Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Could NOT find Atlas (missing: Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY) 
-- Could NOT find CBLAS (missing: CBLAS_LIBRARY) 
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find OPENCL (missing: OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- Checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing: NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
-- Could NOT find Ctags (missing: CTAGS_EXECUTABLE) 
CMake Error at CMakeLists.txt:739 (message):
Ctags required for meta examples.

-- Configuring incomplete, errors occurred!
See also "/home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build/CMakeFiles/CMakeOutput.log".
See also "/home/frawha/Documents/2016-2/Machine Learning/shogun-develop/build/CMakeFiles/CMakeError.log".
CMake error.
Error running CMake
Running make
make arguments: all 
make: *** No rule to make target 'all'. Stop.
make error.
Error running make
Running make
make arguments: install 
make: *** No rule to make target 'install'. Stop.
make error.
Error running make install
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [False] - make: [False] - make install: [False]
Shogun bootstrapping failed!
Please make sure that you have cmake and make installed.
`

**Comment by karlnapf** [comment]
I guess the error message tells you what is wrong: you need ctags for this particular build configuration.
You can pass `-DBUILD_META_EXAMPLES=OFF` as an option to the cmake to avoid this.
You just wont have the examples then

**Comment by luoagnes** [comment]
I also meet the error：Please make sure that you have cmake and make installed. And there is a message is: 
Shogun build environment completed tasks: cmake: [True] - make: [False] - make install: [False]
so, how to install make? I can not find a make package for python, need help.

**Comment by karlnapf** [comment]
The setup.py is oudated. Pls install shogun using anaconda.
If you cannot make sense of the build messages, it might make more sense to install a binary version of shogun (see again anaconda)
