### ISSUE TITLE
When I `cmake cmake -DENABLE_TESTING=on ..`, It occurs some error

### ISSUE THREAD

**Issue by hongguangguo** [shogun-toolbox/shogun#3541]
```
CMake Error at tests/meta/CMakeLists.txt:7 (MESSAGE):
  Test suite for meta examples does not exist!
```
I google it, but now it doesn't work.
Would some one explains, Thank you!

**Comment by hongguangguo** [comment]
I works, I didn't update submodule `data`

**Comment by karlnapf** [comment]
A patch for the readme would be appreciated here as well :)

**Comment by hongguangguo** [comment]
yes, I would. But, I don't know which readme file to patch.

**Comment by karlnapf** [comment]
#3535
