### ISSUE TITLE
How to develop shogun in a easy way.

### ISSUE THREAD

**Issue by hongguangguo** [shogun-toolbox/shogun#3542]
I'm  a newbie. If I want to add a new feature, ex:MyClass. How to compile it, and test directly. I'm very confused.

Would some one illustrate some detail development about shogun ?

for example I want to add a class. 
```
shogun/src/shogun/multiclass/MulticlassLibSVM.h
shogun/src/shogun/multiclass/MulticlassLibSVM.cpp
```
how to compile it, and test. 
Can I write a main fun so as to test it?  is It ok?

**Comment by karlnapf** [comment]
Hi!

We currently have no readme for this. Any contribution is very welcome.

*However*, Shogun does all this in a very standard way

 * Add your class
 * Run `make` to compile Shogun (it is automatically added, you might have to start a fresh build)
 * enable `-DENABLE_TESTING=On` in cmake
 * `make test` runs unit tests, you can add a unit test based on the existing ones
 * you can run a single selected unit test as well via executing `build/tests/unit/shogun-unit-test --gtest_filer=YourTestName*`

Adding something like this to the unit testing page on the wiki would be helpful. Send a patch if you like

**Comment by hongguangguo** [comment]
Thank your reply @karlnapf , I will try it.

**Comment by karlnapf** [comment]
I just commented on a PR in the shogun-wiki repo. You can join efforts in there.
