### ISSUE TITLE
Remove msinttypes dependency

### ISSUE THREAD

**Issue by TianShengLi** [shogun-toolbox/shogun#3545]
Google Code has closed
msinttypes only two files, remove this dependency should not be difficult

CMakeLists.txt (361)

```
IF(MSVC)
	include(external/MSIntTypes)
	LIST(APPEND INCLUDES ${THIRD_PARTY_DIR}/MSIntTypes)

	include(external/MSDirent)
	LIST(APPEND INCLUDES ${MSDIRENT_INCLUDE_DIR})
ENDIF()
```

**Comment by vigsterkr** [comment]
@TianShengLi check feature/windows branch for windows build.... currently there are couple of issues that needs fixing. but there this hole story of MSIntTypes is fixed....
