### ISSUE TITLE
Fix meta example when ´-DENABLE_TESTING=OFF`

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3553]
Since the `WrappedObjectArray` class is guarded and only available when testing is turned on, the meta examples which explicitly import that class will not compile (java, cpp).

Solution:
If variable storing is turned off in meta example `generator.py` (`storeVars` or so), then the includes for `WrappedObjectArray` also have to be omitted.

Nice non trivial entrance task and crucial for any further release

**Comment by karlnapf** [comment]
For now, the workaround is to compile Shogun with the cmake siwtch `-DENABLE_TESTING`

**Comment by IOcodegeass** [comment]
Yes this workaround worked for cpp interface.
Just by compiling using  **cmake switch -DJavaModular=ON -DENABLE_TESTING=ON ..**

**Comment by sorig** [comment]
@karlnapf close this one
