### ISSUE TITLE
Investigate and update jblas matrix library for java

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3554]
The fact that jblas cannot support boolean arrays causes all sorts of problems. We need to use a library that can deal with matrices/arrays in a better way.
These have to be worked around in particular in the meta examples at the moment, see e.g. #3550 
Requires to change the typemaps....

**Comment by besser82** [comment]
I can ask Mikio Braun, if he'd intend to update JBLAS supporting boolean arrays…

**Comment by karlnapf** [comment]
That is an idea.
Though I don't Like the fact that jblas is turning everything into a double..... there must be an ndarray implementation for java no?

**Comment by vigsterkr** [comment]
we do support `org.ujmp` as well, so that should be enough....
