### ISSUE TITLE
`make build_java_meta_examples` always re-compiles all java examples

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3556]
It should rather, just like the cpp meta examples, only re-compile when a dependency was changes.

The `CMakeLists.txt` in `examples/meta/cpp` will serve as inspiration to do that.

Relatively easy entrance cmake hacking task.

**Comment by vigsterkr** [comment]
ok i think this can be now closed \o/
thnx a lot @geektoni
