### ISSUE TITLE
I want a mini_shogun, if I only need tree model, how to extract source code related tree.

### ISSUE THREAD

**Issue by hongguangguo** [shogun-toolbox/shogun#3558]
is There  some easy way to compile only source code I want?

**Comment by vigsterkr** [comment]
@hongguangguo this is currently not possible only with manual hacks. it's on the roadmap, but i am afraid only for 7.0. of course if you wanna help out to speed up the process i could point you to some of the pre-requirments for it.

**Comment by hongguangguo** [comment]
yes, I would like to do it. So as to I know  the project building details.  Than you a lot

**Comment by karlnapf** [comment]
There is some hack script written by @tklein23 but it is old and unlikely to work.
https://github.com/tklein23/shogun-partial-build


For now `ccache` effectively avoiding to re-compile things that haven't changed ... not optimal
