### ISSUE TITLE
SVMLight.h missing

### ISSUE THREAD

**Issue by Pazaak** [shogun-toolbox/shogun#3560]
Hi,
I'm trying to work with MKL, but I am running into a common problem all the times I try to install shogun, SVMLight.h is missing in the usr/include/shogun/classifier/svm folder. This happens to me by installing it in Debian 8 via apt-get libshogun-dev and by compiling from source in Ubuntu 16.04. I can see the file in the source files, but in the installation it seems to be missing. Cmake says that I have all the required packages.
Thank you for your attention.

**Comment by vigsterkr** [comment]
@Pazaak we had to remove the svmlight from teh debian package due to licensing issues. if you wanna use svmlight, you'll have to compile libshogun manuall.
