### ISSUE TITLE
Unable to install package on Ubuntu 16.04

### ISSUE THREAD

**Issue by hrushikesht** [shogun-toolbox/shogun#3576]
The ppa gets successfully added. But after doing `sudo apt-get update` I get  [this](https://gist.github.com/hrushikesht/89ccf3983de3801570958defd811b076).
Do I have to compile from the source?

**Comment by vigsterkr** [comment]
@hrushikesht for the time being we are only generating trusty packages nightly. but i can setup a ppa to create xenial as well.. but till then you should compile from src.

**Comment by mitakas** [comment]
@vigsterkr Can you also setup the ppa to generate stable packages for xenial?

**Comment by karlnapf** [comment]
This will have to wait until after the xmas break ;)

**Comment by vigsterkr** [comment]
https://launchpad.net/~shogun-toolbox/+archive/ubuntu/nightly

now has xenial builds...
and https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable will contain the stable builds for xenial as well
