### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Thuva4** [shogun-toolbox/shogun#3583]
I can not able to install shogun toolbox in Linux mint 18 . I got following error message.

'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''.

**Comment by karlnapf** [comment]
Want to contribute one?
We might work on this early next year

**Comment by mohit9727** [comment]
@karlnapf 
I want to take up this issue, any guidelines/roadmap that I should follow?

**Comment by karlnapf** [comment]
Google is your friend here
@vigsterkr can also point to our current ppa configuation files

**Comment by vigsterkr** [comment]
duplicate of #3576
