### ISSUE TITLE
generating showroom page

### ISSUE THREAD

**Issue by markroxor** [shogun-toolbox/shogun#3587]
Hello all,
I know this is not the right place to ask this but I have tried the IRC already.
But can someone please tell me how Shogun generates their showroom page - http://www.shogun-toolbox.org/showroom with all the notebooks?
Thanks.

**Comment by karlnapf** [comment]
Check https://github.com/shogun-toolbox/shogun-web2

**Comment by karlnapf** [comment]
In paticular https://github.com/shogun-toolbox/shogun-web2/blob/master/templates/showroom.html and the main flask python script

**Comment by markroxor** [comment]
Thanks a lot :)
