### ISSUE TITLE
Fix outdated/broken links in Shogun Wiki

### ISSUE THREAD

**Issue by ivmarkp** [shogun-toolbox/shogun#3589]
Hi -- just getting started with Shogun and as I was going through the Shogun wiki, I came across some outdated links. A quick grep revealed the same issue in multiple places. I've updated the links and pushed the commit to this [repo](https://github.com/ivmarkp/Shogun-Wiki).

There seems to be no way for me to open a PR with the changes in wiki because apparently GitHub doesn't support pull requests for the wiki repository, only the main repository. However, please review the changes [here](https://github.com/ivmarkp/Shogun-Wiki/commits/master?author=ivmarkp).

Thanks,
Vivek Pal

**Comment by karlnapf** [comment]
Thanks for that!
