### ISSUE TITLE
Question on python interface after installing with homebrew

### ISSUE THREAD

**Issue by vikrantvm** [shogun-toolbox/shogun#3594]
I did a homebrew install using `brew install shogun-ml`
From here how can I link it to be able to use it in the python interpreter?
I am not able to use `import modshogun` 
The installation page does not state how to get the python interface running using the homebrew installation.

**Comment by karlnapf** [comment]
You need to expose the modshogun.py (either the one that was installed to your system or the one in the build folder) to your `PYTHONPATH` environmental variable. Then Python will be able to see them and you can `import modshogun`

**Comment by vikrantvm** [comment]
Yes I understand that and was able to use it by building from source. However it would be great if you could point out where to find modshogun.py when installed with homebrew. I was not able to locate it in the Cellar where homebrew installs the binaries. I would ideally like to use homebrew instead of building from source(takes up more space?). Thanks
