### ISSUE TITLE
Linking errors with ATLAS library

### ISSUE THREAD

**Issue by geektoni** [shogun-toolbox/shogun#3609]
Possible issue regarding some linking errors that appear when compiling shogun using ATLAS libraries.

Here the gists with the errors and the CMakeCache that does not work:
* **Errors** https://gist.github.com/geektoni/9ec823a1b05085f33f0c561053a705a9
* **CMakeCache** https://gist.github.com/geektoni/bcdbc9e15fc541d4430ee1eec7522357

The packages that I have installed through apt-get are:
* `liblapack3`, `liblapack-dev`
* `libblas3`, `libblas-common`, `libblas-dev`
* `libatlas3-base`, `libatlas-base-dev`, `libatlas-dev`   

The compilation succeeds when the ATLAS library is not installed and there are only liblapack and libblas. Namely, the compilation only succeeds when these packages are installed:
* `liblapack3`, `liblapack-dev`
* `libblas3`, `libblas-common`, `libblas-dev`

Here the working CMakeCache file:
* https://gist.github.com/geektoni/d2f2dfdbf1fd528e57f279fa1bcca15c

I am on Ubuntu 16.04 and I my gcc version is 4.9.3

**Comment by vigsterkr** [comment]
@geektoni i've just tried to reproduce this under 16.04. i have all those packages installed you've mentioned, but i cannot get the error.... could you do a `dpkg -l > package.list` and send it to me?

**Comment by geektoni** [comment]
@vigsterkr made a gist. If you prefer by email let me know.
https://gist.github.com/geektoni/295b9e165630428509cb78428a3228df

**Comment by vigsterkr** [comment]
@geektoni could you try to reproduce this with the latest develop?

**Comment by geektoni** [comment]
@vigsterkr it seems to work! I don't get any linker errors when compiling now.

**Comment by vigsterkr** [comment]
great! then i'm closing this
