### ISSUE TITLE
Stratified Cross Validation with Combined Kernels using Custom Kernels

### ISSUE THREAD

**Issue by github-ssi** [shogun-toolbox/shogun#3612]
Hello,

I use libshogun 5.1.0 with gcc 4.9.2 on Debian 8, and have the following issue: I am training a CMKLMulticlass machine using a CCombinedKernel. This combined kernel contains several linear/Gaussian kernels and one CCustomKernel which I am constructing from an SGMatrix.

I have 100 feature vectors. Hence the Kernel Matrix of my custom kernel is 100x100, and an initial training on the whole dataset (mkl->train()) works out fine.

Problem is, when I use a 2-fold CStratifiedCrossValidationSplitting, the cross->evaluate() call fails with the following error:

In file /home/berti/src/shogun/shogun/src/shogun/kernel/CombinedKernel.cpp line 169:
  Number of lhs-feature vectors (50) not match with number of rows (100) of custom kernel

I understand that my cross validation uses a set of 50 features per run. The other sub-kernels are implicitly initialized using init() to the size of 50x50, but my custom kernel doesn't have an init() method, or at least such a method is not called from CombinedKernel::init(). Hence the error.

Do you see any chance to use a combined kernel containing a custom kernel with CCrossValidation?

Thank you very much!

Best regards
Bert

**Comment by vigsterkr** [comment]
this should definitely work, we'll look into it!

**Comment by karlnapf** [comment]
Hi Bert,

can you post some code that lets us reproduce your error?
Thanks!

**Comment by github-ssi** [comment]
Hi karlnapf,

the following code just generates a combined kernel from one custom kernel (from SGMatrix) and one Gaussian kernel. MKL is used on 10 input vectors, 10 dimensions each. Training on the full dataset works, but cross validation with 2 folds produces the following error:

    [DEBUG] entering CKernel::remove_lhs_and_rhs
    [DEBUG] leaving CKernel::remove_lhs_and_rhs
    [DEBUG] entering CKernel::remove_lhs_and_rhs
    [DEBUG] leaving CKernel::remove_lhs_and_rhs
    [DEBUG] leaving CKernel::init(0x6b7f00, 0x6b7f00)
    [DEBUG] Starting for loop for kernels
    [DEBUG] Initializing 0x0x6ba250 - "CustomKernel"
    [DEBUG] entering CKernel::remove_lhs_and_rhs
    [DEBUG] leaving CKernel::remove_lhs_and_rhs
    [DEBUG] leaving CKernel::init(0x6b20b0, 0x6b20b0)
    [DEBUG] num_vec_lhs: 5 vs num_rows 10
    [DEBUG] num_vec_rhs: 5 vs num_cols 10
    [ERROR] In file /home/berti/src/shogun/shogun/src/shogun/kernel/CustomKernel.cpp line 158: assertion l->get_num_vectors()==kmatrix.num_rows failed in virtual bool shogun::CCustomKernel::init(shogun::CFeatures*, shogun::CFeatures*) file /home/berti/src/shogun/shogun/src/shogun/kernel/CustomKernel.cpp line 158
    terminate called after throwing an instance of 'shogun::ShogunException'
    Aborted

Here comes the code:

```/**
 * \file custom_mkl.cpp
 * \brief Multi-Class Multiple Kernel Learning example
 *
 * \author Bert Klauninger
 * \version 0.1.0
 * \cond changelog
 *    2017-01-17 - Created
 * \endcond
 *
 */


#include <iostream>
 
#include "shogun/base/init.h"
#include "shogun/io/CSVFile.h"
#include "shogun/io/SGIO.h"
#include "shogun/labels/MulticlassLabels.h"
#include "shogun/features/DenseFeatures.h"
#include "shogun/kernel/GaussianKernel.h"
#include "shogun/kernel/LinearKernel.h"
#include "shogun/kernel/PolyKernel.h"
#include "shogun/kernel/CombinedKernel.h"
#include "shogun/kernel/CustomKernel.h"
#include "shogun/classifier/mkl/MKLMulticlass.h"
#include "shogun/evaluation/StratifiedCrossValidationSplitting.h"
#include "shogun/evaluation/CrossValidation.h"
#include "shogun/evaluation/MulticlassAccuracy.h"

using namespace std;
using shogun::sg_io;
using shogun::MSG_MESSAGEONLY;


int main() {
	int nFolds = 2;
	int nRuns = 2;
	
	shogun::init_shogun_with_defaults();
	sg_io->set_loglevel(shogun::MSG_DEBUG);
	
	double vectors[100] = 
			{ 0.9, 0.1, 0.2, 0.3, 0.5, 0.1, 0.0, 0.4, 0.4, 0.7,
			  0.1, 0.5, 0.0, 0.2, 0.5, 0.0, 0.0, 0.6, 0.6, 0.3,
			  0.8, 0.2, 0.0, 0.7, 0.4, 0.9, 0.1, 0.7, 0.5, 0.4,
			  0.3, 0.3, 0.1, 0.6, 0.3, 0.9, 0.0, 0.9, 0.9, 0.6,
			  0.2, 0.1, 0.2, 0.3, 0.3, 0.1, 0.0, 0.1, 0.3, 0.8,
			  0.7, 0.3, 0.6, 0.4, 0.4, 0.3, 0.0, 0.2, 0.6, 0.2,
			  0.2, 0.1, 0.4, 0.9, 0.1, 0.9, 0.1, 0.8, 0.7, 0.4,
			  0.2, 0.5, 0.3, 0.1, 0.3, 0.8, 0.0, 0.9, 0.8, 0.1,
			  0.5, 0.1, 0.3, 0.0, 0.5, 0.2, 0.0, 0.1, 0.3, 0.6,
			  0.9, 0.7, 0.1, 0.1, 0.5, 0.1, 0.1, 0.3, 0.6, 0.8 };
			  
	double classes[10] = 
			{ 0.0, 1.0, 2.0, 0.0, 2.0, 1.0, 1.0, 0.0, 2.0, 0.0 };
	
	
	shogun::SGMatrix<double> m(vectors, 10, 10, false);
	shogun::CDenseFeatures<double> *features = new shogun::CDenseFeatures<double>(m);
	shogun::SGVector<double> l(classes, 10, false);
	shogun::CMulticlassLabels *labels = new shogun::CMulticlassLabels(l);
	
	/* Generate custom kernel (gram) matrix */
	shogun::SGMatrix<double> k(10, 10);
	
	/* Dot product */
	for (int i = 0; i < 10; ++i) {
		k(i, i) = 1.0;
		for (int j = i; j < 10; ++j) {
			double sim = 0.0;
			for (int k = 0; k < 10; ++k) {
				sim += m(k, i) * m(k, j);
			}
			sim /= 10;
			k(i, j) = sim;
			k(j, i) = sim;
		}
	}

	/* Build combined kernel */
	shogun::CCombinedFeatures *cfeats = new shogun::CCombinedFeatures();
	shogun::CCombinedKernel *cker = new shogun::CCombinedKernel();

	/* 1st kernel: custom */
	shogun::CCustomKernel *k0 = new shogun::CCustomKernel(k);
	cfeats->append_feature_obj(features);
	cker->append_kernel(k0);
	
	/* 2st kernel: gaussian */
	cfeats->append_feature_obj(features);
	cker->append_kernel(new shogun::CGaussianKernel(features, features, 1.2, 10));

	cker->init(cfeats, cfeats);
	
	cout << "cker: " << cker->get_num_vec_lhs() << " lhs vectors, " << cker->get_num_vec_rhs() << " rhs vectors" << endl;
	cout << "feats: " << features->get_num_vectors() << " vectors" << endl;
	cout << "labels: " << labels->get_num_labels() << " labels" << endl;

	/* Create MKL instance */
	shogun::CMKLMulticlass* mkl = new shogun::CMKLMulticlass(1.2, cker, labels);
	
	mkl->set_epsilon(0.00001);
	mkl->parallel->set_num_threads(4);
	mkl->set_mkl_epsilon(0.001);
	mkl->set_mkl_norm(1.5);
	
	/* Train to see weights */
	cout << "Training starts..." << endl;
	mkl->train();
	cout << "Training finished." << endl << endl;
	cker->get_subkernel_weights().display_vector("weights");

	shogun::CMulticlassAccuracy *eval_crit = new shogun::CMulticlassAccuracy();
	shogun::CStratifiedCrossValidationSplitting *splitting =
			new shogun::CStratifiedCrossValidationSplitting(labels, nFolds);
			
	cout << "splittig: " << splitting->get_num_subsets() << " subsets" << endl;
	
	shogun::CCrossValidation *cross = new shogun::CCrossValidation(mkl, cfeats, labels,
			splitting, eval_crit); /// <-- hier haut es ihn auf
	cross->set_autolock(false);
	
	cout << "Cross validation successful" << endl;
	
	cross->set_num_runs(nRuns);

	/* perform x-val and print result */
	shogun::CCrossValidationResult * result =
			(shogun::CCrossValidationResult *)cross->evaluate();
	SG_SPRINT("mean of %d %d-fold x-val runs: %f\n", nRuns, nFolds,
			result->mean);
	
	shogun::exit_shogun();
	return 0;
};
```

Thank you!

**Comment by karlnapf** [comment]
Thanks! Will check soon!
