### ISSUE TITLE
Deep RBM using shogun?

### ISSUE THREAD

**Issue by mohammadAdnan** [shogun-toolbox/shogun#3614]
Hello,

I want to apply deep Restricted Boltzmann Machines using shogun for doing recommendation? Is it possible?

Thanks

**Comment by vigsterkr** [comment]
@mohammadAdnan for these type of questions the mailing list is more appropriate as an issue (hence i'm closing this). currently there's no example showing how to use RBM for recommendation, but certainly you can use it... depends how you actually formulate your problem.
here's a paper that talks about how to use RBM for CF:
http://www.machinelearning.org/proceedings/icml2007/papers/407.pdf

**Comment by mohammadAdnan** [comment]
Thanks, vigsterkr i know about that paper, but i am asking about deep version of that paper (i wanna to do it), for doing recommendation. So can i do that using shogun?

**Comment by vigsterkr** [comment]
what do you exactly mean by deep version... but again subscribe to the mailing list and ask your question there.

**Comment by vigsterkr** [comment]
ah yeah i guess it could be... max it requires some patching in worst case :)

**Comment by mohammadAdnan** [comment]
Yeah i mean deep RBM for doing recommendation, i could also combine auto encoder for the same purpose? I am not quite sure which kind of library is suitable for my problem. I have limited time; 3 month!
