### ISSUE TITLE
Unable to build shogun

### ISSUE THREAD

**Issue by palashahuja** [shogun-toolbox/shogun#3624]
I was trying to do a clean vm _make_ of shogun, using this [Dockerfile](https://hub.docker.com/r/shogun/shogun-dev/~/dockerfile/)

The make procedure gets **stuck** after this line.
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/LDA.cpp.o

I also tried running shogun installation using the same docker file, but I am getting the same error.

**Comment by vigsterkr** [comment]
@palashahuja would really need more information than this... 
like are you building yourself the docker image?
or just launching a docker container based on shogun/shogun-dev and try to compile shogun in it?

**Comment by palashahuja** [comment]
@vigsterkr  I am actually running a docker container based on shogun/shogun-dev, cloned that repo and ran the installation process. The installation seems to stop at that particular line.

**Comment by vigsterkr** [comment]
ok so can you check your cpu load?

**Comment by palashahuja** [comment]
![cpu_load_usage](https://cloud.githubusercontent.com/assets/8504351/22960902/a836a88a-f367-11e6-8796-b533b9b0c225.PNG)

The _make_ process that is running with PID **5089** is taking the maximum cpu usage.

**Comment by palashahuja** [comment]
@vigsterkr, I am unable to understand why is this exactly happening ?

**Comment by karlnapf** [comment]
Closing as this seems to be unrelated to Shogun
