### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Nicolas99-9** [shogun-toolbox/shogun#3625]
I tried to install shogun in several ways : pip, ubuntu ppa and Compiling manually  but everything fail : 

pip install shogun-ml 
Collecting shogun-ml 
Could not find a version that satisfies the requirement shogun-ml (from versions: ) 
No matching distribution found for shogun-ml

-----------------------------------------------------------------------------------------------
_~$ sudo add-apt-repository ppa:shogun-toolbox/stable
 Builds of stable releases
 Plus d’info : https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable
Appuyez sur [ENTRÉE] pour continuer ou Ctrl-C pour annuler l’ajout

gpg: le porte-clefs « /tmp/tmp1nrgpb91/secring.gpg » a été créé
gpg: le porte-clefs « /tmp/tmp1nrgpb91/pubring.gpg » a été créé
gpg: demande de la clef E6BCAB3B sur le serveur hkp keyserver.ubuntu.com
gpg: /tmp/tmp1nrgpb91/trustdb.gpg : base de confiance créée
gpg: clef E6BCAB3B : clef publique « Launchpad PPA for Shogun - A Large Scale Machine Learning Toolbox » importée
gpg: Quantité totale traitée : 1
gpg:               importées : 1  (RSA: 1)
OK_

and then : 
update : 

_W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Impossible de récupérer http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found_

_$ sudo apt-get install libshogun17
E: Impossible to find the package libshogun17_

**Comment by vigsterkr** [comment]
@Nicolas99-9 xenial packages in ppa has been only added just recently and we have not released shogun since then. try the nightly ppa, it has the precompiled python package of shogun as well:
https://launchpad.net/~shogun-toolbox/+archive/ubuntu/nightly/

**Comment by Nicolas99-9** [comment]
now there is no more problem with the installation :  
nicolas~# apt-get install libshogun17Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libshogun17 is already the newest version (5.1.0+1SNAPSHOT201702130606).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 52 non mis à jour.

**but the python import doesn't work : 
ImportError: No module named sg**

**Comment by vigsterkr** [comment]
```import modshogun```

**Comment by vigsterkr** [comment]
and have you actually done:
```
apt-get install python-shogun
```
?

**Comment by Nicolas99-9** [comment]
yes I did : 
apt-get install python-shogun

import modshogun works but the code uses : 
from sg import sg
sg('loglevel', 'WARN')

**Comment by vigsterkr** [comment]
which code?

**Comment by vigsterkr** [comment]
should be
```
from modshogun import sg
````

here are some examples: http://shogun.ml/examples/nightly/index.html

**Comment by Nicolas99-9** [comment]
A code that I'm supposed to run  for an assignment => http://attributes.kyb.tuebingen.mpg.de/

**Comment by Nicolas99-9** [comment]
I tried  : from modshogun import sg
but :
ImportError: cannot import name sg

**Comment by vigsterkr** [comment]
mmm that `sg()` is quite old, but most of the code here should work if you replace `shogun` with `modshogun`:
http://attributes.kyb.tuebingen.mpg.de/new-attributes.py

**Comment by Nicolas99-9** [comment]
Thanks you, I'm going to try to run the code.

**Comment by vigsterkr** [comment]
have fun... let us know if you have any problems!

**Comment by Nicolas99-9** [comment]
labels_trn = Features.Labels(Lplatt_trn)

TypeError: Cannot create new instances of type 'modshogun.Labels'

What does this error means?

**Comment by Nicolas99-9** [comment]
Could you help me (again) ? =)
AttributeError: 'modshogun.LibSVM' object has no attribute 'classify'
prediction=s.classify().get_labels()

**Comment by vigsterkr** [comment]
@Nicolas99-9 here's an example how `LibSVM` works:
http://shogun.ml/examples/nightly/examples/binary_classifier/kernel_svm.html

but please check the examples here as well:
https://github.com/shogun-toolbox/shogun/tree/develop/examples/undocumented/python_modular

and of course here's the whole API documentation:
http://shogun.ml/api/latest/index.html
