### ISSUE TITLE
Surpress "unused variable" warnings in compiled meta examples

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3628]
I.e.

 * java
 * csharp
 * cpp (was done [here](https://github.com/shogun-toolbox/shogun/pull/3611))

This involves adding a flag to the compile command in the corresponding cmake file. Nice minor task to get used to the cmake meta example setup we have

**Comment by sorig** [comment]
I don't think this is actually an issue with java

**Comment by karlnapf** [comment]
Csharp?

**Comment by karlnapf** [comment]
Then I guess we are done! :) thanks!
