### ISSUE TITLE
Shogun error in compilation at 68%  What's wrong ?

### ISSUE THREAD

**Issue by ahmedmazari** [shogun-toolbox/shogun#3630]
In ubuntu 16.04  : 

cmake -DPythonModular=ON ../

make
then l get  :       
[ 67%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/PMurHash.c.o
[ 68%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/dSFMT/dSFMT.c.o
[ 68%] Building C object src/shogun/CMakeFiles/libshogun.dir/lib/external/SFMT/SFMT.c.o
[ 68%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
[ 68%] Built target libshogun
Scanning dependencies of target shogun
[ 68%] Linking CXX shared library libshogun.so
/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo1x_1o.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo1x_9x.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo_init.o): requires dynamic R_X86_64_PC32 reloc against '__stack_chk_fail' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(optimize.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_isinf' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(options.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(stop.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_isinf' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): requires dynamic R_X86_64_PC32 reloc against 'gettimeofday' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(direct_wrap.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(cdirect.o): requires dynamic R_X86_64_PC32 reloc against 'memcpy' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(praxis.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(plip.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(plis.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(pnet.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(pssubs.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(crs.o): requires dynamic R_X86_64_PC32 reloc against 'memcpy' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mlsl.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(ccsa_quadratic.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_count_constraints' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mma.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(cobyla.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_unscale' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(newuoa.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(nldrmd.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(sbplx.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(auglag.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(bobyqa.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_unscale' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(isres.o): requires dynamic R_X86_64_PC32 reloc against 'ceil' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(slsqp.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(esch.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_urand' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(deprecated.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_local_search_alg_deriv' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(qsort_r.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_qsort_r' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(redblack.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(rescale.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(sobolseq.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRect.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRserial.o): requires dynamic R_X86_64_PC32 reloc against 'direct_dirinfcn_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRsubrout.o): requires dynamic R_X86_64_PC32 reloc against 'direct_dirgetlevel_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mssubs.o): requires dynamic R_X86_64_PC32 reloc against 'luksan_mxudot__' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status
src/shogun/CMakeFiles/shogun.dir/build.make:1461: recipe for target 'src/shogun/libshogun.so.17.2' failed
make[2]: *** [src/shogun/libshogun.so.17.2] Error 1
CMakeFiles/Makefile2:192: recipe for target 'src/shogun/CMakeFiles/shogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/shogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by karlnapf** [comment]
* Can you please put this in a gist and delete the super long message?
 * Wat happens if you disable nlopt in cmake?
 * Can you link other applications against your system's nlopt?

**Comment by ahmedmazari** [comment]
cmake  nlopt=OFF   in that way ?

Can you link other applications against your system's nlopt?
actually it's the only error l get

**Comment by karlnapf** [comment]
the docs tell you `cmake -DENABLE_NLOPT=OFF`
`ccmake` is a good tool for such things

Did you actually try 3)?

**Comment by ahmedmazari** [comment]
l didn't understand what did you mean by  Can you link other applications against your system's nlopt?

**Comment by ahmedmazari** [comment]
when l tried everything from scratch l got this compilation error

```
  conflict with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /root/anaconda2/lib

  Some of these libraries may not be found correctly.


CMake Warning at examples/meta/cpp/CMakeLists.txt:16 (ADD_EXECUTABLE):
  Cannot generate a safe runtime search path for target
  feedforward_net_regression because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /root/anaconda2/lib

  Some of these libraries may not be found correctly.


CMake Warning at examples/meta/cpp/CMakeLists.txt:16 (ADD_EXECUTABLE):
  Cannot generate a safe runtime search path for target linear_svm because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /root/anaconda2/lib

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /home/anelmad/shogun/build
root@anelmad-Aspire-V3-372:/home/anelmad/shogun/build# make
[  1%] Generating version header
[  1%] Built target version
[  1%] Built target class_list
[ 67%] Built target libshogun
make[2]: *** No rule to make target '../third_party/libs/nlopt/libnlopt.a', needed by 'src/shogun/libshogun.so.17.2'.  Stop.
CMakeFiles/Makefile2:194: recipe for target 'src/shogun/CMakeFiles/shogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/shogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
