### ISSUE TITLE
How to import shogun in python ?

### ISSUE THREAD

**Issue by ahmedmazari** [shogun-toolbox/shogun#3631]
Hello,
after installing shogun correctly (cmake, make install ..)

l created a new file python file.py  where  l tried to import shogun as follow
`from shogun import * `
or
`from sg import * `

of 
`from modshogun import *`

it doesn't work

how can l import shogun package so  ?

**Comment by karlnapf** [comment]
import modshogun or 
from modshogun import *

See the examples and the readmes
