### ISSUE TITLE
error when I run "cmake .."

### ISSUE THREAD

**Issue by hao555sky** [shogun-toolbox/shogun#3640]
A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find Eigen3 (missing:  EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- Checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Could NOT find Ctags (missing:  CTAGS_EXECUTABLE) 
CMake Error at CMakeLists.txt:739 (message):
  Ctags required for meta examples.

-- Configuring incomplete, errors occurred!
See also "/home/hao/Documents/gsoc/shogun/shogun-shogun_5.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/hao/Documents/gsoc/shogun/shogun-shogun_5.0.0/build/CMakeFiles/CMakeError.log".

os: ubuntu 16.04
Is it the reason that wrong method of cmake?

**Comment by palashahuja** [comment]
@hao555sky, you need to install lapack or blas to make shogun work 
Try running this 
```
sudo apt-get install liblapack-dev libblas-dev
```
Or you could even consult this [Dockerfile](https://hub.docker.com/r/shogun/shogun-dev/~/dockerfile/)
in case you need help for installing shogun

**Comment by hao555sky** [comment]
Sorry for error again, same error.
I want to ask several questions:
* Should I `cd shogun` and run the cmd `git submodule update --init`
* what is the specific cmd about `cmake` when I `cd build`? I always think I use the `cmake` wrong.
Sorry again for these tedious quesions.

**Comment by karlnapf** [comment]
There are detailed instructions in the installation readme.

The error message says to install ctags (or disable meta examples)

Closing as the issues here are not related to Shogun or cmake itself.
If you have trouble using cmake and related, please consider using the precompiled ppa

**Comment by karlnapf** [comment]
I added a more informative error message in 1a3b9d71c2daf48818e4ce1466a83aca5735b07a
