### ISSUE TITLE
New Linalg library cannot compile with Eigen 3.3.x

### ISSUE THREAD

**Issue by OXPHOS** [shogun-toolbox/shogun#3644]
Eigen 3.3.x casts the sum of two boolean vectors/matrices from `bool` to `int`, and results in mixed type error in `linalg::sum(SGVector<bool> op1, SGVector<bool> op2, SGVector<bool> result)`. Though I am not sure whether it is intended or actually a bug.

For example, in method:
```
	void add_impl(SGVector<bool>& a, SGVector<bool>& b, SGVector<bool>& result)
	{
		typename SGVector<bool>::EigenVectorXtMap a_eig = a;
		typename SGVector<bool>::EigenVectorXtMap b_eig = b;
		typename SGVector<bool>::EigenVectorXtMap result_eig = result;
		auto sum = a_eig + b_eig;
		result_eig = sum;
        }
```
While  `a = b = [true, false, true, true]`, `sum` equals `[1, 0, 1, 1]` in `Eigen 3.2.x` but `[2, 0, 2, 2] `in `Eigen 3.3.x`, which cannot be assigned to vector `result` anymore.

There are two ways to solve the problem for now: 1). Warning the users about Eigen versions in `cmake`. 2). Disable `SGVector<bool>.add()`. The new `linalg` library currently supports several linear algebra operations on boolean data structures. However, I suspect it doesn't make too much sense.

EDIT: issue first observed in #3534

**Comment by vigsterkr** [comment]
@OXPHOS how about following up on this with eigen developers first? maybe it's a bug and then they'll fix it in upcoming eigen 3.3.x release. they are quite responsive :)

**Comment by OXPHOS** [comment]
@vigsterkr Doubt they'll be as responsive as you! :) Working on that.

**Comment by OXPHOS** [comment]
@vigsterkr @karlnapf Known for sure that `Vector<bool> + Vector<bool>` is gone in `Eigen` as stated [here](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=426)

**Comment by OXPHOS** [comment]
#3656
