### ISSUE TITLE
replace `new_sgserializable` with c++11 magic

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3645]
This way we can get rid of `class_list.cpp` hacks

It will involve changing the creation of empty `SGObject` instances in `SGObject::clone` and  `SGObject::load_serializable`, and some other places

This is a nice non-trivial entrance task for GSoC projects like the detox

**Comment by vigsterkr** [comment]
one could use c++11 feature for this:
http://en.cppreference.com/w/cpp/types#Runtime_type_identification

**Comment by dracarys09** [comment]
I would like to work on this... please assign this issue to me

**Comment by vigsterkr** [comment]
@dracarys09 just start working on it and send a pr....

**Comment by micmn** [comment]
Can you expand a bit on this? As I can't understand what you have in mind,
I mean: you want something like
`CSGObject* CSGObject::clone() { CSGObject* copy=new object of the same type of this; ... }` ?
But as far as I know this is not possibile even in c++11.

One alternative is to override `clone()` in every subclass of `SGObject`, but this isn't very practical i think. If you want to get rid of `class_list.cpp` using c++11 you could use `type_index` to create a map `type->obj_creation_func()` but you'll still need some factory or registering mechanism...

However...is there the need for `clone()` in `SGObject`? Isn't the copy ctor enough in most cases?
And if for some reason a class need `clone()` it could implement some abstract class which guarantees that is cloneable...(just my thoughts as I was trying to make sense of this issue :) )

**Comment by lisitsyn** [comment]
I agree this is not really easy (or even not possible) in C++ at all. 

I have two ideas in my mind:
* Change all definitions of **all** classes to something like `REGISTERED_CLASS ClassName` and then do the 'magic' there.
* Define `static const Meta<ClassName> ClassNameMeta;` next to **each** class.

Something like that should be done with plugins anyway. Classes are not first-class citizens so we have to hack.

**Comment by karlnapf** [comment]
Ok will close this one for now
