### ISSUE TITLE
LibSVM train() error. (with BinaryLabels)

### ISSUE THREAD

**Issue by mcavdar** [shogun-toolbox/shogun#3651]
I run this [file](https://drive.google.com/file/d/0BzzIxGxNPHK4SFBZT1J5c2RjQ0k/view?usp=sharing) and get the following error:

Traceback (most recent call last):
  File "./attributes.py", line 214, in <module>
    pred,prob,Ltst = train_attribute(attribute_id,C,split)
  File "./attributes.py", line 136, in train_attribute
    s.train()
SystemError: [ERROR] In file /build/shogun-B7ywaa/shogun-5.1.0+1SNAPSHOT201702170202/src/shogun/classifier/svm/LibSVM.cpp line 96: assertion kernel->get_num_vec_lhs()==problem.l failed in virtual bool shogun::CLibSVM::train_machine(shogun::CFeatures*) file /build/shogun-B7ywaa/shogun-5.1.0+1SNAPSHOT201702170202/src/shogun/classifier/svm/LibSVM.cpp line 96

Here's the line 96: 	ASSERT(kernel->get_num_vec_lhs()==problem.l)
"**kernel.get_num_vec_lhs()**" is equal 21866 but I didn't get what was the **problem.l** variable. According to code I printed **labels_trn.get_num_labels()** (equal 36). 

thanks in advance

**Comment by karlnapf** [comment]
The variable you asked about simply is assigned as `problem.l=m_labels->get_num_labels()`

So what is the output of
```
kernel.get_num_vec_lhs()
feats_trn.get_num_vectors()
```
?

**Comment by mcavdar** [comment]
Actually they are both equals 21866.

**Comment by clover978** [comment]
hello, I met the same problem when running the same script attribute.py. Did you solve it? Thanks for help~

**Comment by vigsterkr** [comment]
@clover978 could you provide the script itself as a [gist](http://gist.github.com) plz?

**Comment by clover978** [comment]
https://gist.github.com/clover978/48a34e08ebd60ee388ae8745023b42c7

This is the error massage:
Traceback (most recent call last):
  File "./new-attributes.py", line 227, in <module>
    pred,prob,Ltst = train_attribute(attribute_id,C,split)
  File "./new-attributes.py", line 119, in train_attribute
    labels_trn = Features.Labels(Lplatt_trn)
TypeError: Cannot create new instances of type 'modshogun.Labels'

Then I modify line 119 to `labels_trn = Features.BinaryLabels(Lplatt_trn)`(line 120)

Traceback (most recent call last):
  File "./new-attributes.py", line 228, in <module>
    pred,prob,Ltst = train_attribute(attribute_id,C,split)
  File "./new-attributes.py", line 144, in train_attribute
    s.train()
SystemError: [ERROR] In file /build/shogun-dH6q6j/shogun-6.0.0/src/shogun/classifier/svm/LibSVM.cpp line 106: assertion kernel->get_num_vec_lhs()==problem.l failed in 
virtual bool shogun::CLibSVM::train_machine(shogun::CFeatures*) file /build/shogun-dH6q6j/shogun-6.0.0/src/shogun/classifier/svm/LibSVM.cpp line 106

note that the Lplatt_trn is a 1*36 numpy.ndarray which contains only -1 and 1
You may not able to run it natively for lack of other data files

**Comment by vigsterkr** [comment]
@clover978 oh great! do you maybe have the data set available as well for sharing?

**Comment by vigsterkr** [comment]
is it from here http://attributes.kyb.tuebingen.mpg.de/ ?

**Comment by clover978** [comment]
Yes. it is.
Sorry. I have been busy with uploading the data files. And maybe it's because some network problems, the process is extremely slow so I didn't see your reply.
In additional, the old version of attribute.py uses namespace 'sg', you need to replace it with the new version which can be obtained at the same site.
