### ISSUE TITLE
No libshogun.so found after build, only libshogun.dylib

### ISSUE THREAD

**Issue by cullengao** [shogun-toolbox/shogun#3677]
Hi,

I was building shogun following the tutorials, however I cannot find libshogun.so as indicated in INTERFACE.md.

My procedures are like:
```
> make
> make install
```

and my `build/src/shogun` directory is something like:
```
> ls
CMakeFiles                ShogunTargets.cmake       lib                       shogun_export.h
Makefile                  base                      libshogun.18.0.dylib      tags
ShogunConfig.cmake        cmake_install.cmake       libshogun.18.dylib
ShogunConfigVersion.cmake io                        libshogun.dylib
```

Any thoughts? I'll really appreciate that.

**Comment by vigsterkr** [comment]
@cullengao i guess you are using osx... which is completely normal. .so is for linux.
