### ISSUE TITLE
LD_LIBRARY_PATH failed in finding .dylib with macOS 10.12

### ISSUE THREAD

**Issue by cullengao** [shogun-toolbox/shogun#3678]
Hi all,

I was recently building shogun down in my mac (with macOS 10.12).

When I ran this command
```
$ clang++ -std=c++11 path/to/native_example.cpp -o path/to/native_example -I/path/to/headers -lshogun
```
I encountered a problem when setting `LD_LIBRARY_PATH` failed in finding the linker (`-lshogun`)

I finally solved it by export `LIBRARY_PATH` instead referred to [here](http://stackoverflow.com/questions/13292261/ld-library-path-doesnt-seem-to-work).

Don't know why, but seems worth to report in case of future macOS users getting stuck for days like me.

See also #3677, which I really think should be mentioned in README.

**Comment by vigsterkr** [comment]
@cullengao this is very basic compiler flags. and i would rather suggest you to use `-L<path to the lib folder where you installed shogun>` instead of LIBRARY_PATH....

but anyhow if you feel that this is something that is missing there's the https://github.com/shogun-toolbox/docs repo and send in a PR

**Comment by vigsterkr** [comment]
and btw on mac there is no `LD_LIBRARY_PATH`... it is `DYLD_LIBRARY_PATH`

**Comment by cullengao** [comment]
@vigsterkr Thanks for being so swift to reply. To be honest, I used to work mostly on Python and rather new to compiler stuffs.

Glad you bring up `DYLD_LIBRARY_PATH`. I've actually tried but got no luck. Any thoughts? Would be happy to learn.

**Comment by vigsterkr** [comment]
@cullengao http://lmgtfy.com/?q=gcc+library+flags

**Comment by karlnapf** [comment]
I just added some clarifications, https://github.com/shogun-toolbox/docs/commit/619946795202190b35385888754325dca48e7a79
