### ISSUE TITLE
Headfile "shogun/lib/config.h" not exist

### ISSUE THREAD

**Issue by yangliangquanyoung** [shogun-toolbox/shogun#3681]
There is no  headfile "shogun/lib/config.h" , but there is "shogun/lib/config.h.in" ,are they equals,please?

**Comment by cullengao** [comment]
Hi yang,

I was encountering same problem which I successfully solved by using `find` tool in terminal. You may have a try before getting any short answers, 'cuz you may have similar path trouble otherwise.

Now, the short answer: `-I/build/src/`

**Comment by yangliangquanyoung** [comment]
@cullengao Thanks. I did that before like you said, but I can't find this file in 'shogun' project.

**Comment by vigsterkr** [comment]
@yangliangquanyoung `shogun/lib/config.h` is generated based on your system using `shogun/lib/config.h.in`. the config.h will be installed along with the rest of the headers of shogun to prefix location you've supplied

**Comment by cullengao** [comment]
@yangliangquanyoung So what is your cmake flags and would you share your making procedure?
