### ISSUE TITLE
Get rid of direct access of fields

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#3688]
Just like in #3674 we want to avoid accessing fields of classes directly. We should use get and set instead. This is the first step to start using [tags](https://github.com/shogun-toolbox/shogun/wiki/README_tags).

This involves a lot of code changes so this should not be done by one person in one pull request. A good pull request for this issue would change one class or one base class (like in #3674 again).

**Comment by karlnapf** [comment]
Entrance task for detox project for sure :)

**Comment by MikeLing** [comment]
Hi @lisitsyn and @karlnapf , I would like to work on this :)

**Comment by vigsterkr** [comment]
@MikeLing as previously, just start wokring and sending prs :)

**Comment by MikeLing** [comment]
#3698

**Comment by abhinavrai44** [comment]
#3734

**Comment by karlnapf** [comment]
First few down, but we need more (eventually all classes)

**Comment by karlnapf** [comment]
This is still an open issue: to make algorithms observable, algorithms should only modify their members using `put`

**Comment by karlnapf** [comment]
@lisitsyn I think we do not need this anymore, right?
