### ISSUE TITLE
statistical testing build error when USE_REF_COUNTING=OFF

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3713]
```
shogun/src/shogun/statistical_testing/internals/Block.cpp:51:16: error: ‘class shogun::CFeatures’ has no member named ‘ref_count’
  ASSERT(block->ref_count()==0);
```

Disabling ref counting results in a build error for the merged branch

**Comment by karlnapf** [comment]
Not sure if that was recently fixed, my build is a week old dev branch

**Comment by karlnapf** [comment]
More care is needed!

**Comment by karlnapf** [comment]
`/nfs/nhome/live/ucabhst/git/shogun/shogun_develop/shogun/src/shogun/statistical_testing/internals/DataManager.cpp:388`

**Comment by lambday** [comment]
@karlnapf we merged the fix yesterday :)

**Comment by karlnapf** [comment]
ok so I need to rebase. :)
