### ISSUE TITLE
Apply Cholesky methods in linalg library to Shogun

### ISSUE THREAD

**Issue by OXPHOS** [shogun-toolbox/shogun#3715]
We recently added [Cholesky matrix factorization method](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/LinalgNamespace.h#L362)  and [Cholesky solver](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/LinalgNamespace.h#L378) in Shogun linalg library using `Eigen3`, and now they need to be put into real use - 
By grepping "Cholesky" we can see that the methods are redundantly defined in many classes, and we would like them to be replaced by simply calling `linalg::cholesky_whatever`.

For eg.:
[KernelRidgeRegression](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/regression/KernelRidgeRegression.cpp#L58)
[LeastAngleRegression](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/LinalgNamespace.h#L362)
[statistics](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/Statistics.cpp#L664)
[VarDTCInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/VarDTCInferenceMethod.cpp#L167)
[SingleLaplaceInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/SingleLaplaceInferenceMethod.cpp#L373)
[SingleFITCLaplaceInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/SingleFITCLaplaceInferenceMethod.cpp#L415)
[MultiLaplaceInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp#L317)
[MatrixOperations](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/MatrixOperations.cpp#L81)
[FITCInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/FITCInferenceMethod.cpp#L167)
[ExactInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/ExactInferenceMethod.cpp#L191)
[EPInferenceMethod](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/gp/EPInferenceMethod.cpp#L354)
[LDA](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/classifier/LDA.cpp#L236)

**Comment by yorkerlin** [comment]
It seems that most of the listed methods are written by me.
@OXPHOS  
Are LDLT (https://eigen.tuxfamily.org/dox/classEigen_1_1LDLT.html) and LU solver available in Shogun now?

**Comment by OXPHOS** [comment]
@yorkerlin Nope..I can add them if they're in urgent need, otherwise they'll be considered as entrance tasks. BTW, it seems that ViennaCL doesn't support Cholesky decomposition now ([this issue](https://github.com/viennacl/viennacl-dev/issues/195)).

**Comment by OXPHOS** [comment]
ref #3108

**Comment by karlnapf** [comment]
Are they used in the GPL module? I guess not?

Also, I think one thing is missing is a low-rank update of the cholesky. Wanna add that and apply it to LARS @micmn ? (It is already there, just needs to be integrated in linalg)

**Comment by OXPHOS** [comment]
Nope not in GPL

**Comment by karlnapf** [comment]
Sorry, I meant GP (Gaussian Process)

**Comment by karlnapf** [comment]
As in: is the GP stuff using linalg already?
