### ISSUE TITLE
CARTree can't be imported from modshogun

### ISSUE THREAD

**Issue by sam0410** [shogun-toolbox/shogun#3737]
I was trying to install shogun in ubuntu from [http://www.shogun-toolbox.org/install](http://www.shogun-toolbox.org/install).
I did
`$ sudo add-apt-repository ppa:shogun-toolbox/stable`
`$ sudo apt-get update`
and it was fine.
But when I do 
`$ sudo apt-get install libshogun17`
it says
`Unable to locate package libshogun17`
but when I do 
`Unable to locate package libshogun16` - it works but  if I try
`from modshogun import CARTree`
it says `cannot import name CARTree`
what do I do?

**Comment by vigsterkr** [comment]
@sam0410 i reckon your apt is still not trying to fetch from the ppa, see the list of packages of the stable ppa:
https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable/+packages

libshogun17 is there. try using the `-t` flag for `apt-get` command and specify the repo you wanna use.

mm i think CARTree was not yet part of libshogun16

**Comment by vigsterkr** [comment]
@sam0410 or you are not using an amd64 or i386 architecture?

**Comment by sam0410** [comment]
Hi @vigsterkr !
I am using amd64
I get this when I do `sudo apt-get update`
samikshya@samikshya:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial InRelease           
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease                             
Ign:3 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release
Hit:4 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Err:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
samikshya@samikshya:~$ gksu nautilus

(nautilus:10539): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
samikshya@samikshya:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial InRelease           
Ign:2 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release             
Get:3 http://in.archive.ubuntu.com/ubuntu yakkety InRelease [247 kB]
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Get:11 http://in.archive.ubuntu.com/ubuntu yakkety-updates InRelease [102 kB]                                                                 
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Get:12 http://in.archive.ubuntu.com/ubuntu yakkety/main Sources [903 kB]                                                                      
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Get:13 http://in.archive.ubuntu.com/ubuntu yakkety/main amd64 Packages [1,222 kB]                                                             
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Get:14 http://in.archive.ubuntu.com/ubuntu yakkety/main i386 Packages [1,218 kB]                                                              
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Err:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
  404  Not Found
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Get:15 http://in.archive.ubuntu.com/ubuntu yakkety/main Translation-en [582 kB]                                                               
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Get:16 http://in.archive.ubuntu.com/ubuntu yakkety/main amd64 DEP-11 Metadata [654 kB]                                                        
Get:17 http://in.archive.ubuntu.com/ubuntu yakkety/main DEP-11 64x64 Icons [368 kB]                                                           
Get:18 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main Sources [86.0 kB]                                                             
Get:19 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 Packages [224 kB]                                                       
Get:20 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main i386 Packages [220 kB]                                                        
Get:21 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main Translation-en [99.8 kB]                                                      
Get:22 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 DEP-11 Metadata [146 kB]                                                
Get:23 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main DEP-11 64x64 Icons [86.8 kB]                                                  
Fetched 6,159 kB in 1min 17s (79.9 kB/s)                                                                                                      
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Can you please tell me what to do next?

**Comment by vigsterkr** [comment]
Uuuuhoooh! I just realised, that the xenial ppa support i've added after 5.0.0 release so currently there's only trusty packages in the stable ppa. Lemme check if i could generate them now (xenial packages)

**Comment by sam0410** [comment]
Hi @vigsterkr !
I am using amd64.
I did sudo apt-get update
and I got the following issues-

samikshya@samikshya:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial InRelease           
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease                             
Ign:3 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release
Hit:4 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Err:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
samikshya@samikshya:~$ gksu nautilus

(nautilus:10539): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
samikshya@samikshya:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial InRelease           
Ign:2 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release             
Get:3 http://in.archive.ubuntu.com/ubuntu yakkety InRelease [247 kB]
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Get:11 http://in.archive.ubuntu.com/ubuntu yakkety-updates InRelease [102 kB]                                                                 
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Get:12 http://in.archive.ubuntu.com/ubuntu yakkety/main Sources [903 kB]                                                                      
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Get:13 http://in.archive.ubuntu.com/ubuntu yakkety/main amd64 Packages [1,222 kB]                                                             
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
Get:14 http://in.archive.ubuntu.com/ubuntu yakkety/main i386 Packages [1,218 kB]                                                              
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Err:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                                        
  404  Not Found
Ign:5 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                         
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                          
Ign:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                                     
Get:15 http://in.archive.ubuntu.com/ubuntu yakkety/main Translation-en [582 kB]                                                               
Ign:8 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                                        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                                 
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                                   
Get:16 http://in.archive.ubuntu.com/ubuntu yakkety/main amd64 DEP-11 Metadata [654 kB]                                                        
Get:17 http://in.archive.ubuntu.com/ubuntu yakkety/main DEP-11 64x64 Icons [368 kB]                                                           
Get:18 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main Sources [86.0 kB]                                                             
Get:19 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 Packages [224 kB]                                                       
Get:20 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main i386 Packages [220 kB]                                                        
Get:21 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main Translation-en [99.8 kB]                                                      
Get:22 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 DEP-11 Metadata [146 kB]                                                
Get:23 http://in.archive.ubuntu.com/ubuntu yakkety-updates/main DEP-11 64x64 Icons [86.8 kB]                                                  
Fetched 6,159 kB in 1min 17s (79.9 kB/s)                                                                                                      
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.


Can you please tell me what I should do next?

**Comment by sam0410** [comment]
@vigsterkr ! Thanks!

**Comment by vigsterkr** [comment]
@sam0410 so i've tried, but unfortunately because of some stupid reasons i wont' be able to create you the stable xenial package... but dont worry, just use the nightly package, it is actually much better (has many fixes) than 5.0.0 :)

**Comment by sam0410** [comment]
Thanks @vigsterkr . But I think, this should be included in the documentation as well.

**Comment by vigsterkr** [comment]
@sam0410 we are more than happy to have contributions regarding fine-tuning our library :)
