### ISSUE TITLE
Create data generator class for unit testing

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3740]
* Unit tests currently all set up their own data
 * result: redundant code, larger binaries, etc
 * Task: Create a class in unit test that can generate data for all kinds of tests we are using
 * Then, deploy the class in unit tests, i.e. call its methods rather than generating by hand everytime.

See https://github.com/shogun-toolbox/shogun/pull/3719#discussion_r107030062

**Comment by shreab373** [comment]
hi! can i try this?

**Comment by MikeLing** [comment]
https://github.com/shogun-toolbox/shogun/pull/3812, I will take this as a part of GSoC ;)
