### ISSUE TITLE
How should shogun-data be stored for using examples?

### ISSUE THREAD

**Issue by minxuancao** [shogun-toolbox/shogun#3746]
Hello! I installed shogun on my computer and I'm trying to run a python example. It reports that regression_1d_linear_features_train.dat is missing. So I downloaded the data. Then I realized that there is an alias named data in build/examples/meta/. I'm not sure how to deal with this. I can't create a new dir named data or add data files to the alias.

**Comment by karlnapf** [comment]
Not sure how you installed, but
```
git submodule init
git submodule update
```
does it when you are using git.
