### ISSUE TITLE
error install python-shogun on server

### ISSUE THREAD

**Issue by Erichliu00** [shogun-toolbox/shogun#3766]
I am going to use shogun in an experiment written by tensorflow running on a  ubuntu server, I followed the install instructions but still get error when try to install python-shogun.

> Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-shogun

Any suggestion? Thanks.

**Comment by karlnapf** [comment]
Without the exact steps you did and system specs, we cannot help you
