### ISSUE TITLE
Drop use_reference_counting option

### ISSUE THREAD

**Issue by iglesias** [shogun-toolbox/shogun#3788]
Why to remove it?
* Some tests break when it is off.
* We have to guard the code any time we need to call `ref_count`, `ref`, or `unref` in a  csgobject directly.

Why to keep it?
* The only reason I can think of why this option exists is to improve "efficiency" (and introducing leaks).
* Other?

ps. bugfixing label because this will fix the tests that are failing nightly_none.

**Comment by karlnapf** [comment]
Remove!
As well as all other switches of nightly none....

**Comment by karlnapf** [comment]
Done in 3560969
