### ISSUE TITLE
fix linalg warnings

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3791]
There is plenty, e.g. at
http://buildbot.shogun-toolbox.org/builders/nightly_bsd_license/builds/8/steps/compile/logs/warnings%20%281823%29

**Comment by OXPHOS** [comment]
@karlnapf So one of the warnings complained about comparing `unsigned int` to `int` in a for loop:
         `        for (index_t i = 0; i < a.size(); ++i)`

And both `SGVector` and `SGMatrix` can be taken as parameter (`a`), their `size()` actually return different type. `SGMatrix` returns `uint64_t` and `SGVector` returns `int32_t`. Should we try to stick to one type?

**Comment by karlnapf** [comment]
I think auto will do the magic for you. Or even `range`
@lisitsyn

**Comment by OXPHOS** [comment]
I think to use `auto`/`range`-based for loop, we need a `vector`, or something else we can iterate..I don't see how it will work with `size()`.

**Comment by lisitsyn** [comment]
You may implement `begin() { return 0; }` and `end() { return size(); }`

**Comment by OXPHOS** [comment]
I used `decltype` instead. The issue should be fixed. I'll keep an eye on the builder.
