### ISSUE TITLE
Problem of multiple kernel learning 

### ISSUE THREAD

**Issue by ghzhaole** [shogun-toolbox/shogun#3811]
**I run multiple kernel learning on the shogun cloud，but the error:**

`SystemErrorTraceback (most recent call last)
<ipython-input-10-bc7ef3a27832> in <module>()
     18 
     19 #train to get weights
---> 20 mkl.train()
     21 
     22 w=kernel.get_subkernel_weights()

SystemError: [ERROR] In file /tmp/buildd/shogun-5.0.0+1SNAPSHOT201704240735/src/shogun/classifier/mkl/MKL.cpp line 439: Interleaved MKL optimization is currently only supported with SVMlight`

What should I do ?

**Comment by romainviard** [comment]
Please did you find a solution to this issue. I have the same on shogun6.0.0 ...What I understand is : the build version is compiled using libSVM but I need one buold using SVMlight to use Interleaved MKL...is there one already build because when I built it...it crash at execution....
If someone could give a hand, thanks in advance...

**Comment by ghzhaole** [comment]
I'm sorry, I did not solve the problem. I guess the problem should be caused by Libsvm's authorization. So I found the historical version of Shogun, here is the link :ftp://shogun-toolbox.org/shogun/releases, which 1.1 and 3.2 version I can use. If you have a problem with the installation, you can ask me again.

**Comment by ghzhaole** [comment]
And Why can not I reply directly to the mail?

**Comment by romainviard** [comment]
Ok thanks a lot for the link...I will probably test old version but that does not seem to be a solution for the future ....Maybe have a look elsewhere ? Are you pleased of obtained result ?

**Comment by vigsterkr** [comment]
In order to be able to use MKL you need to have svmlight, which we are not allowed to distribute hence for MKL you need to compile shogun yourself from source. That should solve your problem.

**Comment by romainviard** [comment]
Thats works !!! I m able to use the notebook python MKL.ipynb with the shogun 3.2....YEAH!!! 
Thanks to you.

**Comment by vigsterkr** [comment]
@romainviard you should be able to use with shogun 6.0.0 as well... just make sure you compile shogun yourself...

**Comment by romainviard** [comment]
Thanks for the advice...I tried with shogun 6.0.0 I succeeded to compile and install but the python kernel crash when I try the "import"..I think something went wrong in my process...I have to restart from scratch...

**Comment by vigsterkr** [comment]
@romainviard what does crash mean exactly? could you give some debug output?

**Comment by romainviard** [comment]
No problem I (re)start the compilation from scratch (without my modification) and thats works perfectly ...thanks again...

**Comment by songxujing** [comment]
@ghzhaole 

I've encountered the same error with you now, and manually compiled shogun6.0, but I can't use SVMLight, so what if I want to use it? I need your help！
Thank you very much !

**Comment by zym-wade** [comment]
> @ghzhaole
> I've encountered the same error with you now, and manually compiled shogun6.0, but I can't use SVMLight, so what if I want to use it? I need your help！
> Thank you very much !

you can restart the compilation from scratch
