### ISSUE TITLE
The problem about install shogun 2.0.0

### ISSUE THREAD

**Issue by xxnyufengzhe** [shogun-toolbox/shogun#3822]
I installed Shogun 2.0.0 on the ubuntu14.04 through the Matlab interface，

I have excuted ：./configure --interfaces=matlab_static
                 and ：make
The two step is ok
When I execute: make install
The following error occurred:
Root@xxn-K84HR:/home/xxn/shogun-2.0.0/src# make install

Make -C Shogun install

Make[1]: entering directory `/home/xxn/shogun-2.0.0/src/shogun'

Install -d -m755 //usr/local/lib

Install -d -m755 "//usr/local/include/shogun""

Install -m755 libshogun.so.12.0 //usr/local/lib

Install -m755 libshogun.a //usr/local/lib

Find / -mindepth 1 -type D (-path'*.svn*'-o \ \ \ \!

-name'*interface*'-o -name'*guilib*' -o -name'*doxygen*'\ \ \ \)

-exec install -d -m755 "//usr/local/include/shogun/" \\{\\} \ \;

Find / -mindepth 1 -type D (-path'*.svn*'-o -name! \ \'*wrap*' \ \ -o

-name'*interface*'-o -name'*guilib*' -o -name'*doxygen*'\ \ \ \)

-exec sh -c install -m644 {}/*.h //usr/local/include/shogun/{} \ \ ";

Install: cannot obtain the file status of './transfer/*.h' (STAT): no file or directory

Install: cannot obtain the file status of './optimization/*.h' (STAT): no file or directory

RM -f //usr/local/lib/libshogun.so //usr/local/lib/libshogun.so.12

CD ln -s libshogun.so.12.0 libshogun.so (//usr/local/lib & &; \ \

LN, -s, libshogun.so.12.0, libshogun.so.12)

Ldconfig

Make[1]: leaving directory `/home/xxn/shogun-2.0.0/src/shogun'

Make -C interfaces/matlab_static install-matlab_static and true

Make[1]: entering directory `/home/xxn/shogun-2.0.0/src/interfaces/matlab_static'

The, MATLAB, interface, needs, to, be, installed

Using a different mechanism:

Just, copy, the, sg.mex*, to, a, <dir>, of, choice, your

And addpath <dir>

Make[1]: leaving directory `/home/xxn/shogun-2.0.0/src/interfaces/matlab_static'

Root@xxn-K84HR:/home/xxn/shogun-2.0.0/src#

what should i do??thanks

**Comment by karlnapf** [comment]
Very sorry but we cannot really support this old version anymore, lack of manpower. I suggest to use the octave interface for the latest build. We will try to get the new Matlab bindings working at some point this year
