### ISSUE TITLE
The err about python interface

### ISSUE THREAD

**Issue by xxnyufengzhe** [shogun-toolbox/shogun#3825]
I installed Shogun on the ubuntu16.04 through the python interface，
When I execute: cmake -DPythonModular=ON ..
The following error occurred:
root@xxn-K84HR:/shogun/build# cmake -DPythonModular=ON ..-- Found CCache: /usr/bin/ccache  
-- Using system's malloc
-- dir='/shogun/src'
-- dir='/shogun/build/src'
-- dir='/shogun/src/gpl'
-- Spinlock support found
CMake Warning at src/shogun/CMakeLists.txt:259 (MESSAGE):
  The system Eigen3 version 3.2.92 contains a lot of bugs, which could cause
  some models failing!

-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OpenCL_INCLUDE_DIRS OpenCL_LIBRARIES) (Required is at least version "1.5.0")
-- Eigen3 set as default LINALG_DEFAULT_BACKEND
-- Eigen3 set as default LINALG_LINEAR_SOLVER_LIB
-- Eigen3 set as default LINALG_EIGENSOLVER_LIB
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Could NOT find JSON (missing:  JSON_INCLUDE_DIR JSON_LIBRARY) (Required is at least version "0.11")
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Linker: GNU gold
-- Could NOT find Ctags (missing:  CTAGS_EXECUTABLE) 
CMake Warning at cmake/FindPLY.cmake:24 (message):
  ply import failure:

Call Stack (most recent call first):
  examples/meta/CMakeLists.txt:4 (FIND_PACKAGE)

CMake Error at examples/meta/CMakeLists.txt:6 (message):
  Python module ply required for meta examples.  Install or set
  BUILD_META_EXAMPLES=OFF

-- Configuring incomplete, errors occurred!
See also "/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/shogun/build/CMakeFiles/CMakeError.log".
root@xxn-K84HR:/shogun/build# 

what should i do??thanks

**Comment by MikeLing** [comment]
@xxnyufengzhe Hi, thank you for your report this. So, from the error message, I believe you missing some necessary package for shogun compiling, etc Ctags. Try to install ctage and try it again? :)

**Comment by karlnapf** [comment]
I cite the error message:
```Python module ply required for meta examples. Install or set
BUILD_META_EXAMPLES=OFF```
