### ISSUE TITLE
How can we get the data

### ISSUE THREAD

**Issue by xxnyufengzhe** [shogun-toolbox/shogun#3839]
I have completed the installation of the Shogun Python interface, when i run ：python linear_ridge_regression.py
It is display：
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "/usr/local/share/shogun/examples/python/regression/linear_ridge_regression.py", line 8, in <module>
    f_feats_train = CSVFile("../../data/regression_1d_linear_features_train.dat")
SystemError: [1;31m[ERROR][0m In file /home/xxn/5.1.0.git/src/shogun/io/File.cpp line 71: Error opening file '../../data/regression_1d_linear_features_train.dat'

>>> 
Is that because I didn't generate the data set? How should I generate a data set?
Thanks！

**Comment by vigsterkr** [comment]
@xxnyufengzhe please read the manual carefully....
if you want data repository then you should clone it:
`git submodule update --init`
