### ISSUE TITLE
how can i fusion of two features by two different kernel in shogun??

### ISSUE THREAD

**Issue by xxnyufengzhe** [shogun-toolbox/shogun#3841]
I want to classification for  3 types objects (sample 100, sample 100),  now i extract 2 types features for each object, but their dimension  are different, the first type feature is 16 dimensional, second type features are 128 dimensional, so now the data is two matrix 16 * 300   and  128 * 300, how can i Fusion of the two feature by multi kernel on shogun,  Is there such an example in the Shogun toolbox? （python code）
thanks！

**Comment by karlnapf** [comment]
Check the examples and notebook on multiple kernel learning,
http://www.shogun-toolbox.org/examples/latest/examples/regression/multiple_kernel_learning.html
http://www.shogun-toolbox.org/notebook/latest/MKL.html
