### ISSUE TITLE
Out of memory error caused by linalg with vs2017 

### ISSUE THREAD

**Issue by OXPHOS** [shogun-toolbox/shogun#3844]
The linalg headers are causing `C1060: out of heap space` error when compiling with VS2017 on Appveyor consistently now. (Traced back to [2 months ago](https://ci.appveyor.com/project/vigsterkr/shogun/build/4.2.604)).

The closest solution I found [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1060) suggested that [`/Zmfactor`](https://docs.microsoft.com/en-us/cpp/build/reference/zm-specify-precompiled-header-memory-allocation-limit) option can be added to limit the pre-allocated memory. 

The way I tried that I felt should work is (but I am not completely sure) modifying `CMakeLists`: 
```C++
IF(MSVC)
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm1 ")
ELSE()
	SET(COMPILER_WARNINGS "-Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated")
ENDIF()
```
`Zm1` is taken as a valid option by VS2017 but I still got `C1060` error. So I have no clue how to fix it unless we refactor the macro structures.

Based on the assumption that the problem is caused by the numerous header in `linalg` lib.

**Comment by karlnapf** [comment]
@vigsterkr ?

**Comment by vigsterkr** [comment]
140a8eb77cfcd523711274789d4e5d6b5f30bd52 is hopefully fixing this... let's see couple of builds. but basically disabled VS2017 for the time being (as it takes way too much time to run one job) & disabled parallel build, this way hopefully there's more memory left for building the given source file.

**Comment by vigsterkr** [comment]
feel free to reopen if you start to see this again ;)

**Comment by vigsterkr** [comment]
💃 did not help:
https://ci.appveyor.com/project/vigsterkr/shogun/build/952#L3499

**Comment by vigsterkr** [comment]
ok this should be done as @micmn divided up the files....
