### ISSUE TITLE
Pickle on a BinaryLabels object does not save the values parameter 

### ISSUE THREAD

**Issue by olinguyen** [shogun-toolbox/shogun#3849]
When using pickle to save a `BinaryLabels` object, the `values` field from `get_values()`  does not get saved and becomes null when the object is loaded using pickle. The `labels` are saved properly, but not the `values` parameter. 

```
import pickle
import numpy as np
from modshogun import BinaryLabels

y = np.ones(10)
y = BinaryLabels(y)

print("Binary labels values BEFORE pickling the object")
print(y.get_values())

with open('labels.pkl', 'wb') as output:
    pickle.dump(y, output, pickle.HIGHEST_PROTOCOL)
    
with open('./labels.pkl', 'rb') as f:
    data = pickle.load(f)

print("Binary labels values AFTER pickling the object")
#print(data.get_labels())
print(data.get_values())
```

The output is the following:

> Binary labels values BEFORE pickling the object
> [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
> Binary labels values AFTER loading the pickled object
> []

**Comment by karlnapf** [comment]
The solution is to add a line like
```SG_ADD(m_current_values, ...```
to `CLabels::init()`

Wanna go ahead with this @olinguyen ?

**Comment by MikeLing** [comment]
Hi @karlnapf and @olinguyen, I create a pr in  https://github.com/shogun-toolbox/shogun/pull/3857. And the things has been fixed like:

>
>
>MacBook-Pro-2:build mikeling$ python test.python 
>Binary labels values BEFORE pickling the object
>[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
>Binary labels values AFTER pickling the object
>[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
>
>

**Comment by karlnapf** [comment]
Nice!

**Comment by vigsterkr** [comment]
it can be closed it's fixed and it's in develop branch
