### ISSUE TITLE
CDynamicArray unit tests are leaking

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3862]
check http://buildbot.shogun-toolbox.org/memcheck/20170623-0120.html for details

**Comment by vigsterkr** [comment]
@MikeLing

**Comment by MikeLing** [comment]
https://github.com/shogun-toolbox/shogun/pull/3876 And here is the output of valgrind

mikeling@mikeling-QiTianM6500-N000:~/shogun/build$ valgrind --leak-check=full --show-leak-kinds=all  ./bin/shogun-unit-test --gtest_filter=CDynamicArrayTest*
==8548== Memcheck, a memory error detector
==8548== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==8548== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==8548== Command: ./bin/shogun-unit-test --gtest_filter=CDynamicArrayTest*
==8548== 
Note: Google Test filter = CDynamicArrayTest*
[==========] Running 8 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from CDynamicArrayTest/0, where TypeParam = int
[ RUN      ] CDynamicArrayTest/0.default_array_ctor
[       OK ] CDynamicArrayTest/0.default_array_ctor (10 ms)
[ RUN      ] CDynamicArrayTest/0.custom_array_ctor
[       OK ] CDynamicArrayTest/0.custom_array_ctor (2 ms)
[ RUN      ] CDynamicArrayTest/0.resize_array
[       OK ] CDynamicArrayTest/0.resize_array (3 ms)
[ RUN      ] CDynamicArrayTest/0.save_serializable
[       OK ] CDynamicArrayTest/0.save_serializable (67 ms)
[----------] 4 tests from CDynamicArrayTest/0 (88 ms total)

[----------] 4 tests from CDynamicArrayTest/1, where TypeParam = bool
[ RUN      ] CDynamicArrayTest/1.default_array_ctor
[       OK ] CDynamicArrayTest/1.default_array_ctor (3 ms)
[ RUN      ] CDynamicArrayTest/1.custom_array_ctor
[       OK ] CDynamicArrayTest/1.custom_array_ctor (2 ms)
[ RUN      ] CDynamicArrayTest/1.resize_array
[       OK ] CDynamicArrayTest/1.resize_array (2 ms)
[ RUN      ] CDynamicArrayTest/1.save_serializable
[       OK ] CDynamicArrayTest/1.save_serializable (9 ms)
[----------] 4 tests from CDynamicArrayTest/1 (16 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 2 test cases ran. (238 ms total)
[  PASSED  ] 8 tests.
==8548== 
==8548== HEAP SUMMARY:
==8548==     in use at exit: 244 bytes in 4 blocks
==8548==   total heap usage: 59,888 allocs, 59,884 frees, 3,410,885 bytes allocated
==8548== 
==8548== 4 bytes in 1 blocks are still reachable in loss record 1 of 4
==8548==    at 0x4C2E19F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8548==    by 0x800D0BD: shogun::Parallel::Parallel() (Parallel.cpp:36)
==8548==    by 0x8025858: shogun::init_shogun(void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(bool&, bool&)) (init.cpp:65)
==8548==    by 0x8025B27: shogun::init_shogun_with_defaults() (init.cpp:103)
==8548==    by 0xFFD2E5: main (main_unittest.cc:81)
==8548== 
==8548== 8 bytes in 1 blocks are still reachable in loss record 2 of 4
==8548==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8548==    by 0xA16D7E8: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0xA17D107: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0xA16BDD5: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0x40109C9: call_init.part.0 (dl-init.c:72)
==8548==    by 0x4010ADA: call_init (dl-init.c:30)
==8548==    by 0x4010ADA: _dl_init (dl-init.c:120)
==8548==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==8548==    by 0x1: ???
==8548==    by 0xFFEFFFF72: ???
==8548==    by 0xFFEFFFF89: ???
==8548== 
==8548== 24 bytes in 1 blocks are still reachable in loss record 3 of 4
==8548==    at 0x4C2E19F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8548==    by 0x802584D: shogun::init_shogun(void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(bool&, bool&)) (init.cpp:65)
==8548==    by 0x8025B27: shogun::init_shogun_with_defaults() (init.cpp:103)
==8548==    by 0xFFD2E5: main (main_unittest.cc:81)
==8548== 
==8548== 208 bytes in 1 blocks are still reachable in loss record 4 of 4
==8548==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8548==    by 0xA16D7E8: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0xA17C51A: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0xA16DA9C: omp_set_dynamic (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==8548==    by 0x800D0DF: shogun::Parallel::Parallel() (Parallel.cpp:38)
==8548==    by 0x8025858: shogun::init_shogun(void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(_IO_FILE*, char const*), void (*)(bool&, bool&)) (init.cpp:65)
==8548==    by 0x8025B27: shogun::init_shogun_with_defaults() (init.cpp:103)
==8548==    by 0xFFD2E5: main (main_unittest.cc:81)
==8548== 
==8548== LEAK SUMMARY:
==8548==    definitely lost: 0 bytes in 0 blocks
==8548==    indirectly lost: 0 bytes in 0 blocks
==8548==      possibly lost: 0 bytes in 0 blocks
==8548==    still reachable: 244 bytes in 4 blocks
==8548==         suppressed: 0 bytes in 0 blocks
==8548== 
==8548== For counts of detected and suppressed errors, rerun with: -v
==8548== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
