### ISSUE TITLE
Multiple Kernel Learning example problem

### ISSUE THREAD

**Issue by SanyuanZZ** [shogun-toolbox/shogun#3879]
Hello, I  study MKL recently, and do MKL example('http://www.shogun-toolbox.org/examples/latest/examples/regression/multiple_kernel_learning.html'). I use python in Unbuntu, install shogun by "sudo apt-get install python-shogun". However, I can't do "binary_svm_solver = SVRLight()".  I can't find SVRLight in my python, what should I do?  Can I use LIBSVR to replace?

**Comment by vigsterkr** [comment]
@SanyuanZZ the problem is that SVRLight depends on SVMLight that we are not allowed to distribute hence it's not in the python package. if you can compile shogun from source you can use svmlight hence MKL

**Comment by Galaxy-Fish** [comment]
I compile shogun from source,
but  when i do MKL example,
NameError: name 'SVRLight' is not defined

**Comment by karlnapf** [comment]
Run cmake with -DUSE_SVMLIGHT=on

**Comment by Galaxy-Fish** [comment]
i did it ,but how about this

Traceback (most recent call last):
  File "python.py", line 7, in <module>
    from shogun import *
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 32, in <module>
    _shogun = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 28, in swig_import_helper
    _mod = imp.load_module('_shogun', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/_shogun.so: undefined symbol: _ZN6shogun12CDotFeatures7get_covEb

**Comment by songxujing** [comment]
@Galaxy-Fish 
I have encountered the same problem with you now. How did you solve it?

**Comment by songxujing** [comment]
@vigsterkr 

Traceback (most recent call last):
File "python.py", line 7, in 
from shogun import *
File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 32, in 
_shogun = swig_import_helper()
File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 28, in swig_import_helper
_mod = imp.load_module('_shogun', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/_shogun.so: undefined symbol: _ZN6shogun12CDotFeatures7get_covEb

How to solve it ?
Thank you very much !
