### ISSUE TITLE
FastICA

### ISSUE THREAD

**Issue by arjunmenon** [shogun-toolbox/shogun#3881]
Does the ruby binding has an implementation on blind source separation? 
Can you point to an example for separating different sounds from a wav file.

**Comment by karlnapf** [comment]
Should be possible. Though we don't have an example. See the Ica notebook in the showroom, and have a look at the ruby examples on the website.

I'll try to add an example for ica one of these days

**Comment by karlnapf** [comment]
I have sent a patch with meta examples for all ICA algorithms Shogun has. 
After this has been merged, they will appear on the website "examples", this includes ruby
Loading the soundfile has to be done from ruby for now (Shogun cannot read soundfiles), best is to load the sound, store in vector form (csv or so), and then load using Shogun

**Comment by arjunmenon** [comment]
Hey
Has it been merged?

**Comment by karlnapf** [comment]
No, there was a problem. But I will fix that now.... hopefully ;)

**Comment by karlnapf** [comment]
Sent an update that should be merge-able within the next hour

**Comment by arjunmenon** [comment]
Cool! 
Examples are also in the pipeline?

**Comment by karlnapf** [comment]
http://shogun.ml/examples/nightly/examples/converter/ica_fast.html

You will have to load and convert to your desired sampling rate using something else. But once you have the time series representation of the sound, using shogun is easy. Let us know how it goes

**Comment by arjunmenon** [comment]
Hey
If you can tell any ruby gem to do feature extraction of audio files. I can't find any.

**Comment by karlnapf** [comment]
Not sure I can help you there.
Do you know of a nice standalone c++ library to do that? We could add a wrapper to Shogun ....

thoughts @vigsterkr @lisitsyn @iglesias ?

**Comment by iglesias** [comment]
I think usually loading features into Shogun from files created by another program should be good.

If there's some application in mind where file i/o would not be suitable we could look into the wrapper idea.

**Comment by arjunmenon** [comment]
Having slight trouble getting started.
http://paste.ubuntu.com/25059799/

make is failing to download some dependency?

Better, if the executable have the latest commits? And how to create a ruby interface from there? That would be much easier.
I tried a nightly thinking it would have the latest. After install, `require 'modshogun'` fails in IRB, which is obvious. I know some additional steps is to be done. _But what flummoxes me._ 

--
_Working on Elementary os 0.3.2. 32-bit_

**Comment by arjunmenon** [comment]
As to the vector output, I found this gem - http://wavefilegem.com/examples.html
Look under the third example - `Reading a Wave File Into an Arbitrary Format`

It outputs something like this - http://paste.ubuntu.com/25059826/
WAV file - http://s000.tinyupload.com/index.php?file_id=00455761811235983910

**Comment by karlnapf** [comment]
For the make error, you either need to have eigen3 installed, or have an internet connection so that it can be downloaded

**Comment by karlnapf** [comment]
@arjunmenon make sure to read the installation and the examples readme. I cannot really help with the wav file loading, thats a job for searchengine
