### ISSUE TITLE
ICA algorithms crash if features are empty

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3884]
If you do
```
feats = RealFeatures()

ica=FastICA()
ica.apply(feats)
```

you get an eigen3 error (cryptic) due to the NULL matrix in the features. This should rather be a nice error message (coming from a REQUIRE in the ICA base class or so)

@MikeLing this one is for you

**Comment by MikeLing** [comment]
https://github.com/shogun-toolbox/shogun/pull/3887
