### ISSUE TITLE
Systematically test all iterative methods

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3889]
All models that are trained iteratively should

 * have a progress bar (add to missing ones)
 * have early stopping implemented (with working predictions afterwards) (unit test)
 * should give a *warning* when not converged (unit test), not fail.
 * Have the option to "continue" training more, if that makes sense (if not converged, or early stopped) (unit test)

This is a mix of automatic unit testing, API updates, and bug-fixes in the methods

Example: ICA methods, @geektoni knows all the other models

@geektoni @micmn maybe you can address a few of those

**Comment by karlnapf** [comment]
example for warning rather than error message #3885

**Comment by vrishank97** [comment]
I'd like to take this up as my first contribution here. What all counts as an iterative method?

**Comment by karlnapf** [comment]
Everything where the main training method is a big loop with a stopping condition based on iterations and/or tolerance

**Comment by vrishank97** [comment]
Would something like the perceptron model also require a progress bar (upto max iters)?

**Comment by karlnapf** [comment]
no, as we don't know how long it will run

**Comment by sunalbert** [comment]
Hi, @karlnapf , sorry to disturb you again. I am working on adding progress bar to CRBM. Is there any standard code/template I can follow to test the whether the progress bar works well?

**Comment by karlnapf** [comment]
check `git grep progress(range` to find the places it is used and how
