### ISSUE TITLE
GPL macro problem with interfaces

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3904]
```
/home/wiking/shogun/build/src/interfaces/r/shogunR_wrap.cxx:3604:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 #endif USE_GPL_SHOGUN
        ^~~~~~~~~~~~~~
```

**Comment by besser82** [comment]
Simply change it:  `#endif // USE_GPL_SHOGUN` or `#endif /*USE_GPL_SHOGUN*/` would be fine.

**Comment by karlnapf** [comment]
sorry, that didnt come up locally when I tested it
https://github.com/shogun-toolbox/shogun/commit/728a9f57a65d462c42be0e487dd26a26545db9de
