### ISSUE TITLE
bool CKernel::init(CFeatures* l, CFeatures* r)

### ISSUE THREAD

**Issue by romainviard** [shogun-toolbox/shogun#3909]
Hello,
I know this is not the right forum to ask my question. But I have no other idea...sorry...
It concern the **use** of method init in the Kernel class....
I do not understand why there is two arguments of type combineKernel class ("left-hand side" and "right-hand side"...) ? what is the relation with the training/testing sets ?is there any documentation (or other forum etc..) where I can find a beginning of the answer..... 

Thanks in advance for your help !
RV

**Comment by karlnapf** [comment]
Hi!
You can ask the mailing list on on IRC as well.

left hand side is training set
right hand side is testing set.
Check the nowbooks in the "showroom" on the website for example on multiple-kernel learning, svms, etc
