### ISSUE TITLE
Support linking to OpenBLAS

### ISSUE THREAD

**Issue by dougalsutherland** [shogun-toolbox/shogun#3910]
The LAPACK/BLAS-finding logic [here](https://github.com/shogun-toolbox/shogun/blob/370a66b3473b492cbcdc942179290414a7dc938a/src/shogun/CMakeLists.txt#L278-L322) doesn't seem to support OpenBLAS: [FindLAPACK](https://github.com/Kitware/CMake/blob/master/Modules/FindLAPACK.cmake) will find it okay, but then since the result is neither Accelerate or MKL, it then looks for either atlas or cblas. It would be good to support OpenBLAS properly (not least because [the conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/3237) will want to use that).

It'd also be good to have Eigen use it when found.

**Comment by vigsterkr** [comment]
@dougalsutherland the reference commit should fix your problem with using the right lapack... but the usage of LAPACK by Eigen is still experimental `ENABLE_EIGEN_LAPACK` as it fails to compile...

**Comment by dougalsutherland** [comment]
Seems to work, thanks! (Just linking to openblas, not `ENABLE_EIGEN_LAPACK` which I haven't tried yet.)

**Comment by vigsterkr** [comment]
@dougalsutherland yeah that'll require substantial work to get it work... i've tried getting MKL as well but the problem is that the current way we detect MKL is not good with anaconda... anyhow this should solve your initial main problem :)
