### ISSUE TITLE
SVRLight missing from python 2/3 interface

### ISSUE THREAD

**Issue by MaximilianLomardo** [shogun-toolbox/shogun#3913]
i have been trying to run the example from this link:

http://www.shogun-toolbox.org/examples/latest/examples/regression/multiple_kernel_learning.html#

Everything goes ok until I need to create an instance of SVRLight(), which seems to not be included with shogun, everything else is there (for example LibSVM is included with shogun). Have you encountered this issue before?

**Comment by vigsterkr** [comment]
@MaximilianLomardo how do you install shogun on your machine?

**Comment by MaximilianLomardo** [comment]
@vigsterkr 

I installed Fedora Scientific 25 in a virtual machine (virtual box). I then ran the command:

"sudo dnf install shogun"

This seemed to work ok. I then tried to install the python interfaces for both python 2 and python 3. This was achieved by running the following commands. I don't have the command handy for that anymore, but it was something like:

yum install python2-shogun.6.0.04
yum install python3-shogun.6.0.04

I can import some of the shogun classes, but SVRLight gives me problems. I would use the LibSVR class, but that apparently is not compatible with the MKLRegression class.

As a side note, do you have any more resources/tutorials that involve multiple kernel learning for both classification and regression?

**Comment by vigsterkr** [comment]
@MaximilianLomardo the problem with SVRLight and MKL is that they depend on SVMLight, which we are not allowed to distribute per license, hence if you wanna use those you'll have to compile shogun from source.

@besser82 am i right that this is the case as well on fedora?

**Comment by MaximilianLomardo** [comment]
@vigsterkr Ah ok, do you know of any step by step instructions which I could follow to reinstall shogun from source with SVMLight on my fedora machine? This is the closest I've gotten to getting a working version and this has been a pretty lengthy process. Do you think there is any way to use LibSVR with the MKLRegressio class otherwise?

**Comment by vigsterkr** [comment]
@MaximilianLomardo try http://shogun.ml/install there's a section how to compile it manually
