### ISSUE TITLE
Fix Eigen with Lapack backend

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3914]
there's a new cmake flag called `ENABLE_EIGEN_LAPACK` that enables Eigen to use if a lapack library is detected. Current if one enables it it will make the compilation fail.

**Comment by vigsterkr** [comment]
@micmn do you fancy to look into this? :)

**Comment by vigsterkr** [comment]
i started off fixing in `feature/eigen-lapack` branch

**Comment by vigsterkr** [comment]
@dougalsutherland i reckon i'm done with this.. i'll do more tests but then i'll merge the `feature/eigen-lapack` into develop

**Comment by dougalsutherland** [comment]
Cool! I'll probably wait for the next shogun release rather than backporting this into the conda package, though if you wanted to do a 6.0.1 with this, the lapack cmake changes, and those Windows fixes, I wouldn't complain. :)

**Comment by vigsterkr** [comment]
mmm it fails on osx... it requires further guarding in lapack.h to avoid cyclic definition of functions

**Comment by vigsterkr** [comment]
just merged `feature/eigen-lapack` branch into `develop`, which should enable blas/lapack to be used by Eigen by default
