### ISSUE TITLE
Windows 10, Visual Studio 2017 x64 experiences, /w java

### ISSUE THREAD

**Issue by qcrist** [shogun-toolbox/shogun#3948]
Took me a while to get the build working, not really sure where to put notes, so it goes here.

```
SWIGWORDSIZE64 shouldn't be set on windows
cmake-gui doesn't work, you get duplicate file errors
cmake has to be on the path
build_examples MUST be on, otherwise the java build fails
```

`T:\cmake-3.9.0-rc6-win64-x64\bin\cmake.exe .. -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_META_EXAMPLES=OFF -DENABLE_TESTING=OFF -DINTERFACE_JAVA=ON -DSWIG_EXECUTABLE=T:\swigwin-3.0.12\swig.exe -DJBLAS=T:\jblas-1.2.4.jar`

`msbuild shogun.sln /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=0 /v:m /m`

**Comment by vigsterkr** [comment]
@qcrist this is invaluable information!!! thank you soooooooooo much! as nobody yet tried to use swig on MSVC :) lemme try to address some of these bugs

**Comment by karlnapf** [comment]
Awesome!
