### ISSUE TITLE
compile shogun from source, ImportError:

### ISSUE THREAD

**Issue by Galaxy-Fish** [shogun-toolbox/shogun#3950]
compile shogun from source.
there some mistake 
Traceback (most recent call last):
File "python.py", line 7, in 
from shogun import *
File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 32, in 
_shogun = swig_import_helper()
File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 28, in swig_import_helper
_mod = imp.load_module('_shogun', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/_shogun.so: undefined symbol: _ZN6shogun12CDotFeatures7get_covEb

**Comment by vigsterkr** [comment]
@Galaxy-Fish do you have libshogun.so in library path? like LD_LIBRARY_PATH?

**Comment by Galaxy-Fish** [comment]
i did it like 
#export LD_LIBRARY_PATH = "/my/special/path/lib/libshogun.so:$LD_LIBRARY_PATH"

**Comment by Galaxy-Fish** [comment]
then i cp ~/shogun/build/src/interfaces/python/shogun.py 
to the /usr/local/lib/python2.7/dist-packages/
it worked.
but when the prgram done,there have segfault.

**Comment by Galaxy-Fish** [comment]
i sudo python test.py
there is no segfault error
