### ISSUE TITLE
Trying to customize shogun and wrap into python

### ISSUE THREAD

**Issue by Shenggang** [shogun-toolbox/shogun#3961]
I wrote a kernel class and added that into shogun\src\kernel. In the end I would like to use swig to wrap shogun together with my class into a python package. I have changed kernel.i, kernel_include.i to include my header. Also header_list.txt for generating class_list.cpp. I wonder is there any other file that I missed because when I build the python interface, visual studio complains about not able to resolve methods of my class.

P.S. If I feed source code of my class into the project, I would be able to build _shogun.pyd but my class will crash python. I'm not sure where the code went wrong as it worked in c++. So I'm tring to make sure I don't miss anything.

Any help is appreciated!

**Comment by vigsterkr** [comment]
@Shenggang if you wanna use custom kernel and you are using python you could simply implement your kernel in python using director class.
see the example in `examples/undocumented/python/kernel_director_linear.py` for details

**Comment by Shenggang** [comment]
Thanks for your advise! I will check that out.
