### ISSUE TITLE
shogun/lib/external/pr_loqo.h: No such file or directory

### ISSUE THREAD

**Issue by AlexBinder** [shogun-toolbox/shogun#3962]
history shows that it should have been moved in a gpl subfolder, but when i download a zip, then the gpl subfolder is empty

**Comment by karlnapf** [comment]
Yep, this has been moved. You will have to checkout the submodule if you want the GPL modules.
We have a build where all gpl codes are missing and `LICENSE_GPL_SHOGUN=Off` [here](http://buildbot.shogun-toolbox.org:8080/#/builders/4/builds/35)
This might be broken (just happened recently), happy for any reports on failure cases as we can include them in the test build
