### ISSUE TITLE
conda problems

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3964]
@dougalsutherland could you maybe take a look at this one (conda part):
https://stackoverflow.com/questions/45578184/how-do-i-install-shoguns-python-interface

**Comment by evertes** [comment]
I have the same issue after installing shogun with [conda](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#anaconda) on Ubuntu.

**Comment by dougalsutherland** [comment]
(Sorry for slow reply, I was traveling.) I think it's just that you want to import from `modshogun`, not `shogun`, in the 6.0 release (which is what the conda package has). The docs on the website refer to `shogun` instead because they're for 6.1, where the interface has been renamed.

**Comment by vigsterkr** [comment]
@evertes i'm closing this one, as @dougalsutherland should fix your problem. de ha van valami gond nyugodtan nyisd ki a ticketet :)

**Comment by vigsterkr** [comment]
@dougalsutherland thnx for clarifying. i hope you enjoyed down under :)
