### ISSUE TITLE
Errors using make

### ISSUE THREAD

**Issue by rangira** [shogun-toolbox/shogun#3972]
I am trying to compile the shogun project manually on MacOS. I created a folder "build" , executed the "cmake .." command. 
But it gives me error when I try to use "make". I see that there is no "Makefile" in the build folder. I also tried doing "./configure" but I always get "No such command found".
Could you please share how I am supposed to use "make" especially on mac.

**Comment by vigsterkr** [comment]
The latest release is part of homebrew.
If you want to compile it from source follow this manual:
http://shogun.ml/install#manual

Usually if there's such error with make after cmake, that means that there was an error running cmake. Can you put your full cmake output to pastebin.com and put the link here, please?

**Comment by rangira** [comment]
Thanks for replying. I would still prefer building it from scratch. Here is the output from "cmake"
[](https://pastebin.com/69XUeqWP)

**Comment by vigsterkr** [comment]
ok so as you can see from the output of cmake:
```-- The ctags found is not suitable for meta examples.
-- Could NOT find Ctags (missing: CTAGS_EXECUTABLE)
-- The ctags found is not suitable for meta examples.
-- Could NOT find Ctags (missing: CTAGS_EXECUTABLE)
CMake Error at examples/meta/CMakeLists.txt:11 (message):
 Ctags required for meta examples.  Install or set BUILD_META_EXAMPLES=OFF.
```

namely if you use osx you need to have ctags installed (one way is to install it via brew: `brew install ctags`). or of course you can skip the building of the meta examples by running cmake:
```
cmake BUILD_META_EXAMPLES=OFF ..
```
