### ISSUE TITLE
INSTALL error!

### ISSUE THREAD

**Issue by Jiewen2017** [shogun-toolbox/shogun#3974]
7>CMake Error at examples/undocumented/libshogun/cmake_install.cmake:31 (file):
7>  file INSTALL cannot find
7>  "E:/software_manual/shogun/build/examples/undocumented/libshogun/balanced_conditional_probability_tree".
7>Call Stack (most recent call first):
7>  examples/cmake_install.cmake:32 (include)
7>  cmake_install.cmake:34 (include)
7>
7>
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: E:\software_manual\cmake\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
7>Done building project "INSTALL.vcxproj" -- FAILED.

**Comment by Jiewen2017** [comment]
This error is occur when I startup my vs2017 and right click the INSTALL to build.

my environment is Windows7，vs2017，release x64.

**Comment by MikeLing** [comment]
Hi there, honestly I haven't build Shogun by Visual studio before. Could
you check if all the submodules have been cloned by 'git submodule update
--init'? Maybe they are unrelative, but missing submodule may cause 'not
found' error like that :)

Best Regards

2017-08-31 15:40 GMT+08:00 Jiewen Wen <notifications@github.com>:

**Comment by Jiewen2017** [comment]
https://ci.appveyor.com/project/vigsterkr/shogun

The link is my reference when i build.  the command 'git submodule -q update --init' was ran. however, the error was occur.

**Comment by vigsterkr** [comment]
@Jiewen2017 i guess you are doing something similar or: http://shogun.ml/install#manual-windows ?

**Comment by vigsterkr** [comment]
closing this one; anybody attempts to use shogun on windows should try it with using [conda package](https://anaconda.org/conda-forge/shogun-cpp) starting 6.1.3 there's a binary windows package available
