### ISSUE TITLE
Segmentation fault when training with SVRLight

### ISSUE THREAD

**Issue by ChristosHadoulos** [shogun-toolbox/shogun#3976]
Hello, 
i am getting a `Segmentation fault (core dumped)` error when i train an SVR model with SVRLight in python. This happens on both my local machine (Ubuntu 14.04 LTS) and on a university computer where i run the bulk of my experiments (Ubuntu 16.04 LTS). I compiled shogun from source on both machines using `cmake -DPythonModular=ON ..` .
Additionally, when training an MKLRegression model with SVRLight it takes an awful lot of time to converge. For example, it took 5 hours on a machine with 48 single core CPUs and 64GB RAM to train such a model on a training set of size (2726,198) using 50 kernels. 
If anyone can offer some insights on the matter i would greatly appreciate it.

**Comment by karlnapf** [comment]
Sorry for the delay.
We would need an example here. Can't help with that description.

As for runtime, MKL is slow, especially when you ramp up the number of data and kernels. But if it is unreasonably slow, we should do something of course
