### ISSUE TITLE
Bug in typemap for Ruby

### ISSUE THREAD

**Issue by lordon** [shogun-toolbox/shogun#3980]
Hi!

I noticed an issue in the type interface for Ruby. Given a shogun matrix:

| | |
|-|-|
| a11 | a12
| a21 | a22
| a31 | a32
| a41 | a42

the same matrix is returned to Ruby as the following `NArray` instance:

| | |
|-|-|
| a11 | a21
| a31 | a41
| a12 | a22
| a32 | a42

e.g. if I run the [k-means modular example](https://github.com/shogun-toolbox/shogun/blob/develop/examples/meta/src/clustering/kmeans.sg) both in Python and Ruby and take a closer look into the `RealMatrix c` holding the centroids, in Python it looks like

```
array([[-1.94008349,  2.07996522],
       [-1.85141993,  1.96842635]])
```

whereas in Ruby it looks faulty like 

```
=> NArray.float(2,2): 
[ [ -1,94008.0, -1,85142.0 ], 
  [ 2,07997.0, 1,96843.0 ] ]
```

My first approach was to flatten and rebuild the `matrix` with `m` features into the correct order in Ruby:
`NArray.to_na(matrix.to_a.flatten.each_slice(m).to_a.transpose)`. However this isn't a practicable solution.

I noticed the same behaviour in the other direction as well (a Ruby array passed to a FeatureMatrix gets transformed into a wrong matrix in shogun).

Seems there is a bug in the swig type interface for Ruby, especially regarding matrices.

Tested with:
* Shogun 6.0.0
* Swig 3.0.8
* Ruby 2.2.3
* narray 0.6.1.2

**Comment by lordon** [comment]
This fixed it for me, locally. I'm not sure about any side effects, though..

**Comment by vigsterkr** [comment]
@lordon this great! and thanks for the PR!

**Comment by vigsterkr** [comment]
ok this has been merged... closing

**Comment by karlnapf** [comment]
I mentioned this in the NEWS :)
thanks!
