### ISSUE TITLE
Could it possible to suppory MSYS2 (GCC 7.2.0 under windows)?

### ISSUE THREAD

**Issue by strategist922** [shogun-toolbox/shogun#3983]
Hi,

  Could it possible to support MSYS2 ( GCC 7.2.0 toolchain under windows) to build shogun?

**Comment by karlnapf** [comment]
Sorry what exactly is the question? :)

**Comment by strategist922** [comment]
The issue is "cannot compile shogun win windows version GCC (i.e. MSYS2)"

**Comment by vigsterkr** [comment]
@strategist92 i know that shogun can be compiled using gcc 7.2... if you could share the exact error then i could look into it... is it necessary that you compile shogun with gcc on windows instead of MSVC?

**Comment by strategist922** [comment]
@vigsterkr owing to policy issue, we cannot use MSVC, we wnat to try shogun as backend of ML and combind with R and Python, hope there is a guide have informatio to build windows binary by using windows version gcc 7.2.0

**Comment by vigsterkr** [comment]
@strategist922 mmm i see... i'll have to try to do this :))) first have you tried compiling just shogun itself (without the interface)?

**Comment by vigsterkr** [comment]
@strategist922 i mean the thing is if that's a standard gcc then it should just be the same way as any other platform... i'll dig out a windows machine today and try to check it with msys2.0... but i dont see a reason why it would not be possible.

**Comment by strategist922** [comment]
@vigsterkr , I followed the steps but failed when in CMake steps...

**Comment by vigsterkr** [comment]
could you provide the output of cmake? just put here the pastebin.com link to the output

**Comment by karlnapf** [comment]
any updates?
