### ISSUE TITLE
Custom kernel Issues

### ISSUE THREAD

**Issue by nisarwani** [shogun-toolbox/shogun#3984]
CombinedKernel.cpp line 154: Number of lhs-feature vectors (4345) not match with number of rows (1831) of custom kernel

Is it necessary that feature matrix  rows and columns should match. I have to split my data into train and test where by it may not be possible to pass a square matrix to custom kernel. How to handle this.

**Comment by karlnapf** [comment]
Can you share a minimal example of the code that caused this?
