### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by skn123** [shogun-toolbox/shogun#3985]
In file included from /home/naths/srcs/shogun/src/shogun/kernel/normalizer/SqrtDiagKernelNormalizer.h:16:
In file included from /home/naths/srcs/shogun/src/shogun/kernel/normalizer/KernelNormalizer.h:16:
/home/naths/srcs/shogun/src/shogun/kernel/Kernel.h:212:21: error: member access
      into incomplete type 'shogun::CKernelNormalizer'
                        return normalizer->normalize(compute(idx_a, idx_...
                                         ^
/home/naths/srcs/shogun/src/shogun/kernel/Kernel.h:34:8: note: forward
      declaration of 'shogun::CKernelNormalizer'
        class CKernelNormalizer;

**Comment by skn123** [comment]
[ 79%] Linking CXX executable so_multiclass_BMRM
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_for_static_fini'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_barrier'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_set_num_threads'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_get_max_threads'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_end_serialized_parallel'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_set_dynamic'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_get_num_threads'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_get_wtime'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_end_critical'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_for_static_init_8'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_fork_call'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_for_static_init_4'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_push_num_threads'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_global_thread_num'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_critical'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_reduce_nowait'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_single'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_end_single'
../../../src/shogun/libshogun.so.18.0: undefined reference to `omp_get_thread_num'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_end_reduce_nowait'
../../../src/shogun/libshogun.so.18.0: undefined reference to `__kmpc_serialized_parallel'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vigsterkr** [comment]
@skn123 could you give details of your operating system as well as the version of shogun you are trying to compile

**Comment by skn123** [comment]
I enable linking with OpenCV which was built with OpenMP and then it built nicely! So something to do with missing OpenMP defines in the code

**Comment by vigsterkr** [comment]
mmmm that is weird... can you please paste here the output of a clean `cmake` run so that i can see whether or not it autodetected the openmp flag

**Comment by skn123** [comment]
It detects the flags -fopenmp=libomp so no issues with that also

**Comment by skn123** [comment]
I can live without openmp for now and I am happy with the solution. However, the first problem still needs to be fixed

**Comment by karlnapf** [comment]
Is this still happening with the latest release/develop code?

**Comment by vigsterkr** [comment]
this is fixed
