### ISSUE TITLE
Win 10 shogun with python 3.6

### ISSUE THREAD

**Issue by wjcper2008** [shogun-toolbox/shogun#3986]
can shogun install with python 3.6?
I can not install this toolbox using
`pip install shogun-ml`

I try "Windows build " manually, and build successfully. When I add python interface, it asks me to add many dependencies such as ccache (I cannot install in windows). How can I do with? Thanks

**Comment by karlnapf** [comment]
The windows build we have is here: https://ci.appveyor.com/project/vigsterkr/shogun/branch/develop

AFAIK this is without Python bindings. You are welcome to assist us extending this (we don't have windows machines)

**Comment by vigsterkr** [comment]
@wjcper2008 have you tried conda? shogun is included in conda-forge

**Comment by vigsterkr** [comment]
@wjcper2008 i've just realised couple of days ago that we had a blocking bug for having shogun in conda. Anyhow i have fixed now this blocking bug and pushed it to develop branch. here i wrote up a small howto, for being able to use shogun and it's python interface using anaconda:
https://stackoverflow.com/a/47125101/2798875
