### ISSUE TITLE
Ubuntu 16.04 while adding ppa got 404

### ISSUE THREAD

**Issue by Lashuk1729** [shogun-toolbox/shogun#3987]
While "sudo apt-get update", I encountered 404 error. Can someone help me installing shogun?
Get:13 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                                        
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release                                                           
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                               
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                 
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                            
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                               
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                        
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                           
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                               
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                 
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                            
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                               
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                        
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                           
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                               
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                 
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                            
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                               
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                        
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                           
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                               
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages                                                 
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN                                            
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en                                               
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata                                        
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons                                           
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages                                               
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages                                                
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Err:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en_IN
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 306 kB in 38s (7,908 B/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Lashuk1729** [comment]
The error clearly shows that the "http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu xenial/main amd64 Packages" is not present. I want to work on this bug. But I'm new to shogun-toolbox and github. So, if someone can guide me what to do!

**Comment by lgoetz** [comment]
Try using the nightly ppa. You can do this by adding **ppa:shogun-toolbox/nightly** to your system's Software Sources. Then:

`sudo add-apt-repository ppa:shogun-toolbox/nightly`
`sudo apt-get update`

check-out: https://launchpad.net/%7Eshogun-toolbox/+archive/ubuntu/nightly

**Comment by Lashuk1729** [comment]
Thanks @lgoetz for the solution. 
After adding the repository one might get the problem while installing shogun-toolbox on ubuntu16.04 after this command "sudo apt-get install libshogun17".
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libshogun17
So, one can try this : "sudo apt-get install libshogun18".

**Comment by lgoetz** [comment]
You’re welcome!
