### ISSUE TITLE
Installation error in ubuntu 

### ISSUE THREAD

**Issue by Nirvan101** [shogun-toolbox/shogun#3991]
I'm trying to compile Shogun manually following the instructions in `INSTALL.md`
When I do : 

    git clone https://github.com/shogun-toolbox/shogun.git
    cd shogun
    git submodule update --init
    cd shogun
    mkdir build
    cd build
    cmake [options] ..
    make

I get the following error:

    ../../../src/shogun/libshogun.so.18.0: undefined reference to `GOMP_parallel@GOMP_4.0'
    collect2: error: ld returned 1 exit status
    examples/undocumented/libshogun/CMakeFiles/kernel_machine_train_locked.dir/build.make:101:                 
    recipe for target 'examples/undocumented/libshogun/kernel_machine_train_locked' failed
    make[2]: *** [examples/undocumented/libshogun/kernel_machine_train_locked] Error 1
    CMakeFiles/Makefile2:598: recipe for target             
    'examples/undocumented/libshogun/CMakeFiles/kernel_machine_train_locked.dir/all' failed
    make[1]: *** [examples/undocumented/libshogun/CMakeFiles/kernel_machine_train_locked.dir/all]             
    Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2
 

How do I get past this?

**Comment by vigsterkr** [comment]
@Nirvan101 could you pull the latest develop version (update the submodule as well) and try to compile now.
