### ISSUE TITLE
Kears support?

### ISSUE THREAD

**Issue by strategist922** [shogun-toolbox/shogun#3993]
Hi Team,

    Would it possible to have plan to let shogun can be one of the backends of Keras?

**Comment by karlnapf** [comment]
Sure, that would be a cool integration to add.
We are currently not enough peeps to make this happen though, wanna help?

**Comment by karlnapf** [comment]
GSoC 2018 project...please see our suggested projects (once they are online)
Some things are already in the wiki, following our hackathon 2017
