### ISSUE TITLE
mkl needs preloading when using python interface

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3994]
for some reason MKL shared libraries are not loaded with libshogun (even if they are linked) when using the shogun interface....

**Comment by karlnapf** [comment]
ldd output for `libshogun.so`
https://pastebin.com/v6MHVQxN

and the python interface `_shogun.so`
https://pastebin.com/QhZF5qh4

The error is "Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so."

The current workaround is something in the lines of
`export LD_PRELOAD=/opt/conda/lib/libmkl_core.so:/opt/conda/lib/libmkl_sequential.so`

**Comment by vigsterkr** [comment]
this problem is actually due to a badly setup environment in that docker image.... but we cannot do anything about this, just advise users to fix their environments or play around with env variables

**Comment by vigsterkr** [comment]
reopening this because:
https://mail.scipy.org/pipermail/numpy-discussion/2009-October/046020.html

but we can have couple of workarounds for this from shogun side... so lets be nice with our users

**Comment by vigsterkr** [comment]
we are trying to use this if possible https://software.intel.com/en-us/articles/a-new-linking-model-single-dynamic-library-mkl_rt-since-intel-mkl-103
