### ISSUE TITLE
cmake does not check for openblas headers

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3996]
I.e. when compiling shogun against openblas using anaconda, compilation fails due to a missing `cblas.h`, which can be fixed via `apt-get install libopenblas-dev`. It would be good if cmake checked this and errors

**Comment by vermashresth** [comment]
@karlnapf Can I work on this issue?

**Comment by vigsterkr** [comment]
@vermashresth yes go ahead. take a look how it is done in case of MKL

**Comment by vermashresth** [comment]
@vigsterkr Currently, the [ShogunFindLAPACK.cmake](https://github.com/shogun-toolbox/shogun/blob/develop/cmake/ShogunFindLAPACK.cmake#L70-L72) checks for the existence of `cblas.h` by searching for `cblas_dgemv` function in the found Lapack library. But it is a weak check as it might be possible that `cblas_dgemv` exists but still there is no `cblas.h` header file (for example having libopenblas-base installed and not having libopenblas-dev causes this error).
Would it be better then to remove this check altogether and only look for `cblas.h` header file like it is done in case of MKL?

**Comment by vigsterkr** [comment]
@vermashresth noup that's not a good idea as you need to consider the case when it's an atlas version of LAPACK/BLAS.... basically you need to figure it out that it's openblas based LAPACK/BLAS and if that's the case then you need to do a search for cblas.h

**Comment by vigsterkr** [comment]
@vermashresth mmm it's not necessary to create a `FindOpenBLAS` file to detect the BLAS/LAPACK type.. of course you can do that as well... it's up to you. only thing is that you should be able to figure out whether the detected LAPACK API is openblas... and in case it is then it should be able to find the cblas.h or error if there's no such header available....

**Comment by vermashresth** [comment]
@vigsterkr I'm stuck on figuring out whether the detected LAPACK API is openblas. The path names don't always contain openblas keywords so can't use regex and detecting openblas otherwise doesn't ensure whether it actually is the detected version. Can you suggest some other way? I'm still a beginner so taking time to understand

**Comment by vigsterkr** [comment]
how do you mean that the path name in case of openblas is not always containing openblas keyword? can you show me a distro/installation where this is the case?

**Comment by vermashresth** [comment]
@vigsterkr In my system, I have `libopenblas-dev` installed and at installation time it sets `/usr/lib/libblas.so` to point to `/usr/lib/openblas-base/libblas.so.3` and same with liblapack.so
Now the LAPACK_LIBRARIES retuned by FindLAPACK are `/usr/lib/libblas. so` and `/usr/lib/liblapack.so` 
When I run `readlink -f "/usr/lib/libblas. so"` it shows `/usr/lib/openblas-base/libblas.so.3`
So the detected lapack is openblas one but by name it only shows libblas.so

**Comment by vigsterkr** [comment]
first of all looking into blas is foobar, as we only detect LAPACK... i know that blas is a dependency of LAPACK in this matter but we do not do BLAS detection directly.

second of all if you check this: https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions
you realise that there are some openblas specific functions that could be used to detect whether the detected library is openblas, or something else.
