### ISSUE TITLE
make install should install toy data with examples

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3997]
The (meta) examples need `data/toy`, i.e. a subfolder of the `data` submodule.
`make install` should ensure this is installed with the examples under `prefix/share/shogun/examples` in a way that the examples work out of the box after installing.

Currently, one has to do something like this (I here link the folder)
```
ln -s /opt/shogun/data/toy/ /usr/local/share/shogun/examples/data
cd /usr/local/share/shogun/examples/python/binary_classifier
python kernel_svm.py
```

**Comment by karlnapf** [comment]
Note, not all of the data (too big), just the toy data necessary for the examples

**Comment by vigsterkr** [comment]
people, there is a good reason why we have releases of the shogun-data as well, see for example:
http://shogun.ml/archives/shogun/data/shogun-data-0.11.tar.bz2

**Comment by durovo** [comment]
@vigsterkr So from what I understand, there is no need to move the toy data? Is it up to the user to create a symlink or move it to run the meta examples?
