### ISSUE TITLE
No interface files after installing with homebrew

### ISSUE THREAD

**Issue by krc3004** [shogun-toolbox/shogun#4007]
Hi, I installed shogun using the following command:

brew install homebrew/science/shogun

But I'm unable to locate any of the interface files (I'd like to use shogun in R).  I followed the instructions shown here: http://www.shogun-toolbox.org/examples/latest/quickstart/interfaces.html but was unable to locate shogun.R in any of the folders (include, lib, share) in the top directory.  Perhaps my installation is incorrect?  Do I need to run cmake or related commands?

I noticed that there was a similar question earlier this year; not sure if it was resolved: https://github.com/shogun-toolbox/shogun/issues/3594

Thanks very much!

**Comment by vigsterkr** [comment]
@krc3004 please read about the shogun formula a bit in homebrew, i.e. `brew info shogun`, you will see that there are many options for the formula that are turned off by default... one of which is `--with-r` that will build the R interface for you.
