### ISSUE TITLE
BSS_audio is not found

### ISSUE THREAD

**Issue by ramdishanth** [shogun-toolbox/shogun#4010]
http://www.shogun-toolbox.org/notebook/latest/bss_audio.html

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by vigsterkr** [comment]
:O wonder what has happened... i think it's about the python2->3 switch :(

**Comment by karlnapf** [comment]
Check line 240 and 258 of http://buildbot.shogun-toolbox.org:8080/#/builders/17/builds/51/steps/14/logs/stdio

**Comment by karlnapf** [comment]
Probably can be fixed by not using pylab.

**Comment by karlnapf** [comment]
It is actually `wavPlayer(s1, fs1)`
```
try:
    from IPython.display import Audio
    def wavPlayer(data, rate):
        display(Audio(data, rate=rate))
except ImportError:
    pass
```

Jupyter refactored things in there, so now `display` is not defined anymore

**Comment by karlnapf** [comment]
@vigsterkr I fixed the notebook, it worked on last nightly_default, so I guess website will be auto updated at some point?
