### ISSUE TITLE
delete all VW code

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4030]
Delete all VW code in shogun `src/shogun/classifier/vw/`

Then make sure the build still works
 * delete all tests
 * delete all examples

Run tests and send PR, all fine

**Comment by salonirk11** [comment]
@karlnapf Can I work on this issue?

**Comment by vigsterkr** [comment]
@salonirk11 yes, certainly. make sure that before you send in a PR both all the examples and tests are passing on your machine locally.
