### ISSUE TITLE
Cannot import "WrappedObjectArray" in python

### ISSUE THREAD

**Issue by shubham808** [shogun-toolbox/shogun#4040]
On running ```examples/meta/python/gaussian_processes/gaussian_process_classifier.py``` I get the import error both on my system and on shogun cloud.

**Comment by karlnapf** [comment]
Ah that is a known problem.
@sorig didn't you recently check this?

workaround: remove that part of the example code, it is only for testing. We will try to fix this soon

**Comment by karlnapf** [comment]
If this persists after removing and re-creating the build directory, could you show how you run cmake to reproduce this?

**Comment by shubham808** [comment]
Yes it still persists i used these options with cmake ```cmake -DENABLE_TESTING=ON -DBUILD_META_EXAMPLES=ON -DINTERFACE_PYTHON=ON  ..```

**Comment by karlnapf** [comment]
I cannot confirm this, i.e. doens't happen on my system.
I guess you can dive in and check it out. The class has guards and you can see whether they are set or not. 

BTW I am not sure what you mean when you say you run the example on the shogun cloud? Anyways, the cloud is built with testing disabled, so the class doesn't exist in there

I will close this for now

**Comment by shubham808** [comment]
Yeah it works fine now.
By shogun cloud I meant that when I tried to import the class there it was a cannot import error same as in my system so I thought maybe it's related.
But since it doesn't exist there it makes sense now.
