### ISSUE TITLE
EASY: Use factory methods instead of constructors in meta examples

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4043]
**NOTE**: This task is frozen for now, until we have extended the meta examples to deal with the changes. This is likely to change within the next few weeks

See

For example, we want to change the Gaussian instantiation from
```
GaussianKernel k(2.0)
```
to
```
Kernel k = kernel("GaussianKernel", width=2.0)
```

This also should be done for `KernelMachine`, i.e. use `svm = kernel_machine("LibSVM")`.

Eventually, we want to do this for all constructors in the meta examples. For `Kernel` and `KernelMachine`, this is already possible via #4022 and #4023 so let's start with those. See #4022 for an example how to do this in the examples.

Nice way to get inolved into Shogun's examples, and the new API we are going for

**Comment by prashanthduvvada** [comment]
Will take up the issue

**Comment by grassknoted** [comment]
Could I take the issue up?
