### ISSUE TITLE
EASY: create factory methods to create LinearMachine instances by their name

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4044]
See #4023 for an example.

We want this for `CLinearMachine` as well

Next step is to use this in the examples, as mentioned in #4043

**Comment by karlnapf** [comment]
#3840

**Comment by shubham808** [comment]
@karlnapf I would like to take this one up

**Comment by karlnapf** [comment]
Go for it

**Comment by salonirk11** [comment]
While working with examples, like in #4043 the object returned by ```kernel``` is of ```CKernel``` class and hence ```k.set_width(2.0)``` throws a ```no method named set_width``` error because set_width is a method of ```CGaussianKernel```. 
The src files in ```examples/meta``` thus don't translate. The same problem occurs with examples using  ```linear_machine``` and ```kernel_machine```. We are stuck here.

**Comment by lisitsyn** [comment]
@salonirk11 oh that's a good catch we have not foreseen. It seems we'd also need to change it to `set("width", 2.0)` but this might require some tricks in examples generator.

Thanks for the note!

**Comment by shubham808** [comment]
So should we stop working on examples and create a PR for the factory meathod implementation?

**Comment by lisitsyn** [comment]
@shubham808 yeah factories are the way to go yet.

Good news are that once #4063 is merged (rather soon) the `put('parameter', value)` start working. This means examples would start looking like that:
```
kernel = shogun.kernel('GaussianKernel')
kernel.put('log_width', 1.0)
```

**Comment by salonirk11** [comment]
@lisitsyn ```shogun.kernel("GaussianKernel)``` faces translation problems which we believe is because ```translate.py``` is unable to detect a valid identifier. 
The error log while build shows the following -
``` 
{'Statement': {'Init': [{'ObjectType': 'Kernel'}, {'Identifier': 'gaussian'}, 
{'Expr': {'MethodCall': [{'Identifier': 'shogun'}, {'Identifier': 'kernel'},
{'ArgumentList': [{'Expr': {'StringLiteral': 'GaussianKernel'}}]}]}}]}, '__PARSER_INFO_LINE_NO': 15}
.
.
.
File "/home/canary/shogun/examples/meta/generator/translate.py", line 460, in translateExpr
    "Variable {} not initialised".format(identifier)
NameError: name 'identifier' is not defined
```
where we have made the following changes to ```support_vector_regression.sg```
```
Kernel gaussian = shogun.kernel("GaussianKernel")
gaussian.put("log_width", width)
```

**Comment by shubham808** [comment]
@lisitsyn Also, put seems to work only with data members and not methods. So we cant use it in examples that have code like .https://github.com/shogun-toolbox/shogun/blob/6f1fd162892988e212b5ddfc6de15db3a8bf1026/examples/meta/src/regression/multiple_kernel_learning.sg#L21

Are the statements below in function ```set_width(2.0)``` ignored in ```put('log_width', 2.0)``` ?https://github.com/shogun-toolbox/shogun/blob/6f1fd162892988e212b5ddfc6de15db3a8bf1026/src/shogun/kernel/GaussianKernel.cpp#L95

**Comment by karlnapf** [comment]
I will look into a fix for this after merging #4069 
This requires some changes in the meta grammar. Thanks for reporting the issues, we did indeed not foresee these proboems. Very useful! Once I have sent a patch, you can continue

**Comment by shubham808** [comment]
okay we will continue after the patch  :+1:

**Comment by karlnapf** [comment]
@sorig

**Comment by karlnapf** [comment]
This is now possible to do, using the new put/get API
See https://github.com/shogun-toolbox/shogun/blob/7513cd68101ef3541390303aadadbc1ddfa5cbe1/examples/meta/src/base_api/put_get.sg or https://github.com/shogun-toolbox/shogun/blob/7513cd68101ef3541390303aadadbc1ddfa5cbe1/examples/meta/src/meta_api/kwargs.sg

**Comment by karlnapf** [comment]
I am closing this as it is part of transitioning to the new API and we have lots of examples here already
