### ISSUE TITLE
make errors in brew install

### ISSUE THREAD

**Issue by nilinswap** [shogun-toolbox/shogun#4061]
On trying `brew install homebrew/science/shogun` getting an error in 'make' process.

cd /tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/build/src/shogun && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -I/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src -I/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/build/src -isystem /usr/local/include/eigen3 -I/usr/local/include -I/usr/local/lib/../include -I/usr/local/include/json-c -I/usr/local/opt/libxml2/include/libxml2 -I/usr/local/Cellar/hdf5/1.10.1_2/include -I/usr/local/opt/szip/include -I/usr/local/opt/curl/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated -O3 -funroll-loops -fPIC -std=c++11 -o CMakeFiles/libshogun.dir/lib/external/gpdt.cpp.o -c /tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src/shogun/lib/external/gpdt.cpp
/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src/shogun/lib/external/cdflib.cpp:10052:15: error: ordered comparison between pointer and zero ('int *' and 'int')
if ( n_data < 0 )
~~~~~~ ^ ~
1 error generated.
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/lib/external/cdflib.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2

make: *** [all] Error 2

I have tried many trouble-shooting measures but none fixed this. https://gist.github.com/nilinswap/7014f024688159c4778324298b4764f5 is the gist of the last attempt. Please help

**Comment by noeddl** [comment]
I have the same problem when trying to (manually) build version 6.0.0 on macOS 10.13.2.

**Comment by dougalsutherland** [comment]
This error was fixed in https://github.com/shogun-toolbox/shogun/commit/d67be57eb50eb402b59d9892bfd317454061b6fc, which is present in shogun 6.1.*.

Homebrew-science is now depracated (https://github.com/Homebrew/homebrew-science/pull/6616), and so shogun 6.1 won't be available on it. You could try editing the formula to build 6.1.3, but the next time you `brew update` it'll go away.

You might prefer [conda-forge builds](http://shogun-toolbox.org/install#anaconda).

**Comment by dougalsutherland** [comment]
Oh, https://github.com/Homebrew/homebrew-core/pull/21444 would add shogun to homebrew-core, if you'd prefer to wait for that / get it from the pull.
