### ISSUE TITLE
implement SGSparseMatrix::equals

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4071]
See 80808c65d886309d64d2b1d944cd84e3ae822451
We want the same for our sparse matrices

Easy entrance task, that allows you to get exposed to some internals of shogun. It is mostly copy paste, but requires some understanding of the above patch.

**Comment by vinx13** [comment]
Hello, I would like to work on this.

**Comment by karlnapf** [comment]
Do it. Make sure to read the developing readme before you start
