### ISSUE TITLE
Refactor log-determinant estimation code to work without computation engines

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4074]
We want to delete the files in `lib/computation/*`

However, we don't want to delete @lambday 's nice code to estimate log-determinants of large sparse matrices.

This task is to re-factor things such that we can delete the computation classes. This is a nice entrance task that does only require to read/refactor existing code and tests. This will give you a nice first exposure to the internals of shogun without being overwhelming. Good non-trivial entrance task therefore.

Here is a rough list of steps
0. Read through the code, coming from the log-determinant examples
1. Compile Shogun withe the log-det code enabled (see guards in code).
2, Isolate and run all log-det tests
3. Delete all files in `shogun/lib/computation`. Re-run `cmake` and `make`. The build is now broken, i.e. shogun won't compile
4. Fix the build (will require slight API changes)
5. Make sure all tests work
6. Send PR

**Comment by shubham808** [comment]
@karlnapf i want to take this up.

**Comment by shubham808** [comment]
After looking at the code I got rid of ```computation engines``` and directly computed jobs treating them as ```independent jobs```.
So I deleted ```engines``` directory and then debugged to get everything to work. 
Is this the right approach ? And should I keep going similarly to eventually get rid of all classes in ```computation``` directory ?

**Comment by karlnapf** [comment]
yes, thats exactly it. make sure to send a pr soon to we can give feedback.
Keep in mind we also want to get rid of independent jobs.
Best would be if you used openmp instead for now

**Comment by shubham808** [comment]
@karlnapf using ```omp``` is a good idea. I got rid of ```IndependentJob``` and also the ```aggregators``` are not needed too. However, I am stuck at getting rid of ```JobResult``` classes also i think keeping them around would simplify things.

**Comment by salonirk11** [comment]
Also, is it necessary to remove ```lib/computation/aggregator``` ? Can we reuse these classes from ```mathematics/linalg/rattaprox/logdet/computation/aggregator```?

**Comment by karlnapf** [comment]
Everything in the `computation` folder should go

**Comment by karlnapf** [comment]
Done via #4103
