### ISSUE TITLE
CMAKE Error when DENABLE_TESTING=ON

### ISSUE THREAD

**Issue by Red-devilz** [shogun-toolbox/shogun#4076]
The Cmake installation attempt fails when I attempt to install shogun from source : 
     
    
    cmake -DENABLE_TESTING=ON ..
    
The above command results in the error below 

    [  0%] Performing download step (download, verify and extract) for 'GoogleMock'
	-- downloading...
		 src='http://googlemock.googlecode.com/files/gmock-1.7.0.zip'
		 dst='/home/some_path/shogun/third_party/GoogleMock/gmock-1.7.0.zip'
		 timeout='10 seconds'
	CMake Error at GoogleMock-stamp/download-GoogleMock.cmake:27 (message):
	  error: downloading 'http://googlemock.googlecode.com/files/gmock-1.7.0.zip'
	  failed

		status_code: 22
		status_string: "HTTP response code said error"
		log:   Trying 74.125.68.82...

	  Connected to googlemock.googlecode.com (74.125.68.82) port 80 (#0)

	  GET /files/gmock-1.7.0.zip HTTP/1.1

	  Host: googlemock.googlecode.com

	  User-Agent: curl/7.47.0

	  Accept: */*

	  The requested URL returned error: 404 Not Found

	  Closing connection 0

It seems as though the URL *http://googlemock.googlecode.com/files/gmock-1.7.0.zip* leads to a dead link. Thanks in advance for the help

**Comment by lisitsyn** [comment]
What is the version you're using?

This issue should not appear neither in develop branch nor in the latest release.

**Comment by lisitsyn** [comment]
If you want to compile exactly that version of Shogun you can patch the link in cmake/external/GoogleTestNMock.cmake to something like https://github.com/google/googlemock/archive/release-1.7.0.zip
