### ISSUE TITLE
Problem installing Shogun

### ISSUE THREAD

**Issue by mlsgenaro** [shogun-toolbox/shogun#4082]
**I followed the instructions at http://shogun-toolbox.org/install#anaconda to install shogun on Anaconda. The installation failed and I do not know how to proceed with the installation.**

**I am using Anaconda 1.6.12.**

**System Details:**
genaro@myFreeGeekBox ~/Downloads $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
genaro@myFreeGeekBox ~/Downloads $ uname -a
Linux myFreeGeekBox 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Gist:** https://gist.github.com/mlsgenaro/c33288ee7a6e1269e30dc34f5fcab954

**Comment by karlnapf** [comment]
I don't think this is a shogun problem.
@dougalsutherland maybe we can ask for an hdf version of at least something, rather than exactly something?

**Comment by karlnapf** [comment]
@mlsgenaro google a bit to see how you can resolve package conflicts in conda. The error messages are quite clear

**Comment by dougalsutherland** [comment]
I'm a little confused why this is happening, but the current conda-forge `h5py` recipe depends on a newer hdf5; I'll update the shogun recipe to match, and then it should be able to get `h5py` from `conda-forge` as well. (conda-forge's automated dependency update mechanisms are in flux right now and not doing these updates automatically.)

@mlsgenaro, I'll ping you again in an hour or two when the new Linux build is up.

**Comment by dougalsutherland** [comment]
Also @karlnapf, hdf5 [doesn't maintain binary compatibility](https://abi-laboratory.pro/tracker/timeline/hdf5/), so each build has to depend on a relatively tight version of hdf5.
