### ISSUE TITLE
Serializing model in Python and loading in C++

### ISSUE THREAD

**Issue by alexanderwhatley** [shogun-toolbox/shogun#4084]
I am in a situation where I would like to train the model in Python and load it in C++. In the examples, it appears that only way to do this is with pickle, which will not work in C++. Is there another way? Thanks.

**Comment by karlnapf** [comment]
Should be something in the lines of (of the top of my head)
```
import moshogun as sg
trained_model = sg.LibSVM()
...
file=sg.SerializableAsciiFile("serialized.dat", 'w')
trained_model.save_serializable(file);
```

```
file=new CSerializableAsciiFile("serialized.dat", 'r');
CLibSVM* loaded_model=new LibSVM();
loaded_model->load_serializable(file);
file->close();
SG_UNREF(file);
```

Let me know if that goes through, if not, I can write a concrete example

**Comment by vigsterkr** [comment]
use the SGObject::serialize, deserialize interface. they are exposed via the SWIG interface as well
