### ISSUE TITLE
cmake error in compiling shogun from source

### ISSUE THREAD

**Issue by xristos91** [shogun-toolbox/shogun#4086]
Hello,
I'm trying to build shogun 6.1.0 -or a later version from source (i need to use svmlight), following the instructions in the doc/readme/INSTALL.md file. After executing the `cmake ..` command, i get the following error:

> -- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CCache: /usr/bin/ccache  
-- Using system's malloc
-- Found GDB: /usr/bin/gdb  
-- Found Doxygen: /usr/bin/doxygen (found suitable version "1.8.7", minimum required is "1.8.6") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
CMake Error at src/shogun/CMakeLists.txt:49 (MESSAGE):
  Shogun can only be built with GPL codes if the source files are in
  /home/christos/Downloads/shogun-shogun_6.1.0/src/gpl.  Please download or
  disable.

>  Configuring incomplete, errors occurred!
See also "/home/christos/Downloads/shogun-shogun_6.1.0/build/CMakeFiles/CMakeOutput.log".

I've tried this on machines running Ubuntu 14.04.3 LTS and Ubuntu 16.04.3 LTS and the same thing happens on both occasions. I guess that i have to edit something in the `src/shogun/CMakeLists.txt` file on the `# Allow to hide non-bsd compatible codes` section, but i am not sure as to what exactly, or maybe i need to copy some files to the gpl folder?

If anyone could help with this i would appreciate it greatly.

**Comment by alexanderwhatley** [comment]
+1. I'm getting the same error too.

**Comment by karlnapf** [comment]
The release doesn't come with the gpl files anymore.

Either clone https://github.com/shogun-toolbox/shogun-gpl into the `src/gpl` folder, or directly checkout from github and then do `git submodule init && git submodule update`

Let me know if that solved it

**Comment by xristos91** [comment]
It did solve it, thanks!

However i'm now getting another error during the make procedure, i'm pasting it below.

> Scanning dependencies of target ShogunVersionProtobuf
[  0%] Running C++ protocol buffer compiler on ShogunVersion.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: ShogunVersion.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  0%] Built target ShogunVersionProtobuf
Scanning dependencies of target version
[  1%] Generating version header
[  1%] Built target version
Scanning dependencies of target class_list
[  1%] Generating /home/christos/Downloads/shogun-shogun_6.1.0/build/src/shogun/base/class_list.cpp
[  1%] Built target class_list
Scanning dependencies of target rxcpp
[  1%] Creating directories for 'rxcpp'
[  1%] Performing download step (download, verify and extract) for 'rxcpp'
-- verifying file...
       file='/home/christos/Downloads/shogun-shogun_6.1.0/third_party/rxcpp/v4.0.0.tar.gz'
-- MD5 hash of
    /home/christos/Downloads/shogun-shogun_6.1.0/third_party/rxcpp/v4.0.0.tar.gz
  does not match expected value
    expected: 'feb89934f465bb5ac513c9adce8d3b1b'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/christos/Downloads/shogun-shogun_6.1.0/third_party/rxcpp/v4.0.0.tar.gz'
   timeout='none'
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
-- Retrying...
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz'
CMake Error at rxcpp-stamp/download-rxcpp.cmake:157 (message):
  Each download failed!

> error: downloading 'https://github.com/Reactive-Extensions/RxCpp/archive/v4.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

> Closing connection -1

>       --- LOG END ---

> src/shogun/CMakeFiles/rxcpp.dir/build.make:89: recipe for target 'rxcpp/src/rxcpp-stamp/rxcpp-download' failed
make[2]: *** [rxcpp/src/rxcpp-stamp/rxcpp-download] Error 1
CMakeFiles/Makefile2:238: recipe for target 'src/shogun/CMakeFiles/rxcpp.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/rxcpp.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2




Any ideas?

**Comment by xristos91** [comment]
Thanks to both of you for your help, i appreciate it. I managed to install shogun with interface to Python and i have followed the instructions in the `INTERFACES.md` file but i cannot import it. I'm using the command `from shogun import *` or `import shogun as sg`. Every time i attempt it i get the following error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 20, in <module>
    _shogun = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 19, in swig_import_helper
    return importlib.import_module('_shogun')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libshogun.so.18: cannot open shared object file: No such file or directory

I have tried this with both shogun 6.1.3 and shogun 6.1.0. My python version is 2.7.12.
I hope you can help one last time.

**Comment by karlnapf** [comment]
Google LD_LIBRARY_PATH and look out for how to set that in the documentation
