### ISSUE TITLE
CartTree is not clonable

### ISSUE THREAD

**Issue by rahul13ramesh** [shogun-toolbox/shogun#4089]
CrossValidation with CartTree() results in a systemError. In particular, when one calls the evaluate function of a CrossValidation object, the error occurs. 

Here is the complete script(with log file) that highlights the issue. 
https://gist.github.com/Red-devilz/4b2c6cdc361bf4dcd5e5dc50b8ff3eef

The error is as follows :

    SystemError: [ERROR] In file /build/shogun-V6YrEn/shogun-6.1.3/src/shogun/base/SGObject.cpp line 744: 
    Could not create empty instance of "BinaryTreeMachineNode". The reason for this usually is that get_name() of the 
    class returns something wrong, or that a class has a wrongly set generic type.

I believe the error occurs at [this line](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/evaluation/CrossValidation.cpp#L188) but I could be wrong. An identical error affects StratifiedCrossValidation() also.

**Comment by karlnapf** [comment]
You are probably right. This means our random forests are not clonable.

**Comment by karlnapf** [comment]
Actually I don't even understand why that clone is there in xvalidation. We removed the multicore version a while ago due to problems, so no clone is needed. puzzled. @vigsterkr any comments?

**Comment by vigsterkr** [comment]
this done
