### ISSUE TITLE
Compile error with json-c 0.13

### ISSUE THREAD

**Issue by awild82** [shogun-toolbox/shogun#4098]
I am compiling Shogun on Arch with gcc 7.2.1, cmake 3.10.1, swig 3.0.12, and json-c 0.13-1.
My cmake flags are `-DINTERFACE_PYTHON=ON -DBUILD_META_EXAMPLES=ON`

When I compile with make, I get the error:

/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp: In member function ‘virtual shogun::CNeuralNetwork* shogun::CNeuralNetworkFileReader::read_file(const char*)’:
/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp:54:6: error: ‘is_error’ was not declared in this scope
  if (is_error(json_network))
      ^~~~~~~~
/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp:54:6: note: suggested alternative: ‘mc_error’
  if (is_error(json_network))
      ^~~~~~~~
      mc_error
/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp: In member function ‘virtual shogun::CNeuralNetwork* shogun::CNeuralNetworkFileReader::read_string(const char*)’:
/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp:71:6: error: ‘is_error’ was not declared in this scope
  if (is_error(json_network))
      ^~~~~~~~
/home/awild/Projects/shogun/src/shogun/io/NeuralNetworkFileReader.cpp:71:6: note: suggested alternative: ‘mc_error’
  if (is_error(json_network))
      ^~~~~~~~
      mc_error
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/build.make:5362: src/shogun/CMakeFiles/libshogun.dir/io/NeuralNetworkFileReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:162: src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

If I compile with json off (`-DENABLE_JSON=OFF`), shogun compiles and installs correctly.

After a [little digging](https://json-c.github.io/json-c/json-c-0.13/doc/html/bits_8h.html), I found out that `is_error` is a macro defined by bits.h, which was provided by json-c [until 0.13](https://github.com/json-c/json-c/blob/master/ChangeLog), where it has been removed. The macro simply checked if the pointer provided was NULL, so the likely fix to this would be to replace all `is_error(ptr)` with `ptr == NULL`.

**Comment by karlnapf** [comment]
Thanks for reporting!
Want to send a patch?

**Comment by awild82** [comment]
Yep, I'll send one up in a few hours.

**Comment by meierfra** [comment]
any reason the fix #4104 was never merged to master (after 2 years)? I just tried to compile shogun 6.1.4 and stumbled into this issue
