### ISSUE TITLE
Write cookbook for cross-validation

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4107]
Very good entrance task for all GSoC'ers as everyone will have to touch those cookbooks/examples.

First read: https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/EXAMPLES.md

**Comment by prashanthduvvada** [comment]
Will take up the issue

**Comment by prashanthduvvada** [comment]
@karlnapf 
Isn't cookbook for cross validation already available?
shogun/doc/cookbook/source/examples/evaluation 
Do I have to make changes or create a new one?

**Comment by karlnapf** [comment]
You could write one for a linear svm or a random forest?

**Comment by taichi-yagami** [comment]
@karlnapf Hello Sir, I am novice programmer in ML field, I guess writing cookbook would be great start for getting started with shogun library. If there are any cookbook that needs to be created yet please let me know.

**Comment by karlnapf** [comment]
Xvalidation cookbook exists 

I suggest you start with porting an undocumented example from python to meta example, without a cookbook yet. There are dozens. Start with a simple one, eg kernel
