### ISSUE TITLE
check_format script fails to run

### ISSUE THREAD

**Issue by guruhegde** [shogun-toolbox/shogun#4118]
I faced an issue with check_format script.

It gives the following error:

>Running clang-format-3.8 against branch develop, with hash 2e6dc1490fd3e619bb318cd15ae8692b45abf4dd
>git: 'clang-format-3.8' is not a git command. See 'git --help'.

I found a workaround by modifying script as follows:

 > \-  RESULT_OUTPUT="$(git clang-format-3.8 --commit $BASE_COMMIT --diff --binary `which clang-format-3.8` $LIST)"
 > \+ RESULT_OUTPUT="$(git clang-format --commit $BASE_COMMIT --diff --binary `which clang-format-3.8` $LIST)"

After this, style check passes. 
Has anyone faced this issue? How to fix this without modifying the script?

My system: arch-linux, installed clang from source.

**Comment by geektoni** [comment]
This error is likely to be caused by not having installed the package ```clang-format-3.8``` in your system as advised [here](https://github.com/shogun-toolbox/shogun/wiki/Code-style). Clang alone is not enough to make `check_format.sh` work.
