### ISSUE TITLE
compilation under archlinux 64b (fPIC issue)

### ISSUE THREAD

**Issue by grg121** [shogun-toolbox/shogun#4122]
Hi there! I'm trying to compile the project from source code, when execute cmake I got no missing required packages but when trying to compile:
```

> 
> /usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libarprec.a(add.o): requires dynamic R_X86_64_PC32 reloc against '_ZN2mp8error_noE' which may overflow at runtime; recompile with -fPIC
> /usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libarprec.a(complex.o): requires dynamic R_X86_64_PC32 reloc against '_ZN2mp8error_noE' which may overflow at runtime; recompile with -fPIC
> /usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libarprec.a(cpr.o): requires dynamic R_X86_64_PC32 reloc against '_ZN2mp8error_noE' which may overflow at runtime; recompile with -fPIC
> /usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libarprec.a(cssx.o): requires dynamic R_X86_64_PC32 reloc against '_ZN2mp8error_noE' which may overflow at runtime; recompile with -fPIC
> 

```
someone here: #2822 added COMPILE_FLAGS "-fPIC" to the properties of libshogun (src/shogun/CMakeLists.txt) to make it work.  I've read that it should be solved in the current version but it seems something havent been configured propertly...

I'm compiling the latest version forked directly from github and I use cmake version 3.10.1, my OS is arch linux 

I've also read this: #3604 and I'm trying to figure out if I have the same problem...

**Comment by karlnapf** [comment]
Problem solved?

**Comment by grg121** [comment]
no, sorry. I got troubles with my installlation with arch so I've decided to stop trying to solve the problem and trying again with ubuntu, I forget to comment
