### ISSUE TITLE
Problem running tests  	126 - unit-GPUMatrix (Failed)

### ISSUE THREAD

**Issue by grg121** [shogun-toolbox/shogun#4133]
Hi there! I've just compiled shogun from source with only the python interface (and default c++) and I'm executing tests in order to see is everything is fine and I have one test that isn't working appropriately and I have no idea why...

I have found that some test failed because of missing python packages and I solved it just installing these packages but with this test (126, unit-GPUMatrix) the failure looks like:

https://gist.github.com/grg121/fedc687d8f39b2daf8502d8e5ba2d066

It seems that the matrix multiplication is giving always NaN as result... but I haven't changed anything in the code so it have to be something wrong in my installation or in the code itself at the repo (I doubt it) 

Any idea? I'll inform if found what's happening.

**Comment by grg121** [comment]
Hi! I've solved that... 

I decided to find the test code, I used:

```git
git grep multiplication"
```

in the test folder and the output was:

```r
unit/lib/GPUMatrix_unittest.cc:/** Tests matrix multiplication performed using ViennaCL on two CGPUMatrix objects
unit/lib/GPUMatrix_unittest.cc:TEST(GPUMatrix, matrix_multiplication_with_offset)
```

So I went to that file (unit/lib/GPUMatrix_unittest.cc) and I see that the multiplication is done with 	CGPUMatrix<float64_t> so I googled "cgpumatrix" and I see that that was a R class... Then I realiced that I didn't have R-base package installed in this machine so I installed it and it fixed the problem.

Is weird but it seems to work. I close the issue.

**Comment by grg121** [comment]
ps: I don't have R interface actived so I'm not sure why that have solved this problem but I would swear that I haven't installed anything else and I have not change the code so... if someone know what happened I would be pleased to know it :/

**Comment by karlnapf** [comment]
@grg121 Have a look at the file `GPUMatrix.h`. You will find its definition in Shogun. This has nothing to do with the R matrix ;)

```
/** @brief Represents a column-major matrix on the GPU
 *
 * This class handles matrices on the GPU using [ViennaCL](http://viennacl.sourceforge.net/)
 * as backend for managing GPU memory.
 *
 * It supports conversion to/from SGMatrix objects and Eigen3 matrices. Native
 * ViennaCL methods can also be used on the data of the matrix through vcl_matrix()
 *
 * Supported scalar types: char, uint8_t, int16_t, uint16_t, int32_t,
 * uint32_t, int64_t, uint64_t, float32_t, float64_t.
 */
template <class T> class CGPUMatrix

```

**Comment by grg121** [comment]
Oh... I didn't check that.. You're right. Actually.. yesterday I was doing some test and I got this failure again... but I execute the test again and then it work, I didn't changed anything. So... I'm lost ahaha, I can't imagine why that happens.
