### ISSUE TITLE
KNN error message cleanup

### ISSUE THREAD

**Issue by laurazh** [shogun-toolbox/shogun#4141]
I try to train a distance with LMNN and use it in KNN. However I get an error when I try to see the predicted labels.

 `from shogun import KNN, EuclideanDistance, LMNN, RealFeatures, MulticlassLabels`
 `knn.set_k(4)`
 `knn = KNN(k, EuclideanDistance(features, features), labels)`
 `knn.set_distance(lmnn.get_distance())`
 `labels_predict = knn.apply_multiclass(features)`

> SystemError: [ERROR] In file C:\bld\shogun-cpp_1512689666832\work\shogun-shogun_6.1.3\src\shogun\multiclass\KNN.cpp line 169: assertion m_num_classes>0 failed in shogun::CKNN::apply_multiclass file C:\bld\shogun-cpp_1512689666832\work\shogun-shogun_6.1.3\src\shogun\multiclass\KNN.cpp line 169

I don't understand the error.

**Comment by karlnapf** [comment]
The error is not good. I'll make it an entrance task to put a better message in there.

**Comment by karlnapf** [comment]
@laurazh there is something wrong with you labels. Can you post the output of
`labels.get_values()`

**Comment by laurazh** [comment]
@karlnapf Indeed, the labels are wrong
`array([], dtype=float64)`

To get the labels, I have :
`labels= MulticlassLabels(X.astype(numpy.float64))`
 
where X is a numpy.ndarray, so  X.astype(numpy.float64) is like `array([0., 0., 0., ..., 3., 3., 3.])`

I don't understand, what the MulticlassLabels function need as input ?

**Comment by karlnapf** [comment]
Sorry, I meant, `get_labels()`. i.e.
`sg.MulticlassLabels(np.arange(4).astype(np.float64)).get_labels()`

**Comment by karlnapf** [comment]
I just realised that you simply forget to train the knn instance. Add `knn.train()`

**Comment by karlnapf** [comment]
The task here (for GSoC applicants) is to add a meaningful error message.

**Comment by kumarnitj** [comment]
Hey what is meant by adding meaningful error message here, please do elaborate it. I want to do it

**Comment by laurazh** [comment]
@karlnapf , you were right, I forgot to train the KNN.
It works now, thks!
