### ISSUE TITLE
Error when trying to build with meta examples

### ISSUE THREAD

**Issue by krishnaw14** [shogun-toolbox/shogun#4179]
I successfully built shogun without the examples (#4174 ) but now when I am trying to do the same with meta examples, I am getting an error as follows: 
`$ cmake -DSWIG_EXECUTABLE=/usr/local/bin/swig -DINTERFACE_PYTHON=ON -DBUILD_META_EXAMPLES=ON ..
-- Could NOT find CCache (missing: CCACHE CCACHE_VERSION) 
-- Using system's malloc
CMake Error at src/shogun/CMakeLists.txt:49 (MESSAGE):
  Shogun can only be built with GPL codes if the source files are in
  /Users/krishna/shogun/src/gpl.  Please download or disable with
  LICENSE_GPL_SHOGUN=OFF.

-- Configuring incomplete, errors occurred!
See also "/Users/krishna/shogun/build/CMakeFiles/CMakeOutput.log" `

**Comment by vigsterkr** [comment]
as the error suggest you either checkout the GPL code (`git submodule update --init`) or simply disable to compilation of the GPL part with `-DLICENSE_GPL_SHOGUN=OFF`.

please next time read more carefully the error message before firing an issue
