### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by goldturtle** [shogun-toolbox/shogun#4182]
I am using Ubuntu 16.04 and did the following:

git clone https://github.com/shogun-toolbox/shogun.git
cd shogun
git submodule update --init
mkdir build; cd build; cmake ..; make -j 8 ; make install

I got the following error:

[ 71%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
In file included from /shogun/src/shogun/kernel/normalizer/KernelNormalizer.h:12:0,
                 from /shogun/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:12,
                 from /shogun/build/src/shogun/base/class_list.cpp:62:
/shogun/src/shogun/kernel/Kernel.h: In member function 'float64_t shogun::CKernel::kernel(int32_t, int32_t)':
/shogun/src/shogun/kernel/Kernel.h:213:21: error: invalid use of incomplete type 'class shogun::CKernelNormalizer'
    return normalizer->normalize(compute(idx_a, idx_b), idx_a, idx_b);
                     ^
In file included from /shogun/src/shogun/kernel/normalizer/KernelNormalizer.h:12:0,
                 from /shogun/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:12,
                 from /shogun/build/src/shogun/base/class_list.cpp:62:
/shogun/src/shogun/kernel/Kernel.h:35:8: note: forward declaration of 'class shogun::CKernelNormalizer'
  class CKernelNormalizer;
        ^
src/shogun/CMakeFiles/libshogun.dir/build.make:17409: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o' failed
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:126: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed

What should I do?
Michael.

**Comment by vigsterkr** [comment]
@goldturtle in case you just want to use shogun out of box you can simply use the conda-forge package or the ppa from here: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable

otherwise i'll try to reproduce this error but based on our buildbot 16.04 build should be working:
http://buildbot.shogun-toolbox.org:8080/#/builders/16

**Comment by goldturtle** [comment]
Looks like this happened to other people too:

https://github.com/shogun-toolbox/shogun/issues/2841

Reading the last comment, though, I wouldn't know how to change the include path in a proper way.

**Comment by vigsterkr** [comment]
Do you have somewhere else shogun already installed?

**Comment by goldturtle** [comment]
No. I'd like to compile it from scratch because I want to play around.

**Comment by gf712** [comment]
I'm guessing this can be closed
