### ISSUE TITLE
Can't compile with gcc/g++ 4.8 

### ISSUE THREAD

**Issue by grg121** [shogun-toolbox/shogun#4199]
I've been working in shogun-toolbox project few weeks ago and I could compile it fine in Ubuntu17 with gcc and g++ 7. 

Today I was going to compile it again and I get error when execute "make"

I've realiced I had enabled gcc and g++ 4.8 (which I need to do days ago in order to compile certain software). 

I've just replace gcc and g++ with version 7 and I can compile without get any troubles but I think it could be interesting to comment it, just in case nobody have noticed that and anyone could know how to solve it.

There a gist of the make output: https://gist.github.com/grg121/cdee521328d8667e5430cb6e5f67dedf

seems that isfinite and isnan functions exists since a recently version of c++/gcc and that's the problem reason. 

Maybe we could use an alternative or add a note in INSTALL.MD warning of possible troubles when using gcc 4

**Comment by vigsterkr** [comment]
what's your cmake version?
could you copy-paste `src/shogun/lib/versionstring.h` content? it's in the build directory...

**Comment by grg121** [comment]
I have cmake version 3.9.1 and the content of the mentioned file:

> #define MAINVERSION "6.2.0"

#define VERSION_EXTRA ""
#define VERSION_REVISION 0xfa7728a73
#define VERSION_RELEASE "git_fa7728a73_2018-2-3_13:13"
#define VERSION_YEAR 2018
#define VERSION_MONTH 2
#define VERSION_DAY 3
#define VERSION_HOUR 13
#define VERSION_MINUTE 13
#define VERSION_PARAMETER

**Comment by vigsterkr** [comment]
could you pull as this is a develop branch from beginning of 3rd of February and test it again, please

**Comment by grg121** [comment]
Ups, sorry I had fetched my fork but I forgot to pull...

Now:

#define MAINVERSION "6.2.0"

#define VERSION_EXTRA ""
#define VERSION_REVISION 0xfc9d43cd5
#define VERSION_RELEASE "git_fc9d43cd5_2018-3-8_20:42"
#define VERSION_YEAR 2018
#define VERSION_MONTH 3
#define VERSION_DAY 8
#define VERSION_HOUR 20
#define VERSION_MINUTE 42
#define VERSION_PARAMETER 1

Buy I'm getting the same error :/  (well, not exactly the same but pretty much the same)

(As I said, I am still able to compile with gcc7)

**Comment by gf712** [comment]
can't compile shogun with gcc4.8 anyway because we require c++17
