### ISSUE TITLE
Use fixtures / templates in LibLinear unit test

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4207]
The unit tests for `CLibLinear` are highly redundant copy paste style code -- hard to maintain/read/change.
https://github.com/shogun-toolbox/shogun/blob/develop/tests/unit/classifier/svm/LibLinear_unittest.cc

This easy entrance task is to use googletest's fixture concept to reduce the number of lines of code in this test. It should be possible to reduce things down to 1-2 explicitly coded out tests.

Useful ressources
* Grep for `TEST_F` in the shogun tests 
* https://github.com/google/googletest/blob/master/googletest/docs/Primer.md (search `TEST_F`)
* https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md (search `TYPED_TEST`)

**Comment by vigsterkr** [comment]
closing as this has been fixed
