### ISSUE TITLE
multiple kernel learning   SVMLight error

### ISSUE THREAD

**Issue by songxujing** [shogun-toolbox/shogun#4211]
Traceback (most recent call last):
  File "mul_kernel_learn.py", line 42, in <module>
    binary_svm_solver = sg.SVMLight()
AttributeError: 'module' object has no attribute 'SVMLight'

I'm a shogun beginner and I want to use this tool to do multiple kernel learning. But when I use SVMLight, I get an error. Later I learned that I needed to compile manually, but I encountered a lot of mistakes in the compilation process. I hope everyone can help me and write a detailed compilation step for me. Also, besides manual compilation, is there a more convenient way to use SVMLight? I am ubuntu16.04+python2.7+shogun

**Comment by FaroukY** [comment]
Can you add your code here please. It would help to know the problem in more details. You don't need to compile manually to use the tool, so I don't see why you would wanna compile manually. Post a snippet of your code.

**Comment by FaroukY** [comment]
Its really hard to read your code. Can you format it by clicking on the Code icon?

**Comment by songxujing** [comment]
@FaroukY 
`import shogun as sg
import numpy as np
from shogun import *
f = open('ionosphere.data')
mat = []
labels = []
# read data from file
for line in f:
    words = line.rstrip().split(',')
    mat.append([float(i) for i in words[0:-1]])
    if str(words[-1]) == 'g':
        labels.append(1)
    else:
        labels.append(-1)
f.close()
mat_train = mat[:30]
mat_test = mat[30:110]

lab_train = sg.BinaryLabels(np.array(labels[:30]).reshape((30,)))
lab_test = sg.BinaryLabels(np.array(labels[30:110]).reshape((len(labels[30:110]),)))

feats_train = sg.RealFeatures(np.array(mat_train).T)
feats_test = sg.RealFeatures(np.array(mat_test).T)
# labels_train = sg.RegressionLabels(lab_train)
# labels_test = sg.RegressionLabels(lab_test)

poly_kernel = PolyKernel(10, 2)
gauss_kernel_1 = GaussianKernel(2.0)
gauss_kernel_2 = GaussianKernel(3.0)

combined_kernel = CombinedKernel()
combined_kernel.append_kernel(poly_kernel)
combined_kernel.append_kernel(gauss_kernel_1)
combined_kernel.append_kernel(gauss_kernel_2)
combined_kernel.init(feats_train, feats_train)

binary_svm_solver = sg.SVMLight()
mkl = MKLRegression(binary_svm_solver)
mkl.set_kernel(combined_kernel)
mkl.set_labels(lab_train)
mkl.train()

beta = combined_kernel.get_subkernel_weights()
alpha = mkl.get_alphas()

combined_kernel.init(feats_train, feats_test)
labels_predict = mkl.apply_regression()

error = MeanSquaredError()
mse = error.evaluate(labels_predict, lab_test)
`

**Comment by songxujing** [comment]
`import shogun as sg
import numpy as np
from shogun import *
f = open('ionosphere.data')
mat = []
labels = []
for line in f:
    words = line.rstrip().split(',')
    mat.append([float(i) for i in words[0:-1]])
    if str(words[-1]) == 'g':
        labels.append(1)
    else:
        labels.append(-1)

f.close()
mat_train = mat[:30]
mat_test = mat[30:110]
lab_train = sg.BinaryLabels(np.array(labels[:30]).reshape((30,)))
lab_test = sg.BinaryLabels(np.array(labels[30:110]).reshape((len(labels[30:110]),)))
feats_train = sg.RealFeatures(np.array(mat_train).T)
feats_test = sg.RealFeatures(np.array(mat_test).T)

poly_kernel = PolyKernel(10, 2)
gauss_kernel_1 = GaussianKernel(2.0)
gauss_kernel_2 = GaussianKernel(3.0)

combined_kernel = CombinedKernel()
combined_kernel.append_kernel(poly_kernel)
combined_kernel.append_kernel(gauss_kernel_1)
combined_kernel.append_kernel(gauss_kernel_2)
combined_kernel.init(feats_train, feats_train)

binary_svm_solver = sg.SVMLight()
mkl = MKLRegression(binary_svm_solver)
mkl.set_kernel(combined_kernel)
mkl.set_labels(lab_train)
mkl.train()

beta = combined_kernel.get_subkernel_weights()
alpha = mkl.get_alphas()

combined_kernel.init(feats_train, feats_test)
labels_predict = mkl.apply_regression()

error = MeanSquaredError()
mse = error.evaluate(labels_predict, lab_test)
`
@FaroukY

**Comment by FaroukY** [comment]
I am away from a computer right now so I can't test  it right now on my build. Have you tried following the build instructions at:

http://www.shogun-toolbox.org/install#manual

and if so, what kind of errors did you get during the build?

**Comment by songxujing** [comment]
I built it according to the steps of this website. When I did cmake .., it gave me an error.
xujing@xujing-PC:~/shogun/build$ cmake ..
-- Could NOT find CCache (missing:  CCACHE CCACHE_VERSION) 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SWIG: Found unsuitable version "3.0.8", but required is at
  least "3.0.12" (found /usr/bin/swig3.0)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindSWIG.cmake:75 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:146 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/xujing/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/home/xujing/shogun/build/CMakeFiles/CMakeError.log".

But I installed SWIG3.0.12, I do not know why it would be 3.0.8, so I can not properly install SWIG3.0.12

**Comment by FaroukY** [comment]
Is it possible to do a full cleanup of SWIG? Uninstall everything SWIG related (purge) then reinstall it, but follow the official installation guide for installing SWIG3.0.12. This isn't really Shogun related (Since SWIG>=3.0.12 is required) so I am not sure I can help you with that.

**Comment by songxujing** [comment]
I will reconstruct it according to your suggestion. I wonder if it can be successful. If there are any more problems, I will need your help again. Thank you very much!

**Comment by songxujing** [comment]
@FaroukY
I have successfully installed SWIG3.0.12, but when I rebuild it, I get this error:
CMake Warning at src/shogun/CMakeLists.txt:257 (FIND_PACKAGE):
xujing@xujing-PC:~/shogun/build$ guration file provided by "TFLogger"
   (requested version 0.1.0) with any of the following names:

     TFLoggerConfig.cmake
     tflogger-config.cmake

   Add the installation prefix of "TFLogger" to CMAKE_PREFIX_PATH or set
   "TFLogger_DIR" to a directory containing one of the above files.  If
   "TFLogger" provides a separate development package or SDK, be sure it has
   been installed.

 CMake Warning at cmake/FindPLY.cmake:24 (message):
   ply import failure:

How can this problem be solved?

**Comment by songxujing** [comment]
@ @FaroukY
Currently, I have successfully built shogun. But when I use it, I get an error:

xujing@xujing-PC:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import shogun as sg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 20, in <module>
    _shogun = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 19, in swig_import_helper
    return importlib.import_module('_shogun')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/local/lib/python2.7/dist-packages/_shogun.so: undefined symbol: _ZTIN6shogun20CDirectorLatentModelE

**Comment by karlnapf** [comment]
Check the readme how to set the LD_LIBRARY_PATH

**Comment by songxujing** [comment]
@karlnapf 

I have already compiled shogun manually, but when I use svmlight, it give me an error:

from shogun import SVMlight
Traceback (most recent call last):
File "", line 1, in 
ImportError: cannot import name SVMlight
So, how to solve it?
Thank you!

**Comment by zym-wade** [comment]
> @FaroukY
> I have successfully installed SWIG3.0.12, but when I rebuild it, I get this error:
> CMake Warning at src/shogun/CMakeLists.txt:257 (FIND_PACKAGE):
> xujing@xujing-PC:~/shogun/build$ guration file provided by "TFLogger"
> (requested version 0.1.0) with any of the following names:
> 
> ```
>  TFLoggerConfig.cmake
>  tflogger-config.cmake
> ```
> Add the installation prefix of "TFLogger" to CMAKE_PREFIX_PATH or set
> "TFLogger_DIR" to a directory containing one of the above files. If
> "TFLogger" provides a separate development package or SDK, be sure it has
> been installed.
> 
> CMake Warning at cmake/FindPLY.cmake:24 (message):
> ply import failure:
> 
> How can this problem be solved?

hello！Now I am also compiling shogun manually,and I have encountered the same problem as you, I would like to ask you how to solve this problem?
Thank you!

**Comment by karlnapf** [comment]
`pip install ply`
or compile with `-DBUILD_META_EXAMPLES=Off`
