### ISSUE TITLE
from shogun import svmlight error

### ISSUE THREAD

**Issue by songxujing** [shogun-toolbox/shogun#4212]
I have already compiled shogun manually, but when I use svmlight, it give me an error:

>>> from shogun import SVMlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name SVMlight
 So, how to solve it?
Thank you!

**Comment by songxujing** [comment]
@ @vigsterkr

**Comment by geektoni** [comment]
@songxujing It appears that you've written ```SVMlight``` instead of ```SVMLight```. If that won't solve your problem you will need to give us more details to enable us to actually help you in a constructive way.
