### ISSUE TITLE
Build on windows msvc 2015 fails on Eigen including pthread.h

### ISSUE THREAD

**Issue by fyoda** [shogun-toolbox/shogun#4217]
I'm trying to build shogun 6.1.3 on windows with msvc 2015 using cmake. Here is the log of the configuration generated by cmake:

[https://gist.github.com/fyoda/fca418aa6be771b9c9da5b4193326945](url)

When I build the solution generated for MSVC 2015 I have problems with eigen3. The Eigen3 has downloaded automatically but then it fails to build. Here there is a portion of the MSVC log:

[https://gist.github.com/fyoda/f59cdefb4d8e62b2ce3bfcb4ac8c5fd4](url)

By looking at the CMakeError.log the error seems related to Eigen that tries to include pthread.h

[https://gist.github.com/fyoda/9c1ac9b2fdc418f9aff6910e2078ff85](url)

I don't understand why Eigen tries to include pthread.h on windows.

**Comment by karlnapf** [comment]
None of the above links work

**Comment by karlnapf** [comment]
Thanks for reporting.
The windows build is quite experimental.
There definitely is a problem with eigen not being able to detect your blas setup (second gist)

**Comment by vigsterkr** [comment]
@karlnapf :D

@fyoda i cannot open any of the linked gists... but as you can see on appveyor MSVC 2015 + shogun with bundled eigen just works fine... so unless you can give me some logs i'll close this bug as this seems to be your error

**Comment by fyoda** [comment]
The error doesn’t appear if use the x64 build

**Comment by vigsterkr** [comment]
@fyoda i'm closing this one as this is really some local setup problem.... in case you think that it's not then plz post the ***full*** cmake output not just a part of it.

**Comment by fyoda** [comment]
The error appears when I generated the msvc solution for x86. I doesn’t appear when generation for Win64. Later I will report the cmake log

**Comment by vigsterkr** [comment]
@fyoda oh! x86 build was ***never*** tested... hence it was never intended to work. buuuuuut even in that case this seems to be an eigen related problem actually, not shogun

**Comment by vigsterkr** [comment]
@fyoda if you jump in gitter or irc we could get your problems fixed quicker :)
