### ISSUE TITLE
Update NeuralLayer classes and tests with linalg

### ISSUE THREAD

**Issue by grig-guz** [shogun-toolbox/shogun#4232]
Multiple NeuralLayer functions and tests use Eigen/vanilla  linear algebra operations. For example, 
in NeuralLinearLayer:
https://github.com/shogun-toolbox/shogun/blob/c8c66e61ebc8b6e90cbe726df7557c7291310cab/src/shogun/neuralnets/NeuralLinearLayer.cpp#L97

or in NeuralRectifiedLinearLayer_unittest:
https://github.com/shogun-toolbox/shogun/blob/c8c66e61ebc8b6e90cbe726df7557c7291310cab/tests/unit/neuralnets/NeuralRectifiedLinearLayer_unittest.cc#L90

This needs to be updated with single linalg calls.

**Comment by saatvikshah1994** [comment]
Could I work on this simultaneously with #4233

**Comment by karlnapf** [comment]
@saatvikshah1994 go for it! :) Looking forward to seeing a patch here

**Comment by saatvikshah1994** [comment]
I think this issue can be closed now.

**Comment by karlnapf** [comment]
well done :)

**Comment by karlnapf** [comment]
ah well, actually we also want to linalg-ize the code itself, not just the tests
