### ISSUE TITLE
Redundant code in tests for Neural******Layer classes

### ISSUE THREAD

**Issue by grig-guz** [shogun-toolbox/shogun#4233]
A lot of code gets repeated over and over in some tests, see
https://github.com/shogun-toolbox/shogun/blob/c8c66e61ebc8b6e90cbe726df7557c7291310cab/tests/unit/neuralnets/NeuralRectifiedLinearLayer_unittest.cc#L52

https://github.com/shogun-toolbox/shogun/blob/c8c66e61ebc8b6e90cbe726df7557c7291310cab/tests/unit/neuralnets/NeuralRectifiedLinearLayer_unittest.cc#L111

This needs to be updated with test fixtures and templates to avoid repetitiveness.

**Comment by karlnapf** [comment]
go for it!

**Comment by saatvikshah1994** [comment]
I think this issue can be closed now.

**Comment by karlnapf** [comment]
Definitely.
