### ISSUE TITLE
dirent.h is missing when installed

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4238]
it came out in #4231 that we are not shipping the `dirent.h` just have it when we compile... which makes compilation of dll and static lib successful but compiling against an installed libshogun will not be possible as we dont ship this dirent.h :(

**Comment by vigsterkr** [comment]
@fyoda actually i've just checked, MSDirent is being installed to `shogun/lib/external/MSDirent` so there should be no problem with `dirent.h`.

**Comment by vigsterkr** [comment]
can you actually paste me a compile command and the corresponding error when you observe problems with `dirent.h`?

**Comment by fyoda** [comment]
@vigsterkr 

```
Starting: "E:\Software\Qt\Tools\QtCreator\bin\jom.exe" 
	E:\Software\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fd..\build_debug\_obj\shoguntest.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -DWIN64 -DDEBUG -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I..\libs\shogun\include -IE:\Software\Qt\5.9.3\msvc2015_64\include -IE:\Software\Qt\5.9.3\msvc2015_64\include\QtGui -IE:\Software\Qt\5.9.3\msvc2015_64\include\QtANGLE -IE:\Software\Qt\5.9.3\msvc2015_64\include\QtCore -I..\build_debug\_moc -IE:\Software\Qt\5.9.3\msvc2015_64\mkspecs\win32-msvc -Fo..\build_debug\_obj\ @C:\Users\myUser\AppData\Local\Temp\main.obj.12376.0.jom
main.cpp
C:\Users\myUser\Desktop\shoguntest\libs\shogun\include\shogun/lib/any.h(162): warning C4100: 'other': unreferenced formal parameter
C:\Users\myUser\Desktop\shoguntest\libs\shogun\include\shogun/io/SGIO.h(16): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory
jom: C:\Users\myUser\Desktop\shoguntest\src\Makefile.Debug [..\build_debug\_obj\main.obj] Error 2
```

**Comment by fyoda** [comment]
@vigsterkr I simply add the shogun's include path to my project, then link the .dll against the main.cpp.

**Comment by vigsterkr** [comment]
@fyoda yeah unfortunately that's not enough :) you use qmake? in case of cmake i could tell you how to use shogun, but i'm not so sure yet how to that with Qt build framework

**Comment by fyoda** [comment]
I'm sorry @vigsterkr :), yes I use qmake. I'll send you more information when I go back to my PC.

**Comment by fyoda** [comment]
I'm that the problem is that there is no path specified when `dirent.h` is included

**Comment by vigsterkr** [comment]
@fyoda yes that's the problem,... but that's actually specified in the target cmake, i.e. ShogunTarget.cmake if you'd include shogun like that into your project.

**Comment by fyoda** [comment]
@vigsterkr I understand the point but I don't know how to include the generated ShogunTarget.cmake in my Qt project.

**Comment by fyoda** [comment]
Adding those paths to my .pro file solve the issue.

**Comment by vigsterkr** [comment]
@
