### ISSUE TITLE
port meta examples to new API

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4247]
All meta examples should

* use the generic `put` and `get` methods rather than custom getters setters
* use factory methods, instead of parametrised  constructors, to create new objects, load files, etc (and subsequent put/get calls). Pls use the kwargs feature (see `meta_api/kwargs.sg`
* dont use types apart from the base types: `Machine, Kernel, Labels (not RegressionLabels, etc), Features`

See https://github.com/shogun-toolbox/shogun/blob/develop/examples/meta/src/binary/kernel_support_vector_machine.sg for a fully ported example

Note that this might involve creating new factory methods.

**Comment by karlnapf** [comment]
This is still open, there are still some

* constructor calls ( to be replaced by factory calls)
* specialized method calls (should be refactored to `put/get` or otherwise)

**Comment by ArtemSkrebkov** [comment]
I think I can help to finalize it. Is it still relevant?

**Comment by karlnapf** [comment]
I think this should be almost done?
