### ISSUE TITLE
Drop CLabelsFactory class

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4274]
1. Replace all `cLabelsFactory` calls with
`binary_labels`
`multiclass_labels`

(note that those methods return `Some`)

or alternatively with `obj->as<CBinaryLabels>()` etc

2. Remove the `as_binary` from the `CLabelsFactory`
3. Once all methods are removed, remove the class itself

@vinx13 @shubham808 @FaroukY those are another good candidate for you

**Comment by vigsterkr** [comment]
i reckon this can be closed because of 02ee9a54554a8b6a50f502f58ffe1c05a0a66a32 right @shubham808 ?

**Comment by shubham808** [comment]
yes sure :+1:
