### ISSUE TITLE
drop HAVE_CXX11 macro

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4284]
there's still some places where we have an `ifdef HAVE_CXX11`, but since 6.1.0 release shogun requires that your compile actually supports c++11.

just do a `git grep HAVE_CXX11` and eliminate those macro checks.

**Comment by abhishek-1991** [comment]
Hi Viktor,

I would like to take up this task.

Thanks and Regards,
Abhishek.

**Comment by vigsterkr** [comment]
@abhishek-1991 sure thing, since this is a rather large effort, just start with a file where you find this macro and send in patches.

**Comment by abhishek-1991** [comment]
Hi Victor,

Sorry for returning after long time. I was busy else where. I pulled the latest build today but it is giving compilation error for file "LaRank.cpp". I am using g++ 5.4.0

Thanks and Regards,
Abhishek.
