### ISSUE TITLE
Factory methods should be registered as %newobject in SWIG interface

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4321]
see http://www.swig.org/Doc3.0/Customization.html `12.2 Object ownership and %newobject`

**Comment by vigsterkr** [comment]
@karlnapf maybe @shubham808 could take a go on this. this is a blocker for 6.2.0

**Comment by shubham808** [comment]
sure :) I am looking into it

**Comment by karlnapf** [comment]
ah yes very good point. @shubham808 put it on your todo list. But dont do it this week pls, there is too many other things that need attention first. This can count as a "meta example patch" so just do it instead of porting an example next week or so

**Comment by vigsterkr** [comment]
this is not needed anymore since shared_ptr...
