### ISSUE TITLE
Towards better xvalidation

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4334]
- [ ] Introduce iterator interface for pairs of train/validation indices in `CSplittingStrategy`
- [ ] Remove `CFeatures` training data from `CMachine` state
- [ ] Remove `CLabels` training data from `CMachine` state
- [ ] While the above two are being worked on, we could have a `CMachine::clone_without_data` that allows to clone a machine without cloning the data as well, to be used in xvalidation code.

- [ ] Introduce `CMachine::train(CFeatures*, CLabels*)` (user API)
- [ ] If possible, introduce `CMachine::train(const CFeatures*, const CLabels*)`, via propagating constness in downstream calls. The above user API call would be a wrapper that just calls this method eventually.

- [ ] Introduce a view for features, in the lines of `CFeatures* CFeatures::subset(SGVector,index_t>), that returns a new instance with an active subset, but the same underlying data (no copy)
- [ ] Same view for `CLabels`

- [ ] Rewrite x-validation
 * use iterator interface for subsets
 * clone machine (not data) in every fold
 * create new views for training/validation features/labels in every fold
 * use const methods
 * enable multithreading

**Comment by karlnapf** [comment]
@vinx13 this is for you

**Comment by gf712** [comment]
@karlnapf do you know how much of this is still relevant?

**Comment by karlnapf** [comment]
I think quite some stuff has been done, so closing.
