### ISSUE TITLE
Fail to run the example of Multiple Kernel Learning

### ISSUE THREAD

**Issue by daifeng2016** [shogun-toolbox/shogun#4341]
I have installed the shogun library using python command "conda install -c conda-forge shogun", and some examples can work well.  However, when I test the example of  "Multiple Kernel Learning", some errors arise, such as:
 1) NameError: name 'SVRLight' is not defined
 2)  SystemError: [ERROR] In file C:\bld\shogun-cpp_1512689666832\work\shogun-shogun_6.1.3\src\shogun\classifier\mkl\MKL.cpp line 438: Interleaved MKL optimization is currently only supported with SVMlight
Moreover, I could not use some classes, like GMM. I am wondering if some function fails to work in the python version.
Have anyone met such probelms? How to solve the above problems?

**Comment by karlnapf** [comment]
Hi!
This is due to the licensing of SVMLight (we cannot change that). You will have to compile shogun yourself if you want to use svmlight.

What is the error for GMM? There is a LAPACK dependency there. @dougalsutherland is lapack enabled in the conda build?

**Comment by daifeng2016** [comment]
Thank you for your explanation @karlnapf , the error for GMM is "name 'GMM' is not defined ".

**Comment by karlnapf** [comment]
This is due to a LAPACK dependency. We got rid of this in the latest development version, and this will be in conda with the next release.

Though still it seems weird that lapack is not active in conda, will check that

**Comment by daifeng2016** [comment]
@vigsterkr  Yes, I am using shogun with python version on windows 10 system, and many problems happend.

**Comment by vigsterkr** [comment]
@daifeng2016 yeah unfortunately the windows version has no lapack backend... :( as said by @karlnapf this particular error is fixed in develop, but has not been released yet

**Comment by daifeng2016** [comment]
@vigsterkr Thank you, wishing to see the latest version.

**Comment by dougalsutherland** [comment]
Sorry I didn't see this last week (my github notifications are an endless swamp). Yes, there's no lapack backend on the Windows build yet (https://github.com/conda-forge/shogun-cpp-feedstock/issues/13).

**Comment by luoagnes** [comment]
I compile shogun by hand in ubuntu:14.04 according to INSTALL.md.  in python command line environment, "import shogun" is right, but "from shogun import SVMLight" error and name 'CombinedKernel' is not defined, Why? And how to solve it ?

**Comment by vinx13** [comment]
hi @luoagnes , we are moving to factory methods, you can use `kernel('CombinedKernel')` and `machine('SVMLight')` to create them

**Comment by karlnapf** [comment]
(also need to compile shogun using the GPL compatible submodules if you want to use SVMLIGHT
