### ISSUE TITLE
Clean up CFeatures::dense_dot implementations

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4353]
Currently, there is a ton of copy pasted code in `CFeatures::dense_dot` (in the `.cpp`).

This task is to use C++ (11) features to replace this with a templated version that avoids the heavily redundant code.
Or even use linalg as that will be faster.

Ask if you need a pointer to get started

**Comment by nan-galad** [comment]
I'll bite. Totally new to making open-source contributions and looking to start getting involved in the community. Any pointers would be appreciated!

**Comment by karlnapf** [comment]
This task requires a bit of C++ experience. First have a look at the code and see if you can find things you don't like. Then we can discuss

**Comment by nan-galad** [comment]
It's entirely possible that I'm not totally qualified for this fix as most of my experience lies outside of C++. It's a language I'd like to get more experience with, but at the same time I don't want to waste everyone's time floundering with an issue.

**Comment by ck244** [comment]
Thinking of taking a crack at this. @karlnapf did you mean the code in DenseFeatures.cpp, starting line 633?

**Comment by karlnapf** [comment]
yes, please go for it
 
* try to use SIMD where possible (linalg)
* avoid redundant code
* templates are powerful

**Comment by karlnapf** [comment]
and please no manual template spezialization for different types of the dot products.
