### ISSUE TITLE
start hiding Machines from SWIG

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4354]
As we now use `p = machine("Perceptron")`, we do not need to expose `CPerceptron` to swig anymore.
This task is to check which machines are solely used in the meta examples, and not in the old undocumented examples or the ipython notebooks.
Then, remove those classes from the corresponding `.i` files.

E.g. in `Classifier.i`, remove
```
%rename(Perceptron) CPerceptron;
...
%include <shogun/classifier/Perceptron.h>
```
and in `Classifier_includes.i`, remove
```
 #include <shogun/classifier/Perceptron.h>
```

Make sure to run the tests for a modular interface, and grep the IPython notebooks for appearances of the removed class *and port them to the factory if possible)

**Comment by karlnapf** [comment]
This is a good weekly task regarding examples, @shubham808 @vinx13 @FaroukY

**Comment by karlnapf** [comment]
This is still relevant and a subset of #4463

**Comment by gf712** [comment]
I think all machines have been hidden from SWIG now
