### ISSUE TITLE
clean up linalg unittest

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4383]
E.g. the `Eigen3_operations_unittest.cc` only tests for float64_t.

Make the tests typed so they are executed for every shogun type! See e.g. `SGObjectAll_unittest.cc` for how to do that.

Next, use fixtures to define the necessary matrix objects to avoid the huge amount of redundant code in there

**Comment by gf712** [comment]
Hi! 
Do you still need help with this issue? I just started having a look at how the typed tests work in LDA_unittest.cc. It's pretty neat!

For the linalg tests would you test it just with floats, so it would be a refactor of `Eigen3_operations_unittest.cc`, i.e. the tests are written with floats, so just need to extend to `float32_t` and `floatmax_t` using `TYPED_TEST`. Or, also perform tests with `uint8_t`, `int16_t`, `int32_t` and `int64_t` where possible, which I assume requires a change of the values being tested to work as expected with both int and float types?

**Comment by karlnapf** [comment]
Welcome! :)
Yes totally, this is a good way to get involved with our testing system!
We would want to test the operations for all types that they are supported with. Sometimes that is only floats (some solvers for example), sometimes it is more (add) You can see the definitions [here](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/LinalgBackendBase.h), `DEFINE_FOR_ALL_PTYPE` and the like. It is quite a mess with Macros and all that in there, but basically every operation is explicitly defined for a number of types. I think the first step would be to define the test types in the unit test locally and refactor, then define them globally somehow so we can re-use things.

**Comment by karlnapf** [comment]
The best thing would be to globally define the types for googletest to match things like all shogun ptypes, all floating point ptypes, all numerical ptypes, etc

**Comment by gf712** [comment]
OK! Thank you. For now I am defining the test case types locally. I agree that it is a bit messy to rewrite the types each time.
I will send a PR when that is done, and then can have a look at how to clean up the code a bit!

**Comment by karlnapf** [comment]
No idea. In fact, we have been moving towards getting rid of `CMath::` functions recently, in favour of using `std::` directly. So there should be no need for `powl` anymore.
@vigsterkr do you know why `pow` is still there, we have removed most others
@vinx13 maybe you know?

**Comment by vinx13** [comment]
i have no idea. but here i think it is ok to rename `powl` to `pow`

**Comment by karlnapf** [comment]
Thanks!

**Comment by gf712** [comment]
I think this issue has been addressed
