### ISSUE TITLE
how to install shogun for mingw on windows using qt c++

### ISSUE THREAD

**Issue by muhannad35990** [shogun-toolbox/shogun#4391]
hi all 
I'm trying to use shogun in qt project but I cant compile shogun for mingw on windows
please help

**Comment by karlnapf** [comment]
Shogun natively compiles under windows, see our [appveyor config](https://github.com/shogun-toolbox/shogun/blob/develop/appveyor.yml) and [build](https://ci.appveyor.com/project/vigsterkr/shogun/branch/develop)
Whether Minigw works is unclear to me. @vigsterkr ?

**Comment by muhannad35990** [comment]
thanx for reply
I'm stuck for two weeks on compiling shogun toolbox
I'm working on project in master letter using qt creater and minGW (
www.mingw.org/) for c++ GUI
I want shogun toolbox to be compiled using and can use it as ".a" or ".lib"
file to be added to qt project configuration
please help me

**Comment by karlnapf** [comment]
As said, the project compiles  *natively* without having to use mingw and that is the recommended solution here. All the information you need for that is above. Using anaconda, there are also windows binaries available (only the c++ core, no interfaces as of now AFAIK, patch welcome) https://anaconda.org/conda-forge/shogun

**Comment by muhannad35990** [comment]
thank you very mach that's exactly what I needed
thanks alot
