### ISSUE TITLE
Stuck compilation in debug mode MSVC 2015

### ISSUE THREAD

**Issue by fyoda** [shogun-toolbox/shogun#4394]
Hello,

I'm have built shogun both in debug and release mode using visual studio 2015, properly changing the  RT library for the debug build.
After importing the dll in my project I'm experiencing a super slow compilation in debug mode. The build process get stuck at linking phase without generating the final .exe.

Some else experienced the same problem? Can it be related to the large size of the debug dll of shogun?
Any suggestion is welcome :)

Thanks

**Comment by vigsterkr** [comment]
see #4443
plz try with VS 2017 or later
