### ISSUE TITLE
Error in compiling manually 

### ISSUE THREAD

**Issue by marscrazy** [shogun-toolbox/shogun#4401]
Thanks for your attention and please help me. I was trying to compile shogun manually. However, there was an error.

First, I ran the following command.

`cmake -DPYTHON_INCLUDE_DIR=/home/123/anaconda3/include/python3.6m  -DPYTHON_LIBRARY=/home/123/anaconda3/lib/python3.6/ -DPYTHON_PACKAGES_PATH=/home/123/anaconda3/lib/python3.6/site-packages/ -DINTERFACE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/123/shogun ..`

Then, I ran "make", and an error occured.

```
/home/123/shogun-shogun_6.1.3/src/gpl/shogun/classifier/svm/SVMSGD.cpp:74:38: error: ‘binary_labels’ was not declared in this scope
  auto labels = binary_labels(m_labels);
                                      ^
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/__/gpl/shogun/classifier/svm/SVMSGD.cpp.o] Error 1
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
```

**Comment by geektoni** [comment]
Hi @marscrazy! Currently, the 6.1.3 version of Shogun has a bug caused by some new functionalities introduced into the Shogun's GPL code. If you do not have any particular reason to use specifically the 6.1.3 release, I suggest you to try to build against the latest development version.

**Comment by marscrazy** [comment]
Thanks for noticing. I successfully compiled with the old version (4.0.0). The MKL toolkit inside Shogun is very helpful to me. I hope that the development of the new version will go smoothly.
