### ISSUE TITLE
problem when install Shogun on window7 with Python3.7

### ISSUE THREAD

**Issue by yoyouitikon** [shogun-toolbox/shogun#4403]
Hi, I want to install shogun in my computer. My computer in Window7 and i installed Anaconda firstly. Then under Anaconda Prompt,  run " conda install -c conda-forge shogun".  I got the following error information:

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package
'conda-forge::automat-0.7.0-py_1'.
CondaError: Cannot link a source that does not exist. C:\anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
Rolling back transaction: done
CondaError: Cannot link a source that does not exist. C:\anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

How can I solve this problem? Can shogun run under Window7? 

Thank you very much for your kind help!

**Comment by geektoni** [comment]
Hello @yoyouitikon. From what I can see I think it is an error more related to your Anaconda installation than to Shogun itself. We can be of little use in this case. The best thing you can do now is to google the error and try to fix it before trying to install Shogun.

**Comment by yoyouitikon** [comment]
Dear Giovanni De Toni, 

  Thanks a lot for your kind answer. I did google a lot to solve this problem, however, nothing can be successfully. Besides intalling Anaconda, is there any other way to install Shogun in Python? 

  Thank you very much for your kind help!

  Best regards,
  @yoyouitikon
-----"Giovanni De Toni" <notifications@github.com> wrote: -----
To: "shogun-toolbox/shogun" <shogun@noreply.github.com>

**Comment by karlnapf** [comment]
shogun is also part of vcpkg
https://github.com/Microsoft/vcpkg/blob/master/CHANGELOG.md
