### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4428]
I just noticed that in all license headers we have `(see LICENSE file)` but in the whole project there is no such file (only `COPYING`). And in the [wiki](https://github.com/shogun-toolbox/shogun/wiki/LICENSE) the LICENSE file is for GPL.. Doesn't this need updating?

**Comment by karlnapf** [comment]
Definitely :)
I thought we had updated the file ...
Wanna go ahead and clean this up a bit?

**Comment by gf712** [comment]
Done!
