### ISSUE TITLE
When should we prioritise using the STL algorithms?

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4431]
I am currently writing some new print functions for SGObjects and I need to iterate over a map. There are several ways to do this now. The two ways I would use is a range iterator in a for loop or `std::for_each` with a lambda. In my case this would look like this:
- For loop:
```
for (const auto &it: self->get_map())
{
    auto tag = it.first;
    auto any_pprop = it.second.get_properties();

    if (any_pprop.has_property(pprop)) {
        auto type = demangled_type(it.second.get_value().type_info().name());
        SG_PRINT("\t%s (%s): %s\n", tag.name().c_str(), any_pprop.get_description().c_str(),
                 type.c_str());
        num_param++;
        }
}
```  
- `std::for_each`
```
std::for_each(self->map.begin(), self->map.end(),
              [&pprop, &num_param, &io=io](const auto& it){
                  auto tag = it.first;
                  auto any_pprop = it.second.get_properties();

                  if (any_pprop.has_property(pprop)) {
                      auto type = demangled_type(it.second.get_value().type_info().name());
                      SG_PRINT("\t%s (%s): %s\n", tag.name().c_str(), any_pprop.get_description().c_str(),
                               type.c_str());
                      num_param++;
                  }
              });
```
They are both the same, but the lambda has its own scope which is a bit awkward, as we need to remember to capture `io` when using `SG_PRINT` (or capture `this` by value).
My question is: is it worth always sticking to one over the other, particularly inside the same class, or just do what looks more readable at the time? It would be nice to be consistent, no?

**Comment by karlnapf** [comment]
bringing the io in is awekward indeed. I think this issue is just for printing though, so despite the fact that we usually try to stick to the STL recently, I think you can do an explicit loop here. Or you just bring the io into the scope.
BTW why do you want to print? This should not be necessary as most user API should just return strings (which is supported by swig)

**Comment by gf712** [comment]
This would be a way to replace `print_modsel_params` with something more generic like `print_params(ParameterProperties pprop)`, since we would now have implement a `print_gradient_params` and so on, no?

**Comment by karlnapf** [comment]
Just drop this. We can have the string returning method with a filter and potentially some ready packaged cases for things like hyperparamters

**Comment by karlnapf** [comment]
I think it is best if the caller prints for himself. Think IPython/swig where this happens anyways, and in C++ the caller can then choose where and how to print. Could even use `sg_io` but the point is that there is choice and we don't need to manage this so less code

**Comment by gf712** [comment]
I am just thinking where else I can easyly see the description of the args/params? For example if I want to know what `log_width` is I can right now check it by typing `sg.GaussianKernel().print_modsel_params()` and see `log_width (Kernel width in log domain): float64`. That is the only way (other than going to the docs), right?

**Comment by karlnapf** [comment]
Yes. I guess it would be the above, and then
```
In [3]: sg.GaussianKernel().help("log_width")
Out[3]: Sorry no description entered
```

**Comment by karlnapf** [comment]
Or Pythonic: `[myobj.help(param) for param in myobj.hyperparameters()]`

**Comment by gf712** [comment]
Closing this issue because the main question has been answered
