### ISSUE TITLE
Octave interface cannot be built with Octave 4.4

### ISSUE THREAD

**Issue by ChrisTX** [shogun-toolbox/shogun#4434]
The Octave interface cannot be built with the current Octave 4.4, since `<octave/config.h>` does not exist any longer and was replaced by `<octave/octave-config.h>`. Even after changing that, there's some undeclared symbol errors, and a huge number of deprecated declaration warnings being generated.

**Comment by karlnapf** [comment]
Thanks a lot for reporting!
Patches welcome as this should be fixed before a release
