### ISSUE TITLE
Use of auto in cpp meta examples

### ISSUE THREAD

**Issue by avramidis** [shogun-toolbox/shogun#4436]
This issue is relevant to #4423 In this PR the aim was to convert [this python script](https://github.com/shogun-toolbox/shogun/blob/develop/examples/undocumented/python/features_string_char.py) to a meta example.

When using the factory method to create a CStringFeatures object it is returned as CFeatures. This is fine, however, in the case of generating the meta examples that use this functionality the return object is stored as auto. This doesn't allow the use of CStringFeatures functions.

The problem is caused by the auto in the code below
https://github.com/shogun-toolbox/shogun/blob/d751f6615a2b2009ff44c8a6bc83031ca5e3e60c/examples/meta/generator/targets/cpp.json#L14

Any ideas or pointers of how to fix this?

**Comment by karlnapf** [comment]
As discussed, I think this is possible with `put` `get`, and potentially registering a lazy executed function with `get`, as done [here](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/clustering/KMeansBase.cpp#L367) and the corresponding example
