### ISSUE TITLE
Windows Compilation : error C2783: 'void shogun::sg_generic_free(T *)': could not deduce template argument for '__formal'

### ISSUE THREAD

**Issue by kikish** [shogun-toolbox/shogun#4443]
Hello,

I have a problem when I try to compile shogun under Windows and Visual Studio 2015.
Within Visual Studio, I launch the Build process on the "shogun" project and I have the following error:
```
12>D:\Arezki\Downloads\shogun\src\shogun/io/streaming/ParseBuffer.h(274): error C2783: 'void shogun::sg_generic_free(T *)': could not deduce template argument for '__formal'
12>  D:\Arezki\Downloads\shogun\src\shogun/lib/memory.h(159): note: see declaration of 'shogun::sg_generic_free'
```

Do have an idea on what is going wrong ? Or what I missed ?

Regards,

Arezki.

**Comment by gf712** [comment]
Hi,
That seems to be due to a bug with `constrexpr` in VS2015, according to [this](https://stackoverflow.com/a/42811804). Apparently it can be fixed by upgrading to VS2017 (or using another compiler).

**Comment by gf712** [comment]
Ah, nevermind that expression should give a `static const`, not a `constexpr`, so that should work fine.. It might still be worth trying out on VS2017 if you have it?

**Comment by vigsterkr** [comment]
closing as adding support for 2015 in develop would be way too much work.
@kikish if you want to compile with VS 2015, please try using master branch (latest release)
