### ISSUE TITLE
install shogun failed

### ISSUE THREAD

**Issue by joy1314** [shogun-toolbox/shogun#4445]
I met the error like this when I run the 'make'
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
-- downloading...
     src='https://github.com/ReactiveX/RxCpp/archive/4.1.0.tar.gz'
     dst='/home/joy1314bubian/文档/shogun/third_party/rxcpp/4.1.0.tar.gz'
     timeout='none'
CMake Error at /home/joy1314bubian/文档/shogun/build/rxcpp/src/rxcpp-stamp/download-rxcpp.cmake:27 (message):
  error: downloading
  'https://github.com/ReactiveX/RxCpp/archive/4.1.0.tar.gz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

src/shogun/CMakeFiles/rxcpp.dir/build.make:89: recipe for target 'rxcpp/src/rxcpp-stamp/rxcpp-download' failed
make[2]: *** [rxcpp/src/rxcpp-stamp/rxcpp-download] Error 1
CMakeFiles/Makefile2:317: recipe for target 'src/shogun/CMakeFiles/rxcpp.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/rxcpp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
How to fix this error?
Thank you very much

**Comment by karlnapf** [comment]
this has to do with your local setup not liking https connections
you could download the archive yourself and place it at the mentioned folder to skip the step
