### ISSUE TITLE
A Problem of Cross Validation on Multiple Kernel Learning

### ISSUE THREAD

**Issue by joy1314** [shogun-toolbox/shogun#4447]
I have installed shogun by conda install -c conda-forge shogun
I have written codes to make Cross Validation on Multiple Kernel Learning.

   `def Bin_MKLClassficataion(f_feats_train,f_labels_train):
    features_train = RealFeatures(f_feats_train)
    labels_train = BinaryLabels(f_labels_train)
    

    poly_kernel = PolyKernel(10, 2)
    gauss_kernel_1 = GaussianKernel(2.0)
    gauss_kernel_2 = GaussianKernel(3.0)
    
    
    combined_kernel = CombinedKernel()
    combined_kernel.append_kernel(poly_kernel)
    combined_kernel.append_kernel(gauss_kernel_1)
    combined_kernel.append_kernel(gauss_kernel_2)
    combined_kernel.init(features_train, features_train)
    
    libsvm = LibSVM()
    svm = MKLClassification(libsvm)
    svm.set_interleaved_optimization_enabled(False)
    svm.set_kernel(combined_kernel)
    

    splitting_strategy = StratifiedCrossValidationSplitting(labels_train, 5)
    evaluation_criterium = AccuracyMeasure()
    cross = CrossValidation(svm, features_train, labels_train, splitting_strategy, evaluation_criterium)
    cross.set_autolock(False)
    cross.set_num_runs(2)
    
    
    mkl_obs = ParameterObserverCV(True)
    cross.subscribe_to_parameters(mkl_obs)
    
    
    result = CrossValidationResult()
    result = CrossValidationResult.obtain_from_generic(cross.evaluate())
    
    
    obs = mkl_obs.get_observation(0)
    fold = obs.get_fold(0)
    machine = MKLClassification.obtain_from_generic(fold.get_trained_machine())
    
    
    k = CombinedKernel.obtain_from_generic(machine.get_kernel())
    w = k.get_subkernel_weights()
    
    return result,k,w`

I met the error like this 
    result = CrossValidationResult.obtain_from_generic(cross.evaluate())

SystemError: [ERROR] In file /home/conda/feedstock_root/build_artifacts/shogun-cpp_1540034967896/work/src/shogun/classifier/mkl/MKL.cpp line 896: Assertion R >= 0 failed!

How to fix this?
Thank you very much.

**Comment by karlnapf** [comment]
This looks fine. In order to help you, we would need a fully stand-alone example that isolates the error

**Comment by joy1314** [comment]
@karlnapf I use the data from examples to have a try. But I have the same error. The codes is like this
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
from sklearn.model_selection import KFold

from shogun import RealFeatures
from shogun import BinaryLabels
from shogun import MKLClassification
from shogun import CombinedKernel
from shogun import LibSVM
from shogun import StratifiedCrossValidationSplitting
from shogun import CrossValidation
from shogun import AccuracyMeasure
from shogun import CrossValidationResult
from shogun import ParameterObserverCV
from shogun import PolyKernel
from shogun import GaussianKernel
from shogun import MeanSquaredError


from getdata import get_data
from getdata import get_label_data
from getdata import remove_allzeros_lines

def Bin_MKLClassficataion(f_feats_train,f_labels_train):
    features_train = RealFeatures(f_feats_train)
    labels_train = BinaryLabels(f_labels_train)

    
    poly_kernel = PolyKernel(10, 2)
    gauss_kernel_1 = GaussianKernel(2.0)
    gauss_kernel_2 = GaussianKernel(3.0)
    
    
    combined_kernel = CombinedKernel()
    combined_kernel.append_kernel(poly_kernel)
    combined_kernel.append_kernel(gauss_kernel_1)
    combined_kernel.append_kernel(gauss_kernel_2)
    combined_kernel.init(features_train, features_train)
    
    libsvm = LibSVM()
    svm = MKLClassification(libsvm)
    svm.set_interleaved_optimization_enabled(False)
    svm.set_kernel(combined_kernel)
    
    splitting_strategy = StratifiedCrossValidationSplitting(labels_train, 5)
    evaluation_criterium = AccuracyMeasure()
    cross = CrossValidation(svm, features_train, labels_train, splitting_strategy, evaluation_criterium)
    cross.set_autolock(False)
    cross.set_num_runs(2)
    
    
    mkl_obs = ParameterObserverCV(True)
    cross.subscribe_to_parameters(mkl_obs)
    
    
    result = CrossValidationResult()
    result = CrossValidationResult.obtain_from_generic(cross.evaluate())
    

    obs = mkl_obs.get_observation(0)
    fold = obs.get_fold(0)
    machine = MKLClassification.obtain_from_generic(fold.get_trained_machine())
    
    
    k = CombinedKernel.obtain_from_generic(machine.get_kernel())
    w = k.get_subkernel_weights()
    
    return result,k,w
train_data =
pd.read_table('test_data/classifier_binary_2d_nonlinear_features_train.dat',header=None,sep=' ')
test_data=pd.read_table('test_data/classifier_binary_2d_nonlinear_features_test.dat',header=None,sep=' ')
train_label=pd.read_table('test_data/classifier_binary_2d_linear_labels_train.dat',header=None)
test_label=pd.read_table('test_data/classifier_binary_2d_linear_labels_test.dat',header=None)
train_data=train_data.values
test_data=test_data.values
train_labels=train_label.values
train_labels=train_labels.T
train_labels=train_labels[0]
test_labels=test_label.values
test_labels=test_labels.T
test_labels=test_labels[0]
result,k,w=Bin_MKLClassficataion(train_data,train_labels)

**Comment by karlnapf** [comment]
Same as for #4446
