### ISSUE TITLE
MacOS compatibility issues

### ISSUE THREAD

**Issue by saatvikshah1994** [shogun-toolbox/shogun#4452]
Listing out some issues I've faced when trying to work with shogun on Mac(10.14.1):
1. Sanitizer Support: When building with `-DASAN=On`, I get a ton of undefined symbol errors. A regular C++ program built with `g++ -fsanitize=address` works. I'm pretty sure this happens for all sanitizer variants on MacOSX. 
2. Formatter Script: `script/check-format.sh` - 2 problems here - (1) Enforcement of `clang-format-3.7` which isnt easy to setup on Mac (2) Even after finding the `clang-format-3.7` file online and adding it to PATH, `git-clang-format-3.7` isnt available. This can be solved by allowing latest clang-format perhaps?
3. Benchmark support: Building with `-DBUILD_BENCHMARKS=On`, leads to a similar error as (1) with a linker error finally `ld: library not found for -lbenchmark`. I thought this could be because of some problem with setting up Google Benchmark, but that is setup correctly and a regular program with `g++ -lbenchmark` works fine. **Edit:** This in fact fails for me on an Ubuntu 18.04 box as well with a slightly different error.

Attaching the error logs for (1) and (3) for reference.
[asan_err.txt](https://github.com/shogun-toolbox/shogun/files/2731729/asan_err.txt)
[bmark_err.txt](https://github.com/shogun-toolbox/shogun/files/2731730/bmark_err.txt)
[bmark_err_ubuntu.txt](https://github.com/shogun-toolbox/shogun/files/2739615/bmark_err_ubuntu.txt)

This essentially makes development on a Mac box infeasible since there is no way to format code or check for leaks.

**Comment by vigsterkr** [comment]
@saatvikshah1994 mmm the 3rd part is a bit interesting as i've added the benchmarking part to the codebase and i did actually wrote that and tested it on a mac :)

**Comment by saatvikshah1994** [comment]
@vigsterkr any suggestions about what I might have done wrong? I basically did a `sudo make install` on the latest Google benchmark and ran the sample benchmark they had provided with `-lbenchmark` which worked.

**Comment by gf712** [comment]
I had a look at the benchmarks issue on linux and I managed to compile them manually by switching from the gold linker to the default gcc linker

**Comment by vigsterkr** [comment]
ok so i've just ran this:
```
cmake -DLIBSHOGUN_BUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/wiking/shogun-build -DBUILD_BENCHMARKS=ON ..
make -j2 HashedDocDotFeatures_benchmark
```

worked fine.

i've tried `make RandomFourierDotFeatures_benchmark` and worked as well.

could you please give more info about your macos setup?

btw i know that i should compile with `-DCMAKE_BUILD_TYPE=Release` to get the right results of the benchmark, but i dont have ccache for that and didn't want to wait that long to get you the results.

**Comment by gf712** [comment]
The linux issue is caused by the fact that the gold linker does not have the usual default paths of the default linker. That could be fixed by adding the path to where the benchmark library is located. As a temporary fix you can just use the default linker `-DENABLE_LDGOLD=OFF` instead.

**Comment by saatvikshah1994** [comment]
@vigsterkr Im running on OSX(10.14.1) and XCode Developer Tools 10.1.
I checked `ld -v -lbenchmark` which does have `/usr/local/lib` as a search path and `/usr/local/lib/libbenchmark.a` exists - which makes the error a bit weird. Even still I added `/usr/local/lib` to `LD_LIBRARY_PATH` but the error persists.
@gf712 yes, this does work! I guess I'll set it up on Ubuntu then.

**Comment by saatvikshah1994** [comment]
Sure, here it it: [cmake_out.txt](https://github.com/shogun-toolbox/shogun/files/2743944/cmake_out.txt)
I've tried the latest stable version from https://github.com/google/benchmark and from https://formulae.brew.sh/formula/google-benchmark - Both seem to v1.4.1.

**Comment by saatvikshah1994** [comment]
With respect to the sanitizers, one thing to try could be https://github.com/arsenm/sanitizers-cmake?
This also prevents things like trying to run incompatible sanitizers together.

**Comment by vigsterkr** [comment]
Oh this looks nice! PR is welcome to replace our internal solution ;)
