### ISSUE TITLE
Introducing Concepts

### ISSUE THREAD

**Issue by iglesias** [shogun-toolbox/shogun#4455]
Concepts can help reducing code complexity in templated generic programming, as well as producing simple compiler error messages. In addition, with a slightly long-term view in mind, producing a Concepts library for machine learning could become useful for the C++ community.

The goal of this task is getting hands-on and start playing with Concepts in Shogun.

As a first simple use case, we could start by moving from Traits to Concepts in the [vectorized RNG pull request](https://github.com/shogun-toolbox/shogun/pull/4437/files). For this we need simple concepts such as Integer or RealNumber. Simple concepts like these have most likely already been defined somewhere else. A place to start looking could be the [range library](https://github.com/ericniebler/range-v3). It would be nice to collect other tutorials and libraries for learning purposes.

Of course alternative and additional places where we could continue experimenting more are most welcome.

Detected challenges:
- Compiler support. To avoid overhead during the investigation, at first I'd say is fine if this is configured somewhat a bit "hacky". For example, Concepts support could be kept in a separate experimental branch and if necessary further isolated with some build conf. flag.
- ...

Background:
https://www.youtube.com/watch?v=HddFGPTAmtU
https://en.wikipedia.org/wiki/Concepts_(C%2B%2B)

@saatvikshah1994 

@karlnapf @vigsterkr @lisitsyn share your thoughts :-)

**Comment by karlnapf** [comment]
Would be cool to start playing with this, at least to develop some intuition for what we can do here.
As this didnt make it into C++17, we could maybe (as per suggestion by @gf712 ) use this  google lib that implements some 17/20 features in a c+11 compatible way ...

**Comment by gf712** [comment]
Ah yes, it's https://github.com/abseil/abseil-cpp. But I don't think concepts is something that has been or will be implemented there. This library is more to add C++14/17/(20) STL to C++11 onwards!

**Comment by iglesias** [comment]
All right, it was abseil, sure.

I suggest that at this moment we don't worry too much about this aspect* as this is really an investigation for us to start getting our hands dirty playing with concepts.

* C++ standard support for concepts and the version of it used in Shogun.

**Comment by saatvikshah1994** [comment]
Adding some more reference materials here(apart from what @iglesias recommended) in case anyone is interested:
1. Rough notes I've written up: [ConceptsBasics.pdf](https://github.com/shogun-toolbox/shogun/files/2781073/ConceptsBasics.pdf)
2. [Concepts as She is Spoke](https://www.youtube.com/watch?v=CXn02MPkn8Y)
3. [Concepts in 60](https://www.youtube.com/watch?v=ZeU6OPaGxwM)

One thing more to note is that the **final** C++2a concepts features are still not available on gcc/clang. That said the [Clang Concepts fork](https://github.com/saarraz/clang-concepts) closely resembles it, while gcc's trunk has Concepts TS support.

**Comment by iglesias** [comment]
Playground ready #4477 

I am going to try to close that PR soon merging it into a feature/concepts branch or so.
