### ISSUE TITLE
Add kwargs style factories in Python

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4461]

**Comment by karlnapf** [comment]
@sorig Check it out we now have shogun API for `my_kernel = sg.kernel("GaussianKernel", log_width=1.0)`. One thing that would be really awesome was if the meta language examples would make use of this. Currently, it is not possible to modify say `python.json` in order to produce the correct output. E.g.
```
        "KeywordArguments": {
            "List": ", $elements",
            "Element": "$keyword = $expr",
            "Separator": ", ",
            "InitialSeperatorWhenArgs>0": false
        },
```
produces things like
```
svm = machine("LibSVM"), C1 = 1.1, kernel = k
```
Any change you could also have a quick hack on that? 

Obviously, for the other langs, we don't want to change things (i.e. still go with the put cascades for now).

**Comment by gf712** [comment]
Maybe could add a hardcoded list of keywords to ignore? 
I was thinking maybe with a comment in front of the statement in the .sg file (e.g. `//ignore_kwargs:python`), but that would probably make it harder to implement and probably more tedious to maintain?

**Comment by karlnapf** [comment]
I think this is a simple matter of changing the generator a bit so that it can generate the python style kwargs .... let's see what esben makes of it :)

**Comment by karlnapf** [comment]
Cool stuff, I should have thought that you did that :) thanks!
