### ISSUE TITLE
Suggest class name in factory instantiation

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4475]
## Intro
Instead of using directly the classes from C++, we use factories (see [here](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/util/factory.h)). So for example in Python, instead of
```python
import shogun as sg
kernel = sg.GaussianKernel()
```
we have
```python
import shogun as sg
kernel = sg.kernel("GaussianKernel")
```
To find out what all possible names you can have a look at `src/shogun/base/class_list.cpp`, after compiling shogun.
The issue with this approach is that it is easy to mistype a name, e.g. `"Gaussiankernel"`, and after several hours of writing code these errors might happen more frequently and not so obvious to debug.
Right now you would get a message like this:
```python
SystemError: [ERROR] In file /home/gil/shogun/src/shogun/base/class_list.h line 51: Class Gaussiankernel with primitive type SGOBJECT does not exist.
```
## The task
Catch these errors with SWIG, for example in src/interfaces/shogun.i and try to find out what the user actually meant. This should be written in C++, which would make it accessible to all languages.

## Some pointers
- A good approach would be to calculate the distance between the string the user passed and all the classes in shogun
- All classes in shogun that are exposed via factories can be accessed with [shogun::available_objects()](https://github.com/shogun-toolbox/shogun/blob/e3e8cd197b4dde5a6c75136bea54e7fdc141a947/src/shogun/base/class_list.h#L71)
- A good distance metric for this is levenshtein, which is not implemented anywhere in shogun, but it is pretty straighforward (see [here](https://rosettacode.org/wiki/Levenshtein_distance#C.2B.2B)).
- Check #4473, it has a Python implementation of this

**Comment by karlnapf** [comment]
Note: this should not be implemented in a standard c++ shogun source, but in the swig extension. E.g. see https://github.com/shogun-toolbox/shogun/blob/develop/src/interfaces/swig/shogun.i
