### ISSUE TITLE
errors using ananconda shogun lib in windows

### ISSUE THREAD

**Issue by muhannad35990** [shogun-toolbox/shogun#4484]
I want to use shogun toolbox in QT Mingw c++ environment on windows 7 
I installed anaconda and extracted shogun.lib and shogun.dll form it and  imported the library to QT using this 
 win32:CONFIG(release, debug|release): LIBS += -LC:/ProgramData/Miniconda3/pkgs/shogun-cpp-6.1.3-hccc669c_1002/Library/lib/ -lshogun
 
now I can include anything in the library and QT idintify it but when compile the project I get alot of errors , the error is
![untitled](https://user-images.githubusercontent.com/42198707/51703152-4c234b80-201e-11e9-8457-7c654f9f1064.jpg)
![untitled](https://user-images.githubusercontent.com/42198707/51703204-6fe69180-201e-11e9-842c-9431e7734e05.jpg)

 in the attachement
please help how can i use it in QT c++

**Comment by karlnapf** [comment]
We would need some more detailed description of what you are doing. Not sure this is even a shogun related problem here....

**Comment by muhannad35990** [comment]
I want to use shogun in QT mingw, I tried to compile it using cmake and mingw on windows7 and fail,so I found pre-compiled shogun.lib in anaconda and wanted to link it to my project to use it but the error above is occurs!
I want to use shogun for implement MKL for my project ,could I use the source of MKL only without using the whole library? if not ,is there any precompiled static shogun.a to link to mingw qt on windows?

**Comment by muhannad35990** [comment]
I tried to compile shogun using mingw/windows7 but there is errors 
cmake log is:
`Could NOT find CCache (missing: CCACHE CCACHE_VERSION) 
Using system's malloc
Could NOT find GDB (missing: GDB_VERSION) 
dir='E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/src'
dir='E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/build/src'
dir='E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/src/gpl'
Found OpenMP_C: -fopenmp  
Found OpenMP_CXX: -fopenmp  
Found OpenMP: TRUE   
Could NOT find Eigen3 (missing: EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
Could NOT find OPENCL (missing: OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OpenCL_INCLUDE_DIRS OpenCL_LIBRARIES) (Required is at least version "1.5.0")
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Could NOT find TFLogger (missing: TFLogger_DIR)
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) 
Could NOT find JSON (missing: JSON_INCLUDE_DIR JSON_LIBRARY) (Required is at least version "0.11")
Lzo Library C:/ProgramData/Miniconda3/Library/lib/lzo2.lib
Lzo Include Found in C:/ProgramData/Miniconda3/Library/include
Could NOT find NLOPT (missing: NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
Could NOT find ARPREC (missing: ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
Linker: Default system linker
Ctags flavour: Exuberant
Error copying directory from "
E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/data/toy" to "E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/build/examples/undocumented/data".

Failed to locate sphinx-build executable (missing: SPHINX_EXECUTABLE) 
Failed to locate pandoc executable (missing: PANDOC_EXECUTABLE) 
===================================================================================================================
Summary of Configuration Variables
The following OPTIONAL packages have been found:

 * Doxygen (required version >= 1.8.6)
 * OpenMP
 * CxaDemangle
 * Threads
 * GLPK
 * LibXml2
 * CURL
 * ZLIB
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * Ctags

-- The following REQUIRED packages have been found:

 * PythonInterp

-- The following OPTIONAL packages have not been found:

 * CCache
 * GDB
 * Eigen3 (required version >= 3.1.2)
 * ViennaCL (required version >= 1.5.0)
 * rxcpp
 * TFLogger (required version >= 0.1.0)
 * BLAS
 * CPLEX
 * ARPACK
 * Mosek
 * Protobuf
 * JSON (required version >= 0.11)
 * NLopt
 * LpSolve
 * ColPack
 * ARPREC
 * Sphinx
 * Pandoc

===================================================================================================================
Integrations
  OpenCV Integration is OFF 	 enable with -DOpenCV=ON
===================================================================================================================
Interfaces
  Python is OFF 		 enable with -DINTERFACE_PYTHON=ON
  Octave is OFF 		 enable with -DINTERFACE_OCTAVE=ON
  Java is OFF 		 enable with -DINTERFACE_JAVA=ON
  Perl is OFF 		 enable with -DINTERFACE_PERL=ON
  Ruby is OFF 		 enable with -DINTERFACE_RUBY=ON
  C# is OFF 			 enable with -DINTERFACE_CSHARP=ON
  R is OFF 			 enable with -DINTERFACE_R=ON
  Lua is OFF 		 enable with -DINTERFACE_LUA=ON
  Scala is OFF 		 enable with -DINTERFACE_SCALA=ON
===================================================================================================================
To compile shogun type
  make

To install shogun to C:/Program Files (x86)/shogun type
  make install

or to install to a custom directory
  make install DESTDIR=/my/special/path
  (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
===================================================================================================================
Configuring done
Generating done`



after mingw32-make I get this error 
`E:\shogun\shogun-shogun_6.1.3\shogun-shogun_6.1.3\build>mingw32-make
[  1%] Generating version header
[  1%] Built target version
[  1%] Built target class_list
[  1%] Built target Eigen3
[  2%] Built target rxcpp
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/svm/LibLinear.cpp.obj
In file included from E:\shogun\shogun-shogun_6.1.3\shogun-shogun_6.1.3\src\shogun\classifier\svm\LibLinear.cpp:14:0:
E:/shogun/shogun-shogun_6.1.3/shogun-shogun_6.1.3/src/shogun/base/progress.h:54:23: fatal error: sys/ioctl.h: No such file or directory
compilation terminated.
src\shogun\CMakeFiles\libshogun.dir\build.make:1309: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/classifier/svm/LibLinear.cpp.obj' failed
mingw32-make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/classifier/svm/LibLinear.cpp.obj] Error 1
CMakeFiles\Makefile2:103: recipe for target 'src/shogun/CMakeFiles/libshogun.dir/all' failed
mingw32-make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2`

any help!

**Comment by vigsterkr** [comment]
@muhannad35990 you should stick with the precompiled anaconda version... today i'll test the import of the shared libs into a qt project... note it's gonna be on linux, but one would hope that it shouldn't be such a big difference....

and actually could you create the output of qmake (errors) and paste it on http://pastebin.com and provide the link here. thnx!

**Comment by muhannad35990** [comment]
anaconda version is not working for mingw so I tried to compile it with mingw and get alot of errors

**Comment by muhannad35990** [comment]
finally I successfully compiled shogun using MinGw on windows after some modification in the source code of shogun and I get the static library: 3 files:: libshogun.a,libshogun.dll,libshogun.dll.a
and here is it in the link below if anybody wanted to test it:
https://github.com/muhannad35990/muhannad-shogun

**Comment by karlnapf** [comment]
Hi! Thanks for putting this up. Note that shogun does compile natively under windows.
This is interesting for others as well, so some thoughts on how to share what you did

* if you put up the source code, rather fork the repository, and locally push your changes in a single commit. Then people can see what you actually did. As of now, with the .rar file, I cannot without having to download it, then open and diff it manually, which is a higher barrier than just looking at a commit diff
* As also mentioned in another PR, it would be actually useful if you described the process of what you did here in a blog post: what issues you faced, how you solved them, with lots of links and guidance for others. A tutorial style guide. Then we know a bit about the rationale of what you did. If it is nicely written, we could add it to our wiki for newcomers
