### ISSUE TITLE
Incorrect data coping in SGVector class

### ISSUE THREAD

**Issue by Kolkir** [shogun-toolbox/shogun#4497]
There is an incorrect call of ``std::copy`` algorithm in [SGVector.h:132](https://github.com/shogun-toolbox/shogun/blob/2cab19a30bb4405e9bb1f6177488969b1a36a1ef/src/shogun/lib/SGVector.h#L132) file. The code on specified line clears original data and return wrong result. For example this issue makes impossible to use ``SGVector`` objects as labels for ``CLinearRidgeRegression`` class, because it uses this method.

To solve this problem the line should be changed to ``std::copy_n(vector, vlen, v.begin());``

**Comment by karlnapf** [comment]
Thanks for the report!
Wanna send a patch for this? Preferably with a unit test?

**Comment by Kolkir** [comment]
> 
> 
> Thanks for the report!
> Wanna send a patch for this? Preferably with a unit test?

I can make a PR with fix and test. Am I understand right that I should use this [guide](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md) for this?

**Comment by karlnapf** [comment]
yes, though since the fix is simple, I don't expect any major headaches there.
Have a look at the other unit tests for SGVector::as (if any) and then just add the case that was broken before
