### ISSUE TITLE
Ubuntu 18.04 while adding ppa got error

### ISSUE THREAD

**Issue by utkarsh1508** [shogun-toolbox/shogun#4499]
Builds of stable releases
 More info: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu bionic InRelease                                     
Ign:3 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic InRelease                   
Ign:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy Release
Get:5 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                 
Err:7 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic Release      
  404  Not Found [IP: 91.189.95.83 80]
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease        
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en                                                      
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata                                               
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata                                                 
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons                                                  
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons                                                  
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata                                                  
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata                                                
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages                                                       
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages                                                       
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages                                                        
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN                                                   
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en                                                      
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata                                               
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata                                                 
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons                                                  
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons                                                  
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata                                                  
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata                                                
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages                                                       
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages                                                       
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata
Ign:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata
Err:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 Packages
  404  Not Found [IP: 91.189.95.83 80]
Ign:10 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main i386 Packages
Ign:11 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all Packages
Ign:12 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main Translation-en
Ign:14 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 48x48 Icons
Ign:17 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main DEP-11 64x64 Icons
Ign:18 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main all c-n-f Metadata
Ign:19 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu wheezy/main amd64 c-n-f Metadata
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by karlnapf** [comment]
https://github.com/shogun-toolbox/shogun/wiki/Getting-involved

**Comment by elbaraim** [comment]
I am getting the same error. Could someone fix this?

 Builds of stable releases
 More info: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Ign:1 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu cosmic InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                             
Hit:3 http://be.archive.ubuntu.com/ubuntu cosmic InRelease                                                                               
Err:4 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu cosmic Release                       
  404  Not Found [IP: 91.189.95.83 80]
Hit:5 http://be.archive.ubuntu.com/ubuntu cosmic-updates InRelease                               
Hit:6 http://be.archive.ubuntu.com/ubuntu cosmic-backports InRelease                          
Get:7 http://security.ubuntu.com/ubuntu cosmic-security InRelease [88,7 kB]
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                          
Reading package lists... Done                                                       
E: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by karlnapf** [comment]
we dont have a ppa for this version yet, patch welcome!

**Comment by elbaraim** [comment]
also installation via pip fails...

if I search for the package appears:
`~$ pip3 search shogun`
`shogun-ml (5.0.0)  - The Shogun Machine Learning Toolbox`
`shogun (0.1)       - Threat Intelligence Module`

however if I try to install I get an error
`~$ pip3 install --user shogun-ml`
`Collecting shogun-ml`
`ERROR: Could not find a version that satisfies the requirement shogun-ml (from versions: none)`
`ERROR: No matching distribution found for shogun-ml`

any help please?? I am not an experienced code developer

**Comment by vigsterkr** [comment]
@elbaraim plz use conda for this:
```
conda install --channel conda-forge shogun
```

**Comment by elbaraim** [comment]
Thank you for the tip! @vigsterkr 
However I now get the following error...

`~$ conda install --channel conda-forge shogun`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed`

`UnsatisfiableError: The following specifications were found to be incompatible with each other:`

`  - mkl-service`
`  - pip -> python[version='>=3.7,<3.8.0a0']`

Thank you in advance for the help :smile:

**Comment by elbaraim** [comment]
i am using python3.7 in Ubuntu 18.04

**Comment by elbaraim** [comment]
any help please?

**Comment by vigsterkr** [comment]
@elbaraim can you come around on our IRC channel one of these days?

**Comment by vigsterkr** [comment]
but this env file should get you a working conda env working env: https://github.com/shogun-toolbox/shogun/blob/develop/environment.yml
