### ISSUE TITLE
libshogun18 package not found

### ISSUE THREAD

**Issue by utkarsh1508** [shogun-toolbox/shogun#4501]
sudo apt-get install libshogun18
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libshogun18

**Comment by karlnapf** [comment]
Hi!
Please read this how to get involved: https://github.com/shogun-toolbox/shogun/wiki/Getting-involved
Come and ask us in IRC if you have any specific questions
