### ISSUE TITLE
Cleanup web pages 

### ISSUE THREAD

**Issue by heytitle** [shogun-toolbox/shogun#4512]
Hi Shogun Team, 

I'm Pat, I'm  a student from TU Berlin. I plan to participate in GSoC 2019 under Shogun. While reading pages on shogun.ml, I've found several problems on the web pages. These problems include dead links, outdated commands, and improper rendering. 

I'll take a look on these problems and prepare PRs, and please let me know if you have comments or know other related issues.  

## Page : http://shogun.ml/mission
- [x] Dead links:
    1.   Maybe change it to Google's Colab?  ![image](https://user-images.githubusercontent.com/1214890/52210602-dcb42400-2887-11e9-99c4-1d07e4c4bd8b.png)

  1.  <img width="974" alt="screenshot 2019-02-04 13 24 54" src="https://user-images.githubusercontent.com/1214890/52210670-0705e180-2888-11e9-8239-4ca08117c922.png">

## Page : http://shogun.ml/examples/latest/index.html
- [x] Dead links:
   1. ![image](https://user-images.githubusercontent.com/1214890/52210800-55b37b80-2888-11e9-9692-7e0b35a1b36e.png)

  1. ![image](https://user-images.githubusercontent.com/1214890/52210784-4cc2aa00-2888-11e9-9295-73e2a4ee86c0.png)
- [x] JS Errors (MathJax)
![screenshot 2019-02-04 13 35 42](https://user-images.githubusercontent.com/1214890/52210838-6b28a580-2888-11e9-9f44-de69d7b1340b.png)
- [x] ~~Error in MathJax commands~~ solved by above.
![screenshot 2019-02-04 13 38 06](https://user-images.githubusercontent.com/1214890/52210875-82679300-2888-11e9-8c62-572cc2ea2eb4.png)
![screenshot 2019-02-04 13 38 21](https://user-images.githubusercontent.com/1214890/52210881-85628380-2888-11e9-88fc-d975d8180590.png)
![screenshot 2019-02-04 13 44 58](https://user-images.githubusercontent.com/1214890/52210918-a1662500-2888-11e9-9d7c-32d3d36cfcc6.png)
- [x] ~~Empty code cell~~ fixed on develop
![screenshot 2019-02-04 13 39 52](https://user-images.githubusercontent.com/1214890/52210906-94e1cc80-2888-11e9-9f16-14f1aa088bb4.png)
- [x] Reference Section displays oddly. 
**Current**
![screenshot 2019-02-04 14 27 51](https://user-images.githubusercontent.com/1214890/52211100-218c8a80-2889-11e9-8c47-b7f3802a97d2.png)
**Suggestion** Remove `display: inline; font-size: 75%` from class `label. 
![screenshot 2019-02-04 14 28 16](https://user-images.githubusercontent.com/1214890/52211105-24877b00-2889-11e9-8e83-9c9fec95bf95.png)

## Page : http://shogun.ml/install
- [x] Dead links:
    1. ![image](https://user-images.githubusercontent.com/1214890/52210192-8a263800-2886-11e9-83a0-7dc92e64ce4e.png)
    1. ![image](https://user-images.githubusercontent.com/1214890/52210202-94e0cd00-2886-11e9-987f-9fa70b980a4a.png)
      **UPDATED**: We don't have the apt server at the moment (mentioned in https://github.com/shogun-toolbox/shogun/issues/4512#issuecomment-461898412). So, I will leave this one as it is for now.
    1. ![image](https://user-images.githubusercontent.com/1214890/52211015-e0947600-2888-11e9-9df6-be7e8c3db366.png)

   The page doesn't show any meaningful information, just a default page.
- [x] `Homebrew/science` has been deprecated and `shogun` has been included in [Homebrew's core formulae](https://formulae.brew.sh/formula/shogun). As a result, we need to change the brew command to 
```
brew install shogun
```

- [x] Duplicate import statements for `shogun-style.css`.
![image](https://user-images.githubusercontent.com/1214890/52414600-15046e00-2ae5-11e9-97ef-fcd074709a6a.png)

## Page:  http://shogun.ml/showroom
- [ ] Modal view looks odd. Please see the screenshot below. I think we can just redirect the link to where those notebooks are hosted and get rid of the modal view.
![image](https://user-images.githubusercontent.com/1214890/52210369-30723d80-2887-11e9-9ec1-8591734f4b07.png)

## Shogun HTTPS Certificate
Shogun's HTTPS certificate was expired. I'm not sure whether we need to fix it. In case this issue is relevant, maybe we can consider using [Let's encrpyt](https://letsencrypt.org/).
![image](https://user-images.githubusercontent.com/1214890/52210332-0c166100-2887-11e9-92c9-b8bb8aebfd9e.png)

**Comment by karlnapf** [comment]
Thanks for reporting those. We are more than happy for direct edits to the wiki (it is public), PRs for the examples/cookbooks, and PRs to the website repository

**Comment by heytitle** [comment]
@karlnapf I've created a PR (#4516 ) containing patches for these issues. 
Noting, I haven't updated the Debian installation yet because I'm not sure whether Shogun still has its own APT server. Could you please confirm? Otherwise, I'll just update the section with information from https://packages.debian.org.

I'll create create two new issues for fixing showroom pages and https as they might require further discussion. What do think?

**Comment by karlnapf** [comment]
no own apt server
debian packages are not up to the latest iirc....need to check. We have some ubuntu packages but not the latest....we always struggle to find people helping with the packaging in fact if you are looking for something to help :)
I would leave the showroom for now as we are in the progress of updating the website again, so this should change soon

**Comment by heytitle** [comment]
@karlnapf I can help you with Debian and Ubuntu packaging.
