### ISSUE TITLE
Problem while adding python path for shogun : python interface

### ISSUE THREAD

**Issue by indranilbiswas7** [shogun-toolbox/shogun#4517]
As mentioned in https://github.com/shogun-toolbox/docs/blob/master/INTERFACES.md :
The package support to python for shogun is to be enabled by 
export PYTHONPATH="path/to/modshogun.py:$PYTHONPATH"

following up to which , I did was :
export PYTHONPATH="/home/saphire/shogun/build/src/interfaces/python/shogun.py:$PYTHONPATH";

but still I get :
Traceback (most recent call last):
  File "random_forest_regression.py", line 2, in <module>
    from shogun import Math
ModuleNotFoundError: No module named 'shogun'

on executing any .py file in the examples.

also for Interfacing c++

I did the following :
gcc kmeans.cpp -o kmeans -I//home/saphire/shogun/src/shogun/base -lshogun -L//home/saphire/shogun/src/shogun/libshogun.so
kmeans.cpp:1:10: fatal error: shogun/base/init.h: No such file or directory
 #include <shogun/base/init.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

but the error !!

**Comment by karlnapf** [comment]
This is a standard python path problem. You need to make sure the .py file of the shogun interface in your build folder is in the pythonpath. Best is to print it and compare
