### ISSUE TITLE
Problems building on windows MSVC 2015

### ISSUE THREAD

**Issue by fyoda** [shogun-toolbox/shogun#4520]
Hello,

I have just cloned the develop branch (hash a043624b0) and tried to build it with MSVC 2015.
I have used cmake to generate the MSVC project. When building I get the followings errors:

``
7>C:\Users\myUser\Desktop\shogun\src\shogun/io/streaming/ParseBuffer.h(274): error C2783: 'void shogun::sg_generic_free(T *)': could not deduce template argument for '__formal'
7>  C:\Users\myUser\Desktop\shogun\src\shogun/lib/memory.h(159): note: see declaration of 'shogun::sg_generic_free'
7>C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(180): error C2672: 'shogun::sg_generic_malloc': no matching overloaded function found
7>  C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(143): note: see reference to function template instantiation 'bool shogun::CCustomKernel::set_triangle_kernel_matrix_from_triangle_generic<double>(shogun::SGVector<double>)' being compiled
7>C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(180): error C2783: 'T *shogun::sg_generic_malloc(std::size_t)': could not deduce template argument for '__formal'
7>  C:\Users\myUser\Desktop\shogun\src\shogun/lib/memory.h(113): note: see declaration of 'shogun::sg_generic_malloc'
7>C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(231): error C2672: 'shogun::sg_generic_malloc': no matching overloaded function found
7>  C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(204): note: see reference to function template instantiation 'bool shogun::CCustomKernel::set_triangle_kernel_matrix_from_full_generic<double>(shogun::SGMatrix<double>)' being compiled
7>C:\Users\myUser\Desktop\shogun\src\shogun\kernel\CustomKernel.h(231): error C2783: 'T *shogun::sg_generic_malloc(std::size_t)': could not deduce template argument for '__formal'
7>  C:\Users\myUser\Desktop\shogun\src\shogun/lib/memory.h(113): note: see declaration of 'shogun::sg_generic_malloc'
7>C:\Users\myUser\Desktop\shogun\src\shogun/lib/Trie.h(1128): error C2672: 'sg_generic_free': no matching overloaded function found
7>  C:\Users\myUser\Desktop\shogun\src\shogun/lib/Trie.h(1125): note: while compiling class template member function 'shogun::CTrie<shogun::DNATrie>::~CTrie(void)'
7>  C:\Users\myUser\Desktop\shogun\src\shogun/kernel/string/WeightedDegreeStringKernel.h(199): note: see reference to class template instantiation 'shogun::CTrie<shogun::DNATrie>' being compiled
7>C:\Users\myUser\Desktop\shogun\src\shogun/lib/Trie.h(1128): error C2783: 'void shogun::sg_generic_free(T *)': could not deduce template argument for '__formal'
7>  C:\Users\myUser\Desktop\shogun\src\shogun/lib/memory.h(159): note: see declaration of 'shogun::sg_generic_free'
7>C:\Users\myUser\Desktop\shogun\src\shogun/mathematics/Math.h(159): warning C4804: '>': unsafe use of type 'bool' in operation
7>  C:\Users\myUser\Desktop\shogun\src\shogun\features\DenseSubsetFeatures.h(172): note: see reference to function template instantiation 'T shogun::CMath::abs<T>(T)' being compiled
7>          with
7>          [
7>              T=bool
7>          ]
7>  C:\Users\myUser\Desktop\shogun\src\shogun\features\DenseSubsetFeatures.h(164): note: while compiling class template member function 'void shogun::CDenseSubsetFeatures<bool>::add_to_dense_vec(float64_t,int32_t,float64_t *,int32_t,bool)'
7>  C:\Users\myUser\Desktop\shogun\build\src\shogun\base\class_list.cpp(1000): note: see reference to class template instantiation 'shogun::CDenseSubsetFeatures<bool>' being compiled
7>C:\Users\myUser\Desktop\shogun\src\shogun/mathematics/Math.h(162): warning C4804: '-': unsafe use of type 'bool' in operation
7>  Generating Code...
8>------ Build started: Project: shogun, Configuration: Release x64 ------
8>  Building Custom Rule C:/Users/myUser/Desktop/shogun/src/shogun/CMakeLists.txt
8>  CMake does not need to re-run because C:/Users/myUser/Desktop/shogun/build/src/shogun/CMakeFiles/generate.stamp is up-to-date.
8>LINK : fatal error LNK1181: cannot open input file 'C:\Users\myUser\Desktop\shogun\build\src\shogun\libshogun.dir\Release\distributions\Histogram.cpp.obj'
========== Build: 6 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
``

I used the same clone to build on Mac OS and it worked out without problems.
How can I solve this issue?

**Comment by vigsterkr** [comment]
@fyoda in develop we dropped support for MSVC 2015 :( try 2017

**Comment by fyoda** [comment]
@vigsterkr Thanks for your reply. Which is the latest that supports MSVC 2015?

**Comment by vigsterkr** [comment]
@fyoda that's a good question i think sometime before this commit: b45243cf5afadcea5dee1df21284c2442ee01e98

**Comment by vigsterkr** [comment]
@fyoda but you could use the conda artifacts

**Comment by fyoda** [comment]
Thanks
