### ISSUE TITLE
cannot find shogun package  in shogun docker image 

### ISSUE THREAD

**Issue by luoagnes** [shogun-toolbox/shogun#4527]

**Comment by luoagnes** [comment]
I pull shogun docker image from according to installation instruction, and in its bash ,  I print "python" to python shell, but when import shogun, there is "import error"

``
baobeiwangwangdeMacBook-Air:~ luowang$ sudo docker run -it vigsterkr/shogun-dev bash
Password:
root@a7737bb1e387:/# python 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import shogun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named shogun
>>> import sg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sg
>>> import modshogun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named modshogun
>>> 
``
how to use shogun in python by shogun docker image ?

**Comment by karlnapf** [comment]
it looks like you are on the dev version, which doesnt have the compiled lib installed. Use the other version https://hub.docker.com/u/shogun
