### ISSUE TITLE
Installation successful, but import shogun error

### ISSUE THREAD

**Issue by luoagnes** [shogun-toolbox/shogun#4536]
I pull shogun docker image from according to installation instruction, and in its bash , I print "python" to python shell, but when import shogun, there is "import error"

root@a7737bb1e387:/# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import shogun
> > > Traceback (most recent call last):
> > > File "", line 1, in 
> > > ImportError: No module named shogun
> > > import sg
> > > Traceback (most recent call last):
> > > File "", line 1, in 
> > > ImportError: No module named sg
> > > import modshogun
> > > Traceback (most recent call last):
> > > File "", line 1, in 
> > > ImportError: No module named modshogun

**### The content of dockerfile is:**
FROM ubuntu:16.04 AS build-env
MAINTAINER shogun@shogun-toolbox.org

RUN apt-get update && apt-get install -qq software-properties-common lsb-release
RUN add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) multiverse"
RUN add-apt-repository ppa:shogun-toolbox/nightly
RUN apt-get update -qq
RUN apt-get upgrade -y
# install shogun
RUN apt-get install -qq --force-yes --no-install-recommends libshogun18
RUN apt-get install -qq --force-yes --no-install-recommends python-shogun
The result of install is successful !

so why the installation is successful, but i can not import shogun successfully ?

**Comment by luoagnes** [comment]
I installed the environment from the Dockerfile

**Comment by luoagnes** [comment]
As mentioned in https://github.com/shogun-toolbox/docs/blob/master/INTERFACES.md :
The package support to python for shogun is to be enabled by
export PYTHONPATH="path/to/shogun.py:$PYTHONPATH"

following up to which , I did was :
export PYTHONPATH="path/to/shogun.py:$PYTHONPATH"
but still I get :
Traceback (most recent call last):
File "random_forest_regression.py", line 2, in 
import shogun
ModuleNotFoundError: No module named 'shogun'

I know the "path" is the real path for shogun, but i install the shogun docker environment, how do i know the path of shogun? I cannot find the shogun in bash shell.

**Comment by karlnapf** [comment]
Hi! It is quite unclear what you did, so it is hard to help you. Make sure to read up on how to ask for help, and provide details of what exactly you did

**Comment by karlnapf** [comment]
I’m closing this for now as it seems a generic python setup issue. Best to google/understand what PYTHONPATH is
