### ISSUE TITLE
Importing shogun makes python irresponsive to KeyboardInterrupt

### ISSUE THREAD

**Issue by saeidnp** [shogun-toolbox/shogun#4539]
As soon as I import shogun in python, it does not respond to Ctrl+c any more.
I am testing it with this simple code:
```
import shogun
import time
time.sleep(10)
```

**Comment by geektoni** [comment]
Which version of Shogun are you using? This was a known issue (see https://github.com/shogun-toolbox/shogun/issues/4201) and it is was fixed in the most recent versions of Shogun. I suggest you to try to use the current development branch (`develop`) which will have the fix.

**Comment by saeidnp** [comment]
I was using the latest release (6.1.3), which did not include the fix.
I tried using the latest commit from `develop` branch and it does not ignore KeyboardInterrupt anymore and prints this:
```
[ShogunSignalHandler] Immediately return to prompt / Prematurely finish computations / Pause current computation / Do nothing (I/C/P/D)?
```
Which is expected. But is there a way to recover the normal behavior of KeyboardInterrupt i.e. not being handled by shogun?

**Comment by geektoni** [comment]
Yes, it is possible to use the standard handler. In order to do that, you just need to add to your file the following line:
```
import shogun
shogun.get_global_signal().enable_handler(False)
```

**Comment by saeidnp** [comment]
It worked. Thanks.
