### ISSUE TITLE
Make error during compile libshogun by hand

### ISSUE THREAD

**Issue by luoagnes** [shogun-toolbox/shogun#4542]
I compile shogun by hand, and when i execute the command "make",  there happened some error , the error content is:

Scanning dependencies of target libshogun
[  1%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/Parallel.cpp.o
In file included from /shogun/src/shogun/lib/common.h:80:0,
                 from /shogun/src/shogun/base/Parallel.h:13,
                 from /shogun/src/shogun/base/Parallel.cpp:8:
/shogun/src/shogun/lib/memory.h:106:25: error: ‘std::enable_if_t’ has not been declared
 template <class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                         ^
/shogun/src/shogun/lib/memory.h:106:36: error: expected ‘>’ before ‘<’ token
 template <class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                                    ^
/shogun/src/shogun/lib/memory.h:112:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:112:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:113:4: error: redefinition of ‘template<class T, int <anonymous> > T* shogun::sg_generic_malloc(size_t)’
 T* sg_generic_malloc(size_t len)
    ^
/shogun/src/shogun/lib/memory.h:107:4: error: ‘template<class T, int <anonymous> > T* shogun::sg_generic_malloc(size_t)’ previously declared here
 T* sg_generic_malloc(size_t len)
    ^
/shogun/src/shogun/lib/memory.h:119:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:119:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:125:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:125:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:126:4: error: redefinition of ‘template<class T, int <anonymous> > T* shogun::sg_generic_realloc(T*, size_t, size_t)’
 T* sg_generic_realloc(T* ptr, size_t old_len, size_t len)
    ^
/shogun/src/shogun/lib/memory.h:120:4: error: ‘template<class T, int <anonymous> > T* shogun::sg_generic_realloc(T*, size_t, size_t)’ previously declared here
 T* sg_generic_realloc(T* ptr, size_t old_len, size_t len)
    ^
/shogun/src/shogun/lib/memory.h:139:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:139:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:145:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:145:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:146:4: error: redefinition of ‘template<class T, int <anonymous> > T* shogun::sg_generic_calloc(size_t)’
 T* sg_generic_calloc(size_t len)
    ^
/shogun/src/shogun/lib/memory.h:140:4: error: ‘template<class T, int <anonymous> > T* shogun::sg_generic_calloc(size_t)’ previously declared here
 T* sg_generic_calloc(size_t len)
    ^
/shogun/src/shogun/lib/memory.h:152:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:152:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<!is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:158:24: error: ‘std::enable_if_t’ has not been declared
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                        ^
/shogun/src/shogun/lib/memory.h:158:35: error: expected ‘>’ before ‘<’ token
 template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
                                   ^
/shogun/src/shogun/lib/memory.h:159:6: error: redefinition of ‘template<class T, int <anonymous> > void shogun::sg_generic_free(T*)’
 void sg_generic_free(T* ptr)
      ^
/shogun/src/shogun/lib/memory.h:153:6: error: ‘template<class T, int <anonymous> > void shogun::sg_generic_free(T*)’ previously declared here
 void sg_generic_free(T* ptr)
      ^
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/Parallel.cpp.o] Error 1
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2

The linux system  is Linux Hera02 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

so, why the error happened?  and how to solve it ?

**Comment by luoagnes** [comment]
my cmake command content is:

cmake -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
            -DPYTHON_LIBRARIES= /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so \
            -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2 \
            -DPYTHON_PACKAGES_PATH=/usr/local/lib/python2.7/dist-packages \
            -DINTERFACE_PYTHON=ON ..

**Comment by gf712** [comment]
@luoagnes  do you still have this issue?
