### ISSUE TITLE
Meta examples are built multiple times during the build process.

### ISSUE THREAD

**Issue by geektoni** [shogun-toolbox/shogun#4556]
Shogun's meta examples are generated/built every time we call `make`. This should only happen when those `*.sg` files are modified. This behaviour is reproducible using the latest develop branch and by doing:
```
cd shogun
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON ../
make -j 8
```

**Comment by karlnapf** [comment]
Yes! That’s annoying me as well

Also you can avoid building them via using the other make targets (libshogun, _interface_python, cpp-features-string, etc)

**Comment by vinx13** [comment]
Even if .sg files are the same, meta examples still need to be rebuilt if libshogun is updated.

**Comment by vigsterkr** [comment]
@vinx13 afaik by using `target_link_libraries` that should be taken care via cmake....

**Comment by geektoni** [comment]
@vinx13 The problem is mainly caused by the fact that when I'm modifying a .cpp file, I just need the examples to be linked again against the new libshogun, but currently, the make process also rebuilds them every time.

**Comment by karlnapf** [comment]
you can just build one
`make cpp-features-string`. It generates all of them (that is the problem to be fixed), but it only compiles one.
