### ISSUE TITLE
fix liblinearregression tests

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4561]
the unit test of LibLinearRegression fails every now and then, that causes false alarms in our CI

**Comment by avramidis** [comment]
Can we have artifacts if it's possible to see why it fails? I cannot make it fail locally.

**Comment by gf712** [comment]
the weights learnt go off quite a bit sometimes. It seems to be an issue with something related to RNG. I tested for UB, but couldn't find anything. 

It's also just an issue with clang, which makes it even weirder. If you have clang compile shogun with it and run the test a few times and it will very likely fail occasionally.. 

I think the algorithm expects it to be monotonically decreasing, but sometimes that doesn't happen and it stops training too early, other times it will reach maximum iterations and be stuck in a local minimum with a greater loss... It could also be an issue with the data which I am not sure is always the same when it is generated...

**Comment by avramidis** [comment]
Thank you! I will try with clang.
