### ISSUE TITLE
facing issue in Configuring cmake

### ISSUE THREAD

**Issue by jyotirmoy1997** [shogun-toolbox/shogun#4563]
**```
cd build
cmake [options] ..
```** .### .>>>>> for this command i am facing an error 

- #--

 Building for: Visual Studio 14 2015
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


CMake Error: Could not open file for write in copy operation C:/Users/nEW u/Desk                                                                                            top/shogun_stable/shogun/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


-- Selecting Windows SDK version  to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:27 (project):
  Failed to make directory:

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/3.13.4


-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: C:/Users/nEW u/Desktop/shogun_stable/sh                                                                                            ogun/build/CMakeCache.txt.tmp
CMake Error: : System Error: No such file or directory
CMake Error: Unable to open cache file for save. C:/Users/nEW u/Desktop/shogun_s                                                                                            table/shogun/build/CMakeCache.txt
CMake Error: : System Error: No such file or directory

**Comment by vigsterkr** [comment]
@jyotirmoy1997 you are trying to build with MSVC 2015... that won't work... other than that you seem to have some permission errors

**Comment by jyotirmoy1997** [comment]
MSVC 2015. so should i upgrade it to 2017

**Comment by vigsterkr** [comment]
yes

**Comment by jyotirmoy1997** [comment]
"you seem to have some permission errors" can you elaborate it plz

**Comment by vigsterkr** [comment]
```CMake Error: Could not open file for write in copy operation C:/Users/nEW u/Desk                                                                                            top/shogun_stable/shogun/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp```

**Comment by jyotirmoy1997** [comment]
so any kind of solution. i don' t think there is a error in  setting up the  environment variable

**Comment by vigsterkr** [comment]
sorry but this is your dev env... and clearly you have a problem with permissions... i cannot help you more than this

**Comment by jyotirmoy1997** [comment]
ok thank you

**Comment by jyotirmoy1997** [comment]
victor still facing this issue
-- Building for: Visual Studio 15 2017
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


CMake Error: Could not open file for write in copy operation C:/Users/nEW u/Desk                                                                                            top/shogun_stable/shogun/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


CMake Error at CMakeLists.txt:27 (project):
  Failed to make directory:

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/3.13.4


-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: C:/Users/nEW u/Desktop/shogun_stable/sh                                                                                            ogun/build/CMakeCache.txt.tmp
CMake Error: : System Error: No such file or directory
CMake Error: Unable to open cache file for save. C:/Users/nEW u/Desktop/shogun_s                                                                                            table/shogun/build/CMakeCache.txt
CMake Error: : System Error: No such file or directory

**Comment by JDchaudhary** [comment]
> dev e

I'm facing this problem, do you have any solution

**Comment by JDchaudhary** [comment]
> sorry but this is your dev env... and clearly you have a problem with permissions... i cannot help you more than this

I'm facing this problem, do you have any solution

**Comment by JDchaudhary** [comment]
> `CMake Error: Could not open file for write in copy operation C:/Users/nEW u/Desk top/shogun_stable/shogun/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp`

I'm facing this problem, do you have any solution

**Comment by karlnapf** [comment]
still permission problems ....

**Comment by YashowardhanTripathi** [comment]
just give permission of your cmake folder:-
Terminal command -
$ sudo chown -R username:username foldername

Still prob not resolved then try,

$ sudo chmod -R 777 foldername

Thanks

**Comment by fdciabdul** [comment]
> just give permission of your cmake folder:-
> Terminal command -
> $ sudo chown -R username:username foldername
> 
> Still prob not resolved then try,
> 
> $ sudo chmod -R 777 foldername
> 
> Thanks

they use windows
