### ISSUE TITLE
victor still facing this issue

### ISSUE THREAD

**Issue by jyotirmoy1997** [shogun-toolbox/shogun#4569]
victor still facing this issue
-- Building for: Visual Studio 15 2017
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)

CMake Error: Could not open file for write in copy operation C:/Users/nEW u/Desk                                                                                            top/shogun_stable/shogun/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSys                                                                                            tem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)

CMake Error at CMakeLists.txt:27 (project):
  Failed to make directory:

    C:/Users/nEW u/Desktop/shogun_stable/shogun/build/CMakeFiles/3.13.4

-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: C:/Users/nEW u/Desktop/shogun_stable/sh                                                                                            ogun/build/CMakeCache.txt.tmp
CMake Error: : System Error: No such file or directory
CMake Error: Unable to open cache file for save. C:/Users/nEW u/Desktop/shogun_s                                                                                            table/shogun/build/CMakeCache.txt
CMake Error: : System Error: No such file or directory

_Originally posted by @jyotirmoy1997 in https://github.com/shogun-toolbox/shogun/issues/4563#issuecomment-472000349_

**Comment by karlnapf** [comment]
please stop spamming our issue list via opening new issues @jyotirmoy1997 there is the other thread to discuss this (which I believe contained some clear hints on how to solve this problem)
