### ISSUE TITLE
create unit tests for utils::safe_convert function

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4580]
create all the possible combination for primitive type conversion to check that utils::safe_convert is acting as it should

**Comment by ArtemSkrebkov** [comment]
Just to confirm: is this still relevant? 
I would be glad to help and assign the issue to myself.

**Comment by vigsterkr** [comment]
yep still relevant. eagerly waiting for PR to fix this!

**Comment by ArtemSkrebkov** [comment]
Amazing :) Looks like I don't have rights to assign the issue so I am just leaving a comment that I am going to work on it.

**Comment by vigsterkr** [comment]
Just go ahead and send in a draft pr and in the commit refer to this issue number.
