### ISSUE TITLE
Updated NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [shogun-toolbox/shogun#4583]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-shogun

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by vigsterkr** [comment]
@lisamartin72 thnx, i've just updated the website!
