### ISSUE TITLE
Wrong instructions in INTERFACES.md

### ISSUE THREAD

**Issue by jianhongwu** [shogun-toolbox/shogun#4587]
when I compiled shogun under ubuntu from sources, I followed this instructions:
```
export LD_LIBRARY_PATH="path/to/libshogun.so:$LD_LIBRARY_PATH"
```
in my case, it was:
```
export LD_LIBRARY_PATH="/usr/local/lib/libshogun.so:$LD_LIBRARY_PATH"
```
after that it didn't work, cuz LD_LIBRARY_PATH should be a path, not a file.
I succeeded by doing:
```
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
```
other instructions seems to have the same problem, plz check that.

**Comment by vinx13** [comment]
`path/to/libshogun.so` means the directory of libshogun.so

**Comment by lisitsyn** [comment]
I think the issue is reasonable. I did mention it is a directory in 1551d2a.
