### ISSUE TITLE
MMD unbiased estimate issue

### ISSUE THREAD

**Issue by saeidnp** [shogun-toolbox/shogun#4595]
I run the following code which computes MMD unbiased estimate multiple times. Since both the distributions are Normal(0,1) and the estimate is unbiased, I expect the average output to be 0. However, it always prints the exact same number (-0.6577018139068969)

```
import numpy as np
from torch.distributions.normal import Normal
import shogun as sg

for _ in range(100):
    X = Normal(0,1).sample((7000,)).numpy().reshape(-1,1)
    Y = Normal(0,1).sample((7000,)).numpy().reshape(-1,1)
    mmd = sg.QuadraticTimeMMD()
    mmd.set_p(sg.RealFeatures(X.T.astype(np.float64)))
    mmd.set_q(sg.RealFeatures(Y.T.astype(np.float64)))
    mmd.set_kernel(sg.GaussianKernel(32, 1))
    mmd.set_statistic_type(sg.ST_UNBIASED_FULL)
    stat = mmd.compute_statistic()
    print('stat = ', stat)
```

**Comment by lambday** [comment]
Hi @saeidnp. Thanks for letting us know. I'll check and get back to you on this.

**Comment by karlnapf** [comment]
any updates @lambday ?

**Comment by karlnapf** [comment]
I just tried and I get
```
$ python -c "
import numpy as np
import shogun as sg

for _ in range(100):
    N = 2000
    X = np.random.randn(N).reshape(1,N)
    Y = np.random.randn(N).reshape(1,N)
    mmd = sg.QuadraticTimeMMD()
    mmd.set_p(sg.RealFeatures(X.astype(np.float64)))
    mmd.set_q(sg.RealFeatures(Y.astype(np.float64)))
    mmd.set_kernel(sg.GaussianKernel(32, 1))
    mmd.set_statistic_type(sg.ST_UNBIASED_FULL)
    stat = mmd.compute_statistic()
    print('stat = ', stat)"
('stat = ', -0.2680720353964716)
('stat = ', 0.8969325572252274)
('stat = ', -0.17722320626489818)
('stat = ', -0.3892847162205726)
('stat = ', -0.3456891281530261)
...
```
I guess there is an issue with your random number generator?

**Comment by saeidnp** [comment]
@karlnapf in your code less samples are used than mine.
When I run your code, I get the expected output. But I tried your code with `N = 7000` and got that magic number (-0.6577018139068969) again!

**Comment by karlnapf** [comment]
That seems strange to me but I’ll check!

**Comment by karlnapf** [comment]
I get exactly the same magic number. Crazy! This is a bug and I will dig deeper once I have a moment. @lambday might also be able to help

**Comment by karlnapf** [comment]
This is an overflow issue caused by a `.sum()` call of an Eigen3 block. Will fix it next

**Comment by gbaydin** [comment]
@saeidnp can you please confirm whether this closed issue fixed the "magic number" problem? The issue is closed but I don't see a message here saying that the bug is fixed.

**Comment by karlnapf** [comment]
@gbaydin yes it is solved via my hotfix. Could you confirm if you are using it?

It (unfortunately) will now a tiny bit slower than before due to the lack of low level vectorization in Eigen3 when summing the kernel matrix, now a c++ loop rather than SIMD summations of the columns. But that should only be noticeable when sampling from the null distribution (repeated computation of the test). We will run benchmarks and potentially try to improve it.

**Comment by saeidnp** [comment]
@gbaydin @karlnapf yes it passes my tests.

**Comment by karlnapf** [comment]
Great, thanks
