### ISSUE TITLE
Strange if statement

### ISSUE THREAD

**Issue by voldemoriarty** [shogun-toolbox/shogun#4599]
Browsing the code in `src/shogun/neuralnets/NeuralNetworks.cpp` I noticed a strange if statement

https://github.com/shogun-toolbox/shogun/blob/9537f595679993bd56a833629cba832c97165c5c/src/shogun/neuralnets/NeuralNetwork.cpp#L395

I think the `|| 1` is redundant here

**Comment by yinhaosen** [comment]
I think so the statement always evaluates to true.

**Comment by vinx13** [comment]
@voldemoriarty I think `|| 1` should be removed. Would you like to check the value of `result` and send a PR?

**Comment by karlnapf** [comment]
yep can be removed, == has higher priority than ||, https://en.cppreference.com/w/cpp/language/operator_precedence

**Comment by gf712** [comment]
Not sure if this has been fixed, but if not it's an easy first issue
