### ISSUE TITLE
MKL with SVM for Multiclass face Recognition

### ISSUE THREAD

**Issue by muhannad35990** [shogun-toolbox/shogun#4607]
I want to implement MKL with SVM on face Recognition to fuse multiple features
in openCV Library I use this code for train : 
```
Ptr<TrainData> td = TrainData::create(svm_training_data, ROW_SAMPLE,Labels);
   svm->trainAuto(td);
```
and for prediction of new Data use:
` response1=svm->predict(bowDescriptor1);`

but OpenCv doesn't support custom kernel for SVM so I'm using shogun to do the fusion using MKL , I use this code : 

```

shogun::SGMatrix<double> m(vectors,matAngles.cols,matAngles.rows);
shogun::CDenseFeatures<double> *features = new shogun::CDenseFeatures<double>(m);
shogun::SGVector<double> l(classes,MotionfaceLabels.size(), false);
shogun::CMulticlassLabels *labels = new shogun::CMulticlassLabels(l);

/* Generate custom kernel (gram) matrix */
shogun::SGMatrix<double> k(matAngles.rows,matAngles.rows);
 std::vector< std::vector<double>> kernel1(matAngles.rows,std::vector<double>(matAngles.rows,0));
      /* Dot product */
     for (int i = 0; i <matAngles.rows; i++) {
          k(i, i) = 1.0;
          for (int j = i; j <matAngles.rows; j++) {
              double sim = 0.0;
              for (int k = 0; k < matAngles.cols; k++) {
                  {
                      double to=m(i, k) * m(j, k);
                      sim += to;
                  }
              }
              sim /= matAngles.rows;
              kernel1[i][j]=sim;
              kernel1[j][i]=sim;
              //k(i, j) = sim;
             // k(j, i) = sim;
          }
      }

// /////////////////second kernel////////////////////////////

    int ccccc1=matAngles.rows*matAngles.cols;
    shogun::SGVector<double>  vectors1(ccccc1);
    //double vectors[ccccc];
   shogun::SGVector<double>  classes1(matAngles.rows);
    //double classes[svm_training_data.rows];
    for(int i=0;i<matAngles.cols;i++)
    {
        for(int j=0;j<matAngles.rows;j++)
            vectors1[i+j]=matAngles.at<float>(i,j);
    }
    for(int i=0;i<MotionfaceLabels.size();i++)
        classes1[i]=MotionfaceLabels[i];
    shogun::SGMatrix<double> m1(vectors1, matAngles.cols, matAngles.rows);
    shogun::CDenseFeatures<double> *features1 = new shogun::CDenseFeatures<double>(m1);
 shogun::SGVector<double> l1(classes1,MotionfaceLabels.size(), false);
 shogun::CMulticlassLabels *labels1 = new shogun::CMulticlassLabels(l1);

  /* Generate 2ed custom kernel (gram) matrix */
   shogun::SGMatrix<double> k1(matAngles.rows,matAngles.rows);
    std::vector< std::vector<double>> kernel2(matAngles.rows,std::vector<double (matAngles.rows,0));

    /* Dot product */
  for (int i = 0; i <matAngles.rows; i++) {
        k1(i, i) = 1.0;
        for (int j = i; j <matAngles.rows; j++) {
            double sim = 0.0;
            for (int k = 0; k < matAngles.cols; k++) {
                {
                    double to=m1(i, k) * m1(j, k);
                    sim += to;
                }
            }
            sim /= matAngles.rows;
            kernel2[i][j]=sim;
            kernel2[j][i]=sim;
           // k1(i, j) = sim;
           // k1(j, i) = sim;
        }
    }
for(int i=0;i<kernel1.size();i++)
{
    for(int j=0;j<kernel1[i].size();j++)
    {
        k(i,j)=kernel1[i][j];
    }
}
for(int i=0;i<kernel2.size();i++)
{
    for(int j=0;j<kernel2[i].size();j++)
    {
        k1(i,j)=kernel2[i][j];
    }
}
    /* Build combined kernel */
cfeats = new shogun::CCombinedFeatures();
 cker = new shogun::CCombinedKernel();

    /* 1st kernel: custom */
  shogun::CCustomKernel *k0 = new shogun::CCustomKernel(k);
    cfeats->append_feature_obj(features);
    cker->append_kernel(k0);
    shogun::CCustomKernel *k00 = new shogun::CCustomKernel(k1);
    cfeats->append_feature_obj(features1);
    cker->append_kernel(k00);
    cker->init(cfeats, cfeats);

    /* Create MKL instance */
   shogun::CMKLMulticlass mkl = new shogun::CMKLMulticlass(1.2, cker, labels);
     mkl->set_epsilon(0.00001);
     mkl->parallel->set_num_threads(4);
     mkl->set_mkl_epsilon(0.001);
     mkl->set_mkl_norm(1.5);
 /* Train */
mkl->train();

```

to test on the same train data I use this Line: 

```
 shogun::CMulticlassLabels* res=shogun::CLabelsFactory::to_multiclass(mkl->apply());
 float64_t err=0;
    for(int32_t i=0; i< res->get_num_labels();++i)
    {
        if (labels->get_int_label(i)!=res->get_int_label(i))
                err+=1;
    std::cout<<res->get_int_label(i)<<"::";

    }
    err/=(float64_t)res->get_num_labels();
    std::cout << "prediction error on training data:"<<err<< std::endl;
 
```
but the prediction error is very big and almost all the prediction results are wrong! 
what is the wrong I'm doing?!
please help !

**Comment by karlnapf** [comment]
Hi @muhannad35990 thanks for reporting this. It is very hard to tell what is the problem from the information you provided. If you could provide a stand-alone minimal example that reproduces the behaviour your describe, I can have a look.

**Comment by muhannad35990** [comment]
here is a modifed one with comments on each line 
`//svm_training_data is the first feature matrix that when train using it with opencv lib the results is very good
//matAngles is the second feature matrix that when train using it with opencv lib the results is very good
//now we want to fuse the two featue matrixes using MKL and shogun
//first convert each form cv::mat to SGMatrix
//svm_training_data and matAngles have the same size
   int ccccc=svm_training_data.rows*svm_training_data.cols;
    shogun::SGVector<float64_t>  vectors(ccccc),vectors1(ccccc);

    for(int i=0;i<svm_training_data.rows;i++)
    {
        for(int j=0;j<svm_training_data.cols;j++)
            vectors[i+j]=svm_training_data.at<float>(i,j);
    }
  for(int i=0;i<matAngles.rows;i++)
    {
        for(int j=0;j<matAngles.cols;j++)
            vectors1[i+j]=matAngles.at<float>(i,j);
    }    
 shogun::SGMatrix<float64_t> m(vectors1, svm_training_data.cols, svm_training_data.rows);
shogun::SGMatrix<double> m1(vectors,matAngles.cols,matAngles.rows);
//add labels to SGVector
shogun::SGVector<double>  classes(svm_training_data.rows);
shogun::SGVector<double>  classes1(matAngles.rows);		
	for(int i=0;i<fLabels.size();i++)
    classes[i]=fLabels[i];
    for(int i=0;i<fLabels.size();i++)
        classes1[i]=fLabels[i];
//create  CDenseFeatures from m,m1
shogun::CDenseFeatures<double> *features = new shogun::CDenseFeatures<double>(m);
shogun::CDenseFeatures<double> *features1 = new shogun::CDenseFeatures<double>(m1);
//create SGVector labels from classes
shogun::SGVector<double> l(classes,labels.size(), false);
 shogun::SGVector<double> l1(classes1,MotionfaceLabels.size(), false);
 // create CMulticlassLabels labels
shogun::CMulticlassLabels *labels = new shogun::CMulticlassLabels(l);
 shogun::CMulticlassLabels *labels1 = new shogun::CMulticlassLabels(l1);
 
 //create kernels 
  shogun::CGaussianKernel *chk1=new shogun::CGaussianKernel(features,features,1.2, 10);
 shogun::CGaussianKernel *chk2=new shogun::CGaussianKernel(features1,features,1.2, 10);
     /* Build combined kernel */
 shogun::CCombinedFeatures *cfeats = new shogun::CCombinedFeatures();
 shogun::CCombinedKernel *cker = new shogun::CCombinedKernel();

cfeats->append_feature_obj(features);
cfeats->append_feature_obj(features1);
cker->append_kernel(chk1);
cker->append_kernel(chk2);
cker->init(cfeats, cfeats);

/* Create MKL instance */
shogun::CMKLMulticlass mkl = new shogun::CMKLMulticlass(1.2, cker, labels);
 mkl->set_epsilon(0.00001);
 mkl->parallel->set_num_threads(4);
 mkl->set_mkl_epsilon(0.001);
 mkl->set_mkl_norm(1.5);
/* Train */
mkl->train();

//to test on the same train use this Line:

 shogun::CMulticlassLabels* res=shogun::CLabelsFactory::to_multiclass(mkl->apply());
 //calculate the error rate
 float64_t err=0;
    for(int32_t i=0; i< res->get_num_labels();++i)
    {
        if (labels->get_int_label(i)!=res->get_int_label(i))
                err+=1;
    std::cout<<res->get_int_label(i)<<"::";

    }
    err/=(float64_t)res->get_num_labels();
    std::cout << "prediction error on training data:"<<err<< std::endl;`

**Comment by muhannad35990** [comment]
I finally found the error was in preparing the train data I used the following code to build the feature vector:
```
                    shogun::SGMatrix<float64_t> train_dat1(matAngles.cols, matAngles.rows);
                        for (index_t i=0; i<matAngles.rows; ++i)
                        {
                            for (index_t j=0; j<matAngles.cols; ++j)
                            {

                                train_dat1.matrix[i*matAngles.cols+j]=matAngles.at<float>(i,j);
                            }
                        }
                        shogun::CDenseFeatures<float64_t>* features1=
                                new shogun::CDenseFeatures<float64_t>(train_dat1);  
```

I trained the MKL with this line : 
`mkl->train();`
and it is work good but I want to enhance the result using cross validation ,I used this code: 
//corss validation
```
   CMKLClassification* svmm=new CMKLClassification(new CLibSVM());
   svmm->set_interleaved_optimization_enabled(true);
   svmm->set_kernel(cker);
   index_t num_folds=2;
       CSplittingStrategy* split=new CStratifiedCrossValidationSplitting(labels, num_folds);
       CEvaluation* eval=new CContingencyTableEvaluation(ACCURACY);
       CCrossValidation* cross=new CCrossValidation(svmm, cfeats, labels, split, eval, false);
       CParameterObserverCV mkl_obs{true};
       cross->subscribe_to_parameters(&mkl_obs);
       cross->set_autolock(false);
           cross->set_num_runs(2);
   CCrossValidationResult* result=(CCrossValidationResult*)cross->evaluate();

```
but it gives this error:
```
[DEBUG] starting training
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::init(000000000D0DF430, 000000000D0DF430)
[DEBUG] Starting for loop for kernels
[DEBUG] Initializing 0x000000000D43C850 - "GaussianKernel"
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::init(00000000136197A0, 00000000136197A0)
[DEBUG] Initializing 0x000000000D43C850 - "GaussianKernel"
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] entering CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::remove_lhs_and_rhs
[DEBUG] leaving CKernel::init(00000000136198A0, 00000000136198A0)
Invalid parameter passed to C runtime function.
```

what is the wrong I'm doing, please help!
