### ISSUE TITLE
get("labels") is broken

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4609]
```
import shogun as sg
from shogun import SVMLight
from shogun import BinaryLabels

num = 10
dist = 1
width = 2.1
C = 2.0
traindata_real = concatenate((randn(2,num)-dist, randn(2,num)+dist), axis=1)
testdata_real = concatenate((randn(2,num)-dist, randn(2,num)+dist), axis=1);

trainlab = concatenate((-ones(num), ones(num)));
testlab = concatenate((-ones(num), ones(num)));

feats_train = sg.features(traindata_real);
feats_test = sg.features(testdata_real);
kernel = sg.kernel("GaussianKernel", log_width=width)
kernel.init(feats_train, feats_train)

labels = BinaryLabels(trainlab);

svm = SVMLight(C, kernel, labels)
svm.train()
print(svm.get_labels())
print(svm.get("labels"))
```

the last command will fail... this is consistent with c++ api

**Comment by vigsterkr** [comment]
same is true for LibSVM

**Comment by gf712** [comment]
The issue is probably because the function in https://github.com/shogun-toolbox/shogun/commit/9537f595679993bd56a833629cba832c97165c5c#diff-1689b0bd3ceb28355cc3c05ed7ffe4f0R1100 doesnt have CLabels (or CDistance) in it

**Comment by vigsterkr** [comment]
Ah marvelous... thnx for the quick reply... although it doesnt explain why a deser svm fails with not having labels :s (get_labels do returns the labels)

**Comment by gf712** [comment]
what do you mean? What error do you get?

**Comment by vigsterkr** [comment]
That labels are not set (when trying to run train), but as said gat_labels returns a correct binarylabels obj

**Comment by vigsterkr** [comment]
i'll leave this one open until the getter is not added to the interface

**Comment by gf712** [comment]
is this fixed?

**Comment by karlnapf** [comment]
idk, but I guess it would be easy to find out ...
