### ISSUE TITLE
[Error]:Cannot convert MulticlassLabels to binary labels:

### ISSUE THREAD

**Issue by wang8297161** [shogun-toolbox/shogun#4610]
It can run successfully when i test the example (cross_validation_support_vector_machine.py), which is an official example about binary classification using SVM  and cross validation.
However, when i replace the input feature and label with my own data, which is multilabel.

The error comes as : 
result = cross.evaluate()
Traceback (most recent call last):
  File "/home/zzz/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/zzz/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/zzz/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zzz/pycharm-community-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/zzz/Desktop/test/cross_validation_support_vector_machine.py", line 22, in <module>
    result = cross.evaluate()
SystemError: [ERROR] In file /home/zzz/shogun/src/shogun/labels/BinaryLabels.cpp line 161: Cannot convert MulticlassLabels to binary labels: [ERROR] In file /home/zzz/shogun/src/shogun/labels/BinaryLabels.cpp line 154: Sorry, not yet implemented .

I've uploaded the my data, python file and the official example in the form of zip.

[official example.zip](https://github.com/shogun-toolbox/shogun/files/3083541/official.example.zip)
[my_code.zip](https://github.com/shogun-toolbox/shogun/files/3083543/my_code.zip)

Any advice can be very helpful. Thanks.

**Comment by karlnapf** [comment]
SMVs are for binary label problems. If you want to run SVMs for multiple classes you need to use that corresponsing interface, see e.g. [here](http://shogun.ml/examples/latest/examples/multiclass_classifier/multiclass_linearmachine.html)

**Comment by karlnapf** [comment]
Or you can also use native multiclass SVM implementations. In any case, check out this as well:
http://shogun.ml/api/latest/classshogun_1_1CMulticlassSVM.html

**Comment by wang8297161** [comment]
Thank you for helping me in solving this error. It runs successfully when i rewrite the code, replacing the `svm = machine("LibLinear", liblinear_solver_type="L2R_L2LOSS_SVC") `  with `svm = machine("MulticlassLibSVM", C=C, kernel=gauss_kernel, labels=labs)`, then `svm.train(feats)`. 

However ,the same error still comes when using crossvalidation. 

strategy = splitting_strategy("StratifiedCrossValidationSplitting", labels=labs, num_subsets=2)
evaluation_criterion = evaluation("AccuracyMeasure")
cross = machine_evaluation("CrossValidation", machine=svm, features=feats, labels=labs, splitting_strategy=strategy, evaluation_criterion=evaluation_criterion, num_runs=2)

result = cross.evaluate()

The error comes when the program runs to the " result = cross.evaluate() "
Still, "Cannot convert MulticlassLabels to binary labels"

Here is the full code.
[cross_validation_support_vector_machine.zip](https://github.com/shogun-toolbox/shogun/files/3087545/cross_validation_support_vector_machine.zip)

Again, thanks for your help.

**Comment by karlnapf** [comment]
That is a bug then. 
Could you post your code as a github gist or via pastebin instead of a zip file please?

**Comment by wang8297161** [comment]
OK, no problem. 
[gist](https://gist.github.com/wang8297161/69e3b72d1495d81a3a65b308624d17ca)

**Comment by karlnapf** [comment]
I reproduced the error locally, will check what is going on and then get back to you

**Comment by wang8297161** [comment]
Thanks man, hoping to receive the solution.
