### ISSUE TITLE
Multi-kernel learning problem-SVMLight

### ISSUE THREAD

**Issue by LiYaoooo** [shogun-toolbox/shogun#4622]
Hello, there is a  problem when I ran the example of mkl-ninclass function in shogun toolbox using python 3.5 of windows10.
1. when run these code:

try:
   from shogun import SVMLight
except ImportError:
   print("SVMLight not available")
   exit(0)

it occured "SVMLight not available".

 So can you tell me  how to slove this problem?  I have been load Libvim package into python 3.5.Thank you so much.

**Comment by karlnapf** [comment]
You will have to compile Shogun by hand with `-DUSE_SVMLLIGHT=On` (which will only work if you also set `-DLICENSE_GPL_SHOGUN=On`

**Comment by LiYaoooo** [comment]
Thank your reply. I met a error when compiled Shogun by hand according to installing Shogun .
when I input
cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_META_EXAMPLES=OFF -DENABLE_TESTING=ON ..
,(I have installed Visual Studio 14 2015), it occurs following errors：
C:\Users\LY\shogun\build>cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYP
E=Release -DBUILD_META_EXAMPLES=OFF -DENABLE_TESTING=ON ..
CMake Error at CMakeLists.txt:27 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

   Microsoft (R) build engine version 14.0.25420.1
     Copyright (C) Microsoft Corporation. all rights reserved.

     The build start time is 2019/4/30 16:48:40.
     Project "C:\Users\LY\shogun\build\CMakeFiles\3.14.0\VCTargetsPath.vc on node 1
Xproj" (default target).
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\Platfor
mToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1
 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [C:\Users\LY\shogun\build\CMakeFiles\3.14.0\VCTargetsPa
th.vcxproj]
    The build project "C:\Users\LY\shogun\build\CMakeFiles\3.14.0\VCTargetsPath.vcx has been completed
Operation of proj" (default target) - failed.

     The build failed.

     "C:\Users\LY\shogun\build\CMakeFiles\3.14.0\VCTargetsPath.vcxproj" (default
Standard) (1) ->
     (Desktop_PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\Platf
ormToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8
.1 was not found. Install the required version of Windows SDK or change the SDK
version in the project property pages or by right-clicking the solution and sele
cting "Retarget solution". [C:\Users\LY\shogun\build\CMakeFiles\3.14.0\VCTargets
Path.vcxproj]

        0 warning
        1 error

    Timing Cost  00:00:00.59


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/LY/shogun/build/CMakeFiles/CMakeOutput.log".

What should I do?

**Comment by LiYaoooo** [comment]
And I didn't see -DUSE_SVMLLIGHT=On and -DLICENSE_GPL_SHOGUN=On, and only saw -USE_SVMLLIGHT=On and -LICENSE_GPL_SHOGUN=On. Do -DUSE_SVMLLIGHT=On and -DLICENSE_GPL_SHOGUN=On occur afer compiling shougun (that is, after cmake compiling)?

**Comment by karlnapf** [comment]
Sorry I am not sure I follow. But I reccommend to read our readmes for compiling. They cover the whole cmake process and compiling
