### ISSUE TITLE
Security warning for website on Mozilla Firefox

### ISSUE THREAD

**Issue by cseas** [shogun-toolbox/shogun#4630]
Mozilla Firefox displays a security warning when visiting the Shogun website: https://shogun.ml/

Screenshot:
![Selection_028](https://user-images.githubusercontent.com/29686866/57568691-8f0c0200-7408-11e9-80d3-d32aa8eba4eb.png)

This warning is not displayed when visiting the site without https:
http://shogun.ml
The https link is mentioned [here](https://github.com/shogun-toolbox/shogun/wiki/Google-season-of-docs-2019).

**Comment by lisitsyn** [comment]
Thanks for reporting. I can reproduce that. It looks like the certificate has expired long ago.

@vigsterkr didn't you add let's encrypt for that? I have some vague memory of that..

**Comment by scpeters** [comment]
I think this has been fixed
