### ISSUE TITLE
Implement Levenstein string distance algorithm

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4639]
To be used in #4473

First standalone against `std::string`, and then also embedded in a `CDistance` specialization.

**Comment by assignment6** [comment]
Hello,
Does this have to be in Python?  I can do in C ;-)

**Comment by gf712** [comment]
Hey @assignment6, no, the idea is to have it in C++ so that it can be exposed to the other languages!

**Comment by assignment6** [comment]
Ol.  But the other languages are based on C ;-), just sayin'

**Comment by infinidoko** [comment]
Hi, please i would like to work on this if the issue is still available. I can implement the algorithm in c++.

**Comment by karlnapf** [comment]
please go ahead

**Comment by hariduttt** [comment]
Has it been implemented or I would like to work on it.

**Comment by voldemoriarty** [comment]
https://bitbucket.org/clearer/iosifovich/src/master/

**Comment by karlnapf** [comment]
We sometimes copy paste import code of license permits, it is standalone and minimal, and very specific to what we need (contains nothing else).

**Comment by h-sigma** [comment]
[levenshtein.txt](https://github.com/shogun-toolbox/shogun/files/3396916/levenshtein.txt)
Would this suffice? I can rewrite it to not use standard library classes.

**Comment by vigsterkr** [comment]
@h-sigma great start but for being able to review and give you feedback we would actually would like to have a pull request sent in with the changes you propose. for how to go further: https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md

**Comment by tthebst** [comment]
Hi, I want to try this. Anything special I need to know?

**Comment by darelover** [comment]
Hi, I would like to work on this issue but I have few doubts:

1. Where should I put the file in the project?
2. Should i make it a header file or not?
3. Is there any header file that i need to include?

**Comment by gf712** [comment]
> Hi, I would like to work on this issue but I have few doubts:
> 
>     1. Where should I put the file in the project?

You could probably put it in shogun/distance

>     2. Should i make it a header file or not?

Check out other distance implementations, such as EuclideanDistance.[h](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/distance/EuclideanDistance.h)/[cpp](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/distance/EuclideanDistance.cpp)

>     3. Is there any header file that i need to include?

see above, and also checkout https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md. We can help more once you start a PR!

**Comment by devramx** [comment]
Requesting review :)
[PR#4778](https://github.com/shogun-toolbox/shogun/pull/4778)

**Comment by sdcpk** [comment]
Is this issue this available to work on?

**Comment by Caynosadler** [comment]
@karlnapf is this issue still open, i'll like to work on it

**Comment by anis-agwan** [comment]
Is this issue fixed or still open?

**Comment by krutikabapat** [comment]
Is this issue still open?

**Comment by vigsterkr** [comment]
fixed in #4806
