### ISSUE TITLE
GMM segfaults when calling train_smem().

### ISSUE THREAD

**Issue by geektoni** [shogun-toolbox/shogun#4654]
Shogun's Gaussian Mixture Models model fails with a segfault if we try to call `gmm.train_em()` and `gmm.train_smem()` one after the other without adding `gmm.sample()` between them (?!). This happens with the current `develop` branch.

Minimal example:
```c++
#include <shogun/base/init.h>
#include <shogun/base/some.h>
#include <shogun/clustering/GMM.h>
#include <shogun/features/Features.h>
#include <shogun/io/File.h>                            
#include <shogun/io/SerializableAsciiFile.h>         
#include <shogun/lib/DynamicObjectArray.h>                      
#include <shogun/lib/SGMatrix.h>
#include <shogun/lib/SGVector.h>
#include <shogun/mathematics/Math.h>
#include <shogun/util/factory.h>                    
                   
using namespace shogun;
                                                                     
int main(int, char*[])                        
{                                                                                       
init_shogun_with_defaults();                                 
CMath::init_random(1);                   
                                                           
auto f_feats_train = wrap(csv_file("../../data/classifier_4class_2d_linear_features_train.dat"));
auto features_train = wrap(features(f_feats_train));
                                                                                                 
auto num_components = wrap(3);
auto gmm = some<CGMM>(num_components);

gmm->put("features", features_train);
gmm->train_em();
//auto output = gmm->sample() // If this line is not used this code will segfault.

gmm->train_smem();

exit_shogun();
return 0;
}
```

**Comment by geektoni** [comment]
Actually, this bug happens also when calling directly `train_smem()`. Therefore, I would say that `train_smem()` is atm broken.

**Comment by karlnapf** [comment]
which one is called in ::train()?

**Comment by geektoni** [comment]
The `train()` method only sets the feature needed. In order to train the `GMM` you need to call `train_em()` or `train_smem()`.

**Comment by ghost** [comment]
The problem is these lines
https://github.com/shogun-toolbox/shogun/blob/46129dab22ec734937602467b7d5c2b7d0fc248e/src/shogun/clustering/GMM.cpp#L328-L334
Components of candidate are "SG_UNREF"ed, then candidate is deleted, thus double "SG_UNREF" because of the destructor.
Don't know if sending a batch is worth it, since viktor's PR solves these memory problems.

**Comment by karlnapf** [comment]
I think it is worth :) but only if it takes you a few mins only.... but since you basically solved the problem already, why not put it in...
