### ISSUE TITLE
name 'CombinedKernel' is not defined

### ISSUE THREAD

**Issue by sancica-github** [shogun-toolbox/shogun#4660]
I succeed install the shogun by manually In order to use  MKL,  cmake -DUSE_SVMLIGHT=ON.
I first open the doc/ipynb-notebooks,and test the MKL.ipynb，but this code can't run as follows:
kernel = CombinedKernel()
NameError: name 'CombinedKernel' is not defined.
I need your helps.

**Comment by sancica-github** [comment]
where can I find the python api?

**Comment by gf712** [comment]
Hi @sancica-github did you compile shogun with the develop branch? If so it should be:
```python
import shogun as sg
kernel = sg.kernel("CombinedKernel")
```

**Comment by sancica-github** [comment]
@gf712 Thank you for your reply，It's work. Do you know where can I find the latest examples or the cookbook, the examples from the official website are outdated. This project is no longer update?

**Comment by karlnapf** [comment]
The examples in the website are for the latest release. The development branch is not released yet. However you can build the examples/cookbook locally, see the readme.
