### ISSUE TITLE
SGVector::resize_vector is broken

### ISSUE THREAD

**Issue by theartful** [shogun-toolbox/shogun#4663]
The current implementation of resize_vector is
```C++
template<class T>
void SGVector<T>::resize_vector(int32_t n)
{
	assert_on_cpu();
	vector=SG_REALLOC(T, vector, vlen, n);

	if (n > vlen)
		memset(&vector[vlen], 0, (n-vlen)*sizeof(T));
	vlen=n;
}
```
It reallocates new memory segment and deallocates the previous one, without taking into account other SGVectors pointing at the same area. A possible solution is not to deallocate the previous data, and make the `ReferencedData` detach, thus effectively creating a new SGVector.

**Comment by vigsterkr** [comment]
@theartful realloc will try to actually extend the existing memory region, so the pointer should not change actually only the size....
```The realloc() function changes the size of the memory block pointed to by ptr to size bytes. The contents will be unchanged in the range from the start of the region up to the minimum of the old and new sizes```

or i'm not so sure what you mean here...?

**Comment by theartful** [comment]
`SG_REALLOC` actually doesn't use realloc. This is the implementation:
```C++
template<class T, std::enable_if_t<is_sg_referenced<T>::value, T>* = nullptr>
T* sg_generic_realloc(T* ptr, size_t old_len, size_t len)
{
	T* new_ptr = new T[len]();
	size_t min_len=old_len;
	if (len<min_len)
		min_len=len;
	for (size_t i=0; i<min_len; i++)
		new_ptr[i]=ptr[i];
	delete[] ptr;
	return new_ptr;
}
```
Also I believe that realloc might move the data to a new place if it couldn't extend.

**Comment by vigsterkr** [comment]
that's for memory that has been allocated with new operator.... not with SG_MALLOC/CALLOC

**Comment by vigsterkr** [comment]
the corresponding code piece is this:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/memory.cpp#L289-L335

**Comment by vigsterkr** [comment]
the corresponding code piece is this:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/memory.cpp#L289-L335
