### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skn123** [shogun-toolbox/shogun#4691]
Fresh checkout from Master

/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:83:10: error: no template named 'CoverTreePoint'
        typedef CoverTreePoint<RandomAccessIterator> TreePoint;
                ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:84:2: error: use of undeclared identifier 'v_array'
        v_array<TreePoint> points;
        ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:84:21: error: use of undeclared identifier 'points'; did you mean 'printf'?
        v_array<TreePoint> points;
                           ^~~~~~
                           printf
/usr/include/stdio.h:318:12: note: 'printf' declared here
extern int printf (const char *__restrict __format, ...);
           ^
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/tapkee_shogun.cpp:18:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/tapkee.hpp:10:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/embed.hpp:11:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/methods.hpp:29:
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:86:8: error: use of undeclared identifier 'points'
                push(points, TreePoint(iter, callback(iter,iter)));
                     ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:88:2: error: use of undeclared identifier 'node'
        node<TreePoint> ct = batch_create(callback, points);
        ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:88:18: error: use of undeclared identifier 'ct'
        node<TreePoint> ct = batch_create(callback, points);
                        ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:88:46: error: use of undeclared identifier 'points'; did you mean 'printf'?
        node<TreePoint> ct = batch_create(callback, points);
                                                    ^~~~~~
                                                    printf
/usr/include/stdio.h:318:12: note: 'printf' declared here
extern int printf (const char *__restrict __format, ...);
           ^
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/tapkee_shogun.cpp:18:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/tapkee.hpp:10:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/embed.hpp:11:
In file included from /home/naths/srcs/shogun/src/shogun/lib/tapkee/methods.hpp:29:
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:90:2: error: use of undeclared identifier 'v_array'
        v_array< v_array<TreePoint> > res;
        ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:90:11: error: use of undeclared identifier 'v_array'
        v_array< v_array<TreePoint> > res;
                 ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:90:30: error: expected expression
        v_array< v_array<TreePoint> > res;
                                    ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:90:32: error: use of undeclared identifier 'res'
        v_array< v_array<TreePoint> > res;
                                      ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:92:30: error: use of undeclared identifier 'ct'
        k_nearest_neighbor(callback,ct,ct,res,k);
                                    ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:92:33: error: use of undeclared identifier 'ct'
        k_nearest_neighbor(callback,ct,ct,res,k);
                                       ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:92:36: error: use of undeclared identifier 'res'
        k_nearest_neighbor(callback,ct,ct,res,k);
                                          ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:96:20: error: use of undeclared identifier 'res'
        assert(end-begin==res.index);
                          ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:97:18: error: use of undeclared identifier 'res'
        for (int i=0; i<res.index; ++i)
                        ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:105:8: error: use of undeclared identifier 'res'
                        if (res[i][j].iter_-begin==res[i][0].iter_-begin)
                            ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:105:31: error: use of undeclared identifier 'res'
                        if (res[i][j].iter_-begin==res[i][0].iter_-begin)
                                                   ^
/home/naths/srcs/shogun/src/shogun/lib/tapkee/neighbors/neighbors.hpp:107:30: error: use of undeclared identifier 'res'
                        local_neighbors.push_back(res[i][j].iter_-begin);
                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by karlnapf** [comment]
can you try this on develop?
