### ISSUE TITLE
server restart

### ISSUE THREAD

**Issue by pcaiyappa** [shogun-toolbox/shogun#4694]
Hi Shogun developers

Thanks for your toolbox. I'm looking to download it and use the Oligo kernel in an SVM for some sequence analysis. Looks like your server is down, can you please restart it? I wanted to get access to the docs.

Thanks
PC

**Comment by karlnapf** [comment]
Yes, we are doing some work on it. If you want to access the docs, you can build it yourself:

`make doc`, or
`make cookbook`
`make doxygen`

There are also various readmes in `doc/readme`

**Comment by pcaiyappa** [comment]
Got it. Thank you!
