### ISSUE TITLE
Hosting tarballs on website?

### ISSUE THREAD

**Issue by scpeters** [shogun-toolbox/shogun#4696]
The homebrew-core formula for shogun references a tarball on your website, but it is not accessible at the moment.

* http://shogun-toolbox.org/archives/shogun/releases/6.1/sources/shogun-6.1.3.tar.bz2
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/shogun.rb#L4

Do you intend to host tarballs on your website for stable releases or should they be accessed directly from GitHub?

**Comment by karlnapf** [comment]
yes we intend to host those ... but the website is nonfunctional atm. The tarballs will be back once the website runs again, in the meantime, please use github

**Comment by scpeters** [comment]
Is there a difference between your hosted tarballs and the github tarball? I tried switching to use the github tarball in https://github.com/Homebrew/homebrew-core/pull/41561 and the homebrew CI build fails:

* https://gist.github.com/scpeters/1dd17bae16915321d21e1aca55e01a0e

~~~
CMake Error at src/shogun/CMakeLists.txt:49 (MESSAGE):
  Shogun can only be built with GPL codes if the source files are in
  /tmp/shogun-20190702-39570-1q5ni8c/shogun-shogun_6.1.3/src/gpl.  Please
  download or disable.
~~~

**Comment by scpeters** [comment]
maybe this is related to #4402 ?

**Comment by samdbrice** [comment]
@karlnapf is there a benefit to using shogun-toolbox.org as opposed to [GitHub Releases](https://help.github.com/en/articles/creating-releases)?

**Comment by karlnapf** [comment]
Afaik this has historic reasons — github releases weren’t a thing back a while ago at least
I don’t see any reason not to transition, apart from maybe potential issues with submodules. @vigsterkr ?

**Comment by karlnapf** [comment]
The gpl error above surely is exactly that

**Comment by karlnapf** [comment]
Unfortunately: https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073

**Comment by scpeters** [comment]
Ok, do you have a plan for fixing the website or hosting the tarballs somewhere else?

**Comment by karlnapf** [comment]
I tend to think we will make those available on the website again (we have infrastructure to automate that). Probably will the next release, which hopefully will happen soon (we are pushing the technical bits necessary for that, which is why some of the website/hosting didnt get looked after that well)

**Comment by scpeters** [comment]
It's been a month now and I don't see any working tarballs. Would it be possible to manually upload a working tarball to the GitHub release page for the 6.1.3 or 6.1.4 release since the default GitHub tarballs don't include the submodule code? Otherwise I will suggest that we remove shogun from homebrew-core until a suitable tarball is made publicly available.

**Comment by vigsterkr** [comment]
@scpeters thank you for tracking this issue! due to summer holidays this has not been handled properly. i'll make sure that this will be addressed during this week and will update this issue once the proper tarballs are available (again).

**Comment by vigsterkr** [comment]
@scpeters just an update: currently refactoring our microservices and the tarballs should be back online within the next 12h

**Comment by vigsterkr** [comment]
@scpeters ok the old archives are back alive. i'm closing this issue... the 6.1.4 release archive will be available shortly

**Comment by scpeters** [comment]
thanks!
