### ISSUE TITLE
dont use repetitively string literals in c++ code

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4707]
due to the new tags framework we started to put string literals repetitively all around the code., hence the whole codebase starts to looks like a script code...
see for example:
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/regression/GaussianProcessRegression.cpp#L60
  https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/regression/GaussianProcessRegression.cpp#L68
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/observers/ParameterObserverCV.cpp#L97-L108

this might be fun and good in a short script (although not a longer one), but for a compiled framework this is just anti-pattern. and actually making refactor a pain in the ass in the future.

could we just agree that since we require c++17 we start to create:
`static constexpr const char * kSeedKey = "seed";`

public properties in the class and use this when referring to the actual key. or better yet we could directly create a static Tag<T> as well.

**Comment by gf712** [comment]
Yup, static tag would be good, or we use https://github.com/hogliux/semimap to have a compile/runtime time map in SGObject::Self, but would have to change things to make thread safe...

**Comment by karlnapf** [comment]
I had a discussion with @geektoni on this when we has working on the observer stuff and started removing getters/setters. I actually think we should just stick to those (e.g. `set_variance_vector`)....the put/get stuff imo should be solely for users.

On the other hand, if we can do compile time evaluated string-based tag access, I am fine with that as well, but I am not sure that is currently within reach?

So agreed, those scripty things should not be done and in fact be removed.

BTW, `void CParameterObserverCV::print_observed_value( CrossValidationStorage* value) const` are not good methods to have anyways ... we have a to string method that is exactly for that, the whole thing can be dropped @geektoni would you mind?

**Comment by iglesias** [comment]
Me gusta, @vigsterkr.

Only, shall we
```
constexpr std::string_view kSeedKey = "seed";
```
iso
```
static constexpr const char * kSeedKey = "seed";
```
for extra 💃 ?

**Comment by gf712** [comment]
This is good to ensure that we have a compile time error if we access something in the parameter map that doesn’t exist but we still have the runtime lookup..

**Comment by lisitsyn** [comment]
I don't think we should have these values as const strings. It would be better to have them as const Tags. In the best case these Tags should be constexpr evaluated into a number (hash) so that map access is really fast.

I see that as something like the following snippet:

Header:
```cpp
class GaussianProcessRegression {

   static const Tag<float> CURRENT_VALUE{"current_value"};

}

```

Implementation:
```cpp
...
put(CURRENT_VALUE, i)
...
```

**Comment by vigsterkr** [comment]
@lisitsyn yeah that was kind of the idea... that to use static variables instead of spreading around string literals.
