### ISSUE TITLE
refactor SGObject hacks

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4710]
SGObject::dispatch_array_type SGObject::get_dispatch_all_base_types and related methods are all hacks that should be implemented using visitor patterns.

**Comment by ktiefe** [comment]
First draft
https://github.com/shogun-toolbox/shogun/pull/4775

please check if it is a right way to resolve it.

**Comment by ktiefe** [comment]
probably i will need to use this:
https://www.etlcpp.com/blog/2017/11/12/templated-implementation-of-the-visitor-pattern/

for next step.
