### ISSUE TITLE
AppVeyor build url returns error

### ISSUE THREAD

**Issue by samdbrice** [shogun-toolbox/shogun#4723]
The [AppVeyor build url](https://ci.appveyor.com/project/vigsterkr/shogun) in the [Windows section](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#manual-windows) of the INSTALL docs return an error.

The url is currently: https://ci.appveyor.com/project/vigsterkr/shogun

<img width="1153" alt="Screen Shot 2019-07-17 at 2 21 49 AM" src="https://user-images.githubusercontent.com/7470577/61364654-1deb2f80-a83b-11e9-8713-293f22729876.png">

**Comment by vigsterkr** [comment]
indeed that should be updated as we've dropped appveyor in favour of azure pipelines

**Comment by krutikabapat** [comment]
@vigsterkr what is the new url for it?

**Comment by vigsterkr** [comment]
it's not appveyor anymore. it's azure pipelines... https://dev.azure.com/shogunml/shogun/_build?definitionId=2

but maybe it'd be better actually to write a bit more about windows compilation based on this content: https://github.com/shogun-toolbox/shogun/blob/develop/.ci/windows-steps.yml#L42
