### ISSUE TITLE
Update Fedora Package url in INSTALL docs

### ISSUE THREAD

**Issue by samdbrice** [shogun-toolbox/shogun#4724]
INSTALL docs [Fedora section](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#fedora-) - package url needs to be updated...

**From:** https://admin.fedoraproject.org/pkgdb/package/rpms/shogun/

**To:** https://apps.fedoraproject.org/packages/shogun

**Comment by karlnapf** [comment]
@besser82

**Comment by samdbrice** [comment]
This is super easy I can just take care of it
