### ISSUE TITLE
force disable USE_SWIG_DIRECTORS in case of SWIG 4.0.0

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4727]
swig 4.0 uses std::unexpected_handler when directors are enabled, which is removed in c++17  (https://en.cppreference.com/w/cpp/error/unexpected_handler). So if SWIG 4.0.0 is used we need to forcefully disable USE_SWIG_DIRECTORS cmake setting.

this will be fixed in 4.0.1 and later (see: https://github.com/swig/swig/blob/master/CHANGES.current#L37) so the check should be only for swig 4.0.0.

**Comment by ghost** [comment]
was this fixed? I installed swig 4.0.0 and the python interface was built without problems. build fails however with other interfaces but for different reason.
