### ISSUE TITLE
shogun 6.1.4 does not compile with shogun's gpl code

### ISSUE THREAD

**Issue by AlexB79** [shogun-toolbox/shogun#4741]
Hi all,

i need to use for a code to reproduce results svm light. cmake tells me that i must enable GPL shogun and download the gpl code.

Done, then: 

[ 74%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/__/gpl/shogun/classifier/svm/QPBSVMLib.cpp.o
/home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp: In constructor ‘shogun::CFeatureBlockLogisticRegression::CFeatureBlockLogisticRegression(float64_t, shogun::CFeatures*, shogun::CLabels*, shogun::CIndexBlockRelation*)’:
/home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp:37:31: error: ‘class shogun::CFeatures’ has no member named ‘as’; did you mean ‘has’?
  set_features(train_features->as<CDotFeatures>());
                               ^~
                               has
/home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp:37:46: error: expected primary-expression before ‘>’ token
  set_features(train_features->as<CDotFeatures>());

**Comment by ghost** [comment]
Did you change the code by mistake?
This is line 37 in FeatureBlockLogisticRegression.cpp `set_features(train_features->as<CDotFeatures>());`, which differs from the one in the error message `set_features(train_features->as());`

If so, please go to shogun/src/gpl/ and run `git reset --hard`, and then go to shogun/ and run `git submodule --init --recursive`

**Comment by AlexB79** [comment]
Hi Ahmed,

no it is more serious.

the code is from the zip from shogun-gpl
https://github.com/shogun-toolbox/shogun-gpl/

the github has it in its code:
CFeatureBlockLogisticRegression::CFeatureBlockLogisticRegression(
float64_t z, CFeatures* train_features,
CLabels* train_labels, CIndexBlockRelation* feature_relation) :
CLinearMachine()
{
init();
set_feature_relation(feature_relation);
set_z(z);
set_features(train_features->as<CDotFeatures>());
set_labels(train_labels->as<CBinaryLabels>());
register_parameters();
}

**Comment by ghost** [comment]
The master branch of shogun-gpl submodule is following the develop branch of shogun, and not the releases. Try acquiring the gpl code from this link https://github.com/shogun-toolbox/shogun-gpl/releases or https://github.com/shogun-toolbox/shogun-gpl/tree/29ca2ff930cd5d963b3a78e79160cc04d48970c2.

**Comment by AlexB79** [comment]
Hi Ahmed, that fixes the error, but ...

now it creates during linking an unrelated one:

[100%[100%] Linking CXX executable minimal
../../src/shogun/libshogun.so.18.0: undefined reference to `dsyev_'
../../src/shogun/libshogun.so.18.0: undefined reference to `dorgqr_'
../../src/shogun/libshogun.so.18.0: undefined reference to `dstemr_'
../../src/shogun/libshogun.so.18.0: undefined reference to `dsyevr_'
../../src/shogun/libshogun.so.18.0: undefined reference to `dsygvx_'
../../src/shogun/libshogun.so.18.0: undefined reference to `dgesvd_'

This seems to be related to not linking against  lapack I guess. I do not
see what it tries to compile unfortunately.

the most recent related i found was:
https://github.com/shogun-toolbox/shogun/issues/3752 , an unresolved one.

I am using ubuntu 18.04 LTS,

[image: image.png]

build/src/shogun has a lib, however i need to use the python interface in a
virtualenv ...

**Comment by ghost** [comment]
Yes it seems related to lapack, and it might be a bug in the way we detect blas and lapack.
Installing libopenblas `apt install libopenblas-base` might solve the problem, but before you do that, please go to a clean build directory, run `cmake <shogun directory>`, and send the output.

**Comment by AlexB79** [comment]
Hi Ahmed,

its a purely linking issue.
what fixed for me was just to install liblapacke-dev -- the e-appended
version of it.  its 5am in Vietnam now, i go to sleep :) thank you for the
help.

Regards, Alex

**Comment by karlnapf** [comment]
Thanks for sorting this out @theartful 

I wonder whether our cmake lapack detection needs update?

**Comment by Matthewlliu** [comment]
> Hi all,
> 
> i need to use for a code to reproduce results svm light. cmake tells me that i must enable GPL shogun and download the gpl code.
> 
> Done, then:
> 
> [ 74%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/__/gpl/shogun/classifier/svm/QPBSVMLib.cpp.o
> /home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp: In constructor ‘shogun::CFeatureBlockLogisticRegression::CFeatureBlockLogisticRegression(float64_t, shogun::CFeatures*, shogun::CLabels*, shogun::CIndexBlockRelation*)’:
> /home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp:37:31: error: ‘class shogun::CFeatures’ has no member named ‘as’; did you mean ‘has’?
> set_features(train_features->as());
> ^~
> has
> /home/binder/experiments/2019_exp/20072019_buildeclipse/shogunbuild/shogun-shogun_6.1.4/src/gpl/shogun/classifier/FeatureBlockLogisticRegression.cpp:37:46: error: expected primary-expression before ‘>’ token
> set_features(train_features->as());

Hello, 

I am installing the Shogun 6.1.4. When I directly running the cmake, it tells me "Shogun can only be built with GPL codes if the source files are in ~/shogun-shogun_6.1.4/src/gpl.  Please download or disable."

I saw your issue that you have solved the gpl code problem. Currently there is nothing under the /src/gpl folder, so I wonder where to download the gpl code?

Thanks.

**Comment by AlexBinder** [comment]
Hi Matthew, 

the current develop branch with the current shogun-gpl (https://github.com/shogun-toolbox/shogun-gpl) does not compile for me, however 

6.1.4 compiles for me with (from above) https://github.com/shogun-toolbox/shogun-gpl/tree/29ca2ff930cd5d963b3a78e79160cc04d48970c2 

that needs some preparations on an ubuntu:

--sudo apt-get install protobuf-compiler libeigen3-dev libjson-c-dev libjsoncpp-dev
(downloading the eigen3 tar bz does not work, links points to nirvana)
--minimal examples do not compile for me, therefore I need to do something like:

this is for a globally installed python3.6, if you work with virtualenv adapt the paths,


cmake ../ -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6m -DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.6/dist-packages -DINTERFACE_PYTHON=ON -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DUSE_SVMLIGHT=ON -DLICENSE_GPL_SHOGUN=ON -DBUILD_META_EXAMPLES=OFF -DBUILD_EXAMPLES=OFF -DJSON_INCLUDE_DIR=/usr/include/json-c 

 python binding i can test in 30 mins (dunno if it runs,)
