### ISSUE TITLE
Cross validation examples occasionally segfaults

### ISSUE THREAD

**Issue by ghost** [shogun-toolbox/shogun#4742]
This happened to me locally multiple times. They either segfault, or hang indefinitely. Specifically: cross_validation_support_vector_machine and cross_validation_pipeline.

**Comment by karlnapf** [comment]
whoops, that is probably my recent changes.
Is this a segfault due to double free (i.e. missing `SG_REF`) or something else?

**Comment by ghost** [comment]
I believe yes, it's mostly related to wrongly placed `SG_REF/SG_UNREF`, you shouldn't bother. Should be solved with Viktor's PR.
I managed to reproduce a case causing segfault in code like this
```
	#pragma omp parallel for shared(results)
	for (auto i = 0; i<num_subsets; ++i)
	{
		auto features_train = view(m_features, idx_train);
	}
```
with idx_train being an SGVector defined outside the loop. The segfault happens inside SubsetStack , so it might also be solved when we replace it.

**Comment by karlnapf** [comment]
Ok, let's keep this open anyways. If there is no movement with the smart pointer PR and the subset stack, I will look into fixing this ...
