### ISSUE TITLE
Add 'GSoC' label to GSoC related PRs and issues

### ISSUE THREAD

**Issue by samdbrice** [shogun-toolbox/shogun#4744]
Use the wiki etc as a lookup

**Comment by ghost** [comment]
I think you need write-access to the repo to be able to do that.

**Comment by samdbrice** [comment]
https://github.com/shogun-toolbox/shogun/issues?q=label%3A%22Tag%3A+GSoC%22&utf8=%E2%9C%93

Not exactly comprehensive but a good start.
