### ISSUE TITLE
Fix meta examples cpp codegen

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4770]
The codegen for cpp meta examples is currently a 'bit' broken as literals.cpp has a compilation errors, as namespaces are hard-coded in the generated code, namely:
```
using namespace shogun;
using namespace shogun::io;
```

but in case of `literals.cpp` since no headers are included that contains the `shogun::io` namespace, compilation fails.

**Comment by gf712** [comment]
can we just hard code the relevant header for all examples?

**Comment by vigsterkr** [comment]
@gf712 that's one option... including some basic header that defines `shogun::io` should work, like Serializer.h

**Comment by vigsterkr** [comment]
fixed in 580a3b3
