### ISSUE TITLE
Can't find 'LibSVM' or 'LibLinear' in shogun packages

### ISSUE THREAD

**Issue by VisintZJ** [shogun-toolbox/shogun#4773]
I have 'make install' shogun successfully. I try to run 'from shogun import LibSVM' or 'from shogun import LibLinear' according to official document(https://www.shogun-toolbox.org/examples/latest/examples/binary_classifier/linear_svm.html) but pycharm told me it didn't find functions. I can normaly import CustomKernel and BinaryLabels. So, what do I need to write if I want to use 'LibSVM' and 'LibLinear'？

**Comment by gf712** [comment]
Hi, those docs are out of date relative to the develop branch.
Now you should do something like:
```python
import shogun as sg
svm = sg.machine("LibSVM", **kwargs)
```

**Comment by VisintZJ** [comment]
@gf712 Oh, thanks! By the way, is there a new ducument for develop branch？

**Comment by gf712** [comment]
i think you should be able to generate it yourself using `make doc`?

**Comment by karlnapf** [comment]
`make cookbook` will do the trick, check `build/doc/cookbook/` afterwards
