### ISSUE TITLE
Cannot import from shogun after PYTHONPATH has been set

### ISSUE THREAD

**Issue by TinaLuan** [shogun-toolbox/shogun#4781]
I installed shogun by conda. using `conda install -c conda-forge shogun`
I've done this step `export PYTHONPATH="path/to/shogun.py:$PYTHONPATH"` as well.

When I print out the PYTHONPATH, here is what my terminal shows:
```
echo $PYTHONPATH
/Applications/anaconda3/lib/python3.6/site-packages/shogun.py
```

I can import shogun **but cannot import functions or classes from shogun**

![Screen Shot 2019-10-22 at 15 51 46](https://user-images.githubusercontent.com/21965763/67259863-ec41ce80-f4e3-11e9-89b6-a6046451497b.png)

![Screen Shot 2019-10-22 at 16 08 01](https://user-images.githubusercontent.com/21965763/67260255-2c09b580-f4e6-11e9-986c-6bc4edefbe8a.png)

Could anyone help please?

**Comment by wangmengbo** [comment]
Did you manage to solve this issue?
