### ISSUE TITLE
Shogun and Anaconda not working

### ISSUE THREAD

**Issue by Gerry051992** [shogun-toolbox/shogun#4788]
Hello, 
I am new to this and I sincerely hope this has not been solved already and I just have not been able to find the solution.

I did use the shogun toolbox with anaconda and jupyter notebooks before, but since I reinstalled Anaconda a while ago, I cannot get shogun to work anymore. 
The error message seems to be telling me, that shogun does not work with Python 3.7, but I believe that I did use shogun with Python 3.7 before.

This is the error message I am getting in the anaconda prompt:
Package pip conflicts for:
shogun -> python[version='>=3.6,<3.7.0a0'] -> pip
python=3.7 -> pip
Package wheel conflicts for:
shogun -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
shogun -> protobuf=3.4 -> setuptools -> certifi[version='>=2016.09']
Package msgpack-python conflicts for:
shogun -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
Package wincertstore conflicts for:
python=3.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
shogun -> protobuf=3.4 -> setuptools -> wincertstore[version='>=0.2']
Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
shogun -> protobuf=3.4 -> setuptools
Package ca-certificates conflicts for:
shogun -> curl[version='>=7.59.0,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0'] -> openssl=1.0 -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates

Any help would be much appreciated! 

Cheers guys.

**Comment by yanmi1995** [comment]
I also meet this problem, and I am sure I used it before on anaconda-python3.7

**Comment by vigsterkr** [comment]
mmm. this is weird i'll try to check on it, but usually in past i had some problems with protobuf. i needed to force that the protobuf package is installed from conda-forge, instead of conda

**Comment by Gerry051992** [comment]
Thank you for looking into it!
Any news?

**Comment by vigsterkr** [comment]
@Gerry051992 hello haven't got around to test it yet... i'll do it in the next 48h! sorry about this

**Comment by Gerry051992** [comment]
@vigsterkr Would just like to let you know that the issue doesn't seem to be solved. Thank you for your help!

**Comment by Gerry051992** [comment]
@vigsterkr are you still panning to look into it? The problem still doesn't seem solved...

**Comment by Aakash1822** [comment]
@vigsterkr the issue doesn't yet solved. I think we should check protobuf package for installation. Will I try it
