### ISSUE TITLE
manual build fails on WSL

### ISSUE THREAD

**Issue by ed-aka-yaboi** [shogun-toolbox/shogun#4790]
I'm running on WSL (ubuntu) and am trying to build manually. Directory structure is like so:
~/shogun
~/shogunBuild
I run ccmake ../shogun from ~shogunBuild and configure. After installing whatever I'm prompted to, I run make in ~/shogunBuild. this leads to the following error:

/home/me/shogunBuild/examples/meta/cpp/meta_api/literals.cpp:5:25: error: ‘io’ is not a namespace-name
 using namespace shogun::io;
                         ^~
/home/me/shogunBuild/examples/meta/cpp/meta_api/literals.cpp:5:27: error: expected namespace-name before ‘;’ token
 using namespace shogun::io;
                           ^
examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/build.make:62: recipe for target 'examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/meta_api/literals.cpp.o' failed
make[2]: *** [examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/meta_api/literals.cpp.o] Error 1
CMakeFiles/Makefile2:6338: recipe for target 'examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/all' failed
make[1]: *** [examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vigsterkr** [comment]
@blakat360 mmm the literals error is known actually... it's a bug that should be easy to fix. but that's only an example so you should already have the library compiled as well as other examples. lemme see if i can fix this quickly

**Comment by karlnapf** [comment]
had this error as well recently...after deleting/recreating my build dir (for other reasons), it didnt happen again. Not sure why but might work for you too

**Comment by karlnapf** [comment]
You could also disable the meta examples using `-DBUILD_META_EXAMPLES=Off` if you dont need them...they are only built once the lib is already done as @vigsterkr mentioned above

**Comment by vigsterkr** [comment]
@blakat360 pull the latest develop that has the fix for this

**Comment by ed-aka-yaboi** [comment]
Can confirm it works
