### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by HarlanZhou** [shogun-toolbox/shogun#4798]
win 10 , i add classpath and can't run run_test.py

**Comment by gf712** [comment]
You need to add more details than that for us to help!

**Comment by HarlanZhou** [comment]
> You need to add more details than that for us to help!

i try to use anaconda to install shogun,but i doesn't work.Then i set the system classpath for shogun, and also doesn't work.Finally , i move shogun fold to python3.6/Libs/site-package, and it still doesn't work, what should i do .Thanks for u help

**Comment by gf712** [comment]
@HarlanZhou do you still have issues?
