### ISSUE TITLE
folding expression issue while installing 

### ISSUE THREAD

**Issue by hasnain2808** [shogun-toolbox/shogun#4799]
I am getting this error while running cmake ../ from the build directory

`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_FOLDING_EXPRESSIONS
-- Performing Test HAVE_FOLDING_EXPRESSIONS - Failed
CMake Error at CMakeLists.txt:63 (MESSAGE):
  Compiling shogun requires a compiler with folding expression support!

-- Configuring incomplete, errors occurred!
See also "/home/sd/projects/shogunn/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/home/sdl/projects/shogunn/shogun/build/CMakeFiles/CMakeError.log".
`
any help is appreciated

**Comment by vigsterkr** [comment]
@hasnain2808 you would need newer version of gcc compiler that actually supports folding expression. if you just wanna use shogun you could try to use the conda precompiled package

**Comment by hasnain2808** [comment]
Okay will try installing it

**Comment by vigsterkr** [comment]
https://anaconda.org/conda-forge/shogun

**Comment by hasnain2808** [comment]
I want to build it from source

**Comment by vigsterkr** [comment]
gcc7 should work or a newer clang..

**Comment by hasnain2808** [comment]
Yeah installing clang now

**Comment by hasnain2808** [comment]
Installed clang still it gives me the same error
C++ 17 tests are working

**Comment by gf712** [comment]
fold expressions are supported from gcc 6 and clang 3.6, so you need to check that you are compiling with one of those two. Check https://en.cppreference.com/w/cpp/compiler_support#cpp17 for C++17 compiler support

**Comment by hasnain2808** [comment]
Just now did some name linking which resolved the issue

**Comment by hasnain2808** [comment]
now getting this error
yes I have installed python3.6-dev 

`/home/moha/projects/shogunn/shogun/build/src/interfaces/python/shogunPYTHON_wrap.cxx:180:11: fatal error: Python.h: No such file or directory
 # include <Python.h>
           ^~~~~~~~~~
compilation terminated.
src/interfaces/python/CMakeFiles/_interface_python.dir/build.make:73: recipe for target 'src/interfaces/python/CMakeFiles/_interface_python.dir/shogunPYTHON_wrap.cxx.o' failed
make[2]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/shogunPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:625: recipe for target 'src/interfaces/python/CMakeFiles/_interface_python.dir/all' failed
make[1]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

waited for an hour to compile this and in the end got this

**Comment by gf712** [comment]
that means your python header file is not in the include paths. checkout https://www.shogun-toolbox.org/install#manual-python to see how to add the paths required for custom python installation

**Comment by gf712** [comment]
btw, if you don't have ccache rerunning cmake will probably require you to wait for another hour I think

**Comment by hasnain2808** [comment]
I did include those dpython paths
And yeah cache is running so I won't have to wait for another hour

**Comment by hasnain2808** [comment]
Used miniconda and venv both fail with the same error

**Comment by hasnain2808** [comment]
I successfully built shogun for ubuntu 16.04 with python3. 6 and installed it systemwide for python3.6 but I get this error while trying to import shogun

Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.6/dist-packages/shogun.py", line 17, in <module> from _shogun import * ImportError: /usr/local/lib/python3.6/dist-packages/_shogun.so: undefined symbol: _ZNK6shogun8SGObject12shallow_copyEv

**Comment by hasnain2808** [comment]
#4800
