### ISSUE TITLE
undefined symbol: _ZNK6shogun8SGObject12shallow_copyEv

### ISSUE THREAD

**Issue by hasnain2808** [shogun-toolbox/shogun#4800]
I successfully built shogun for ubuntu 16.04 with python3. 6 and installed it systemwide for python3.6 but i get this error while trying to import shogun

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/shogun.py", line 17, in <module>
    from _shogun import *
ImportError: /usr/local/lib/python3.6/dist-packages/_shogun.so: undefined symbol: _ZNK6shogun8SGObject12shallow_copyEv
`
Any help is appreciated

**Comment by gf712** [comment]
that seems like you have an older version of libshogun in your library path.. You should make sure that you `make install` and that the path of libshogun is in PATH or LD_LIBRARY_PATH. Did you install shogun with anaconda before? you are probably loading that dynamic library instead of the one you compiled..

**Comment by hasnain2808** [comment]
Dumb question but can you give me an example of adding shogun to ld library path i tried but it is not working out

**Comment by hasnain2808** [comment]
I have shogun build at
/home/sdl/projects/shogunn/shogun/build

**Comment by gf712** [comment]
you should run make install, so that it is available from something like /usr/local/lib, or even ~/anaconda3 if you have it. If you keep it in the build folder just do `export LD_LIBRARY_PATH= /home/sdl/projects/shogunn/shogun/build/src/shogun` and that should work

**Comment by gf712** [comment]
or append it with `export LD_LIBRARY_PATH= /home/sdl/projects/shogunn/shogun/build/src/shogun:$LD_LIBRARY_PATH` if you already have that env variable defined

**Comment by hasnain2808** [comment]
I did make install

**Comment by gf712** [comment]
ah ok, where did it install it to?

**Comment by hasnain2808** [comment]
That i don't know
I had given it python directories while doing make

**Comment by hasnain2808** [comment]
So it should get installed there directly?

**Comment by gf712** [comment]
did you pass `-DCMAKE_INSTALL_PREFIX` to cmake?

**Comment by hasnain2808** [comment]
Actually i am not sure about it because i used the commands from interfaces.md
I guess i will re make and rebuild?

**Comment by hasnain2808** [comment]
Should i remake?
Btw shogun.py was there somewhere in ubuntu lib

**Comment by hasnain2808** [comment]
Ohh thanks a lot 
Import export ld library path worked

**Comment by hasnain2808** [comment]
I am able to import shogun

**Comment by gf712** [comment]
Good!
