### ISSUE TITLE
[bug, SEGSEGV] func deserialize: return internal ptr of deleted smart_ptr

### ISSUE THREAD

**Issue by ivan-v-kush** [shogun-toolbox/shogun#4803]
**Solution:**
maybe `shogun::io::deserialize` will return smart ptr? If OK, I'll make a PR

**Problem:**

files: 
`/src/shogun/io/serialization/Deserializer.cpp`
 `/src/shogun/base/some.h`
`/src/shogun/base/SGObject.cpp`

method returns a pointer:
```
CSGObject* shogun::io::deserialize(const std::string& _path, CDeserializer* _deser)
{
....
	return _deser->read_object().get();
}
```

but `read_object` returns smart pointer  `Some`:
```
class CDeserializer : public CSGObject
{
public:
    virtual Some<CSGObject> read_object() = 0;
```

when `deserialize` is finished this smart ptr is deleted, so also deleted ptr, returned by `get`:

```
	Some<T>::~Some()
	{
		reset(); //calls unref
	}
```

call `unref`
```
	}
template <class T>
void Some<T>::unref()
{
    if (raw)
    {
        if ((raw)->unref() == 0)
            (raw) = NULL;
    };
}
```

in `(raw)->unref()` memory cleans
```
int32_t CSGObject::unref()
{
	int32_t count = m_refcount->unref();
	if (count<=0)
	{
		SG_TRACE("unref() refcount {}, obj {} ({}) destroying", count, this->get_name(), fmt::ptr(this));
		delete this;
		return 0;
	}
	else
	{
		SG_TRACE("unref() refcount {} obj {} ({}) decreased", count, this->get_name(), fmt::ptr(this));
		return m_refcount->ref_count();
	}
}
```

**Comment by ivan-v-kush** [comment]
maybe `deserialize` will return smart ptr? If OK, I'll make a PR

**Comment by vigsterkr** [comment]
Update the develop branch to the latest commit. It uses shared_ptr smart pointer
