### ISSUE TITLE
Installation issue - make throws error while building tapkee_shogun.cpp.o

### ISSUE THREAD

**Issue by SaurusXI** [shogun-toolbox/shogun#4805]
Building shogun from source (development branch). 
First the following command is passed to cmake:

`cmake -DINTERFACE_PYTHON=ON -DBUILD_META_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=/home/zeus/shogun_stuff ..`

Then, on running `make`

`[ 37%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/lib/tapkee/tapkee_shogun.cpp.o
In file included from /home/zeus/shogun/src/shogun/lib/tapkee/methods.hpp:17,
                 from /home/zeus/shogun/src/shogun/lib/tapkee/embed.hpp:11,
                 from /home/zeus/shogun/src/shogun/lib/tapkee/tapkee.hpp:10,
                 from /home/zeus/shogun/src/shogun/lib/tapkee/tapkee_shogun.cpp:20:
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp: In function ‘tapkee::SparseWeightMatrix tapkee::tapkee_internal::linear_weight_matrix(const RandomAccessIterator&, const RandomAccessIterator&, const Neighbors&, PairwiseCallback, tapkee::ScalarType, tapkee::ScalarType) [with RandomAccessIterator = __gnu_cxx::__normal_iterator<int*, std::vector<int> >; PairwiseCallback = pimpl_kernel_callback<shogun::Kernel>]’:
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp:108:15: error: ‘k’ not specified in enclosing ‘parallel’
  108 |   DenseMatrix gram_matrix = DenseMatrix::Zero(k,k);
      |               ^~~~~~~~~~~
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp:105:9: error: enclosing ‘parallel’
  105 | #pragma omp parallel shared(begin,end,neighbors,callback,sparse_triplets) default(none)
      |         ^~~
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp:133:38: error: ‘trace_shift’ not specified in enclosing ‘parallel’
  133 |    gram_matrix.diagonal().array() += trace_shift*trace;
      |                                      ^~~~~~~~~~~
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp:105:9: error: enclosing ‘parallel’
  105 | #pragma omp parallel shared(begin,end,neighbors,callback,sparse_triplets) default(none)
      |         ^~~
/home/zeus/shogun/src/shogun/lib/tapkee/routines/locally_linear.hpp:137:61: error: ‘shift’ not specified in enclosing ‘parallel’
  137 |    SparseTriplet diagonal_triplet(index_iter,index_iter,1.0+shift);
      |                                                             ^~~~~
`
and a bunch of other errors associated with types and variables.
Final lines read:
`make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/build.make:5241: src/shogun/CMakeFiles/libshogun.dir/lib/tapkee/tapkee_shogun.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:648: src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`

Perhaps an issue with dependencies?

**Comment by vigsterkr** [comment]
@SaurusXI could you plz share more details of your runtime env? like version and type of your compiler, OS etc.

**Comment by SaurusXI** [comment]
build uses gcc/g++ right? 
Running GCC v9.2.0 on Arch Linux
Please let me know if any other specific info is needed

**Comment by vigsterkr** [comment]
@SaurusXI well you can use gcc, clang and VC++ (these are tested) for building. i'll quickly try to reproduce this in a docker image of arch linux. would this docker image of archlinux be a good resembles of your env: https://hub.docker.com/_/archlinux

**Comment by SaurusXI** [comment]
Not too sure, since most packages in the base group have been removed in this image. Then again, not sure that that is relevant to the problem at hand, so give it a shot maybe?

**Comment by SaurusXI** [comment]
Also, I'd like to point out that most errors are associated with types and variable parameters. For instance, the first error happens at the constructor call `DenseMatrix gram_matrix = DenseMatrix::Zero(k,k);` and mentions some problem with 'k'. Other errors are similar.

**Comment by gf712** [comment]
@SaurusXI are you still trying to compile shogun?

**Comment by SaurusXI** [comment]
Sorry for the late response @gf712 - I have a bad habit of not checking my mail. I have distrohopped a bit sense then, and shogun seems to compile on my current build Arch without any issues. Not sure what the problem was, but I'll close this issue.
