### ISSUE TITLE
[Discussion] Let's colaborate with SciRuby for Ruby wrapper

### ISSUE THREAD

**Issue by Shekharrajak** [shogun-toolbox/shogun#4814]
Hi,

Thanks for the amazing library for machine learning. I think it is one of best machine learning tool which provide Ruby wrapper. 

Since GSoC Org application has been opened and deadline is close. I hope Shogun will be participating in GSoC 2020 and have project idea list ready. 

Please let me know the Ruby wrapper ideas and enhancement plan. Also let me know if Shogun community can collaborate with SciRuby for any Ruby wrapper related projects. SciRuby already working on best Data Science related Ruby gems which is used worldwide. So it will be great if SciRuby gems (like daru- Data Analysis and Visualization in Ruby, nmatrix and other visualization and statistics related gems ): https://github.com/sciruby API work smoothly with shogun API.

It will surely make Shogun more useful in Ruby community.

What do you think? @vigsterkr , @iglesias

**Comment by vigsterkr** [comment]
@Shekharrajak we are planning to apply for GSoC 2020!

indeed we wanted for a time to switch from nmatrix (or whatever the library we use at the moment) for ruby type maps to something more modern, as that project seems to be abandoned, or not that well maintained anymore. if you are interested working on this project, plz outline your idea and you can already start sending in some preliminary PRs

**Comment by vigsterkr** [comment]
i guess a gem would be nice to have of the shogun ruby interface for starters :)

**Comment by Shekharrajak** [comment]
Thanks @vigsterkr for the response. Can you please share some links or discussion about Ruby wrapper, so that I can understand the current status of the project and any plans you have in mind. it will be helpful.

**Comment by vigsterkr** [comment]
@Shekharrajak basically you can just build manually the ruby wrapper like this:
```
cmake -DINTERFACE_RUBY=ON ..
make
```

this should actually build all the example for ruby. although now that i'm talking about this there's a bug currently against ruby interface:
https://github.com/shogun-toolbox/shogun/issues/4177

needs to be checked whether there's an easy workaround for this.

**Comment by vigsterkr** [comment]
in order to reproduce the error you should enable this: https://github.com/shogun-toolbox/shogun/blob/develop/tests/meta/CMakeLists.txt#L60

**Comment by vigsterkr** [comment]
and comment out this one https://github.com/shogun-toolbox/shogun/blob/develop/examples/meta/CMakeLists.txt#L136

you'll see currently these tests are failing:
```
	116 - generated_ruby-base_api-factory (Failed)
	117 - generated_ruby-base_api-put_get_add (Failed)
	131 - generated_ruby-binary-svmlight_linear_term (Failed)
	158 - generated_ruby-evaluation-clustering (Failed)
	164 - generated_ruby-features-string_features (Failed)
```

**Comment by iglesias** [comment]
> Thanks @vigsterkr for the response. Can you please share some links or discussion about Ruby wrapper, so that I can understand the current status of the project and any plans you have in mind. it will be helpful.

We use swig to generate interfaces between the C++ core of Shogun and Ruby (along with other languages).

**Comment by Shekharrajak** [comment]
Okay! So currently Ruby wrapper is not functional. I will check!

**Comment by vigsterkr** [comment]
well to be honest it mostly is, there are couple of function calls that will fail, but most of the library is usable from ruby

**Comment by Shekharrajak** [comment]
Okay! So can anyone please make a TODO list to make it usable again?

**Comment by vigsterkr** [comment]
i've just written you above what needs to be done

**Comment by vigsterkr** [comment]
here you go a project https://github.com/shogun-toolbox/shogun/projects/13

**Comment by Shekharrajak** [comment]
Thanks @vigsterkr !  Should we add idea in SciRuby Idea page also and let's see if we find good student who can work on this? 
The idea is to make it usable and functional(compatible) with SciRuby gems as well.

What do you think?

**Comment by vigsterkr** [comment]
@Shekharrajak sure thing... i mean imo since SciRuby is using nmatrix as far as i can understand, shogun should be usable without any trouble.

**Comment by vigsterkr** [comment]
fyi: i'll add somewhere a gist with a simple ruby based jupyter notebook just to test it out.

**Comment by vigsterkr** [comment]
@Shekharrajak i've managed to export a `daru` df to nmatrix with `to_nmatrix` method (once, nmatrix is installed)... is there a plan to support https://github.com/ruby-numo/numo-narray as well?

**Comment by Shekharrajak** [comment]
Thanks, @vigsterkr ! SciRuby team is working on [NumRuby](https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2020-Ideas#numruby-projects) project: https://github.com/SciRuby/numruby . If you find numo-narray useful then it should be compatible as well.

**Comment by Shekharrajak** [comment]
@vigsterkr, You can have your gist or wiki page where this idea will be added for the GSoC 2020, I have added the idea at SciRuby idea page for this GSoC: https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2020-Ideas#shogun, feel free to edit/update it and add yourself as mentor. 

Thanks!

**Comment by vigsterkr** [comment]
@Shekharrajak here's a working example shogunML with SciRuby stack: https://gist.github.com/vigsterkr/48a5f0523528bbab85bec04464ca2b6c

**Comment by karlnapf** [comment]
bump

**Comment by Shekharrajak** [comment]
Hi Guys,

We are adding this idea in GSoC 2021 for SciRUby : https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2021-Ideas

Interested people can reach out to SciRuby mailing list: sciruby-dev
