### ISSUE TITLE
Fundamental ML algorithms: Linear Latent Gaussian Models

### ISSUE THREAD

**Issue by naruarjun** [shogun-toolbox/shogun#4840]
This is a project idea every year but I haven't seen this being selected once, I know this wasn't a high priority before. I am excited by this idea and was targeting this as my GSOC project. But I wanted to know what is the priority status of this project and what is the proficiency level that you are looking for in the applicant. I have some statistics knowledge, but I am not familiar with half the theory in the project description and will start to read it now. My proficiency with c++ is good but can definitely be improved (haven't worked much with templates). Am I a applicant that has a chance of being selected? If so could you give me some pointers?

**Comment by jonpsy** [comment]
Hey naruarjun,
I think by this issue you are trying to give a brief introduction about yourself and your interest in a specific GSOC idea.
The correct way is to go to [here](https://groups.google.com/a/numfocus.org/forum/#!forum/gsoc) and subscribe to the mailing list and send a mail to introduce yourself as Shogun comes under NumFocus. 

Then you could chat with the [shogun community](https://riot.im/app/#/room/#shogun:matrix.org)

To start contributing 

- Try setting up the environment first https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md
- Solve good first issues 

For much better explanation, [click here!](https://github.com/shogun-toolbox/shogun/wiki/Getting-involved)

On a side note, I think issues should only be related to the code base bugs/developments/issues and not for introduction. Anyway Good luck :) (From a fellow GSOC aspirant)

**Comment by naruarjun** [comment]
Alright, thanks for the help.
