### ISSUE TITLE
Missing Hyperlink in Multi-class Support Vector Machine Page

### ISSUE THREAD

**Issue by krutikabapat** [shogun-toolbox/shogun#4842]
Missing hyperlink for **kernel_svm** at https://www.shogun-toolbox.org/examples/latest/examples/multiclass_classifier/svm.html. It should redirect to 
https://www.shogun-toolbox.org/examples/latest/examples/binary_classifier/kernel_svm.html

**Comment by tanaymeh** [comment]
I would like to fix this up!

**Comment by naruarjun** [comment]
Looking at the code in the repo, I think it should be linked to the Kernel Support Vector Machine page in the binary classifier docs. It is already linked to that in the repo, the change is not reflected in the website.

**Comment by krutikabapat** [comment]
@naruarjun What is the location of binary classifier docs?

**Comment by naruarjun** [comment]
shogun/doc/cookbook/source/binary/kernel_support_vector_machine.rst

**Comment by krutikabapat** [comment]
@naruarjun Thankyou!
