### ISSUE TITLE
Typo In Bray Curtis Distance

### ISSUE THREAD

**Issue by krutikabapat** [shogun-toolbox/shogun#4843]
When I open https://www.shogun-toolbox.org/examples/latest/examples/distance/braycurtis.html
there is a typo in the hyperlink of **BrayCurtis Distance**
 < http://people.revoledu.com/kardi/tutorial/Similarity/BrayCurtisDistance.html >
It should be replaced with [BrayCurtis Distance](http://people.revoledu.com/kardi/tutorial/Similarity/BrayCurtisDistance.html). Hyperlink should be added in the name itself.

**Comment by vigsterkr** [comment]
it's ok just to send in a PR for this not necessary to create an issue. and yes the hyperlink should be fixed in the references section

**Comment by krutikabapat** [comment]
Okay, I will do that! Thanks!
