### ISSUE TITLE
add a section to EXAMPLE.md to solve sphinx-build detection

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4845]
many people had problems having the cookbook target available that is due to not detecting the sphinx-build path in cmake.

we should have in https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/EXAMPLES.md#rendering-locally a small part describing how to tell cmake where sphinx-build is actually residing, i.e. `-DSPHINX_EXECUTABLE=<absolute path to sphinx-build>`

**Comment by jonpsy** [comment]
May I take up this issue, Im facing this problem too so it would be much helpful from user perspective ☺

**Comment by vigsterkr** [comment]
go ahead no need to ask just send in a pr
