### ISSUE TITLE
Change KMeans "mus" parameter to something more user friendly

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4847]
Right now "cluster centres" in KMeansBase is a parameter called "mus". This is probably not a good name, at least for user facing code. This should be changed in KMeansBase.cpp. Should be straightforward, but will probably require some test/example code refactoring.

**Comment by zwasd** [comment]
Is `initial_centers` a good name?

**Comment by gf712** [comment]
Well it's not initial_centers though, it's the cluster centres right? If you look at KMeansBase::get_cluster_centers() that returns mus. I think you'll need to register `mus_initial` and name that `initial_centers` and then remove `mus`. `mus` is already registered using `watch_method("cluster_centers", &KMeansBase::get_cluster_centers);`

**Comment by gf712** [comment]
and then you'll need to add a callback function that checks the shape of the provided cluster centres (like in set_initial_centers), but that we can have a look at once a PR is started.

**Comment by ana-simionescu** [comment]
How can I test the functionality after making my changes?

**Comment by gf712** [comment]
Hi, you could either write a unittest or a meta example! There is information about both [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md#testing) :)

**Comment by Khalifa1997** [comment]
Can I still work on this :D

**Comment by krutikabapat** [comment]
@gf712 Basically we want the name of the parameter mus to be cluster_centers and mus_initial as initial_clusters. Right?

**Comment by mukhituly** [comment]
I want to work on it. Can you guide me?

**Comment by vigsterkr** [comment]
there are already several PRs open about this... although none of them actually finished.
