### ISSUE TITLE
Some of .md file dosen't have proper hyperlinking

### ISSUE THREAD

**Issue by skymatte** [shogun-toolbox/shogun#4857]
For example in https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INTERFACES.md, proper hyperlinking to install.md is not there.

**Comment by vigsterkr** [comment]
just send in a PR :) thnx!

**Comment by skymatte** [comment]
I sent a PR in #4859 (https://github.com/shogun-toolbox/shogun/pull/4859/commits/b0c9a4889d4bbed9f0daa8bace62d55456827ddb). Please verify it.

**Comment by skymatte** [comment]
> just send in a PR :) thnx!

I sent a PR in #4859 . Please verify it.
