### ISSUE TITLE
Refactor meta examples relative paths to absolute paths

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4865]
Currently the meta examples are failing on windows build do the the fact that the relative path is not correct in all the meta examples, see for example: 
https://github.com/shogun-toolbox/shogun/blob/develop/examples/meta/src/binary/averaged_perceptron.sg#L1

on windows this should be:
```
File f_feats_train = csv_file("../../../data/classifier_binary_2d_linear_features_train.dat")
```

there's two way to solve this:
 1) change the meta example generator that basically fixes this relative path based on a platform
 2) change the meta examples generator in a way that it does a join over the path given here and an environment variable, say `SHOGUN_DATA` which contains the absolute path to the right directory. this of course adds more lines of code to the generated examples (in each languages there has to be some env var extractor code)..

**Comment by gf712** [comment]
Could we not use cmake for this: `@SHOGUN_DATA@/file.dat`?

**Comment by vigsterkr** [comment]
and all of the sg files are configured files? doable, this way we dont need to touch any meta stuff.

**Comment by gf712** [comment]
yes, automatically configure_file in cmake for each file

**Comment by vigsterkr** [comment]
that's a quite easy patch imo... lets do that.
