### ISSUE TITLE
CARTree leaks

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4867]
simply valgrind one of the metaexamples, i.e.:
```
valgrind --leak-check=full ./cpp-regression-cartree
```

**Comment by neeravjain24** [comment]
Can you please provide the link to where should we do this I am having trouble getting the location of file

**Comment by gf712** [comment]
@neeravjain24 `./cpp-regression-cartree` is located in the build directory: `build/examples/meta/cpp/regression`. you should be able to find files using `find` on linux :)

**Comment by neeravjain24** [comment]
Thanks for the help @gf712 but I am currently using windows but still thanks for letting me know the file path

**Comment by gf712** [comment]
@neeravjain24 the windows bulld is work in process right now. I would recommend using docker for windows or switch to linux if you can.
If you want to build in windows with visual studio and msvc you'll have to wait until this is merged #4719
