### ISSUE TITLE
random_matrix not yet implemented

### ISSUE THREAD

**Issue by Khalifa1997** [shogun-toolbox/shogun#4892]
So I have been skimming through the API docs, I came across the SGVector implementation of random_vector, however, I couldn't find anything at all about generating a random matrix, if that's the case I would love to work on this issue. My thought process is that I would make use of the current SGVector implementation and SGMatrix's constructor `SGMatrix (SGVector< T > vec, index_t nrows, index_t ncols)` for more code reuse

**Comment by vigsterkr** [comment]
could you please give a use-case for SGMatrix random?

note: https://www.shogun.ml/api/latest/classshogun_1_1CDataGenerator.html

**Comment by Khalifa1997** [comment]
Hmm I guess one would argue consistency between the two or to have the same functionality numpy has, I have googled abit and I read a few things about "Random Matrix theory" but that seems abit further down the line. What do you think @vigsterkr

**Comment by vigsterkr** [comment]
mmm, i would suggest go ahead with other already existing issues ;)
in fact there was already a push to have cleared up all the SG containers (vector matrix etc) from specialized methods, like random, as the idea is that SG containers are only used for typemapping between various languages... but operations over them should be done by other methods.
