### ISSUE TITLE
bundled RapidJSON breaks after re-running cmake

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4894]

**Comment by vinnik-dmitry07** [comment]
Actually, I do not know the reason you change these lines  https://github.com/shogun-toolbox/shogun/blame/develop/src/shogun/CMakeLists.txt#L430, but they make RAPIDJSON_INCLUDE_DIRS not set by _RapidJSON.cmake_ and thus next time a crash happens.

**Comment by vinnik-dmitry07** [comment]
I have tested the old version and it builds two times, so consider backing it.
