### ISSUE TITLE
Installation issue(Building from source code)

### ISSUE THREAD

**Issue by bhavukkalra** [shogun-toolbox/shogun#4913]
I am using MacOs X mojave 10.14.15
anaconda as a virtual enviroment,
i installed all dependencies with homebrew
but after ruuning make i am getting this build error

> [  0%] Performing configure step for 'Eigen3'
-- Standard libraries to link to explicitly: none
-- Found unsuitable Qt version "5.9.7" from /opt/anaconda3/envs/QA/bin/qmake
-- The Fortran compiler identification is unknown
-- A cache variable, namely BLAS_DIR, has been set to specify the install directory of BLAS
-- Looking for BLAS -- mkl.h not found
-- Looking for MKL BLAS: not found
-- Looking for Goto BLAS: not found
-- Looking for Open BLAS: not found
-- Looking for Eigen BLAS: not found
-- Looking for Eigen BLAS: not found
-- Looking for Atlas BLAS: not found
-- Looking for PhiPACK BLAS: not found
-- Looking for CXML BLAS: not found
-- Looking for DXML BLAS: not found
-- Looking for SunPerf BLAS: not found
-- Looking for SCSL BLAS: not found
-- Looking for SGIMATH BLAS: not found
-- Looking for IBM ESSL BLAS: not found
-- Looking for IBM ESSL MT BLAS: not found
-- Looking for ACML BLAS: not found
-- Looking for ACML BLAS: not found
-- Looking for ACML BLAS: not found
-- Looking for Apple BLAS: not found
-- Looking for NAS BLAS: not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Generic BLAS: not found
-- Looking for Generic BLAS: not found
-- Looking for Generic BLAS: not found
-- Looking for Generic BLAS: not found
-- Looking for Generic BLAS: not found
CMake Warning at cmake/FindBLAS.cmake:1371 (message):
  BLA_VENDOR has been set to All but blas libraries could not be found or
  check of symbols failed.

  Please indicate where to find blas libraries.  You have three options:

  - Option 1: Provide the installation directory of BLAS library with cmake
  option: -DBLAS_DIR=your/path/to/blas

  - Option 2: Provide the directory where to find BLAS libraries with cmake
  option: -DBLAS_LIBDIR=your/path/to/blas/libs

  - Option 3: Update your environment variable (Linux: LD_LIBRARY_PATH,
  Windows: LIB, Mac: DYLD_LIBRARY_PATH)

  

  To follow libraries detection more precisely you can activate a verbose
  mode with -DBLAS_VERBOSE=ON at cmake configure.

  You could also specify a BLAS vendor to look for by setting
  -DBLA_VENDOR=blas_vendor_name.

  List of possible BLAS vendor: Goto, ATLAS PhiPACK, CXML, DXML, SunPerf,
  SCSL, SGIMATH, IBMESSL, Intel10_32 (intel mkl v10 32 bit),Intel10_64lp
  (intel mkl v10 64 bit, lp thread model, lp64 model), Intel10_64lp_seq
  (intel mkl v10 64 bit, sequential code, lp64 model),Intel( older versions
  of mkl 32 and 64 bit), ACML, ACML_MP, ACML_GPU, Apple, NAS, Generic
Call Stack (most recent call first):
  cmake/FindLAPACK.cmake:138 (find_package)
  test/CMakeLists.txt:30 (find_package)

>-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS.
-- Could NOT find CHOLMOD (missing: CHOLMOD_INCLUDES CHOLMOD_LIBRARIES) 
-- Could NOT find UMFPACK (missing: UMFPACK_INCLUDES UMFPACK_LIBRARIES) 
-- Could NOT find SUPERLU (missing: SUPERLU_INCLUDES SUPERLU_LIBRARIES SUPERLU_VERSION_OK) 
-- Checking for one of the modules 'hwloc'
-- Looking for Fortran sgemm
CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CheckFortranFunctionExists.cmake:63 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  cmake/FindBLAS.cmake:297 (check_fortran_function_exists)
  cmake/FindBLAS.cmake:1297 (check_fortran_libraries)
  cmake/FindBLASEXT.cmake:53 (find_package)
  cmake/FindBLASEXT.cmake:86 (find_package_blas)
  cmake/FindPASTIX.cmake:214 (find_package)
  test/CMakeLists.txt:83 (find_package)

>-- Configuring incomplete, errors occurred!
See also "/Users/bhavuk/Desktop/shogun/build/Eigen3/src/Eigen3-build/CMakeFiles/CMakeOutput.log".
See also "/Users/bhavuk/Desktop/shogun/build/Eigen3/src/Eigen3-build/CMakeFiles/CMakeError.log".
make[2]: *** [Eigen3/src/Eigen3-stamp/Eigen3-configure] Error 1
make[1]: *** [src/shogun/CMakeFiles/Eigen3.dir/all] Error 2
make: *** [all] Error 2

**Comment by vigsterkr** [comment]
@bhavukkalra plz check how we build the macos version of shogun in our CI: https://github.com/shogun-toolbox/shogun/blob/develop/.ci/macos-steps.yml

**Comment by GuoxinYin** [comment]
I am still confused about how to solve this. Could you elaborate more? Thank you!
