### ISSUE TITLE
problem on installation of shogun with python 3.7 in conda

### ISSUE THREAD

**Issue by Aakash1822** [shogun-toolbox/shogun#4925]
I got an issue with the installment of shogun in conda environment.
Which python version is more compatible for Shogun

**Comment by vinnik-dmitry07** [comment]
The buildbout is configured using Python 3.6.8.

**Comment by vinnik-dmitry07** [comment]
Provide the issue, please

**Comment by Aakash1822** [comment]
okay, I will try with the mentioned version
