### ISSUE TITLE
Documentation link for API examples(404 not found)

### ISSUE THREAD

**Issue by bhavukkalra** [shogun-toolbox/shogun#4931]
The API examples link in the README.md on the homepage of repository i.e
https://github.com/shogun-toolbox/shogun
 seems to be not working(error code 404 not found) i.e
https://www.shogun.ml/examples/latest/index.html
 and needs to be changed.

**Comment by ghost** [comment]
i'd like to solve this but there is no file existing as index.html

**Comment by bhavukkalra** [comment]
Shogun comes with automatically generated API examples. How to use them is provided here
https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/EXAMPLES.md#meta_examples.
Should we just remove that API examples link from README.md or we can replace it with the above link.
@vigsterkr @gf712 thoughts?

**Comment by ghost** [comment]
Yes even on the official website [https://www.shogun-toolbox.org/](url)
 "examples"  button in navigation bar doesn't work and gives out a 404 error.

**Comment by vigsterkr** [comment]
fixed
