### ISSUE TITLE
setup.py file in source code has a syntax error

### ISSUE THREAD

**Issue by ghost** [shogun-toolbox/shogun#4936]
setup.py file in [https://github.com/shogun-toolbox/shogun/releases/latest](url) source code have a syntax error and need to be resolved.
![synta](https://user-images.githubusercontent.com/59612338/76761985-6f770000-67b6-11ea-9866-f9ee10e8d28f.png)

**Comment by vigsterkr** [comment]
@its-crypted even if you resolve that there's a lot more things to do about that to get this finally working....

**Comment by ghost** [comment]
Sorry but I'm new here so I didn't knew about it that much I tried to eliminate it but it was proceeding further. Thanks for the review
