### ISSUE TITLE
Problem Installing Shogun in Ubuntu 16.04

### ISSUE THREAD

**Issue by aks-alokraj** [shogun-toolbox/shogun#4939]
I'm getting the following error:

_CMake Error at CMakeLists.txt:63 (MESSAGE):
  Compiling shogun requires a compiler with folding expression support!
-- Configuring incomplete, errors occurred!_

**Comment by vigsterkr** [comment]
as the error says, your compiler does not support a feature that is required. plz make sure you are using a compiler that supports c++17 standard
