### ISSUE TITLE
examples don't compile even after having required libraries.

### ISSUE THREAD

**Issue by aneesh404** [shogun-toolbox/shogun#4943]
all examples examples in src/shogun wont compile even after having necessary libraries.

command used:
```
gcc KMeansMiniBatch.cpp -I /usr/include/eigen3 -o kmeans 
```

which gives the following errors+warning messages:
https://pastebin.com/niiS0tKg

I also tried to compile it with c++17:
```
' g++ -std=c++17 KMeansMiniBatch.cpp -I /usr/include/eigen3 -o kmeans '
```

but that gives another different set of errors 
https://pastebin.com/JatLrVKX

**Comment by gf712** [comment]
You shouldn't compile the examples manually if you don't know what you are doing. In your second line you haven't added shogun dynamic library, or its path.

**Comment by gf712** [comment]
see https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/EXAMPLES.md

**Comment by aneesh404** [comment]
Thanks @gf712 for quick reply. I had set that in the LD_LIBRARY_PATH. 

I'm sorry I forgot to mention here, but I was getting a different error with adding the shogun library too

/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

I guess I'm making some error in compiling, I'll try to find it.

**Comment by vigsterkr** [comment]
@aneesh404 use make targets instead of trying to compile it by hand...

**Comment by aneesh404** [comment]
Makes more sense to use targets than compile each file, thanks @vigsterkr and @gf712
