### ISSUE TITLE
Getting error while installing shogun - E: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by Avi-000-Avi** [shogun-toolbox/shogun#4967]
sudo add-apt-repository ppa:shogun-toolbox/stable
 Builds of stable releases
 More info: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release
Hit:3 http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic InRelease
Ign:4 http://ppa.launchpad.net/shogun-toolbox/nightly/ubuntu bionic InRelease
Ign:6 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu bionic InRelease
Err:8 http://ppa.launchpad.net/shogun-toolbox/nightly/ubuntu bionic Release                    
  404  Not Found [IP: 91.189.95.83 80]
Err:9 http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Err:10 http://repo.unpatti.ac.id/ubuntu bionic InRelease
  502  Connection refused [IP: 103.56.70.6 80]
Err:11 http://repo.unpatti.ac.id/ubuntu bionic-updates InRelease
  502  Connection refused [IP: 103.56.70.6 80]
Err:12 http://repo.unpatti.ac.id/ubuntu bionic-backports InRelease
  502  Connection refused [IP: 103.56.70.6 80]
Err:13 http://repo.unpatti.ac.id/ubuntu bionic-security InRelease
  502  Connection refused [IP: 103.56.70.6 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/shogun-toolbox/nightly/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/shogun-toolbox/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by karlnapf** [comment]
patch welcome!

**Comment by karlnapf** [comment]
(shogun isnt released yet for this distro)
