### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ricardoclandim** [shogun-toolbox/shogun#4982]
When I run make, after cmake .. appears the following error:

[  0%] Generating version header                                                                                        [  0%] Built target version                                                                                             [  0%] Generating /home/ricardoclandim/shogun/build/src/shogun/base/class_list.cpp                                      [  0%] Built target class_list                                                                                          [  0%] Performing download step (download, verify and extract) for 'bitsery'                                            -- verifying file...                                                                                                           file='/home/ricardoclandim/shogun/third_party/bitsery/v4.6.0.tar.gz'                                             -- MD5 hash of                                                                                                              /home/ricardoclandim/shogun/third_party/bitsery/v4.6.0.tar.gz                                                         does not match expected value                                                                                             expected: 'accb462f98a59ed2bc4ffa7de374c24b'                                                                              actual: 'd41d8cd98f00b204e9800998ecf8427e'                                                                        -- File already exists but hash mismatch. Removing...                                                                   -- Downloading...                                                                                                          dst='/home/ricardoclandim/shogun/third_party/bitsery/v4.6.0.tar.gz'                                                     timeout='none'                                                                                                       -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 -- Retrying...                                                                                                          -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 -- Retry after 5 seconds (attempt #2) ...                                                                               -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 -- Retry after 5 seconds (attempt #3) ...                                                                               -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 -- Retry after 15 seconds (attempt #4) ...                                                                              -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 -- Retry after 60 seconds (attempt #5) ...                                                                              -- Using src='https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz'                                                 CMake Error at bitsery-stamp/download-bitsery.cmake:159 (message):                                                        Each download failed!       

Does anybody have an idea of how to solve it? Thanks

**Comment by LiuYuHui** [comment]
you can manually download bitsery from this [link](https://github.com/fraillt/bitsery/archive/v4.6.0.tar.gz), and then put it in shogun/third_party/bitsery.
