### ISSUE TITLE
renaming factories

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4993]
Our factory names are a bit unfortunate, as they don't immediately make clear what these functions are doing, and worse, they cause conflicts when directly imported into the namespace (c.f. #4992 ).

To avoid that, I suggest that we rename them in the lines of `kernel` -> `create<Kernel>` in c++, and `create_kernel` in meta examples, which is much more clear and doesnt have the same potential for name conflicts. This task is to do that. It is also an excellent opportunity to learn more about the meta examples system and the new API of shogun.

These things need to be done (roughly in order)
* refactor all C++ factories in `factory.h`, see the discussion below for more details
* make shogun compile
* fix c++ unit tests (there will be compiler errors)
* Replace factory calls in meta examples (requires touching all `*.sg.in` files. Then
  * fix c++ meta examples (compiler errors makes this easy)
     * note this requires mapping meta example calls like `create_kernel` to `create<Kernel>` in c++, similar as done with `put/get`
  * fix python meta examples (might need to look into swig code)
  * fix remaining meta examples
* fix notebooks
* fix python graphical examples

Note that you can very easily automate this task via searching (`grep` or even `git grep`) for patterns like `kernel(\"` and the like for all existing factory names in the shogun codebase

**Comment by vigsterkr** [comment]
a possible quicker and more pragmatic approach is to do this:
https://kevinaboos.wordpress.com/2013/07/23/clang-tutorial-part-ii-libtooling-example/

you could take this example https://github.com/kevinaboos/LibToolingExample/blob/master/Example.cpp and amend it for your needs.

note that this will not change anything in the meta examples (or swig related code) so that still needs greping unfortunately.

**Comment by vigsterkr** [comment]
@karlnapf could we use the `create_` prefix instead of `make_`? and this is only affecting SWIG, right? i am for all the unification, but do we need more verbosity in c++ codebase than actually what we have to take already now ? :S namely we could keep these factories in c++ interface and just have a swig wrapper definition in factory.i

**Comment by karlnapf** [comment]
++ for "create", (edited above)
I see your point about verbosity, but I would change the c++ name as well as otherwise things diverge and create confusion.

**Comment by gf712** [comment]
But then for C++ that wouldn't be very idiomatic no? What you would have is `make_factory<Kernel>(name);` no (if you were to use factories at all)?

**Comment by karlnapf** [comment]
what about `create<Kernel>(name)` ? (This is a bit more tricky to get into the meta examples but possible)

**Comment by karlnapf** [comment]
and then `create_kernel` for swig. That is a difference that I think wouldnt be as confusing as say `kernel` and `create_kernel`, and it would also follow our templated `put/get` call patterns/translations

**Comment by gf712** [comment]
I don't mind. I don't have that much experience with runtime libraries, I was just thinking there is make_shared, make_unique, and so..

**Comment by karlnapf** [comment]
yep, that's why I suggested "make" in the first place. I like it more, but I do not mind "create"

**Comment by gf712** [comment]
I mean `create` seems to be used in Qt, I guess that is *the reference* for this kind of pattern...

**Comment by karlnapf** [comment]
One problem: different factories take different arguments. How to deal with that?

**Comment by gf712** [comment]
what do you mean? We can use a variadic template for that though, and instantiate it in swig.
```cpp
template <typename T, typename ...Args>
std::shared_ptr<T> create(std::string_view name, Args&& ...args)
{
   if constexpr(std::is_same_v<T, Kernel>)
     return create_object<T>(name.data());
   if constexpr(std::is_same_v<T, Features>)
     return detail::create<T>(std::forward<Args>(args)...); // dispatch from here
}
```
and then in swig (not sure about the syntax)
```cpp
%template(create_kernel) create<Kernel>;
%template(create_features) create<Features, File>;
%template(create_features) create<Features, SGMatrix<double>>; // assuming this overload works
```

And then one day when reflection is a thing then we can go to the next level and do some crazy stuff, and just have `create("GaussianKernel")` and it returns a Kernel instance without any template stuff :D

**Comment by karlnapf** [comment]
sweet! I'll edit a bit above in the instructions

**Comment by gf712** [comment]
I think this feature has now been fully implemented, or is there something missing?

**Comment by karlnapf** [comment]
yes #4995
