### ISSUE TITLE
remove `.clone` in linalg methods

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#5014]
Linalg methods that return newly allocated vectors sometimes clone an input vector, instead of just allocating empty memory. That is unnecessary and could be changed.

**Comment by Aakash1822** [comment]
where to make this changes

**Comment by gf712** [comment]
@karlnapf maybe we should also add a numpy style `empty_like` constructor to SGVector/Matrix (if there isn't one already?)

**Comment by karlnapf** [comment]
IMO vector/matrix shouldnt even be initialized by default (they weren't in the past and I dont know when that changed, might we worth a look), much rather have `zeros` `ones` like in numpy. The problem is that now it will be hard to get rid of this. So maybe having another ctor for that is good yes
