### ISSUE TITLE
conda installation not working

### ISSUE THREAD

**Issue by aattukutti** [shogun-toolbox/shogun#5028]
According to the [docs](https://www.shogun-toolbox.org/install#binaries), you can install the shogun library using anaconda. However, when I use the 'conda install -c conda-forge shogun' command, the prompt gets stuck on solving environment.

How do I fix this issue?

**Comment by geektoni** [comment]
It works quite fine for me. It may be an issue of your local environment rather than shogun. Could you please give us more information about the error you are facing (e.g. OS, error message, etc.)?

**Comment by gf712** [comment]
I think it depends a lot on your environment. If you have a lot of packages there might be conflicts with the shogun required libraries. It also takes me a while to install it, and sometimes it fails. I would recommend installing shogun with conda in a new environment if that is possible.

**Comment by aattukutti** [comment]
![image](https://user-images.githubusercontent.com/64346806/81880492-46eb6680-95ab-11ea-987f-ccd0911f7a0e.png)
I am using windows 10. No error message pops up. The installation just gets stuck.

**Comment by aattukutti** [comment]
I've uninstalled and reinstalled anaconda. I'm getting the following error now.
![image](https://user-images.githubusercontent.com/64346806/81894977-bc1c6300-95ce-11ea-884e-bae10101578f.png)

**Comment by vigsterkr** [comment]
windows package is broken for the time being... sorry. there's an effort to fix this see https://github.com/shogun-toolbox/shogun/pull/4927

**Comment by aattukutti** [comment]
Is there any other way to install on windows? I tried compiling from source but I don’t have several of the dependencies and it would be extremely cumbersome to install of them by hand.

**Comment by gf712** [comment]
Yes, you can get docker for Windows
