### ISSUE TITLE
Am I missing a requirements list?

### ISSUE THREAD

**Issue by TusharSariya** [shogun-toolbox/shogun#5039]
I am clearly missing a bunch of requirements, but where did I miss to do them? this is on a relatively fresh install of ubuntu 20.04:

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_FOLDING_EXPRESSIONS
-- Performing Test HAVE_FOLDING_EXPRESSIONS - Success
-- Performing Test HAVE_IF_CONSTEXPR
-- Performing Test HAVE_IF_CONSTEXPR - Success
-- Performing Test HAVE_IF_INIT
-- Performing Test HAVE_IF_INIT - Success
-- Performing Test HAVE_STD_STRING_VIEW
-- Performing Test HAVE_STD_STRING_VIEW - Success
-- Could NOT find CCache (missing: CCACHE CCACHE_VERSION) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
CMake Warning at CMakeLists.txt:411 (MESSAGE):
  Doxygen based documentation generation is enabled, but couldn't find
  doxygen.

  In order to turn off this warning either disable doxygen documentation
  generation with -DENABLE_DOXYGEN=OFF cmake option or install doxygen.

-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- dir='/home/tushar/Documents/shogun/src'
-- dir='/home/tushar/Documents/shogun/build/src'
-- dir='/home/tushar/Documents/shogun/src/gpl'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Performing Test HAVE_CXA_DEMANGLE
-- Performing Test HAVE_CXA_DEMANGLE - Success
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for signgam
-- Looking for signgam - found
-- Looking for fdopen
-- Looking for fdopen - found
-- Looking for lgammal
-- Looking for lgammal - found
-- Using system's malloc
-- Performing Test HAVE_STD_ALIGNED_ALLOC
-- Performing Test HAVE_STD_ALIGNED_ALLOC - Success
-- Could NOT find Eigen3 (missing: EIGEN_INCLUDE_DIR) (Required is at least version "3.1.2")
-- Could NOT find OPENCL (missing: OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OpenCL_INCLUDE_DIRS OpenCL_LIBRARIES) (Required is at least version "1.5.0")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Could NOT find rxcpp (missing: rxcpp_INCLUDE_DIR) 
-- Could NOT find TFLogger (missing: TFLogger_DIR)
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- LAPACK requires BLAS
-- Performing Test HAVE_STD_VARIANT
-- Performing Test HAVE_STD_VARIANT - Success
-- Could NOT find spdlog (missing: spdlog_DIR)
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
-- Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
CMake Warning at src/shogun/CMakeLists.txt:432 (find_package):
  By not providing "FindRapidJSON.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "RapidJSON", but CMake did not find one.

  Could not find a package configuration file provided by "RapidJSON" with
  any of the following names:

    RapidJSONConfig.cmake
    rapidjson-config.cmake

  Add the installation prefix of "RapidJSON" to CMAKE_PREFIX_PATH or set
  "RapidJSON_DIR" to a directory containing one of the above files.  If
  "RapidJSON" provides a separate development package or SDK, be sure it has
  been installed.

-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing: SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Could NOT find NLOPT (missing: NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing: ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Linker: GNU gold
-- Checking to see if CXX compiler accepts flag -flto=thin
-- Checking to see if CXX compiler accepts flag -flto=thin - no
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Could NOT find Ctags (missing: CTAGS_EXECUTABLE) 
CMake Warning at cmake/FindPLY.cmake:24 (message):
  ply import failure:

Call Stack (most recent call first):
  examples/meta/CMakeLists.txt:4 (FIND_PACKAGE)

CMake Error at examples/meta/CMakeLists.txt:6 (message):
  Python module ply required for meta examples.  Install or set
  BUILD_META_EXAMPLES=OFF

-- Configuring incomplete, errors occurred!
See also "/home/tushar/Documents/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/home/tushar/Documents/shogun/build/CMakeFiles/CMakeError.log".

**Comment by TusharSariya** [comment]
I was able to install eigen 3.1.4 but am still missing a lot of packages, Im not sure If i missed something in the documentation:
-- dir='/home/tushar/Documents/shogun/src'
-- dir='/home/tushar/Documents/shogun/build/src'
-- dir='/home/tushar/Documents/shogun/src/gpl'
-- Using system's malloc
-- Could NOT find OPENCL (missing: OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION OpenCL_INCLUDE_DIRS OpenCL_LIBRARIES) (Required is at least version "1.5.0")
-- Could NOT find rxcpp (missing: rxcpp_INCLUDE_DIR) 
-- Could NOT find TFLogger (missing: TFLogger_DIR)
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- LAPACK requires BLAS
-- Could NOT find spdlog (missing: spdlog_DIR)
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
-- Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing: SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Could NOT find NLOPT (missing: NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing: ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Linker: GNU gold
-- Ctags flavour: Exuberant
-- Found Ctags: /usr/bin/ctags (found version "exuberant ctags 5.9~svn20110310") 
CMake Warning at cmake/FindPLY.cmake:24 (message):
  ply import failure:

Call Stack (most recent call first):
  examples/meta/CMakeLists.txt:4 (FIND_PACKAGE)


CMake Error at examples/meta/CMakeLists.txt:6 (message):
  Python module ply required for meta examples.  Install or set
  BUILD_META_EXAMPLES=OFF


-- Configuring incomplete, errors occurred!
See also "/home/tushar/Documents/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/home/tushar/Documents/shogun/build/CMakeFiles/CMakeError.log".

**Comment by gf712** [comment]
I think the error message explains it: "CMake Error at examples/meta/CMakeLists.txt:6 (message):
Python module ply required for meta examples. Install or set
BUILD_META_EXAMPLES=OFF". The other packages are optional.
