### ISSUE TITLE
Cpp missing occurred when Shogun was installed manually using `python setup.py install` method.

### ISSUE THREAD

**Issue by Dawntown** [shogun-toolbox/shogun#5040]
Hello,
I'd like to install shogun package with Python interface in anaconda env. Given some package deficiencies, especially `SVMLight()` missing, in ready-to-install methods, I determined to install it via compiling by hand. The version I used is v6.1.3 downloaded from the github release page, and, in the activated conda env, it was installed via 
```python
python setup.py install --prefix=$HOME/miniconda3/envs/shogun
```

Then the fatal error info showed up as follow
``` bash
[  0%] Built target ShogunVersionProtobuf
[  0%] Built target ChunksProtobuf
[  1%] Generating version header
[  1%] Built target version
[  2%] Built target class_list
[  2%] Built target HeadersProtobuf
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/SGObject.cpp.o
/export/home/zhouxiaocheng/software/shogun-shogun_6.1.3/src/shogun/base/SGObject.cpp:32:10: fatal error: rxcpp/operators/rx-filter.hpp: No such file or directory
 #include <rxcpp/operators/rx-filter.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/SGObject.cpp.o] Error 1
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2
make error.
Error running make install
Verifying Shogun preconditions
Shogun build environment completed tasks: cmake: [True] -  make: [False] - make install: [False]
Shogun bootstrapping failed!
Please make sure that you have cmake and make installed.
```
I cannot find any similar errors or solutions on google, so I decided to seek help by setting forth a new issue. So kindly, I hope you can offer a favor.

**Comment by gf712** [comment]
I am not sure where that setup.py file is coming from but there is an explanation on how to build shogun for python [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#manual-python)

**Comment by Dawntown** [comment]
> I am not sure where that setup.py file is coming from but there is an explanation on how to build shogun for python [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#manual-python)

Thank you for your suggestion. I tried it, but it came out the same error. 
(PS: The setup.py is located in the root directory, `./shogun-shogun_6.1.3/setup.py`)

**Comment by karlnapf** [comment]
@Dawntown `setup.py`is outdated and should not be used to compile shogun. You will need to follow the instructions in the manual and read the error messages.

@gf712 @vigsterkr would you mind if we removed it actually? Causing lots of noise ....
