### ISSUE TITLE
H file missing when compiling shogun

### ISSUE THREAD

**Issue by Dawntown** [shogun-toolbox/shogun#5041]
I follow the [install manual](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#manual) to compile shogun manually. I'd like to install it in anaconda env, so the following steps were taken.
```bash
git clone https://github.com/shogun-toolbox/shogun.git
cd shogun
git submodule update --init
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/export/home/zhouxiaocheng/miniconda3/envs/shogun -DPYTHON_EXECUTABLE=/export/home/zhouxiaocheng/miniconda3/envs/shogun/bin/python -DPYTHON_INCLUDE_DIR=/export/home/zhouxiaocheng/miniconda3/envs/shogun/include/python3.6m -DPYTHON_LIBRARY=/export/home/zhouxiaocheng/miniconda3/envs/shogun/lib/libpython3.6m.so -DINTERFACE_PYTHON=ON ..

make
```
Then, the [h file missing error info](https://gist.github.com/Dawntown/40be215bf0f27a8486dcdde800f79db3) showed up.
```bash
/export/home/zhouxiaocheng/software/shogun/src/shogun/io/fmt/fmt.h:5:10: fatal error: spdlog/fmt/fmt.h: No such file or directory
 #include <spdlog/fmt/fmt.h>
          ^~~~~~~~~~~~~~~~~~
```
I have no idea how to fix it. Could you do me a favor?

**Comment by gf712** [comment]
This is *probably* because the detected compiler is gcc provided by anaconda, which then doesn't lookup for the files in you root directory (it uses /anaconda as it's root), where I assume you have spdlog installed already. Easiest fix is to clean build directory, `conda deactivate`, rerun cmake and build. If that doesn't work then you should disable the detection of spdlog and let shogun fetch it (to do this you can either remove your local spdlog installation or remove the relevant line in CMakeLists.txt, I would do the former if possible)

**Comment by gf712** [comment]
Actually, even better, set the CC and CXX environment variables. In the bash shell you are compiling (before running cmake):
```bash
export CC=/usr/bin/gcc # or whichever compiler you want to use
export CXX=/usr/bin/g++
```
And now it should work fine even with the conda environment active

**Comment by Dawntown** [comment]
@gf712 
The root's gcc and g++ seem very old. Their versions are both v4.8.5, which were reported as broken and disable to compile a simple test program by checking process. You can find the completed log info [here](https://gist.github.com/Dawntown/4a563100415aad6552be016536c98a2b).
```bash
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ - broken
CMake Error at /export/home/zhouxiaocheng/miniconda3/envs/shogun/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/bin/g++"

  is not able to compile a simple test program.
```
As a normal user, it seems to be hard to modify the root gcc and g++. In fact, I have updated the gcc and g++ in my virtual env to v7.* during the more previous try, and there is a conda installing version shogun (No SVMLight() function) in that env. Do these impinge on the correct compiling process?
I don't know which lines are relevant or which files are the local spdlog installation. Could you please provide more details if I have to do so?

**Comment by gf712** [comment]
Do you know if you have spdlog installed? It would be somewhere in /usr/local/include

**Comment by Dawntown** [comment]
@gf712 Yes, if you mean in the anaconda env, but perhaps no, if in the root directory, at least I cannot find it.

**Comment by gf712** [comment]
That is odd. I just  tried on my machine to compile with the anaconda spdlog and it worked fine...Did you ` conda install -c conda-forge spdlog ` in the active conda env?

**Comment by Dawntown** [comment]
@gf712 
I tried `conda install spdlog`, and it returned `# All requested packages already installed` but the same compiling error occurred. Consequently, I determined to create a new environment because of that the previous multiple tries have inevitably brought some latent barriers against compiling correctly. These are the installation steps.
```bash
conda create -n sg numpy cmake spdlog ply ctags swig -c conda-forge
conda activate sg
conda install -c anaconda gxx_linux-64 gcc_linux-64
conda install ply ctags swig -c conda-forge

# Mandatory step, it should be called, or an error requiring root privilege to install eigen3 shows up
conda install -c omnia eigen3
# Both two steps as follows might be needed, if the error reemerges.
conda deactivate
conda activate sg

cmake \
-DCMAKE_INSTALL_PREFIX=/export/home/zhouxiaocheng/miniconda3/envs/sg \
-DPYTHON_EXECUTABLE=/export/home/zhouxiaocheng/miniconda3/envs/sg/bin/python \
-DPYTHON_INCLUDE_DIR=/export/home/zhouxiaocheng/miniconda3/envs/sg/include/python3.8 \
-DPYTHON_LIBRARY=/export/home/zhouxiaocheng/miniconda3/envs/sg/lib/libpython3.8.so \
-DINTERFACE_PYTHON=ON ..

make
```
Now, the compiling moves on successfully but somewhat slowly (up to 18% for about an hour). Thank you so much for your patience to offer assistance. Please do not close the issue right now, since it may be costing overnight to complete and be safe to use.

**Comment by gf712** [comment]
you should do parallel compilation btw, `make -j NUM_CORES`, where NUM_CORES is the number of cores you can use to compile, with `make -j4` it should take an hour in total on modern laptop. Also if you are just going to train models, rather than develop the tool, make sure you are compiling in release mode with cmake (you can lookup online how to do that)

**Comment by gf712** [comment]
Glad it is working now though!

**Comment by Dawntown** [comment]
@gf712 Still, the compiling finally failed... My heart broke...
```bash
...
/export/home/zhouxiaocheng/software/shogun/build/src/interfaces/python/shogunPYTHON_wrap.cxx:79222:12: warning: 'int BoolVector_setslice(PyObject*, Py_ssize_t, Py_ssize_t, PyObject*)' defined but not used [-Wunused-function]
 static int BoolVector_setslice(PyObject *self, Py_ssize_t ilow, Py_ssize_t ihigh, PyObject* v)
            ^~~~~~~~~~~~~~~~~~~
/export/home/zhouxiaocheng/software/shogun/build/src/interfaces/python/shogunPYTHON_wrap.cxx:6657:20: warning: 'const char* typecode_string(PyObject*)' defined but not used [-Wunused-function]
 static const char* typecode_string(PyObject* py_obj) {
                    ^~~~~~~~~~~~~~~
make[2]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/shogunPYTHON_wrap.cxx.o] Error 1
make[1]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/all] Error 2
make: *** [all] Error 2
```
I have modified the options of `cmake` and `make` as you mentioned.
```bash
cmake \
-DCMAKE_INSTALL_PREFIX=/export/home/zhouxiaocheng/miniconda3/envs/sg \
-DPYTHON_EXECUTABLE=/export/home/zhouxiaocheng/miniconda3/envs/sg/bin/python \
-DPYTHON_INCLUDE_DIR=/export/home/zhouxiaocheng/miniconda3/envs/sg/include/python3.8 \
-DPYTHON_LIBRARY=/export/home/zhouxiaocheng/miniconda3/envs/sg/lib/libpython3.8.so \
-DINTERFACE_PYTHON=ON \
-DCMAKE_BUILD_TYPE=Release ..

make -j 8
```
Then, I downgraded the python to v3.6 in `sg` env and tried again. There popped up another error...
```bash
...
[ 79%] Linking CXX shared module _shogun.so
[ 79%] Built target _interface_python
make: *** [all] Error 2
```

**Comment by gf712** [comment]
You’re going to have to show the actual error. Can you paste the whole output on pastebin please?

**Comment by Dawntown** [comment]
[This](https://gist.github.com/Dawntown/22c3079feb56fa0e5e1c7215c7c7180a) is the whole output log I can find in the terminal history buffer.

**Comment by gf712** [comment]
You need to provide the whole output. Just run `make -j8 > output.txt` and share output.txt. The swig generated file is huge so it will emit lots of warnings.

**Comment by Dawntown** [comment]
I just rerun `make`, and updated the [link](https://gist.github.com/Dawntown/22c3079feb56fa0e5e1c7215c7c7180a) above. You can see the very whole output [here](https://gist.githubusercontent.com/Dawntown/22c3079feb56fa0e5e1c7215c7c7180a/raw/2a21eac4030ee627b3cf8c4a9d39b19385ca61d6/make_with_py36.log).

**Comment by karlnapf** [comment]
Note that if you try to compile shogun in 8 threads, your computer will likely crash ;)

**Comment by karlnapf** [comment]
```
/export/home/zhouxiaocheng/miniconda3/envs/sg/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /export/home/zhouxiaocheng/miniconda3/envs/shogun/lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'
```
Seems like your c++ setup is broken.
BTW the error seems to happen when the cpp meta examples are compiled, which happens *after* libshogun itself. Try disabling them `-DDISABLE_META_CPP=ON`. I see you enabled the python interface... the python examples will still be available with the above switch

**Comment by gf712** [comment]
It seems like glibc provided by conda is missing some symbols.. Usually you would use the system library on a linux distro(and have an update that, but @Dawntown says he isn't root on the machine)
Anaconda libstdc++.so symbols:
```bash
strings libstdc++.so.6.0.26 | grep ^GLIBC_
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.6
GLIBC_2.4
GLIBC_2.3.2
```
I think you have two options: compile glibc and then add that to your LD_LIBRARY_PATH or use shogun's dev docker image to compile the latest shogun.

**Comment by Dawntown** [comment]
In fact, I do have these symbols.
```bash
$ strings ~/miniconda3/envs/sg/lib/libstdc++.so.6.0.27 | grep ^GLIBC_
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.6
GLIBC_2.4
GLIBC_2.3.2
```

**Comment by Dawntown** [comment]
I am compiling it again with `-DDISABLE_META_CPP=ON`. Thanks for your friendly reminding @karlnapf Please don't worry about that, I am using a computing cluster.

**Comment by gf712** [comment]
But you will still need the symbols to link libshogun to the python library _shogun.so, no? If not you are probably going to have a runtime error

**Comment by Dawntown** [comment]
Compiling was completed, and it can `make install` smoothly. However, in python, the `SVRLight()` is still missing...
```bash
(sg) [zhouxiaocheng@GPU-P100-2 build]$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shogun as sg
>>> solver = sg.SVRLight()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'shogun' has no attribute 'SVRLight'
```
Does that mean the only solution is to install docker? Or how can I link libshogun to the python library _shogun.so?

**Comment by gf712** [comment]
that is because we use a factory pattern now. `sg.create_machine("SVRLight")`. Hope it works!

**Comment by Dawntown** [comment]
Yes! That works! Thank you very much! @karlnapf @gf712  Do you offer the newest tutorial? I realized that [the example I referred to](https://www.shogun-toolbox.org/examples/latest/examples/regression/multiple_kernel_learning.html) very differs with this version. Thank you again!

**Comment by gf712** [comment]
you should be able to build the docs locally. You can also look at the examples generated in your build directory `build/tests/meta/generated_results/python/`

**Comment by Dawntown** [comment]
I found it. The examples are located in `build/examples/meta/python/`. They work very well. Thank you :D
