### ISSUE TITLE
 AppVeyor CI build link for Windows packages not working.  

### ISSUE THREAD

**Issue by craftyshark** [shogun-toolbox/shogun#5043]
When going the App Veyor CL link (https://ci.appveyor.com/project/vigsterkr/shogun) in INSTALL.md under the windows Ready to Install packages, the page says project not found or access denied.

**Comment by gf712** [comment]
Hi, we don't use AppVeyor anymore. We only use [Azure Pipelines](https://dev.azure.com/shogunml/shogun/_build?definitionId=2) for all the builds.
Someone should fix the documentation.

**Comment by craftyshark** [comment]
Well, shoot, I guess I'll take that part out. I guess that'll be my first little contribution. Thanks!

**Comment by gf712** [comment]
Thanks!
