### ISSUE TITLE
Add temporary value support for zip_iterator

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#5050]
Currently zip_iterator can only handle lvalues, but it would be nice to have it work with rvalues.
This would probably require quite a bit of template programming and refactoring `zip_iterator`.

What currently works
```cpp
auto dot_iterator = DotIterator(feat);
for (const auto& [X, y]: zip_iterator(dot_iterator, labels)] {
...
}
```

What should also work
```cpp
for (const auto& [X, y]: zip_iterator(DotIterator(feat), labels)] {
...
}
```

Currently all the iterable objects passed to `zip_iterator` are stored by reference in a tuple to avoid copying them, but this means that `zip_iterator(DotFeatures(feat), labels)` gives a compile time error as we are trying to access a reference to a temporary. We would have to somehow have a constructor and tuple type pack that would have either a lvalue or reference to lvalue depending on the iterator type.

```cpp
// given the instantiation
zip_iterator(DotIterator(feat), labels)
// this iterator would have a tuple type:
std::tuple<DotIterator, std::shared_ptr<Labels>&> m_container_tuples;
```

**Comment by karlnapf** [comment]
Slightly more advanced entrance task for C++ geeks :)
