### ISSUE TITLE
when compiling: fatal error: Eigen/Eigen: No such file or directory

### ISSUE THREAD

**Issue by Hephaestus12** [shogun-toolbox/shogun#5087]
This has been there for a week now. I have tried installing Eigen, running CMake again in a new directory, but still, this error persists. When I checkout an older commit and run it, it seems to compile fine.
I am trying some way with symlinks as someone on IRC suggested, but not entirely sure how to proceed. Any suggestions as to what I can do?

[Output](https://pastebin.com/KDM0sKzK) on running cmake ..      
[Output](https://pastebin.com/7aEYES5T) on running make   

[Output when running cmake in fresh directory](https://pastebin.com/7fYqFMM0)
[Output when running make in fresh directory](https://pastebin.com/gdtK3R25)

**Comment by geektoni** [comment]
To make this issue more informative, we need more information about which steps you have performed (cmake command output) and the complete error message you are getting once you run `make`. It would also be useful to know which is the older commit that still works for you, so we can understand which are the changes that were applied in the meantime.

**Comment by Hephaestus12** [comment]
[Output](https://pastebin.com/KDM0sKzK) on running cmake ..      
[Output](https://pastebin.com/7aEYES5T) on running make

**Comment by geektoni** [comment]
> [Output](https://pastebin.com/KDM0sKzK) on running cmake ..
> [Output](https://pastebin.com/7aEYES5T) on running make

We need the full cmake output. Namely, create a new build directory and run cmake from there.

**Comment by Hephaestus12** [comment]
[Output when running cmake in fresh directory](https://pastebin.com/7fYqFMM0)
[Output when running make in fresh directory](https://pastebin.com/gdtK3R25)

**Comment by karlnapf** [comment]
this is not an eigen error but related to spdlog .... fmt being mentioned. 
@gf712 any ideas?

**Comment by gf712** [comment]
Indeed, what version of spdlog do you have locally?

**Comment by Hephaestus12** [comment]
> Indeed, what version of spdlog do you have locally?
```
Package: libspdlog-dev
Architecture: amd64
Version: 1:0.16.3-1
Priority: optional
Section: universe/libdevel
Source: spdlog
Origin: Ubuntu
```


[This](https://pastebin.com/Y6LK7dri) is the entire log message:

**Comment by gf712** [comment]
@Hephaestus12 I think this has been solved right? The problem was that it was using an old shogun installation, and the Eigen config file was still there, but the Eigen directory that it pointed to was gone.
