### ISSUE TITLE
model selection?

### ISSUE THREAD

**Issue by kaigu1997** [shogun-toolbox/shogun#5088]
I am a beginner to shogun. When I am looking for example of hyperparameter optimization of gaussian process, the cookbook tells me to using gradient model selection. (in meta examples no optimization provided) However, with the newest update, there is no model selection folder, with all the files in it being removed.
So what should I do? I checked all the meta examples but none of them mentioned about that.
Will you provide that in meta examples, or update cookbook?

**Comment by kaigu1997** [comment]
I have seen a folder named optimization, but no meta example mentioned about that, so idk if I could use that to do the model selection (i.e. hyperparameter optimization).

**Comment by gf712** [comment]
Hi, we have currently disabled the model selection module in shogun because it was not compatible with some recent changes. We are currently working on bringing it back!

**Comment by gf712** [comment]
If you want to use a stable version of shogun please use a release. The model selection stuff is only disabled in the development branch.

**Comment by kaigu1997** [comment]
> 
> 
> If you want to use a stable version of shogun please use a release. The model selection stuff is only disabled in the development branch.

Thanks for your reply. I guess I would use the 6.1.4 release now, and hope 7.0.0 could be coming soon :P
