### ISSUE TITLE
Refactor Preprocessor

### ISSUE THREAD

**Issue by jonpsy** [shogun-toolbox/shogun#5090]
The preprocessor classes have a few redundant features which need cleanup. I'll list them below for convenience 

- ```m_fitted``` is scattered around throughout the code, which could prove to be fatal. 
-  The ```cleanup()``` method should be removed as objects are destroyed automatically with smart pointers
-  ```fit()``` method could be split into two, namely, ```fit()``` and ```fit_impl()``` where the former does the input-checks and the latter does the actual computation.

Here's how I want to go about solving this:

- Remove ```cleanup()``` method from preprocessor class and derivatives
- Separate fit() method into two wherein it calls the **helper function** fit_impl() which handles the computation which finally sets m_fitted to true. This immediately solves the m_fitted problem, now one could rest easy about manually toggling the m_fitted method inside class implementation.

**Comment by karlnapf** [comment]
Thx!
