### ISSUE TITLE
Error in compilation: SG_CONSTRAINT

### ISSUE THREAD

**Issue by javiermaldonadoc** [shogun-toolbox/shogun#5092]
I'm trying to compile the latest version (develop) and shows this error:
shogun/src/shogun/preprocessor/RFFPreprocessor.cpp:26:17: error: ‘castable’ was not declared in this scope
   26 |   SG_CONSTRAINT(castable<ShiftInvariantKernel>()));

**Comment by LiuYuHui** [comment]
@javiermaldonadoc could you give the complete error message?

**Comment by javiermaldonadoc** [comment]
i've solve this issue after erase all my local copy and reinit the local repo. I think my local copy was broken somehow.... Thanks!
