### ISSUE TITLE
Converting code from 6.1.4 to develop branch

### ISSUE THREAD

**Issue by spiovesan** [shogun-toolbox/shogun#5128]
I am using some example written for Shogun 6.1.4 with the develop branch and I am having some issues. I can handle class name changes, use of shared pointers but some functions look disappeared as `SGMatrix<T>::transpose_matrix() `and `SGMatrix<T>::submatrix()`. Is there some documentation how to port the code from 6.1.4 to current branch?

**Comment by karlnapf** [comment]
Hi
Yes that’s gone. All languages that you can use shogun from have that functionality. Which one are you using? In c++ this can be done using e.g. eigen3
If you show some snippets we can give pointers
There unfortunately is no guide for porting atm (7.0 not released yet)

**Comment by spiovesan** [comment]
Hi,
[this ](https://github.com/PacktPublishing/Hands-On-Machine-Learning-with-CPP/blob/master/Chapter04/shogun/shogun-cluster.cc) is the code sample I am trying to convert:

        auto csv_file = std::make_shared<CSVFile>(dataset_name.string().c_str());
        Matrix data;
        data.load(csv_file);

        // Exclude cluster and index info from data
        // Shogun csv loader loads matrixes in column major order
        Matrix::transpose_matrix(data.matrix, data.num_rows, data.num_cols);
        Matrix inputs = data.submatrix(1, data.num_cols - 1);  // make a view
        inputs = inputs.clone();                // copy exact data
        Matrix outputs = data.submatrix(3, 4);  // make a view
        outputs = outputs.clone();              // copy exact data

        // Transpose back because shogun algorithms expect that samples are in
        // colums
        Matrix::transpose_matrix(inputs.matrix, inputs.num_rows,
                                 inputs.num_cols);

I am trying to use [this book](https://github.com/PacktPublishing/Hands-On-Machine-Learning-with-CPP)sample code. I think I will hit hard on something else...
