### ISSUE TITLE
Eigen3.3.8 is not supported

### ISSUE THREAD

**Issue by devchilll** [shogun-toolbox/shogun#5131]
Hello, I am trying to build Shogun, but my Mac OS has Eigen3.3.8, and the Checklist has this error checking:
```
  IF(${EIGEN3_VERSION_STRING} VERSION_GREATER 3.3.7)
    MESSAGE(FATAL_ERROR "The system Eigen3 version ${EIGEN_VERSION} isn't supported!")
  ENDIF()
  SHOGUN_INCLUDE_DIRS(SCOPE PUBLIC SYSTEM ${EIGEN3_INCLUDE_DIR})
```

Any workaround? thanks!

**Comment by gf712** [comment]
Hi, I can try and build shogun with Eigen 3.3.8 and see if it works. If so I will bump the required Eigen version
