### ISSUE TITLE
Python 3.8 not supported (ready-to-install package via conda-forge)

### ISSUE THREAD

**Issue by ahlraf** [shogun-toolbox/shogun#5132]
Hi, I've been trying to install shogun on my Windows 10 via conda-forge

<conda install -c conda-forge shogun>

returns:

<Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  75%|███████████████████████████████████████             | 3/4 [00:01<00:00,  1.59it/s]\failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - shogun -> python[version='3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.>

I've attempted <conda update --all>, but there's been no change.

How do I work this out?
Thanks!

**Comment by ahlraf** [comment]
Worked on changing environment, I think it's an issue with anaconda itself.

**Comment by arya2910** [comment]
@ahlraf  i am also getting the same error. if you got the answer tell me please.

**Comment by ahlraf** [comment]
> @ahlraf i am also getting the same error. if you got the answer tell me please.

I think it's specific to anaconda. You could try to downgrade the version  [see here](https://github.com/conda/conda/issues/9004). What worked for me is creating a virtual environment, and installing shogun through conda there.
```
conda create --name myenv
conda activate myenv

```
