### ISSUE TITLE
Addition of Docker File

### ISSUE THREAD

**Issue by imsiddhant07** [shogun-toolbox/shogun#5134]
Hello, 
I noticed the repo does not have a 'dockerfile', If needed may I add one to the repo?

**Comment by gf712** [comment]
Hi, there are two Dockerfile files in the repo:
1 - The shogun SDK that is used for testing. The image contains all required libraries to build shogun and most optional libraries.
https://github.com/shogun-toolbox/shogun/blob/develop/configs/shogun-sdk/Dockerfile
2 - The shogun Dockerfile. It contains the last major release of shogun, but this is quite outdated now.

You can also find these on https://hub.docker.com/u/shogun

**Comment by siddhantjain07** [comment]
Thank you @gf712 for clarification.
So is any updating required/expected in point 2?

**Comment by gf712** [comment]
No, it will be updated when we release again

**Comment by siddhantjain07** [comment]
Ok, thank you for looking into it.
