### ISSUE TITLE
Windows build documentation out of date 

### ISSUE THREAD

**Issue by bandjhughes** [shogun-toolbox/shogun#5142]
The documentation near the bottom of the[ Installing Shogun page](https://www.shogun.ml/install#manual-windows) states:

 "Please see our [AppVeyor](https://ci.appveyor.com/project/vigsterkr/shogun) build. It is recommended to use "Visual Studio 14 2015" or "MSBuild"...".

However, the [AppVeyor](https://ci.appveyor.com/project/vigsterkr/shogun) link is broke.  Also attempting to configuring build in Visual Studio 14 2015 results in a the following error message from the CMake file "**_Compiling shogun requires a compiler with folding expression support!_**".

**Comment by LiuYuHui** [comment]
Hi @bandjhughes, I think you can use this command 
https://github.com/shogun-toolbox/shogun/blob/9b8d856971af5a295dd6ad70623ae45647a6334c/.ci/windows-steps.yml#L42
and we recommend using Visual Studio 15 2017 now.
