### ISSUE TITLE
Importing error of shogun installed with conda

### ISSUE THREAD

**Issue by hmzhangBio** [shogun-toolbox/shogun#5150]
I installed shogun using "conda install -c conda-forge shogun". I can import it successfully in python environment. However, I got the following errors when I imported other classes of shogun

>>> import shogun as sg
>>> from sg.Features import StringCharFeatures, RealFeatures
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sg'

I'm wondering do I use shogun in a wrong way? Are there any examples showing how to use shogun installed with conda?
Thanks!

**Comment by pandeyanuradha** [comment]
Hey @hmzhangBio, I am facing the same error, could you get any solution for this?

**Comment by gf712** [comment]
Hi, so Features is a class not a module. Features is the base class of all features .But that doesn't seem to be the issue.. What python version are you using?

**Comment by pandeyanuradha** [comment]
Hey, so the python version I am using is : Python 3.6.3 :: Anaconda, Inc.

**Comment by hmzhangBio** [comment]
@gf712 , Thanks for the reply! I use Python 3.6.7 installed from miniconda3.
