### ISSUE TITLE
[Help wanted] Issue while installing shogun for windows

### ISSUE THREAD

**Issue by AdityaNikhil** [shogun-toolbox/shogun#5157]
I am trying to install shogun on my windows machine. I'm currently following the instructions as stated [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#windows-build-)

Almost all the steps are successfully executed and I'm especially encountering the problem from here,
![image](https://user-images.githubusercontent.com/30192967/106375220-6a13ab80-63b0-11eb-90e2-9e9482e862d0.png)

- **get_latest_artifact.py** file is posing errors when trying to run.(Saying list index out of range)
- The command `FOR /F "delims=" %i IN ('where .\%clcacheArtifactName%:*.tar*') DO tar --extract --file=%i --directory %CLCACHE_DIR% --gzip`  outputs **INFO: Could not find files for the given pattern(s).**

I need serious help to move forward as I'm stuck here.

**Comment by arya2910** [comment]
can you tell me how to install shogun in windows??

**Comment by AdityaNikhil** [comment]
@arya2910, just follow the instructions from [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md) according to your OS.

**Comment by arya2910** [comment]
@AdityaNikhil ,I got it:)
thankyou

**Comment by arya2910** [comment]
Put these lines into the Anaconda Prompt:

`rem - Records comments (remarks); @rem - do not print command just its result (the rem result is empty)
`
Be careful cmake can search out of the build directory to load libraries thus remove other directories that contain the shogun sources

```
@rem [FILL THIS SECTION WITH THE VALUES YOU WANT
@rem For example: SET MAIN_DIR=D:\Build
SET MAIN_DIR=X:\Path\To\Build
@rem Basically your number of cores
SET MAX_CPU_COUNT=8
@rem Take a look at https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators
SET PLATFORM=-G "Visual Studio 16 2019" -A x64
@rem FILL THIS SECTION WITH THE VALUES YOU WANT]

SET REPO_DIR=%MAIN_DIR%\shogun
SET VENV_DIR=%MAIN_DIR%\envs\shogun
SET CLCACHE_DIR=%MAIN_DIR%\clcache
SET SourcesDirectory=%REPO_DIR%\build
SET BinariesDirectory=%MAIN_DIR%\binaries
SET targetPrefix=%BinariesDirectory%\opt
SET clcacheArtifactName=clcache-vs17
SET buildConfiguration=Release
SET SourceBranchName=develop

git clone https://github.com/shogun-toolbox/shogun %REPO_DIR%
CHDIR /d %REPO_DIR%
git submodule update --init --force --depth=5
conda create --quiet --prefix %VENV_DIR% --mkdir --yes python=3.6.* setuptools numpy scipy eigen snappy zlib ctags ply jinja2 gtest mkl-devel swig -c conda-forge
activate %VENV_DIR%

```

@AdityaNikhil can you tell me how to execute these lines.

**Comment by AdityaNikhil** [comment]
First of all, I hope you have managed to install a few things as per instructed [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#windows-build-)(lines 1-4)
Now open the **anaconda prompt** and paste the above lines excluding the ones starting with **@rem**.

For example, exclude the first 2 lines and insert the 3rd line - **SET MAIN_DIR=X:\Path\To\Build**
Above, in **X:\Path\To\Build**, specify a path for the build.

**Comment by arya2910** [comment]
```
(base) PS C:\Users\arya gupta> CHDIR /d %REPO_DIR%
Set-Location : A positional parameter cannot be found that accepts argument '%REPO_DIR%'.
At line:1 char:1
+ CHDIR /d %REPO_DIR%
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

```
this is the error i got while executing CHDIR `/d %REPO_DIR%` this line

**Comment by AdityaNikhil** [comment]
You did not set your **REPO_DIR** location.
What did you set your **REP_DIR** location to?!

**Comment by arya2910** [comment]
now i set my **REPO_DIR** loacation but now also its showing like this

```
(base) PS C:\Users\arya gupta> CHDIR C:\Users\arya gupta\%REPO_DIR%
Set-Location : A positional parameter cannot be found that accepts argument 'gupta\%REPO_DIR%'.
At line:1 char:1
+ CHDIR C:\Users\arya gupta\%REPO_DIR%
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

**Comment by AdityaNikhil** [comment]
Not like that,
while you're configuring all the **SET** statements, like these,

- SET REPO_DIR=%MAIN_DIR%\shogun
- SET VENV_DIR=%MAIN_DIR%\envs\shogun
- SET CLCACHE_DIR=%MAIN_DIR%\clcache
- SET SourcesDirectory=%REPO_DIR%\build

You have to give a directory path in place of **%**.
Example,
- SET REPO_DIR=D:\Build\shogun
- SET VENV_DIR=D:\Build\envs\shogun
- SET CLCACHE_DIR=D:\Build\clcache
- SET SourcesDirectory=D:\Build\build

Hence, give proper paths and run this command **CHDIR /d %REPO_DIR%** again.

**Comment by arya2910** [comment]
how to check that shogun is finally installed?? and how can i use it

**Comment by AdityaNikhil** [comment]
Run the shogun virtual environment and run a simple python script that includes **import shogun** statement in it.(Make sure to run the python script with the shogun virtual environment )

**Comment by arya2910** [comment]
i did that only but getting  the same error everytime.

**Comment by arya2910** [comment]
what's shogun virtual environment??

**Comment by raorashmi487** [comment]
> I am trying to install shogun on my windows machine. I'm currently following the instructions as stated [here](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md#windows-build-)
> 
> Almost all the steps are successfully executed and I'm especially encountering the problem from here,
> ![image](https://user-images.githubusercontent.com/30192967/106375220-6a13ab80-63b0-11eb-90e2-9e9482e862d0.png)
> 
> * **get_latest_artifact.py** file is posing errors when trying to run.(Saying list index out of range)
> * The command `FOR /F "delims=" %i IN ('where .\%clcacheArtifactName%:*.tar*') DO tar --extract --file=%i --directory %CLCACHE_DIR% --gzip`  outputs **INFO: Could not find files for the given pattern(s).**
> 
> I need serious help to move forward as I'm stuck here.

Hi Aditya, were you able to solve this error, it looks like i am stuck at this point too.
