### ISSUE TITLE
problem with developing.md

### ISSUE THREAD

**Issue by arya2910** [shogun-toolbox/shogun#5160]
```
arya gupta@LAPTOP-DH8F7VDN MINGW64 ~
$ git clone https://github.com/YOUR_USERNAME/shogun
Cloning into 'shogun'...
remote: Repository not found.
fatal: repository 'https://github.com/YOUR_USERNAME/shogun/' not found

```
I was following the steps according to shogun git development cycle but i am getting this output .can anyone help me with this

**Comment by LiuYuHui** [comment]
Hi @arya2910, you should first fork the shogun repo, then substitute `arya2910` for `YOUR_USERNAME`.

**Comment by arya2910** [comment]
okay .i did it after this what??
