### ISSUE TITLE
Inquiry about Google Summer of Code Application

### ISSUE THREAD

**Issue by hs094** [shogun-toolbox/shogun#5182]
I am a Novice Open Source Programmer, I wanted to Inquire about the Possibilities of Application for Google Summer of Code with this Repo.

**Comment by geektoni** [comment]
Dear @iamhardikat11, thank you for your interest in the project! :) The project development is paused for the moment, so most likely we won't be part of GSoC this year.

**Comment by iamhardikat11** [comment]
Ok.
