### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by yurivict** [shogun-toolbox/shogun#5188]
There have been no commits for 2+ years.

**Comment by eskayML** [comment]
I think so, probably reaching out to the maintainers would be a good idea to try

**Comment by ml31415** [comment]
@karlnapf @lisitsyn @vigsterkr @iglesias @yorkerlin Maybe one of you has more information on the state of the project?

**Comment by lisitsyn** [comment]
Well we're here but life happens and we've got no momentum to continue huge changes we've planned. There is also huge competition in ML nowadays so we definitely have some problems with going forward.

What would you like to know?

**Comment by ml31415** [comment]
Hi lisitsyn! Big thanks for your answer. I was considering using shogun for a new ML project. But with the website offline and not commits for some years, it just looked like the project came to some surprisingly abrupt end, given that it seemed to have been a numfocus / pydata sponsored project before.

**Comment by iglesias** [comment]
Thanks for sharing your personal opinion, @ml31415.

If you need help with anything specific, please ask.

Good luck with your project.
